import { Router } from "express";
import { CheckEmailController } from "../controller/CheckEmailController.js";
import { CompleteProfileController } from "../controller/CompleteProfileController.js";
import { CompleteRegistrationController } from "../controller/CompleteRegistrationController.js";
import { LoginController } from "../controller/LoginController.js";
import { LogoutController } from "../controller/LogoutController.js";
import { OAuthController } from "../controller/OAuthController.js";
import { RegisterController } from "../controller/RegisterController.js";
import { RequestPasswordResetController } from "../controller/RequestPasswordResetController.js";
import { ResetPasswordController } from "../controller/ResetPasswordController.js";
import { VerifyOTPController } from "../controller/VerifyOTPController.js";
import { UpdateProfileController } from "../controller/UpdateProfileController.js";
import { ChangePasswordController } from "../controller/ChangePasswordController.js";
import { AvatarController, uploadAvatar } from "../controller/AvatarController.js";

export const authRoutes = Router();

authRoutes.post("/register", RegisterController.register);
authRoutes.post("/verify-otp", VerifyOTPController.verify);
authRoutes.post("/complete-registration", CompleteRegistrationController.complete);
authRoutes.post("/login", LoginController.login);
authRoutes.post("/oauth", OAuthController.login);
authRoutes.post("/check-email", CheckEmailController.check);
authRoutes.post("/request-password-reset", RequestPasswordResetController.request);
authRoutes.post("/reset-password", ResetPasswordController.reset);
authRoutes.post("/complete-profile", CompleteProfileController.complete);
authRoutes.post("/logout", LogoutController.logout);
authRoutes.put("/profile", UpdateProfileController.update);
authRoutes.put("/change-password", ChangePasswordController.change);
authRoutes.post("/change-password/send-otp", ChangePasswordController.sendOTP);
authRoutes.post("/avatar", uploadAvatar, AvatarController.upload);
