const { q, SRC } = require('./fe_data.cjs');
const { TEST_SRC } = require('./qa_data.cjs');

// 2. AUTOMATION TESTER (SELENIUM/PLAYWRIGHT)
const autoTestQuestions = [
  // Foundation (6)
  q("AUTO_TEST-FOUND-01", "Automation Tester (Selenium/Playwright)", "foundation", "intermediate", "middle",
    "So sánh kiến trúc bên dưới của Microsoft Playwright và Selenium WebDriver: Cơ chế giao tiếp qua Chrome DevTools Protocol / BiDi (WebSocket một kết nối) của Playwright khác gì với HTTP JSON Wire Protocol / W3C WebDriver của Selenium?",
    ["Selenium gửi từng lệnh HTTP request riêng lẻ đến WebDriver binary, độ trễ mạng lớn và dễ bị timeout", "Playwright duy trì một kết nối WebSocket trực tiếp duy nhất với trình duyệt, lắng nghe sự kiện DOM thời gian thực hai chiều", "Playwright hỗ trợ đa tiến trình cô lập (Browser Contexts) trong cùng một instance trình duyệt, giúp chạy hàng trăm bài test song song cực nhẹ"],
    ["Tại sao kiến trúc WebSocket giúp Playwright tự động chờ (Auto-waiting) thông minh hơn Selenium?", "Cơ chế W3C WebDriver BiDi mới trong Selenium 4 cải thiện những gì so với phiên bản cũ?"] ,
    ["Playwright", "Selenium", "WebDriver", "Architecture", "CDP"],
    [TEST_SRC.playwright, TEST_SRC.selenium],
    ["Cho rằng Playwright và Selenium chỉ khác nhau về cú pháp ngôn ngữ viết test"]
  ),
  q("AUTO_TEST-FOUND-02", "Automation Tester (Selenium/Playwright)", "foundation", "intermediate", "middle",
    "Thiết kế mô hình Page Object Model (POM) và Component Object Model trong kiểm thử tự động: Tại sao POM giúp giảm thiểu chi phí bảo trì test script khi giao diện người dùng (UI) thay đổi?",
    ["POM đóng gói cấu trúc định vị phần tử (Locators) và các hành vi tương tác của trang vào một Class độc lập", "Tách rời hoàn toàn mã kiểm thử (Test Scripts & Assertions) khỏi mã giao diện (UI Locators)", "Khi giao diện đổi cấu trúc HTML, chỉ cần cập nhật selector tại duy nhất một nơi trong Page Object class mà không phải sửa hàng chục file test"],
    ["Sự khác biệt giữa Page Object Model và Screenplay Pattern trong kiểm thử tự động là gì?", "Làm thế nào để tránh việc biến Page Object thành 'God Class' chứa hàng trăm phương thức lộn xộn?"] ,
    ["Page Object Model", "POM", "Test Architecture", "Maintainability"],
    [TEST_SRC.playwright],
    ["Hardcode selector trực tiếp trong các câu lệnh test lặp đi lặp lại khắp mọi file"]
  ),
  q("AUTO_TEST-FOUND-03", "Automation Tester (Selenium/Playwright)", "foundation", "advanced", "senior_lead",
    "Nguyên nhân gốc rễ và chiến lược loại bỏ hiện tượng 'Kiểm thử không ổn định' (Flaky Tests - lúc pass lúc fail): Tại sao việc lạm dụng lệnh chờ cứng (`Thread.sleep()`) lại là giải pháp tồi tệ nhất?",
    ["Flaky tests thường do: bất đồng bộ mạng (AJAX/Fetch chưa xong), hiệu ứng animation đang chạy, phần tử bị che khuất, hoặc phụ thuộc dữ liệu chung", "`Thread.sleep()` làm chậm toàn bộ test suite một cách vô ích và vẫn có thể fail nếu mạng đột ngột chậm hơn thời gian sleep", "Giải pháp chuẩn: sử dụng Auto-waiting dựa trên trạng thái (Actionability checks: visible, enabled, stable) và cơ chế Polling Assertions (`expect().toPass()`)"],
    ["Làm thế nào để đo lường tỷ lệ Flaky Test Rate của toàn bộ test suite trên CI/CD dashboard?", "Cơ chế Test Retry tự động có nên được bật vô tội vạ để che giấu flaky tests không?"] ,
    ["Flaky Tests", "Auto-waiting", "Thread.sleep Anti-pattern", "Test Stability"],
    [TEST_SRC.playwright],
    ["Khuyên chèn `Thread.sleep(5000)` vào mọi bước test để giải quyết lỗi không tìm thấy phần tử"]
  ),
  q("AUTO_TEST-FOUND-04", "Automation Tester (Selenium/Playwright)", "foundation", "basic", "junior",
    "Chiến lược lựa chọn bộ định vị phần tử (Locators Strategy): So sánh mức độ tin cậy và độ bền vững giữa ID, Data Attributes (`data-testid`), XPath, CSS Selector, và User-facing Locators (getByRole, getByText)?",
    ["User-facing locators (`getByRole`, `getByLabel`) và `data-testid` có độ bền vững cao nhất, không bị ảnh hưởng khi đổi cấu trúc CSS layout", "XPath tuyệt đối (`/html/body/div[2]/div[1]/button`) cực kỳ mỏng manh, sẽ hỏng ngay khi có một thay đổi nhỏ về DOM", "CSS selector theo class trang trí (`.btn-primary-v2`) dễ bị phá vỡ khi designer cập nhật lại stylesheet"],
    ["Khi nào việc sử dụng XPath tương đối (`//button[contains(text(), ...)]`) vẫn là lựa chọn bắt buộc?", "Làm thế nào để thuyết phục đội Frontend cam kết gắn `data-testid` chuẩn cho các phần tử quan trọng?"] ,
    ["Locators Strategy", "data-testid", "getByRole", "XPath", "CSS Selector"],
    [TEST_SRC.playwright],
    ["Lấy toàn bộ selector bằng cách click chuột phải 'Copy Full XPath' từ Chrome DevTools"]
  ),
  q("AUTO_TEST-FOUND-05", "Automation Tester (Selenium/Playwright)", "foundation", "intermediate", "middle",
    "Cơ chế quản lý trạng thái lưu trữ và phiên đăng nhập (Storage State / Cookies / Session Storage) trong Playwright: Làm thế nào để đăng nhập một lần duy nhất và tái sử dụng phiên cho hàng trăm bài test tiếp theo?",
    ["Thực hiện đăng nhập trong bước Global Setup, lưu toàn bộ cookies và localStorage vào tệp `auth.json`", "Các bài test sau chỉ cần nạp `storageState: 'auth.json'` vào Browser Context để khởi động trực tiếp ở trạng thái đã đăng nhập", "Tiết kiệm 80-90% tổng thời gian chạy test suite vì không phải gõ username/password lại ở mỗi ca test"],
    ["Làm thế nào để xử lý kiểm thử đồng thời nhiều vai trò người dùng (Admin và User) trong cùng một kịch bản test?", "Cách xử lý khi token đăng nhập lưu trong storageState bị hết hạn giữa chừng?"] ,
    ["Storage State", "Authentication Sharing", "Execution Speed", "Session Reuse"],
    [TEST_SRC.playwright],
    ["Bắt mọi test case đều phải mở trang đăng nhập và gõ lại mật khẩu từ đầu"]
  ),
  q("AUTO_TEST-FOUND-06", "Automation Tester (Selenium/Playwright)", "foundation", "advanced", "senior_lead",
    "Kim tự tháp kiểm thử tự động (Test Automation Pyramid): Tỷ lệ phân bổ lý tưởng giữa Unit Test, API/Integration Test, và UI E2E Test là gì? Tại sao các tổ chức cố gắng tự động hóa 100% bằng UI test thường thất bại (mô hình Ice-cream Cone)?",
    ["Tỷ lệ lý tưởng: 70% Unit Test (nhanh, rẻ, cô lập), 20% API/Integration Test (ổn định, bao quát luồng dữ liệu), 10% UI E2E Test (kiểm tra luồng cốt lõi)", "Mô hình ngược Ice-cream Cone: quá nhiều UI test dẫn đến thời gian chạy hàng giờ, chi phí bảo trì khổng lồ, và liên tục bị fail ảo", "Nguyên tắc: Đẩy việc kiểm thử xuống tầng thấp nhất có thể; chỉ dùng UI test cho các luồng hành trình người dùng thực sự quan trọng"],
    ["Làm thế nào để chuyển đổi các ca test validation logic từ tầng UI xuống tầng API testing?", "Chi phí ROI của việc duy trì một bộ test UI tự động được tính toán dựa trên các thông số nào?"] ,
    ["Test Automation Pyramid", "Ice-cream Cone Anti-pattern", "ROI of Automation", "Testing Strategy"],
    [TEST_SRC.istqb],
    ["Cho rằng mục tiêu của Automation Tester là phải tự động hóa 100% mọi thứ bằng giao diện UI"]
  ),

  // Practical Skills (8)
  q("AUTO_TEST-SKILL-01", "Automation Tester (Selenium/Playwright)", "practical_skills", "advanced", "senior_lead",
    "Thiết kế cấu trúc thư mục và kiến trúc Framework kiểm thử tự động hoàn chỉnh từ con số 0 (sử dụng TypeScript/Java/Python): Em tổ chức các tầng Config, BasePage, Fixtures, Utilities, Test Data, và Reporters ra sao?",
    ["Tầng Config: quản lý biến môi trường, timeout, trình duyệt, base URL; BasePage: chứa các wrapper tương tác an toàn", "Fixtures: cung cấp các tài nguyên test được quản lý vòng đời tự động (Page, UserContext, DB connection)", "Tách biệt Test Data (JSON/Faker) và Test Scripts; tích hợp báo cáo Allure Report tự động chụp ảnh khi fail"],
    ["Làm thế nào để triển khai Custom Fixtures trong Playwright để tự động khởi tạo dữ liệu mẫu trước mỗi test?", "Chiến lược quản lý mã nguồn framework theo mô hình Clean Code để cả nhóm cùng đóng góp dễ dàng?"] ,
    ["Framework Architecture", "Playwright Fixtures", "Clean Code", "Custom Runners"],
    [TEST_SRC.playwright],
    ["Viết toàn bộ code khởi tạo browser, login và test dồn vào một file kịch bản dài nghìn dòng"]
  ),
  q("AUTO_TEST-SKILL-02", "Automation Tester (Selenium/Playwright)", "practical_skills", "intermediate", "middle",
    "Kỹ thuật xử lý các phần tử phức tạp trên giao diện: Em tương tác với iFrames, Shadow DOM, Modal dialogs, và Cửa sổ mới (Multiple Browser Tabs/Windows) trong Playwright/Selenium như thế nào?",
    ["Playwright tự động xuyên qua Shadow DOM mặc định mà không cần cú pháp đặc biệt; Selenium cần dùng `getShadowRoot()`", "iFrames: dùng `frameLocator()` trong Playwright hoặc `switchTo().frame()` trong Selenium để chuyển ngữ cảnh an toàn", "Multiple Tabs: dùng sự kiện `context.waitForEvent('page')` để bắt lấy tab mới mở và thực hiện assertions"],
    ["Làm thế nào để xử lý các hộp thoại hệ thống native (Alert, Confirm, File Chooser) trong Playwright?", "Cách tương tác với các phần tử vẽ trên HTML5 `<canvas>` hoặc đồ họa SVG?"] ,
    ["iFrames", "Shadow DOM", "Multiple Tabs", "File Upload", "Complex UI"],
    [TEST_SRC.playwright],
    ["Bó tay không tương tác được khi phần tử nằm bên trong một thẻ iframe nhúng"]
  ),
  q("AUTO_TEST-SKILL-03", "Automation Tester (Selenium/Playwright)", "practical_skills", "intermediate", "middle",
    "Chặn và giả lập lưu lượng mạng (Network Mocking & Interception) trong kiểm thử tự động: Em sử dụng phương thức `page.route()` của Playwright để mock phản hồi API, giả lập lỗi 500, hoặc làm chậm mạng (Network Throttling) ra sao?",
    ["Sử dụng `page.route('**/api/v1/orders', route => route.fulfill({ status: 500 }))` để kiểm tra khả năng hiển thị thông báo lỗi của UI mà không cần can thiệp server thật", "Mock các dữ liệu trả về phức tạp để kiểm thử các trạng thái giao diện hiếm gặp (tài khoản VIP, giỏ hàng có 100 món)", "Hủy bỏ việc tải các tài nguyên nặng không cần thiết (Google Analytics, font chữ, banner ngoài) để tăng tốc độ chạy test lên 50%"],
    ["Khi nào việc lạm dụng Mock API làm mất đi giá trị của bài test E2E thực sự?", "Làm thế nào để ghi lại (HAR recording) và phát lại lưu lượng mạng cho các bài test ngoại tuyến?"] ,
    ["Network Interception", "API Mocking", "HAR Recording", "Negative Testing"],
    [TEST_SRC.playwright],
    ["Chỉ biết test với dữ liệu thật của backend mà không biết cách mock API để kiểm thử các kịch bản lỗi"]
  ),
  q("AUTO_TEST-SKILL-04", "Automation Tester (Selenium/Playwright)", "practical_skills", "advanced", "senior_lead",
    "Tối ưu hóa thời gian thực thi: Em thiết lập chạy kiểm thử song song (Parallel Execution) trên nhiều Workers trong Playwright hoặc Selenium Grid/Docker như thế nào? Cách giải quyết xung đột dữ liệu dùng chung (Data Collisions)?",
    ["Cấu hình số lượng Workers tối ưu dựa trên số lõi CPU của máy chạy test (vd: `workers: 4`)", "Đảm bảo tính độc lập tuyệt đối giữa các test case (No Shared State): mỗi test case tự sinh tài khoản hoặc dữ liệu mẫu ngẫu nhiên (Faker.js)", "Sử dụng tag (`@smoke`, `@regression`) để phân chia các bộ test chạy theo lịch trình khác nhau trong CI"],
    ["Tại sao việc nhiều bài test cùng đăng nhập vào 1 tài khoản test duy nhất sẽ làm hỏng hoàn toàn việc chạy song song?", "Cách cấu hình Docker shm-size (`/dev/shm`) để tránh crash trình duyệt Chrome khi chạy song song?"] ,
    ["Parallel Execution", "Workers Optimization", "Selenium Grid", "Data Isolation"],
    [TEST_SRC.playwright],
    ["Viết các test case có thứ tự phụ thuộc lẫn nhau (Test B chỉ chạy được nếu Test A chạy pass)"]
  ),
  q("AUTO_TEST-SKILL-05", "Automation Tester (Selenium/Playwright)", "practical_skills", "intermediate", "middle",
    "Tích hợp Automation Test vào CI/CD Pipeline (GitHub Actions / GitLab CI): Em cấu hình workflow tự động kích hoạt test khi có Pull Request mới, lưu trữ Video/Trace/Screenshot khi test fail, và xuất bản báo cáo HTML ra sao?",
    ["Viết file cấu hình `.github/workflows/test.yml` cài đặt môi trường Node, cache dependencies và cài đặt browser binaries", "Cấu hình lưu trữ Artifacts (`actions/upload-artifact`) để tự động upload thư mục báo cáo khi có bước test bị fail", "Tích hợp Playwright Trace Viewer (`trace: 'on-first-retry'`) cho phép xem lại từng frame video và log mạng của lần chạy bị lỗi"],
    ["Làm thế nào để gửi thông báo tóm tắt kết quả kiểm thử (Slack / Telegram Webhook) sau khi pipeline hoàn tất?", "Cách thiết lập cơ chế chạy thử nghiệm (Canary run) trước khi merge code vào nhánh main?"] ,
    ["CI/CD Integration", "GitHub Actions", "Trace Viewer", "Artifacts", "Allure Report"],
    [TEST_SRC.playwright],
    ["Chỉ biết chạy test trên máy tính cá nhân bằng lệnh npm test mà không biết cách đưa vào CI/CD"]
  ),
  q("AUTO_TEST-SKILL-06", "Automation Tester (Selenium/Playwright)", "practical_skills", "intermediate", "middle",
    "Kiểm thử hồi quy thị giác (Visual Regression Testing): Em thiết lập kiểm thử so sánh ảnh chụp màn hình tự động (`toHaveScreenshot()`) trong Playwright như thế nào? Cách xử lý các yếu tố động (giờ hệ thống, ảnh quảng cáo, avatar động) để tránh so sánh sai lệch (False Failures)?",
    ["Sử dụng lệnh `expect(page).toHaveScreenshot('landing.png')` để so sánh với ảnh chuẩn (Golden Baseline)", "Che mờ hoặc ẩn các phần tử động bằng tùy chọn `mask: [locator]` (đồng hồ thời gian, banner quảng cáo, dữ liệu ngẫu nhiên)", "Điều chỉnh ngưỡng dung sai (threshold / pixel ratio) để bỏ qua các sai lệch siêu nhỏ do render font chữ trên các hệ điều hành khác nhau"],
    ["Tại sao việc chạy Visual Test trên máy Mac của dev lại ra kết quả khác với khi chạy trên máy chủ Linux trong CI?", "Làm thế nào để cập nhật hàng loạt ảnh baseline (`--update-snapshots`) khi có sự thay đổi thiết kế giao diện chính thức?"] ,
    ["Visual Regression", "Screenshot Testing", "Pixel Comparison", "Masking Dynamic Content"],
    [TEST_SRC.playwright],
    ["So sánh ảnh toàn màn hình có chứa cả đồng hồ đếm ngược dẫn đến việc test bị fail 100% mọi lần chạy"]
  ),
  q("AUTO_TEST-SKILL-07", "Automation Tester (Selenium/Playwright)", "practical_skills", "intermediate", "middle",
    "Kiểm thử hiệu năng trang web và khả năng tiếp cận (Accessibility Testing) tự động: Cách tích hợp thư viện `@axe-core/playwright` và thu thập các chỉ số Web Vitals trực tiếp trong kịch bản kiểm thử tự động?",
    ["Tích hợp AxeBuilder để tự động quét toàn bộ cây DOM tìm các vi phạm chuẩn WCAG 2.1 (độ tương phản màu sắc, thiếu thẻ alt, thiếu nhãn form)", "Sử dụng Chrome DevTools Protocol để trích xuất các chỉ số hiệu năng (LCP, CLS, TTFB) sau khi trang tải xong", "Thiết lập quy tắc gãy build (Assertion failure) nếu phát hiện bất kỳ lỗi accessibility nào ở mức độ Critical"],
    ["Làm thế nào để tạo báo cáo vi phạm accessibility chi tiết xuất ra định dạng JSON/HTML?", "Cách bỏ qua (Exclude) tạm thời một số lỗi a11y của thư viện ngoài trong khi chờ nhà cung cấp sửa chữa?"] ,
    ["Axe-core", "Accessibility Automation", "Web Vitals", "Automated Audit"],
    ["https://github.com/dequelabs/axe-core-npm/tree/develop/packages/playwright"],
    ["Chỉ kiểm tra tính năng chức năng (Functional) mà bỏ qua hoàn toàn việc kiểm thử tự động các tiêu chuẩn accessibility"]
  ),
  q("AUTO_TEST-SKILL-08", "Automation Tester (Selenium/Playwright)", "practical_skills", "advanced", "senior_lead",
    "Quản lý dữ liệu kiểm thử động (Dynamic Test Data Generation): Em sử dụng thư viện Faker.js kết hợp trực tiếp gọi API Backend để chuẩn bị trạng thái dữ liệu (Pre-condition setup) trước khi chạy UI test ra sao?",
    ["Không dùng UI để chuẩn bị dữ liệu: gọi thẳng API Backend (sử dụng Playwright `request` context) để tạo nhanh tài khoản, nạp tiền và tạo đơn hàng trong 100ms", "Dùng Faker.js sinh dữ liệu ngẫu nhiên hợp lệ (email, số điện thoại, tên tuổi) đảm bảo tính duy nhất cho mỗi bài test", "Tự động dọn dẹp (Teardown) dữ liệu sau khi test xong bằng API DELETE hoặc khôi phục snapshot database"],
    ["Tại sao việc chuẩn bị dữ liệu qua API lại giúp bộ test E2E chạy nhanh hơn gấp 5 lần so với làm qua giao diện UI?", "Chiến lược quản lý dữ liệu kiểm thử phân tán khi nhiều môi trường test dùng chung 1 database?"] ,
    ["Test Data Management", "Faker.js", "API Preconditions", "Speed Optimization"],
    [TEST_SRC.playwright],
    ["Dùng UI để click chuột qua 15 bước chỉ để tạo một dữ liệu mẫu phục vụ cho việc kiểm thử tính năng khác"]
  ),

  // Scenario (6)
  q("AUTO_TEST-SCEN-01", "Automation Tester (Selenium/Playwright)", "scenario", "advanced", "senior_lead",
    "Tình huống: Bộ kiểm thử tự động gồm 600 test cases chạy trên pipeline CI/CD mất hơn 1 tiếng 45 phút, làm chậm nghiêm trọng quy trình phát hành của toàn công ty. Các nhà phát triển bắt đầu phàn nàn và bỏ qua kết quả test. Em lập kế hoạch tối ưu hóa để rút ngắn thời gian chạy xuống dưới 15 phút ra sao?",
    ["Chuyển đổi các kịch bản kiểm tra logic phức tạp từ tầng UI sang tầng API Testing (loại bỏ các UI test dư thừa)", "Tái sử dụng phiên đăng nhập (Storage State) để loại bỏ bước đăng nhập lặp lại ở 600 bài test", "Kích hoạt chạy song song (Parallel execution) chia tải qua nhiều Docker containers hoặc GitHub Actions Matrix (Sharding 4-8 shards)"],
    ["Làm thế nào để sử dụng tính năng Sharding trong Playwright (`--shard=1/4`) để chia tải đều cho 4 máy chủ CI?", "Chặn tải các tài nguyên không cần thiết (hình ảnh nặng, mã tracking ngoài) đóng góp gì vào việc giảm thời gian?"] ,
    ["Execution Time Optimization", "Sharding", "Parallelism", "CI Bottleneck"],
    [TEST_SRC.internal],
    ["Đề xuất mua máy chủ có cấu hình mạnh hơn gấp 10 lần mà không tối ưu hóa mã nguồn kịch bản test"]
  ),
  q("AUTO_TEST-SCEN-02", "Automation Tester (Selenium/Playwright)", "scenario", "intermediate", "middle",
    "Tình huống: Một bài test kiểm thử luồng thanh toán giỏ hàng chạy trên máy tính cá nhân (Local) luôn thành công 100%, nhưng khi chạy trên máy chủ CI (Headless Linux Docker) thì bị fail ngẫu nhiên 40% các lần chạy. Em điều tra và khắc phục sự cố môi trường này thế nào?",
    ["Bật chế độ chụp Video và Trace Viewer của Playwright trên CI để xem lại chính xác những gì đã xảy ra tại thời điểm fail", "Kiểm tra sự khác biệt về kích thước màn hình mặc định (Viewport): môi trường Headless thường có resolution nhỏ làm ẩn nút bấm vào menu burger", "Kiểm tra sự khác biệt về múi giờ (Timezone UTC vs Local), ngôn ngữ hệ thống, và tốc độ mạng trên máy chủ CI"],
    ["Làm thế nào để đồng bộ kích thước Viewport cố định (`viewport: { width: 1920, height: 1080 }`) trong cấu hình framework?", "Cách debug trực tiếp trên môi trường Docker bằng giao diện đồ họa (VNC viewer) khi cần thiết?"] ,
    ["Headless Debugging", "CI Failure", "Trace Viewer", "Viewport Difference"],
    [TEST_SRC.playwright, TEST_SRC.internal],
    ["Đoán mò và liên tục commit mã thử nghiệm lên git để 'cầu may' cho pipeline chạy pass"]
  ),
  q("AUTO_TEST-SCEN-03", "Automation Tester (Selenium/Playwright)", "scenario", "intermediate", "middle",
    "Tình huống: Đội ngũ Frontend thay đổi toàn bộ thư viện UI component từ Bootstrap sang Tailwind CSS và đổi cấu trúc DOM, khiến 70% bộ test tự động của em bị báo lỗi 'Element not found' đồng loạt. Em xử lý khủng hoảng này ra sao và phòng ngừa cho tương lai?",
    ["Tập trung sửa chữa các lớp Page Object tương ứng thay vì sửa từng file test (nếu đã áp dụng POM chuẩn thì chỉ cần sửa tại 1 nơi duy nhất)", "Làm việc với đội Frontend để thống nhất gắn các thuộc tính `data-testid` hoặc `aria-label` bất biến, độc lập với class CSS của Tailwind", "Cập nhật các locator sang dạng hướng tới người dùng (User-facing locators như `getByRole('button', { name: 'Thanh toán' })`) để không bao giờ bị phụ thuộc vào class CSS nữa"],
    ["Tại sao việc sử dụng CSS class làm locator trong dự án dùng Tailwind CSS là một sai lầm chết người?", "Quy trình phối hợp giữa Frontend và QA khi có đợt tái cấu trúc giao diện lớn (UI Revamp) là gì?"] ,
    ["UI Revamp", "Broken Locators", "Tailwind CSS", "data-testid Governance"],
    [TEST_SRC.internal],
    ["Đi sửa thủ công hàng trăm file test bằng cách paste lại các class mới của Tailwind vào"]
  ),
  q("AUTO_TEST-SCEN-04", "Automation Tester (Selenium/Playwright)", "scenario", "advanced", "senior_lead",
    "Tình huống: Ứng dụng tích hợp tính năng xác thực hai yếu tố (2FA / OTP qua Email hoặc SMS) khi đăng nhập. Kịch bản kiểm thử tự động E2E bị chặn lại ở bước nhập mã OTP 6 số. Em giải quyết bài toán tự động hóa luồng 2FA này như thế nào?",
    ["Giải pháp 1 (TOTP): Sử dụng thuật toán Time-based One-Time Password với thư viện `otplib` bằng Secret Key dùng chung để tự sinh mã 6 số hợp lệ trong code test", "Giải pháp 2 (Email Mock/API): Sử dụng dịch vụ Mailosaur hoặc Mailpit để đọc mã OTP tự động từ hộp thư test qua API", "Giải pháp 3 (Bypass in Test): Thống nhất với Backend cung cấp tài khoản test chuyên dụng có mã OTP cố định hoặc header bí mật trên môi trường Staging"],
    ["Tại sao không bao giờ nên dùng số điện thoại thật để nhận SMS OTP trong kiểm thử tự động?", "Làm thế nào để đảm bảo cơ chế bypass trên Staging tuyệt đối không bị lọt lên môi trường Production?"] ,
    ["2FA Automation", "OTP Handling", "TOTP Algorithm", "Mailosaur", "Security in Testing"],
    [TEST_SRC.internal],
    ["Tắt hoàn toàn tính năng 2FA trên toàn bộ hệ thống để làm automation cho dễ"]
  ),
  q("AUTO_TEST-SCEN-05", "Automation Tester (Selenium/Playwright)", "scenario", "intermediate", "middle",
    "Tình huống: Trang web có tính năng Infinite Scroll (cuộn chuột vô tận để tải thêm dữ liệu). Kịch bản test tự động cần cuộn xuống để tìm và bấm vào một phần tử nằm ở vị trí thứ 150. Em viết kịch bản cuộn và kiểm tra điều kiện dừng an toàn ra sao để tránh vòng lặp vô tận?",
    ["Viết vòng lặp có điều kiện dừng rõ ràng: kiểm tra sự xuất hiện của phần tử mục tiêu sau mỗi lần cuộn màn hình (`locator.scrollIntoViewIfNeeded()`)", "Thiết lập giới hạn số lần cuộn tối đa (Max Scroll Attempts = 20) và thời gian timeout để tránh vòng lặp vô tận nếu phần tử không tồn tại", "Đợi dữ liệu mới tải xong (chờ network idle hoặc chờ số lượng phần tử tăng lên) trước khi thực hiện lần cuộn tiếp theo"],
    ["Cách thay thế bằng việc gọi API để lấy trực tiếp dữ liệu thay vì cuộn chuột 50 lần trên UI?", "Xử lý virtual list (chỉ giữ một số lượng DOM node nhất định trong RAM khi cuộn) trong kịch bản test ra sao?"] ,
    ["Infinite Scroll", "Dynamic Loading", "Infinite Loop Prevention", "DOM Scrolling"],
    [TEST_SRC.internal],
    ["Viết vòng lặp `while (true)` cuộn chuột không có điều kiện thoát khiến test case bị treo vĩnh viễn"]
  ),
  q("AUTO_TEST-SCEN-06", "Automation Tester (Selenium/Playwright)", "scenario", "advanced", "senior_lead",
    "Tình huống: Khi kiểm thử tính năng tải file báo cáo PDF về máy, kịch bản test cần xác minh xem file PDF có thực sự được tải về thành công và nội dung bên trong file có chứa đúng tên khách hàng hay không. Em tự động hóa việc đọc và kiểm tra nội dung file nhị phân này ra sao?",
    ["Sử dụng sự kiện `page.waitForEvent('download')` trong Playwright để bắt lấy đối tượng tệp tin được tải xuống", "Lưu file vào thư mục tạm và sử dụng thư viện xử lý PDF (`pdf-parse`) để trích xuất văn bản từ tệp PDF thành chuỗi", "Thực hiện các câu lệnh `expect(pdfText).toContain('Tên khách hàng')` để xác minh nội dung chính xác mà không cần mở giao diện đọc PDF"],
    ["Làm thế nào để dọn dẹp các tệp tin tạm sau khi bài test hoàn tất để không làm đầy ổ đĩa CI?", "Cách kiểm tra các định dạng tệp khác như Excel (.xlsx) bằng thư viện `xlsx` hoặc CSV trong automation test?"] ,
    ["File Download", "PDF Parsing", "Binary Verification", "Automated Validation"],
    [TEST_SRC.playwright, TEST_SRC.internal],
    ["Chỉ kiểm tra nút bấm Tải về có bấm được không mà không xác minh xem file có tải về thật và nội dung có đúng không"]
  ),

  // CV Validation (5)
  q("AUTO_TEST-CV-01", "Automation Tester (Selenium/Playwright)", "cv_validation", "advanced", "senior_lead",
    "Trong dự án xây dựng Automation Framework được ghi trên CV của em: Em đã tự tay thiết kế những thành phần kiến trúc nào? Quy mô bộ test đạt bao nhiêu kịch bản và tỷ lệ bao phủ tự động hóa (Automation Coverage) là bao nhiêu phần trăm?",
    ["Mô tả cấu trúc framework: ngôn ngữ, công cụ cốt lõi, cơ chế quản lý cấu hình, báo cáo, logging", "Nêu rõ số liệu cụ thể: số lượng test cases tự động (vd: 300+ tests), thời gian chạy toàn bộ (vd: 12 phút với 4 workers), tần suất chạy trong CI", "Tỷ lệ bao phủ thực tế trên các luồng nghiệp vụ cốt lõi (Core Regression Flow)"],
    ["Những khó khăn kỹ thuật lớn nhất khi triển khai framework đó cho toàn đội ngũ là gì?", "Nếu được bắt đầu lại dự án đó, em sẽ lựa chọn công nghệ hoặc thư viện nào khác?"] ,
    ["Framework Design", "Scale", "Coverage Metric", "CV Deep Dive"],
    [TEST_SRC.internal],
    ["Chỉ viết vài script đơn giản theo mẫu có sẵn của người khác nhưng ghi nhận là tự xây dựng toàn bộ framework"]
  ),
  q("AUTO_TEST-CV-02", "Automation Tester (Selenium/Playwright)", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kỹ năng chuyển đổi từ Selenium sang Playwright. Em đã lập kế hoạch chuyển đổi như thế nào và sự khác biệt về độ ổn định cũng như thời gian thực thi sau khi chuyển đổi được đo lường ra sao?",
    ["Lý do chuyển đổi: Selenium chạy chậm, nhiều flaky tests do timing, cấu hình grid phức tạp", "Chiến lược chuyển đổi từng bước (Gradual Migration): viết tính năng mới bằng Playwright, chuyển đổi dần các module cũ có rủi ro cao", "Số liệu cải thiện rõ rệt: giảm thời gian chạy từ 45 phút xuống 8 phút, giảm tỷ lệ flaky tests từ 15% xuống dưới 1%"],
    ["Những tính năng nào của Playwright mà Selenium không có đã mang lại giá trị lớn nhất cho đội ngũ của em?", "Cách đào tạo các thành viên quen với Selenium chuyển sang viết cú pháp async/await của Playwright?"] ,
    ["Selenium to Playwright", "Migration Strategy", "ROI Metric", "CV Verification"],
    [TEST_SRC.internal],
    ["Nói chung chung là 'Playwright nhanh hơn' mà không đưa ra được số liệu so sánh cụ thể từ dự án thực tế"]
  ),
  q("AUTO_TEST-CV-03", "Automation Tester (Selenium/Playwright)", "cv_validation", "intermediate", "middle",
    "Em ghi nhận kinh nghiệm kiểm thử tự động API kết hợp với UI trên cùng một kịch bản kiểm thử (Hybrid Automation). Hãy dẫn chứng một bài test cụ thể mà việc kết hợp cả hai tầng đã mang lại hiệu quả vượt trội?",
    ["Mô tả kịch bản: Dùng API để chuẩn bị dữ liệu (tạo tài khoản, thêm sản phẩm vào kho trong 200ms) -> Dùng UI để thực hiện hành vi người dùng cần test (bấm thanh toán) -> Dùng API để đối soát trạng thái đơn hàng trong DB", "Lợi ích: tiết kiệm 80% thời gian thực thi so với làm toàn bộ qua UI và tăng độ tin cậy của bài test lên tối đa", "Sử dụng cùng một framework và chia sẻ context phiên đăng nhập liền mạch giữa API client và Browser page"],
    ["Làm thế nào để đồng bộ token xác thực từ API response vào browser cookies của Playwright?", "Khi bài test bị fail, làm sao để biết lỗi phát sinh từ tầng API hay tầng UI?"] ,
    ["Hybrid Automation", "API and UI Integration", "Execution Efficiency", "CV Verification"],
    [TEST_SRC.internal],
    ["Chưa từng kết hợp API vào UI test mà chỉ chạy hai bộ test tách biệt hoàn toàn"]
  ),
  q("AUTO_TEST-CV-04", "Automation Tester (Selenium/Playwright)", "cv_validation", "advanced", "senior_lead",
    "Em hãy kể về một con bọ (Bug) nghiêm trọng trên môi trường production mà chính bộ test tự động của em đã bắt được thành công ngay trong pipeline CI/CD trước khi kịp phát hành ra ngoài?",
    ["Mô tả cụ thể lỗi: lỗi tính sai thuế VAT trong giỏ hàng, lỗi vỡ giao diện thanh toán trên trình duyệt Safari, hoặc lỗi quyền hạn người dùng", "Cách bài test phát hiện ra lỗi: assertion nào đã kích hoạt báo động trong pipeline", "Tác động ngăn ngừa: giúp công ty tránh được tổn thất tài chính hoặc sự cố ngưng trệ dịch vụ nghiêm trọng"],
    ["Tại sao lập trình viên không phát hiện ra lỗi đó trong quá trình code và unit test?", "Sau sự cố đó, em có bổ sung thêm kịch bản kiểm thử biên nào liên quan không?"] ,
    ["Production Bug Prevention", "Automation Value", "CI/CD Safety Gate", "CV Verification"],
    [TEST_SRC.internal],
    ["Kể về một lỗi nhỏ không đáng kể hoặc thừa nhận bộ test tự động chưa bao giờ bắt được bug nào hữu ích"]
  ),
  q("AUTO_TEST-CV-05", "Automation Tester (Selenium/Playwright)", "cv_validation", "intermediate", "middle",
    "Trong dự án có cấu hình báo cáo Allure Report hoặc Playwright HTML Report trên CV, em đã tùy biến báo cáo để cung cấp thông tin hữu ích cho các bên liên quan (Developers, QA Lead, Management) như thế nào?",
    ["Tích hợp tự động đính kèm ảnh chụp màn hình (Screenshot on Failure), video ghi lại quá trình chạy, và log console của trình duyệt", "Phân loại test cases theo tính năng (Epics, Features, Stories), độ nghiêm trọng và môi trường kiểm thử", "Xuất bản báo cáo tự động lên GitHub Pages hoặc máy chủ nội bộ để toàn đội ngũ có thể truy cập xem kết quả tức thời"],
    ["Làm thế nào để theo dõi lịch sử xu hướng kết quả kiểm thử (History Trend) qua các lần chạy trên Allure Report?", "Cách gửi tóm tắt tỷ lệ Pass/Fail kèm đường link báo cáo lên kênh chat Slack của nhóm?"] ,
    ["Allure Report", "HTML Reporting", "Test Analytics", "Artifact Publishing", "CV Verification"],
    [TEST_SRC.internal],
    ["Chỉ đọc kết quả test qua màn hình console log đen trắng mà không có hệ thống báo cáo trực quan"]
  ),

  // Behavioral (5)
  q("AUTO_TEST-BEHAV-01", "Automation Tester (Selenium/Playwright)", "behavioral", "intermediate", "middle",
    "Khi bộ test tự động thường xuyên bị fail ảo (Flaky Tests) khiến các Developers mất niềm tin và coi kết quả kiểm thử tự động như 'tiếng ồn' (Noise) rồi tự ý bấm bypass để merge code, em hành động ra sao để khôi phục niềm tin?",
    ["Thừa nhận vấn đề một cách cầu thị: cách ly ngay các test case bị flaky ra khỏi pipeline chính (gắn tag `@quarantine` hoặc tắt tạm thời) để pipeline chạy xanh ổn định", "Tập trung điều tra và phân tích nguyên nhân gốc rễ của từng test flaky: sửa selector, tăng độ tin cậy chờ đợi, xử lý dữ liệu cô lập", "Chỉ đưa test case quay trở lại pipeline chính sau khi đã chứng minh nó chạy pass liên tục 50 lần không lỗi trên môi trường thử nghiệm"],
    ["Làm thế nào để duy trì văn hóa 'Đỏ là phải dừng' (Stop-the-line culture) khi pipeline test bị fail?", "Cách truyền thông minh bạch về độ ổn định của bộ test cho toàn thể đội ngũ kỹ thuật?"] ,
    ["Flaky Test Quarantine", "Restoring Trust", "Engineering Discipline", "Test Reliability"],
    [TEST_SRC.internal],
    ["Bảo thủ cho rằng code test của mình không có lỗi và đổ lỗi cho máy chủ CI chạy chậm"]
  ),
  q("AUTO_TEST-BEHAV-02", "Automation Tester (Selenium/Playwright)", "behavioral", "basic", "junior",
    "Khi một lập trình viên phàn nàn rằng việc chạy bộ kiểm thử tự động của em trong Pull Request mất quá nhiều thời gian làm chậm tốc độ merge code của họ, em phản hồi và hợp tác giải quyết thế nào?",
    ["Lắng nghe với tinh thần thấu cảm: tốc độ phản hồi nhanh là nhu cầu chính đáng của lập trình viên để giữ nhịp độ công việc", "Tối ưu hóa pipeline phân tầng: trên Pull Request chỉ chạy bộ Smoke Test cốt lõi (chạy dưới 5 phút) để xác nhận nhanh; bộ Full Regression sẽ chạy vào ban đêm (Nightly build)", "Phân tích xem có kịch bản test nào bị nghẽn thời gian và tối ưu hóa chạy song song để rút ngắn thời gian hơn nữa"],
    ["Làm thế nào để cân bằng giữa tốc độ phản hồi nhanh cho Developer và độ an toàn chất lượng của sản phẩm?", "Cách giải thích để Developer hiểu rằng 5 phút chờ test sẽ tiết kiệm hàng giờ đi fix bug trên production?"] ,
    ["Developer Experience", "Pipeline Speed", "Smoke vs Regression", "Collaboration"],
    [TEST_SRC.internal],
    ["Phản ứng gay gắt cho rằng developer thiếu kiên nhẫn và từ chối tối ưu hóa thời gian chạy test"]
  ),
  q("AUTO_TEST-BEHAV-03", "Automation Tester (Selenium/Playwright)", "behavioral", "intermediate", "middle",
    "Trong nhóm có các bạn Manual QA lớn tuổi hoặc mới vào nghề còn e ngại việc học viết code tự động hóa. Em khuyến khích, hỗ trợ và chuyển giao kiến thức (Knowledge Transfer) cho các bạn ra sao?",
    ["Không tạo rào cản kỹ thuật phức tạp: bắt đầu bằng việc hướng dẫn các bạn sử dụng công cụ ghi nhận mã tự động (Playwright Codegen) để làm quen với cú pháp", "Xây dựng các Page Object và từ khóa dễ hiểu (Keyword-driven / Helper functions) để các bạn có thể viết test case tự động mà không cần hiểu sâu về kiến trúc", "Tổ chức các buổi workshop nội bộ cầm tay chỉ việc, động viên và ghi nhận công sức khi các bạn tự tay viết được bài test tự động đầu tiên"],
    ["Làm thế nào để phân chia công việc hài hòa giữa thành viên viết framework và thành viên viết test scripts?", "Cách xây dựng tài liệu hướng dẫn viết test (Contributing Guide) dễ hiểu cho người mới?"] ,
    ["Knowledge Transfer", "Mentorship", "Team Upskilling", "Empathy"],
    [TEST_SRC.internal],
    ["Tỏ thái độ thượng đẳng kỹ thuật xem thường các bạn Manual QA chỉ biết test tay"]
  ),
  q("AUTO_TEST-BEHAV-04", "Automation Tester (Selenium/Playwright)", "behavioral", "advanced", "senior_lead",
    "Trước áp lực từ ban quản lý muốn cắt giảm nhân sự kiểm thử thủ công và yêu cầu em phải tự động hóa 100% toàn bộ hệ thống trong vòng 3 tháng, em phân tích tính khả thi và tư vấn chiến lược cho lãnh đạo như thế nào?",
    ["Giải thích khách quan dựa trên nguyên lý khoa học kiểm thử: tự động hóa 100% là ảo tưởng phi thực tế (Unrealistic Expectation) và cực kỳ tốn kém", "Chỉ ra những phần việc mà máy móc không bao giờ thay thế được con người: Trải nghiệm người dùng (UX), Kiểm thử khám phá (Exploratory), và Đánh giá tính thẩm mỹ", "Đề xuất lộ trình tự động hóa thực tế (Automation Roadmap): tập trung 70-80% vào các tính năng hồi quy ổn định có ROI cao nhất, kết hợp kiểm thử thủ công thông minh"],
    ["Làm thế nào để tính toán chi phí duy trì bảo trì (Maintenance Cost) của test script để lãnh đạo thấy được bức tranh toàn cảnh?", "Cách trình bày bài toán đầu tư kiểm thử tự động một cách thuyết phục trước ban giám đốc?"] ,
    ["Realistic Expectations", "Automation Strategy", "Leadership Advisory", "ROI Analysis"],
    [TEST_SRC.internal],
    ["Hứa hão với ban giám đốc rằng mình sẽ làm được 100% rồi sau đó làm việc quá tải và thất bại toàn diện"]
  ),
  q("AUTO_TEST-BEHAV-05", "Automation Tester (Selenium/Playwright)", "behavioral", "intermediate", "middle",
    "Khi có sự bất đồng quan điểm giữa em và Tech Lead về việc nên chọn Cypress hay Playwright cho dự án mới, em tiếp cận thảo luận, lập bảng so sánh Proof of Concept (PoC) và đưa ra quyết định dựa trên những tiêu chí nào?",
    ["Không tranh luận cảm tính: cùng Tech Lead thống nhất bộ tiêu chí đánh giá kỹ thuật (Khả năng hỗ trợ đa tab, tốc độ chạy, hỗ trợ Safari/WebKit, hỗ trợ iframe, cộng đồng và giấy phép)", "Thực hiện bản PoC thực tế: viết thử cùng 3 kịch bản kiểm thử phức tạp của chính dự án trên cả 2 công cụ để đo đạc số liệu khách quan", "Trình bày kết quả minh bạch và tôn trọng quyết định cuối cùng của đội ngũ vì mục tiêu chung của sản phẩm"],
    ["Những nhược điểm cố hữu nào của Cypress (chạy trong cùng tab trình duyệt) mà Playwright đã giải quyết triệt để?", "Làm thế nào để duy trì tinh thần đồng đội tích cực sau khi cuộc thảo luận công nghệ kết thúc?"] ,
    ["PoC Evaluation", "Tool Selection", "Playwright vs Cypress", "Constructive Consensus"],
    [TEST_SRC.internal],
    ["Bảo thủ khăng khăng bảo vệ công cụ mình thích mà không chịu làm thử nghiệm đánh giá khách quan"]
  )
];

console.log("AUTO_TEST questions defined:", autoTestQuestions.length);
module.exports = { autoTestQuestions };
