const { q, SRC } = require('./fe_data.cjs');

const beQuestions = [
  // Foundation (6)
  q("BE-FOUND-01", "Backend Developer", "foundation", "intermediate", "middle",
    "Giải thích các cấp độ cô lập giao dịch (Transaction Isolation Levels) trong chuẩn ANSI SQL: Read Uncommitted, Read Committed, Repeatable Read và Serializable. Mỗi cấp độ phòng chống những hiện tượng bất thường (anomalies) nào?",
    ["Trình bày chính xác 4 cấp độ cô lập và cơ chế khóa bên dưới (MVCC, Shared/Exclusive Locks)", "Giải thích rõ ràng Dirty Read, Non-Repeatable Read, Phantom Read và Serialization Anomaly", "Nêu rõ cấp độ cô lập mặc định của PostgreSQL (Read Committed) và MySQL InnoDB (Repeatable Read)"],
    ["MVCC (Multi-Version Concurrency Control) giải quyết vấn đề Read vs Write không block nhau ra sao?", "Trong trường hợp nào Serializable gây ra hiệu năng sụt giảm nghiêm trọng?"],
    ["ACID", "Database", "Transaction Isolation", "MVCC"],
    ["https://www.postgresql.org/docs/current/transaction-iso.html"],
    ["Không phân biệt được Non-repeatable read và Phantom read"]
  ),
  q("BE-FOUND-02", "Backend Developer", "foundation", "intermediate", "middle",
    "Nguyên lý vận hành bên dưới của cấu trúc chỉ mục B-Tree và Hash Index trong cơ sở dữ liệu quan hệ là gì? Khi nào chỉ mục tổng hợp (Composite Index) không được sử dụng bởi Query Optimizer?",
    ["Hiểu B-Tree cân bằng độ cao O(log n), tối ưu cho truy vấn dải (range queries) và sắp xếp", "Nắm rõ nguyên tắc tiền tố bên trái nhất (Leftmost Prefix Rule) của Composite Index", "Giải thích chi phí ghi (write overhead) và phình to dung lượng khi tạo quá nhiều index"],
    ["Clustered Index và Non-Clustered Index khác nhau thế nào về lưu trữ con trỏ dữ liệu?", "Index Skip Scan là gì và hoạt động ra sao?"],
    ["Indexing", "B-Tree", "SQL Optimization", "Database Internals"],
    ["https://use-the-index-luke.com/"],
    ["Nghĩ rằng gắn index vào tất cả các cột sẽ giúp hệ thống luôn nhanh"]
  ),
  q("BE-FOUND-03", "Backend Developer", "foundation", "advanced", "senior_lead",
    "Phân biệt giữa Concurrency và Parallelism. Kiến trúc Event Loop (Single-threaded I/O non-blocking) của Node.js khác với mô hình Thread-per-request của Java truyền thống và Goroutines (M:N scheduling) của Go như thế nào?",
    ["Phân biệt rạch ròi giữa Concurrency (xử lý nhiều việc cùng lúc) và Parallelism (chạy đồng thời vật lý)", "Giải thích cách Node.js xử lý I/O bound qua libuv và nhược điểm khi gặp CPU bound", "So sánh chi phí cấp phát bộ nhớ: Thread OS (~1MB) vs Goroutine (~2KB) vs Java Virtual Threads"],
    ["Cơ chế Work Stealing trong Go runtime scheduler hoạt động như thế nào?", "Làm thế nào để xử lý tác vụ tính toán nặng trong Node.js mà không làm đóng băng Event Loop?"],
    ["Concurrency", "Event Loop", "Goroutines", "Thread Pool", "Go"],
    ["https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick"],
    ["Nhầm lẫn giữa Concurrency và Parallelism hoặc cho rằng Node.js là multi-threaded hoàn toàn"]
  ),
  q("BE-FOUND-04", "Backend Developer", "foundation", "intermediate", "middle",
    "So sánh giao thức truyền tải giữa RESTful (JSON qua HTTP/1.1) và gRPC (Protocol Buffers qua HTTP/2). Trường hợp nào nên sử dụng gRPC thay cho REST trong kiến trúc Backend?",
    ["Phân tích ưu thế của HTTP/2: multiplexing, header compression (HPACK), streaming 2 chiều", "Hiểu cơ chế serialize nhị phân gọn nhẹ của Protobuf so với văn bản JSON", "Chỉ ra use-case phù hợp: gRPC cho giao tiếp nội bộ giữa các Microservices, REST cho Public API client"],
    ["Làm thế nào để trình duyệt web gọi được dịch vụ gRPC qua gRPC-Web?", "Backward & Forward compatibility được quản lý thế nào trong Protocol Buffers?"],
    ["gRPC", "REST", "HTTP/2", "Protocol Buffers", "Microservices"],
    ["https://grpc.io/docs/what-is-grpc/core-concepts/"],
    ["Cho rằng gRPC có thể thay thế hoàn toàn REST trong mọi tình huống bao gồm public web"]
  ),
  q("BE-FOUND-05", "Backend Developer", "foundation", "advanced", "senior_lead",
    "Định lý CAP và định lý PACELC giải thích sự đánh đổi trong hệ thống phân tán như thế nào? Giữa tính nhất quán mạnh (Strong Consistency) và tính nhất quán cuối cùng (Eventual Consistency), em chọn mô hình nào cho luồng thanh toán ví điện tử?",
    ["Giải thích CAP: Consistency, Availability, Partition Tolerance - không thể đạt cả 3 khi có network partition", "Giải thích PACELC: Khi có Partition thì chọn A hay C, Else thì chọn Latency hay Consistency", "Phân tích luồng thanh toán tài chính bắt buộc Strong Consistency để tránh chi tiêu trùng (Double spending)"],
    ["Thuật toán đồng thuận Raft giải quyết bài toán Leader Election và Log Replication thế nào?", "Cơ chế 2PC (Two-Phase Commit) có nhược điểm gì trong microservices?"],
    ["CAP Theorem", "PACELC", "Distributed Systems", "Eventual Consistency"],
    ["https://en.wikipedia.org/wiki/CAP_theorem"],
    ["Khẳng định một hệ thống phân tán có thể đạt được cả 3 yếu tố C, A, P cùng lúc"]
  ),
  q("BE-FOUND-06", "Backend Developer", "foundation", "basic", "junior",
    "Bảo mật mật khẩu người dùng trong cơ sở dữ liệu: Tại sao không bao giờ được dùng MD5 hay SHA-256 thuần để hash mật khẩu? Các thuật toán như bcrypt, Argon2 và cơ chế Salt phòng chống tấn công Rainbow Table như thế nào?",
    ["Hiểu rằng SHA/MD5 được thiết kế để tính toán nhanh, dễ bị tấn công brute-force bằng GPU hiện đại", "Bcrypt và Argon2 tích hợp cost factor/work factor có thể điều chỉnh để làm chậm kẻ tấn công", "Salt ngẫu nhiên duy nhất cho mỗi tài khoản ngăn chặn hoàn toàn tấn công bằng Rainbow Table"],
    ["Argon2id vượt trội hơn bcrypt ở khả năng kháng tấn công bằng phần cứng chuyên dụng ASIC/GPU ra sao?", "Kỹ thuật Re-hashing mật khẩu khi nâng cấp cost factor diễn ra như thế nào?"],
    ["Security", "Password Hashing", "bcrypt", "Argon2", "Salt"],
    [SRC.owasp],
    ["Đề xuất mã hóa hai chiều mật khẩu (Reversible Encryption) thay vì dùng one-way salted hash"]
  ),

  // Practical Skills (8)
  q("BE-SKILL-01", "Backend Developer", "practical_skills", "advanced", "senior_lead",
    "Em cấu hình và tinh chỉnh Database Connection Pool (ví dụ HikariCP hoặc pgBouncer) như thế nào? Công thức ước tính kích thước pool tối ưu (Pool Size) dựa trên số lượng CPU core và tốc độ đĩa I/O?",
    ["Áp dụng công thức kinh điển của PostgreSQL: connections = ((core_count * 2) + effective_spindle_count)", "Hiểu nguy cơ khi đặt pool size quá lớn: context switching cao, cạn kiệt tài nguyên RAM máy chủ DB", "Cấu hình connection timeout, max lifetime và leak detection threshold để phát hiện rò rỉ kết nối"],
    ["Sự khác biệt giữa Session pooling và Transaction pooling trong pgBouncer là gì?", "Làm thế nào để giám sát trạng thái connection pool qua Prometheus metrics?"],
    ["HikariCP", "Connection Pooling", "PostgreSQL", "Database Optimization"],
    ["https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing"],
    ["Nghĩ rằng cứ tăng connection pool lên hàng ngàn kết nối là hệ thống sẽ xử lý nhanh hơn"]
  ),
  q("BE-SKILL-02", "Backend Developer", "practical_skills", "intermediate", "middle",
    "Các chiến lược caching với Redis: Cache-Aside, Write-Through, Write-Behind. Em làm thế nào để phòng chống 3 sự cố kinh điển: Cache Penetration, Cache Breakdown và Cache Avalanche?",
    ["Phân biệt Cache-Aside (đọc cache trước, miss thì đọc DB rồi ghi cache) với Write-Through", "Cache Penetration: dùng Bloom Filter hoặc cache kết quả null có TTL ngắn", "Cache Breakdown: dùng Mutex Lock phân tán; Cache Avalanche: thêm jitter ngẫu nhiên vào TTL"],
    ["Cơ chế Redis Sentinel vs Redis Cluster khác nhau thế nào về failover và sharding?", "Làm thế nào để xử lý cache eviction policy (LRU, LFU) khi Redis đầy RAM?"],
    ["Redis", "Caching Strategy", "Cache Avalanche", "Bloom Filter"],
    ["https://redis.io/docs/latest/develop/use/patterns/"],
    ["Không biết cách xử lý khi hàng triệu request cùng ập vào khi một key cache hết hạn (Breakdown)"]
  ),
  q("BE-SKILL-03", "Backend Developer", "practical_skills", "advanced", "senior_lead",
    "Khi sử dụng Message Queue (Kafka hoặc RabbitMQ) cho xử lý bất đồng bộ, em thiết kế kiến trúc phân vùng (Partitioning), Consumer Group và cơ chế Idempotent Consumer ra sao để đảm bảo dữ liệu không bị trùng lặp hoặc mất mát?",
    ["Chọn Partition Key phù hợp để đảm bảo thứ tự xử lý dữ liệu cho từng thực thể (ví dụ: userId)", "Thiết kế Consumer lưu trữ Message ID đã xử lý vào DB có Unique Constraint hoặc Redis atomic SETNX", "Cấu hình ACK thủ công (Manual Acknowledgment) chỉ sau khi business logic hoàn tất"],
    ["Hiện tượng Consumer Lag là gì và làm sao để scale consumer mà không vi phạm quy tắc số partition?", "Dead Letter Queue (DLQ) được thiết lập thế nào khi tin nhắn lỗi liên tục?"] ,
    ["Kafka", "Message Queue", "Idempotency", "Consumer Group"],
    ["https://kafka.apache.org/documentation/#intro_concepts_and_terms"],
    ["Mặc định tin tưởng message queue sẽ không bao giờ gửi trùng tin nhắn (at-least-once delivery)"]
  ),
  q("BE-SKILL-04", "Backend Developer", "practical_skills", "intermediate", "middle",
    "Chiến lược quản lý Database Migration không gián đoạn dịch vụ (Zero-Downtime Migration) bằng Expand and Contract pattern khi cần đổi tên cột hoặc tách bảng lớn trong môi trường production?",
    ["Giai đoạn Expand: thêm cột mới, cập nhật code để ghi đồng thời cả 2 cột (Dual-write) và đọc từ cột cũ", "Giai đoạn Backfill: chạy background script copy dữ liệu cũ sang mới theo batch nhỏ", "Giai đoạn Contract: chuyển đọc sang cột mới hoàn toàn và drop cột cũ an toàn"],
    ["Tại sao việc chạy lệnh ALTER TABLE thêm NOT NULL không có DEFAULT trên bảng 50 triệu dòng có thể làm treo database?", "Công cụ như gh-ost hoặc pt-online-schema-change giải quyết khóa bảng ra sao?"],
    ["Database Migration", "Zero-downtime", "Expand Contract", "Schema Design"],
    [SRC.internal],
    ["Chạy trực tiếp câu lệnh DROP COLUMN hoặc RENAME COLUMN trực tiếp trên production đang chịu tải"]
  ),
  q("BE-SKILL-05", "Backend Developer", "practical_skills", "intermediate", "middle",
    "Em xây dựng hệ thống Rate Limiting để bảo vệ API chống lạm dụng bằng thuật toán nào (Token Bucket, Leaky Bucket, Sliding Window Counter)? Cách triển khai phân tán với Redis?",
    ["So sánh: Token Bucket (hỗ trợ burst traffic), Leaky Bucket (tốc độ ra đều), Sliding Window (chính xác cao)", "Triển khai bằng Redis Sorted Set hoặc Redis Lua Script để đảm bảo tính nguyên tử (Atomicity)", "Trả về HTTP Status Code 429 Too Many Requests kèm header Retry-After và X-RateLimit-Remaining"],
    ["Làm thế nào để tránh race condition khi nhiều request từ cùng một user đến các server khác nhau?", "Tiered Rate Limiting theo cấp bậc tài khoản (Free vs Pro) được cấu hình thế nào?"],
    ["Rate Limiting", "Token Bucket", "Redis Lua", "API Protection"],
    [SRC.internal],
    ["Lưu đếm rate limit trong memory của từng instance máy chủ đơn lẻ thay vì tập trung hóa"]
  ),
  q("BE-SKILL-06", "Backend Developer", "practical_skills", "advanced", "senior_lead",
    "Trong kiến trúc Microservices, khi một nghiệp vụ trải dài qua 3 dịch vụ khác nhau (Order, Payment, Inventory), em áp dụng Saga Pattern theo mô hình Choreography hay Orchestration? Cách thiết kế Compensating Transactions (giao dịch bù trừ)?",
    ["Choreography: dịch vụ phát event qua Message Bus, phù hợp hệ thống đơn giản ít service", "Orchestration: có dịch vụ Saga Orchestrator quản lý state machine và điều phối, dễ debug và kiểm soát", "Compensating Transaction: hoàn trả trạng thái khi có bước thất bại (ví dụ: hoàn tiền nếu kho hết hàng)"],
    ["Saga giải quyết bài toán thiếu tính Isolation trong ACID như thế nào?", "Làm sao để đảm bảo Saga Orchestrator không trở thành điểm nghẽn đơn độc (Single Point of Failure)?"],
    ["Saga Pattern", "Microservices", "Compensating Transaction", "Distributed Architecture"],
    ["https://microservices.io/patterns/data/saga.html"],
    ["Nhầm lẫn Saga với 2-Phase Commit hoặc không chuẩn bị phương án hoàn tác khi bước sau bị lỗi"]
  ),
  q("BE-SKILL-07", "Backend Developer", "practical_skills", "intermediate", "middle",
    "Em thiết lập hệ thống Observability cho Backend bao gồm Structured Logging, Distributed Tracing (OpenTelemetry) và Metrics (Prometheus) như thế nào để phát hiện nút thắt cổ chai?",
    ["Gắn Trace ID và Span ID xuyên suốt các microservices qua HTTP headers (W3C TraceContext)", "Ghi log theo định dạng JSON có ngữ cảnh (userId, requestId, durationMs) thay vì ghi plain text", "Thiết lập chỉ số RED (Rate, Errors, Duration) và USE (Utilization, Saturation, Errors) cho services"],
    ["Lấy mẫu log và trace (Sampling Rate) được cấu hình ra sao để tiết kiệm chi phí lưu trữ?", "Sự khác biệt giữa Liveness Probe và Readiness Probe trong Kubernetes đối với backend service?"],
    ["OpenTelemetry", "Distributed Tracing", "Prometheus", "Observability"],
    ["https://opentelemetry.io/docs/concepts/observability-primer/"],
    ["Chỉ dùng console.log truyền thống không có cấu trúc hoặc không thể trace luồng qua nhiều service"]
  ),
  q("BE-SKILL-08", "Backend Developer", "practical_skills", "intermediate", "middle",
    "Chiến lược kiểm thử tự động cho Backend: Em viết Unit Test và Integration Test như thế nào? Cách sử dụng Testcontainers để kiểm thử tích hợp với database thật thay vì dùng H2 in-memory DB?",
    ["Unit test tập trung kiểm tra logic nghiệp vụ thuần túy bằng Mock/Stub (Mockito, Jest)", "Integration test dùng Testcontainers khởi tạo container PostgreSQL/Redis thật trong Docker, phản ánh đúng dialect", "Tránh rủi ro của in-memory DB (H2) do khác biệt về cú pháp SQL, jsonb và transaction lock"],
    ["Làm thế nào để tăng tốc độ chạy Integration Test với Testcontainers (reuse container)?", "Chiến lược làm sạch dữ liệu kiểm thử giữa các test cases để tránh phụ thuộc lẫn nhau?"],
    ["Testing", "Testcontainers", "Integration Test", "Docker"],
    ["https://testcontainers.com/"],
    ["Lạm dụng mock 100% trong kiểm thử DB dẫn đến test pass trên local nhưng lỗi cú pháp trên production"]
  ),

  // Scenario (6)
  q("BE-SCEN-01", "Backend Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Trong đợt Flash Sale, hệ thống phát hiện 2 giao dịch trừ tiền cùng một tài khoản diễn ra đồng thời dẫn đến số dư bị âm (Race Condition). Em phân tích và xử lý bằng Khóa lạc quan (Optimistic Lock) hay Khóa bi quan (Pessimistic Lock)?",
    ["Phân tích nguyên nhân: Lost Update do hai transaction đọc cùng số dư ban đầu rồi ghi đè lên nhau", "Optimistic Lock: thêm cột `version`, cập nhật `WHERE id = ? AND version = ?`, retry nếu thất bại (hợp với ít xung đột)", "Pessimistic Lock: dùng `SELECT ... FOR UPDATE` khóa dòng tại DB hoặc dùng Redis Distributed Lock Redlock"],
    ["Khi nào Pessimistic Lock gây ra nguy cơ nghẽn hàng đợi hoặc Deadlock?", "Tại sao không nên lock theo userId bằng Java synchronized trong môi trường chạy nhiều pod/instance?"],
    ["Race Condition", "Optimistic Lock", "Pessimistic Lock", "Concurrency"],
    [SRC.internal],
    ["Đề xuất dùng biến cờ (flag) trong memory của ứng dụng để kiểm tra số dư"]
  ),
  q("BE-SCEN-02", "Backend Developer", "scenario", "intermediate", "middle",
    "Tình huống: Vào giờ cao điểm, API Gateway liên tục báo lỗi 504 Gateway Timeout. Log backend cho thấy toàn bộ database connection pool đã bị cạn kiệt, thời gian chờ lấy kết nối tăng vọt. Em khoanh vùng và xử lý sự cố thế nào?",
    ["Kiểm tra pg_stat_activity hoặc SHOW PROCESSLIST để tìm các Slow Queries đang chiếm giữ connection", "Rà soát code xem có tình trạng mở connection nhưng gọi API bên thứ ba chậm bên trong transaction không", "Tạm thời tăng pool size trong giới hạn RAM máy chủ DB, ngắt các long-running query và áp dụng query timeout bắt buộc"],
    ["Làm thế nào để cô lập một query chậm không làm chết toàn bộ các endpoint khác?", "Tại sao không bao giờ nên thực hiện I/O mạng (gọi external API) bên trong một DB Transaction?"],
    ["Database Incident", "Connection Pool", "Slow Query", "Troubleshooting"],
    [SRC.internal],
    ["Chỉ tăng timeout của Nginx/Gateway mà không xử lý nguyên nhân gốc rễ connection bị chiếm giữ"]
  ),
  q("BE-SCEN-03", "Backend Developer", "scenario", "intermediate", "middle",
    "Tình huống: Một đối tác cổng thanh toán gửi webhook thông báo thanh toán thành công 3 lần liên tiếp trong 2 giây cho cùng một đơn hàng do cơ chế retry tự động. Hệ thống của em bị cộng điểm thưởng 3 lần. Em thiết kế lại logic idempotent ra sao?",
    ["Tạo bảng `processed_webhooks` lưu trữ `idempotency_key` hoặc `transaction_id` từ đối tác với Unique Constraint", "Thực hiện kiểm tra và chèn khóa trong một transaction nguyên tử trước khi kích hoạt logic cộng điểm", "Nếu khóa đã tồn tại, trả về HTTP 200 OK ngay lập tức kèm thông báo giao dịch đã được ghi nhận trước đó"],
    ["Nếu server đang xử lý dở dang thì webhook thứ hai ập đến, làm sao dùng Redis SETNX with TTL làm lock tạm?", "Tại sao vẫn phải trả về 200 OK cho đối tác thay vì trả về lỗi 400?"],
    ["Idempotency", "Webhook", "Payment Processing", "Distributed Lock"],
    [SRC.internal],
    ["Kiểm tra bằng câu lệnh SELECT thông thường rồi mới INSERT mà không có Unique Index dẫn đến race condition"]
  ),
  q("BE-SCEN-04", "Backend Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Dịch vụ backend viết bằng Node.js/Java chạy trên Kubernetes bị crash liên tục với mã lỗi OOMKilled (Exit Code 137) sau mỗi 6 tiếng hoạt động. Em thực hiện các bước thu thập thông tin và fix memory leak thế nào?",
    ["Cấu hình cờ JVM tự động tạo Heap Dump khi gặp OOM (-XX:+HeapDumpOnOutOfMemoryError) hoặc dùng v8-profiler cho Node.js", "Phân tích heap dump bằng Eclipse Memory Analyzer (MAT) hoặc Chrome DevTools Memory để tìm Dominator Tree", "Khoanh vùng nguyên nhân rò rỉ: lưu trữ cache trong biến static không có giới hạn kích thước, rò rỉ event listener hoặc unclosed resources"],
    ["Sự khác biệt giữa Memory Leak do code và cấu hình giới hạn RAM của container K8s quá thấp?", "Làm thế nào để thiết lập alert cảnh báo RAM tăng dần đều (Memory Leaking Trend) trên Grafana?"],
    ["Memory Leak", "OOMKilled", "Heap Dump", "Kubernetes"],
    [SRC.internal],
    ["Tự động khởi động lại pod định kỳ bằng cronjob thay vì tìm và sửa tận gốc memory leak"]
  ),
  q("BE-SCEN-05", "Backend Developer", "scenario", "intermediate", "middle",
    "Tình huống: Cơ sở dữ liệu báo lỗi Deadlock Detected khi nhiều luồng thực hiện cập nhật chéo giữa bảng đơn hàng và bảng kho hàng. Em phân tích đồ thị chờ đợi (Wait-for Graph) và sắp xếp lại thứ tự khóa thế nào?",
    ["Đọc Deadlock Log (LATEST DETECTED DEADLOCK trong MySQL hoặc log PostgreSQL) để xác định 2 transaction và 2 ổ khóa", "Nguyên tắc phòng ngừa: chuẩn hóa thứ tự cập nhật tài nguyên (luôn cập nhật bảng Order trước rồi đến Inventory, hoặc khóa theo ID tăng dần)", "Cấu hình retry logic tự động với khoảng nghỉ ngẫu nhiên khi bắt được lỗi deadlock"],
    ["Tại sao việc khóa theo thứ tự ID tăng dần (ORDER BY id ASC) lại ngăn chặn được deadlock trong batch update?", "Lock Escalation là gì và có thể dẫn đến deadlock bất ngờ ra sao?"],
    ["Deadlock", "Lock Ordering", "Database Concurrency", "Wait-for Graph"],
    [SRC.internal],
    ["Cho rằng deadlock là lỗi ngẫu nhiên của database và chỉ tăng deadlock_timeout để bỏ qua"]
  ),
  q("BE-SCEN-06", "Backend Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Ổ cứng máy chủ Database chính bị đầy 95% do bảng Audit Log lịch sử giao dịch tăng thêm 100GB mỗi tháng. Em thiết kế giải pháp phân vùng bảng (Table Partitioning) và lưu trữ dữ liệu nguội (Cold Storage) ra sao mà không gián đoạn dịch vụ?",
    ["Thiết kế Range Partitioning theo tháng hoặc năm cho bảng Audit Log", "Tạo partition mới tự động bằng pg_partman hoặc scheduler", "Xuất các partition cũ hơn 6 tháng thành file Parquet nén và tải lên Amazon S3 / Google Cloud Storage, sau đó DROP partition cũ trong DB"],
    ["Tại sao việc DROP một partition cũ lại nhanh hơn và không gây fragmentation so với chạy câu lệnh DELETE hàng triệu dòng?", "Làm thế nào để người dùng vẫn có thể tra cứu lịch sử cũ trên S3 bằng Athena/Trino khi cần?"],
    ["Table Partitioning", "Data Archival", "Database Maintenance", "S3 Cold Storage"],
    [SRC.internal],
    ["Chạy lệnh DELETE trực tiếp hàng triệu bản ghi làm nghẽn WAL log và khóa bảng nghiêm trọng"]
  ),

  // CV Validation (5)
  q("BE-CV-01", "Backend Developer", "cv_validation", "advanced", "senior_lead",
    "Trong dự án backend trên CV mà em đảm nhận hệ thống chịu tải cao nhất: Kiến trúc tổng thể gồm những thành phần nào, thông số QPS/RPS đỉnh điểm đạt bao nhiêu, và nút thắt cổ chai lớn nhất nằm ở đâu?",
    ["Mô tả mạch lạc kiến trúc: Gateway, Service layers, Caching, DB, Message Queue", "Nêu số liệu thực tế về throughput (RPS), độ trễ P95/P99 và cấu hình tài nguyên phần cứng", "Chỉ rõ nút thắt cổ chai thực sự (DB I/O, network bandwidth, CPU serialization) và giải pháp đã làm"],
    ["Nếu lưu lượng truy cập tăng gấp 5 lần hiện tại, thành phần nào sẽ sập đầu tiên?", "Tại sao em lại chọn mô hình cơ sở dữ liệu đó thay vì NoSQL hoặc ngược lại?"],
    ["Architecture", "System Scalability", "Throughput Profiling", "CV Deep Dive"],
    [SRC.internal],
    ["Đưa ra số liệu RPS hàng triệu không tương xứng với cấu hình hệ thống hoặc nói hệ thống không có nút thắt nào"]
  ),
  q("BE-CV-02", "Backend Developer", "cv_validation", "intermediate", "middle",
    "Em có ghi kinh nghiệm tối ưu hóa truy vấn SQL trên CV. Em hãy dẫn chứng một câu query cụ thể bị chậm, cách em đọc Execution Plan (EXPLAIN ANALYZE) để tìm nguyên nhân và kết quả sau khi tối ưu?",
    ["Chỉ rõ vấn đề phát hiện từ EXPLAIN: Seq Scan trên bảng lớn, Nested Loop không phù hợp, Sort trên đĩa", "Hành động cụ thể: thêm Composite Index, viết lại câu lệnh loại bỏ function trên cột được index, hoặc dùng CTE tối ưu", "Số liệu cải thiện rõ rệt: thời gian chạy từ vài giây xuống dưới 50ms, giảm số block read"],
    ["Tại sao đôi khi thêm index nhưng database optimizer vẫn quyết định chọn Sequential Scan?", "Chỉ số Cost trong EXPLAIN được tính toán dựa trên những yếu tố nào?"],
    ["EXPLAIN ANALYZE", "Query Optimization", "Execution Plan", "CV Verification"],
    [SRC.internal],
    ["Nói chung chung là 'thêm index' mà không nhớ được cấu trúc query hoặc không hiểu cách đọc EXPLAIN"]
  ),
  q("BE-CV-03", "Backend Developer", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu việc xây dựng hệ thống phân quyền Authentication & Authorization. Em đã triển khai mô hình RBAC (Role-Based) hay ABAC (Attribute-Based) và cơ chế kiểm tra quyền tại tầng API diễn ra như thế nào?",
    ["Mô tả cấu trúc bảng dữ liệu: Users, Roles, Permissions, User_Roles, Role_Permissions", "Giải thích cách đính kèm permissions vào JWT claims hoặc kiểm tra quyền qua Middleware/Interceptor với Redis cache", "Cách xử lý thu hồi quyền hạn tức thời (Revocation) khi admin thay đổi quyền của một user đang đăng nhập"],
    ["Sự khác biệt khi mở rộng từ RBAC sang ABAC cho các quy tắc phụ thuộc ngữ cảnh (vd: chỉ được sửa đơn hàng của chính mình)?", "Bảo mật chống tấn công BOLA (Broken Object Level Authorization) được triển khai ra sao?"],
    ["RBAC", "Authorization", "JWT", "Security Architecture"],
    [SRC.owasp, SRC.internal],
    ["Chỉ kiểm tra quyền dựa trên role hardcode trong code mà không có cấu trúc phân quyền động"]
  ),
  q("BE-CV-04", "Backend Developer", "cv_validation", "advanced", "senior_lead",
    "Em hãy chia sẻ về một sự cố dữ liệu hoặc outage nghiêm trọng nhất trên môi trường production trong các dự án trên CV mà em tham gia khắc phục. Em đã điều tra nguyên nhân gốc và phục hồi dữ liệu ra sao?",
    ["Tường thuật rõ ràng: thời điểm phát hiện -> đánh giá mức độ ảnh hưởng -> biện pháp ngăn chặn lây lan -> tìm root-cause -> phục hồi", "Trung thực về nguyên nhân (lỗi code, thiếu migration, hạ tầng) và áp dụng Point-in-time Recovery (PITR) nếu có mất dữ liệu", "Hành động phòng ngừa hậu sự cố: bổ sung automated test, alert giám sát, tài liệu runbook"],
    ["Thời gian RTO (Recovery Time Objective) và RPO (Recovery Point Objective) của hệ thống lúc đó là bao nhiêu?", "Bài học quan trọng nhất về mặt quy trình kỹ thuật mà em rút ra là gì?"],
    ["Incident Response", "Root Cause Analysis", "PITR", "Disaster Recovery"],
    [SRC.internal],
    ["Đổ lỗi hoàn toàn cho đồng nghiệp khác hoặc khẳng định chưa từng có sự cố nào xảy ra"]
  ),
  q("BE-CV-05", "Backend Developer", "cv_validation", "intermediate", "middle",
    "Khi tích hợp với các hệ thống đối tác thứ ba (Cổng thanh toán, Đơn vị vận chuyển, SMS/Email) trên dự án CV, em đã thiết kế các cơ chế Circuit Breaker, Retry và Fallback như thế nào để hệ thống không bị treo lây?",
    ["Sử dụng thư viện Circuit Breaker (Resilience4j, Opossum) với 3 trạng thái: Closed, Open, Half-Open", "Cấu hình Retry với Exponential Backoff kèm Jitter ngẫu nhiên để tránh hiện tượng thundering herd", "Thiết lập Timeout chặt chẽ cho các HTTP client và cơ chế Fallback (trả về dữ liệu tạm hoặc đẩy vào hàng đợi retry sau)"],
    ["Tại sao việc retry liên tục không có jitter có thể làm sập luôn hệ thống đối tác khi họ vừa hồi phục?", "Làm thế nào để giám sát tỷ lệ lỗi của Circuit Breaker trên dashboard?"],
    ["Circuit Breaker", "Resilience", "Retry Pattern", "Third-party Integration"],
    [SRC.internal],
    ["Gọi API đối tác mà không cấu hình timeout hoặc không có cơ chế xử lý khi đối tác mất kết nối"]
  ),

  // Behavioral (5)
  q("BE-BEHAV-01", "Backend Developer", "behavioral", "intermediate", "middle",
    "Khi cần thay đổi một API cốt lõi có breaking change nhưng có hàng chục nghìn ứng dụng di động phiên bản cũ của người dùng chưa cập nhật, em xử lý phiên bản hóa (API Versioning) và phối hợp với các bên ra sao?",
    ["Duy trì chiến lược Versioning rõ ràng (URI path `/v2` hoặc Header-based versioning)", "Không xóa bỏ logic cũ ngay lập tức mà duy trì song song cả 2 phiên bản trong giai đoạn deprecation", "Phối hợp với Mobile team và Product để lên kế hoạch thông báo ép người dùng cập nhật phiên bản (Force Update) sau thời gian ân hạn"],
    ["Làm thế nào để giảm thiểu chi phí bảo trì code khi phải duy trì nhiều phiên bản API cùng lúc?", "Quy trình thông báo Deprecation Header (Sunset header) theo chuẩn RFC được thiết lập thế nào?"],
    ["API Versioning", "Backward Compatibility", "Stakeholder Collaboration", "Deprecation"],
    [SRC.internal],
    ["Tự ý thay đổi schema API mà không thông báo trước cho mobile team dẫn đến app người dùng bị crash"]
  ),
  q("BE-BEHAV-02", "Backend Developer", "behavioral", "intermediate", "middle",
    "Khi xảy ra tranh cãi chuyên môn với Frontend Developer về việc một logic tính toán phức tạp nên được xử lý ở Backend hay Frontend, em tiếp cận thảo luận và đưa ra quyết định dựa trên những tiêu chí nào?",
    ["Lắng nghe góc nhìn của Frontend về độ mượt mà trải nghiệm và phản hồi tức thời cho người dùng", "Xem xét nguyên tắc Single Source of Truth và tính bảo mật của dữ liệu (không bao giờ tin tưởng client để tính toán giá tiền/khuyến mãi)", "Đánh giá chi phí tính toán phần cứng máy chủ so với tài nguyên thiết bị của người dùng để chọn giải pháp cân bằng"],
    ["Nếu Frontend cho rằng backend trả về dữ liệu quá cồng kềnh, em có giải pháp nào (BFF pattern, GraphQL)?", "Làm thế nào để giữ không khí thảo luận trên tinh thần xây dựng giải pháp kỹ thuật tốt nhất?"],
    ["Collaboration", "Frontend-Backend", "Conflict Resolution", "Architecture Decision"],
    [SRC.internal],
    ["Áp đặt quyền hạn một cách cứng nhắc hoặc đẩy hết trách nhiệm cho phía bên kia"]
  ),
  q("BE-BEHAV-03", "Backend Developer", "behavioral", "intermediate", "middle",
    "Trước sức ép từ ban quản lý yêu cầu release gấp tính năng backend quan trọng trong 3 ngày, buộc phải bỏ qua khâu viết Unit Test và kiểm tra bảo mật, em phản hồi và quản trị rủi ro thế nào?",
    ["Minh bạch hóa nợ kỹ thuật (Tech Debt) và rủi ro trực tiếp: lỗi dữ liệu tài chính, rủi ro bảo mật lộ thông tin", "Đề xuất phương án giảm bớt phạm vi tính năng (Scope Trimming) thành MVP để kịp thời hạn mà vẫn đảm bảo kiểm thử phần cốt lõi", "Cam kết kế hoạch bổ sung test và rà soát an toàn ngay trong sprint tiếp theo nếu được chấp thuận giải pháp tạm thời"],
    ["Làm thế nào để giải thích rủi ro kỹ thuật cho người quản lý không có nền tảng công nghệ hiểu được?", "Nếu lãnh đạo vẫn kiên quyết chấp nhận rủi ro để chạy thử, em cần làm gì để tự bảo vệ hệ thống (Audit log, Feature Flag)?"],
    ["Technical Debt", "Risk Management", "Stakeholder Communication", "Deadline Pressure"],
    [SRC.internal],
    ["Âm thầm làm ẩu không báo cáo rủi ro hoặc phản kháng tiêu cực bất hợp tác"]
  ),
  q("BE-BEHAV-04", "Backend Developer", "behavioral", "advanced", "senior_lead",
    "Sau khi hệ thống gặp một sự cố nghiêm trọng do chính đoạn code backend của em gây ra làm gián đoạn dịch vụ, em chủ trì buổi họp rút kinh nghiệm (Post-mortem) với thái độ và hành động thế nào?",
    ["Dũng cảm nhận trách nhiệm cá nhân nhưng duy trì văn hóa không đổ lỗi (Blameless Post-mortem) tập trung vào lỗ hổng quy trình", "Phân tích nguyên nhân khách quan: tại sao unit test không bắt được lỗi, tại sao staging không phát hiện, cơ chế canary deployment ở đâu", "Đưa ra danh sách hành động cải tiến cụ thể (Action Items) có người phụ trách và thời hạn hoàn thành"],
    ["Làm thế nào để xây dựng văn hóa blameless post-mortem trong một nhóm có nhiều thành viên sợ bị phạt?", "Em chia sẻ bài học kinh nghiệm này cho toàn bộ phòng kỹ thuật như thế nào?"],
    ["Blameless Post-mortem", "Accountability", "Engineering Culture", "Continuous Improvement"],
    [SRC.internal],
    ["Tìm cách giấu lỗi, đổ thừa cho môi trường hoặc đồng nghiệp khác"]
  ),
  q("BE-BEHAV-05", "Backend Developer", "behavioral", "advanced", "senior_lead",
    "Khi nhận thấy hệ thống Backend nguyên khối (Monolith) hiện tại bắt đầu xuất hiện nhiều điểm nghẽn, em đánh giá và thuyết phục đội ngũ kỹ thuật về việc chuyển đổi sang Microservices hoặc Modular Monolith như thế nào?",
    ["Đánh giá trung thực năng lực vận hành, kích thước đội ngũ và chi phí phức tạp của hệ thống phân tán", "Ưu tiên giải pháp Modular Monolith trước để làm sạch ranh giới nghiệp vụ (Bounded Contexts) thay vì vội vã tách service", "Thuyết phục dựa trên số liệu thực tế về tốc độ release, độ trễ và chi phí hạ tầng thay vì chạy theo trào lưu"],
    ["Khi nào Microservices thực sự là một sai lầm đối với một startup quy mô nhỏ?", "Chiến lược bóc tách từng module (Strangler Fig Pattern) diễn ra từng bước như thế nào?"],
    ["Architecture Evolution", "Monolith vs Microservices", "Technical Leadership", "Strategic Thinking"],
    [SRC.internal],
    ["Cổ súy chia nhỏ microservices một cách mù quáng khi đội ngũ chưa có đủ năng lực DevOps và CI/CD"]
  )
];

console.log("BE questions defined:", beQuestions.length);
module.exports = { beQuestions };
