const { q } = require('./fe_data.cjs');

const DA_SRC = {
  powerbi: "https://learn.microsoft.com/en-us/power-bi/",
  tableau: "https://help.tableau.com/current/pro/desktop/en-us/default.htm",
  dax: "https://dax.guide/",
  pandas: "https://pandas.pydata.org/docs/",
  stats: "https://docs.scipy.org/doc/scipy/reference/stats.html",
  sql_zoo: "https://sqlzoo.net/",
  internal: "Tình huống nghiệp vụ và phỏng vấn thực tế - JobReady AI"
};

// 3. DATA ANALYST (30 questions)
const dataAnalystQuestions = [
  // Foundation (6)
  q("DA-FOUND-01", "Data Analyst", "foundation", "intermediate", "junior",
    "Thống kê ứng dụng trong phân tích dữ liệu: Phân biệt Phân phối Chuẩn (Normal Distribution) và Phân phối Lệch (Skewed Distribution). Khi nào nên sử dụng Mean, Median và Mode để phản ánh đúng thực tế dữ liệu?",
    ["Phân phối Chuẩn: Dữ liệu đối xứng hình chuông, Mean = Median = Mode; các quy tắc thực nghiệm (68-95-99.7%)", "Phân phối Lệch (Skewed / Power-law): Thường gặp trong thu nhập, giá trị đơn hàng, thời gian on-site; có ngoại lai (outliers) kéo lệch Mean", "Lựa chọn đại diện: Mean rất nhạy cảm với ngoại lai; Median là thước đo trung tâm vững chắc (robust) nhất cho dữ liệu phân phối lệch; Mode đại diện cho giá trị có tần suất xuất hiện cao nhất (dữ liệu định danh/rời rạc)"],
    ["Tại sao báo cáo lương trung bình (Mean salary) trong ngành công nghệ thường gây tranh cãi và Median phản ánh thực tế tốt hơn?", "Độ lệch chuẩn (Standard Deviation) và Khoảng tứ phân vị (IQR) đo lường mức độ biến thiên dữ liệu khác nhau ra sao?"],
    ["Applied Statistics", "Normal Distribution", "Mean vs Median", "Skewed Distribution", "Outliers"],
    [DA_SRC.stats, DA_SRC.internal],
    ["Mặc định dùng Mean cho mọi loại dữ liệu và bỏ qua tác động bóp méo của các giá trị ngoại lai"]
  ),
  q("DA-FOUND-02", "Data Analyst", "foundation", "advanced", "middle",
    "Nguyên lý Kiểm định Giả thuyết (Hypothesis Testing) trong A/B Testing: Ý nghĩa của Null Hypothesis (H0), p-value, Mức ý nghĩa (Alpha), Lỗi Loại I (False Positive) và Lỗi Loại II (False Negative)?",
    ["Null Hypothesis (H0): Giả định không có sự khác biệt giữa phiên bản A và B; Alternative Hypothesis (H1): Có sự khác biệt thực sự", "p-value: Xác suất quan sát thấy kết quả cực đoan như hiện tại nếu giả thiết H0 là đúng; nếu p-value < alpha (thường là 0.05), bác bỏ H0", "Type I Error (Alpha - False Positive): Kết luận có hiệu quả trong khi thực tế không có (phê duyệt tính năng vô dụng)", "Type II Error (Beta - False Negative): Kết luận không có hiệu quả trong khi thực tế tính năng tốt; Statistical Power (1 - Beta, thường là 80%) là khả năng phát hiện hiệu ứng thực tế"],
    ["Tại sao việc 'nhìn trộm' (peeking) kết quả A/B test hàng ngày rồi dừng test sớm khi thấy p < 0.05 lại làm tăng vọt False Positive?", "Cách tính toán dung lượng mẫu tối thiểu (Minimum Sample Size) trước khi kích hoạt A/B test?"],
    ["Hypothesis Testing", "A/B Testing Statistics", "p-value", "Type I and II Errors", "Statistical Power"],
    [DA_SRC.stats, DA_SRC.internal],
    ["Tuyên bố A/B test thắng cuộc chỉ sau 2 ngày chạy thử với mẫu 100 người dùng mà không tính p-value"]
  ),
  q("DA-FOUND-03", "Data Analyst", "foundation", "advanced", "middle",
    "Mối tương quan và Quan hệ Nhân quả (Correlation vs Causation): Nghịch lý Simpson (Simpson's Paradox) và Thiên vị sống sót (Survivorship Bias) ảnh hưởng thế nào đến kết luận phân tích?",
    ["Tương quan không phải nhân quả: Hai biến số cùng tăng/giảm có thể do biến ẩn thứ ba (Confounding Variable) hoặc trùng hợp ngẫu nhiên (Spurious Correlation)", "Simpson's Paradox: Xu hướng xuất hiện ở các nhóm dữ liệu riêng rẽ bị đảo ngược hoàn toàn khi gộp chung các nhóm lại với nhau (do tỷ trọng quy mô giữa các nhóm không đồng đều)", "Survivorship Bias: Chỉ phân tích tập dữ liệu 'sống sót' qua một bộ lọc (vd: chỉ khảo sát khách hàng đang hoạt động mà bỏ qua khách hàng đã rời bỏ dịch vụ) dẫn đến nhận định sai lầm"],
    ["Nêu một ví dụ thực tế về Simpson's Paradox trong việc so sánh tỷ lệ chuyển đổi giữa hai kênh tiếp thị?", "Làm thế nào để thiết kế một nghiên cứu Causal Inference (suy luận nhân quả) khi không thể chạy A/B test trực tiếp?"],
    ["Correlation vs Causation", "Simpson's Paradox", "Survivorship Bias", "Confounding Variables"],
    [DA_SRC.internal],
    ["Khẳng định chắc chắn tính năng mới làm tăng doanh thu chỉ vì thấy hai đồ thị cùng đi lên cùng thời điểm"]
  ),
  q("DA-FOUND-04", "Data Analyst", "foundation", "intermediate", "junior",
    "Phân tích Đoàn hệ (Cohort Analysis) và Chỉ số Giữ chân người dùng (Retention Rate): Khái niệm N-Day Retention, Unbounded Retention và cách đọc biểu đồ Cohort Heatmap?",
    ["Cohort: Nhóm người dùng chia sẻ cùng một đặc điểm hoặc hành vi trong cùng một khoảng thời gian (thường là ngày/tuần đầu tiên đăng ký hoặc cài ứng dụng)", "N-Day Retention (Bracket Retention): Tỷ lệ phần trăm người dùng quay lại ứng dụng vào đúng ngày thứ N (vd: Day 1, Day 7, Day 30 Retention)", "Unbounded Retention: Tỷ lệ người dùng quay lại vào ngày thứ N HOẶC bất kỳ ngày nào sau đó; phù hợp với các ứng dụng không dùng hàng ngày (du lịch, thương mại điện tử)", "Cohort Heatmap: Bảng màu hiển thị tỷ lệ giữ chân theo từng mốc thời gian; giúp phát hiện xu hướng cải thiện sản phẩm qua từng phiên bản phát hành"],
    ["Đường cong giữ chân (Retention Curve) phẳng ra (flattening curve) mang ý nghĩa gì đối với sự phù hợp sản phẩm-thị trường (Product-Market Fit)?", "Phân biệt Cohort theo thời gian (Acquisition Cohort) và Cohort theo hành vi (Behavioral Cohort)?"],
    ["Cohort Analysis", "Retention Rate", "N-Day Retention", "Product-Market Fit", "Retention Curve"],
    [DA_SRC.internal],
    ["Chỉ theo dõi số lượng người đăng ký mới (Vanity Metric) mà bỏ qua tỷ lệ giữ chân của các nhóm người dùng cũ"]
  ),
  q("DA-FOUND-05", "Data Analyst", "foundation", "intermediate", "junior",
    "Kinh tế học đơn vị (Unit Economics) và Chỉ số Tăng trưởng Sản phẩm: Mối quan hệ giữa CAC (Customer Acquisition Cost), LTV (Customer Lifetime Value), Payback Period và Churn Rate?",
    ["CAC: Tổng chi phí bán hàng và tiếp thị chia cho số lượng khách hàng mới thu được trong kỳ", "LTV: Tổng lợi nhuận ròng ước tính mà một khách hàng mang lại trong suốt vòng đời sử dụng dịch vụ (`LTV = (ARPU * Gross Margin) / Churn Rate`)", "Tỷ lệ vàng LTV/CAC: Tỷ lệ lý tưởng là 3:1; nếu < 1:1 công ty đang đốt tiền lỗ vốn; nếu > 5:1 công ty đang đầu tư quá dè dặt và bỏ lỡ cơ hội mở rộng thị trường", "Payback Period: Thời gian (số tháng) cần thiết để một khách hàng tạo ra đủ lợi nhuận bù đắp chi phí thu hút họ; Churn Rate: Tỷ lệ khách hàng hủy đăng ký/ngừng sử dụng dịch vụ"],
    ["Sự khác biệt giữa Logo Churn (mất khách hàng) và Net Revenue Churn (mất doanh thu)?", "Tại sao Net Revenue Retention (NRR) > 100% lại là chỉ số quan trọng nhất của các công ty SaaS tăng trưởng nhanh?"],
    ["Unit Economics", "LTV CAC", "Payback Period", "Churn Rate", "SaaS Metrics"],
    [DA_SRC.internal],
    ["Tính LTV bằng cách lấy tổng doanh thu chia cho số người dùng mà không trừ giá vốn và không tính Churn Rate"]
  ),
  q("DA-FOUND-06", "Data Analyst", "foundation", "intermediate", "junior",
    "Nguyên lý Trực quan hóa Dữ liệu (Data Visualization Principles): Quy tắc lựa chọn biểu đồ phù hợp, quản lý Tỷ lệ Mực trên Dữ liệu (Data-Ink Ratio của Edward Tufte) và tránh biểu đồ gây hiểu lầm?",
    ["Lựa chọn biểu đồ chuẩn: So sánh thành phần (Bar chart), Biến thiên theo thời gian (Line chart), Phân phối tần suất (Histogram / Boxplot), Tương quan giữa 2 biến (Scatter plot)", "Data-Ink Ratio: Tối đa hóa tỷ lệ mực thể hiện dữ liệu thực tế; loại bỏ các thành phần rác trang trí (Chartjunk, lưới nền quá đậm, 3D effect không cần thiết)", "Tránh biểu đồ gây hiểu lầm: Không cắt ngắn trục Y (Trunked Y-axis) trong Bar chart để thổi phồng mức độ chênh lệch; hạn chế Pie chart khi có quá nhiều phần tử (> 5 lát cắt)", "Phối màu trực quan: Dùng bảng màu tuần tự cho dữ liệu liên tục, bảng màu phân kỳ cho dữ liệu có điểm trung hòa (âm/dương), và màu tương phản cho dữ liệu phân loại"],
    ["Khi nào nên dùng Boxplot (biểu đồ hộp) thay vì Bar chart để thể hiện giá trị đơn hàng?", "Làm thế nào để thiết kế biểu đồ thân thiện với người bị mù màu (Colorblind accessibility)?"],
    ["Data Visualization", "Edward Tufte", "Chart Selection", "Data-Ink Ratio", "Ethical Charting"],
    [DA_SRC.internal],
    ["Sử dụng biểu đồ tròn 3D với 12 màu sắc lộn xộn để trình bày cơ cấu thị phần cho Ban Giám đốc"]
  ),

  // Practical Skills (8)
  q("DA-PRAC-01", "Data Analyst", "practical_skills", "advanced", "middle",
    "Thành thạo SQL Window Functions trong phân tích kinh doanh: Ứng dụng `ROW_NUMBER()`, `RANK()`, `LEAD()`, `LAG()`, Frame Clauses (`ROWS BETWEEN`) để tính Tỷ lệ Tăng trưởng MoM và Doanh thu Lũy kế (Running Total)?",
    ["`ROW_NUMBER()` vs `RANK()` vs `DENSE_RANK()`: Xử lý xếp hạng và gán thứ tự phân hạng khi có giá trị trùng lặp", "`LAG()` / `LEAD()`: Truy xuất giá trị của dòng trước/sau mà không cần self-join; ứng dụng tính % tăng trưởng doanh thu theo tháng (Month-over-Month Growth): `(curr - prev) / prev * 100`", "`SUM() OVER (PARTITION BY ... ORDER BY ... ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)`: Tính tổng doanh thu tích lũy tăng dần theo thời gian", "Frame Clauses: Phân biệt `RANGE BETWEEN` (theo giá trị logic) và `ROWS BETWEEN` (theo số lượng dòng vật lý); ứng dụng tính Trung bình trượt 7 ngày (7-day Moving Average)"],
    ["Làm thế nào để xử lý giá trị NULL trong hàm `LAG()` khi tháng đầu tiên không có dữ liệu trước đó?", "Cách sử dụng Window Function để tìm lần mua hàng thứ hai (Second Purchase) của từng khách hàng?"],
    ["SQL Window Functions", "Running Total", "Moving Average", "MoM Growth", "Lag Lead"],
    [DA_SRC.sql_zoo, DA_SRC.internal],
    ["Sử dụng vòng lặp trong code ứng dụng hoặc self-join 5 lần để tính doanh thu lũy kế thay vì Window Function"]
  ),
  q("DA-PRAC-02", "Data Analyst", "practical_skills", "advanced", "middle",
    "Phân tích Phễu Chuyển đổi (Funnel Analysis) và Tỷ lệ Rơi rụng (Drop-off Analysis): Cách viết truy vấn SQL phân tích hành vi từng bước trong luồng mua hàng và định vị nút thắt cổ chai?",
    ["Mô hình phễu chuẩn: Bước 1 (Xem trang chủ) -> Bước 2 (Xem sản phẩm) -> Bước 3 (Thêm vào giỏ) -> Bước 4 (Vào thanh toán) -> Bước 5 (Đặt hàng thành công)", "Kỹ thuật SQL: Sử dụng Conditional Aggregation (`COUNT(CASE WHEN event = ... THEN 1 END)`) kết hợp với cửa sổ thời gian (Session Windowing)", "Tính toán tỷ lệ: Tỷ lệ chuyển đổi tổng thể (End-to-end Conversion Rate) và Tỷ lệ rơi rụng tại từng bước chuyển tiếp (Step-by-step Drop-off Rate)", "Phân khúc đa chiều (Drill-down Segmentation): Cắt lát phễu theo Thiết bị (iOS vs Android), Kênh tiếp thị (Organic vs Ads), và Khu vực địa lý để tìm ra nhóm người dùng bị kẹt"],
    ["Tại sao một phễu có tỷ lệ chuyển đổi chung 5% nhưng trên iOS là 8% và Android là 1% lại chỉ ra lỗi kỹ thuật ứng dụng?", "Cách xử lý người dùng thực hiện các bước không theo thứ tự tuần tự trong phễu?"] ,
    ["Funnel Analysis", "Drop-off Rate", "Conversion Funnel", "Conditional Aggregation", "Bottleneck Discovery"],
    [DA_SRC.sql_zoo, DA_SRC.internal],
    ["Chỉ nhìn vào tỷ lệ chuyển đổi cuối cùng 3% mà không biết người dùng đang bỏ cuộc ở bước nào nhiều nhất"]
  ),
  q("DA-PRAC-03", "Data Analyst", "practical_skills", "advanced", "middle",
    "Phân khúc khách hàng bằng mô hình RFM (Recency, Frequency, Monetary) trong SQL/Python: Cách tính điểm số, phân chia phân khúc (Champions, At-Risk, Lost) và đề xuất hành động kinh doanh?",
    ["Recency (R): Số ngày kể từ lần mua hàng gần nhất; Frequency (F): Tổng số lần mua hàng; Monetary (M): Tổng số tiền đã chi tiêu", "Phương pháp chấm điểm: Sử dụng hàm `NTILE(5)` trong SQL để chia khách hàng thành 5 phân vị (quintiles) từ 1 đến 5 cho từng tiêu chí R, F, M", "Phân nhóm phân khúc kinh doanh: 'Champions' (5-5-5, mua gần đây, mua thường xuyên, chi nhiều); 'Loyal Customers' (R cao, F cao); 'At Risk' (R thấp, F cao, lâu rồi không quay lại); 'Lost' (1-1-1)", "Đề xuất hành động tiếp thị: Gửi ưu đãi VIP cho Champions; gửi chiến dịch Win-back / giảm giá cho nhóm At Risk; ngừng gửi email tốn kém cho nhóm Lost"],
    ["Tại sao việc phân vị theo `NTILE` có thể gặp vấn đề nếu 80% khách hàng chỉ mua đúng 1 lần duy nhất?", "Cách kết hợp phân khúc RFM với thuật toán phân cụm K-Means trong Python để tìm cụm tự nhiên?"] ,
    ["RFM Segmentation", "Customer Scoring", "NTILE SQL", "Targeted Marketing", "Lifecycle Marketing"],
    [DA_SRC.pandas, DA_SRC.internal],
    ["Xem tất cả khách hàng như nhau và gửi cùng một thông điệp khuyến mãi đại trà cho mọi người"]
  ),
  q("DA-PRAC-04", "Data Analyst", "practical_skills", "advanced", "senior_lead",
    "Phân tích Đánh giá Kết quả A/B Test trong thực tế: Cách kiểm tra tính hợp lệ của thí nghiệm (Sample Ratio Mismatch - SRM), kiểm định hai mẫu t-test / Z-test, và giải thích kết quả cho Product Manager?",
    ["Kiểm tra SRM (Sample Ratio Mismatch): Dùng kiểm định Chi-Square goodness-of-fit kiểm tra xem tỷ lệ phân bổ người dùng thực tế có khớp với tỷ lệ thiết kế (vd: 50:50) không; nếu có SRM (p < 0.001) thì thí nghiệm bị lỗi kỹ thuật, kết quả hoàn toàn vô giá trị", "Lựa chọn kiểm định: Z-test cho tỷ lệ nhị phân (Conversion Rate), Two-sample t-test hoặc Mann-Whitney U test cho các chỉ số doanh thu/ARPU có phân phối lệch", "Khoảng tin cậy (Confidence Interval - CI 95%): Diễn giải biên độ tác động (Effect Size) thực tế thay vì chỉ nhìn vào p-value", "Khuyến nghị hành động: Đưa ra quyết định Go / No-Go rõ ràng kèm phân tích rủi ro và tác động thứ cấp (Guardrail Metrics: Thời gian tải trang, tỷ lệ hủy đơn)"],
    ["Điều gì xảy ra nếu chỉ số doanh thu tăng nhưng chỉ số Guardrail về độ hài lòng người dùng giảm mạnh?", "Novelty Effect (Hiệu ứng mới lạ) có thể làm sai lệch kết quả A/B test trong tuần đầu tiên như thế nào?"] ,
    ["A/B Testing Analysis", "Sample Ratio Mismatch", "Chi-Square Test", "Confidence Intervals", "Guardrail Metrics"],
    [DA_SRC.stats, DA_SRC.internal],
    ["Bỏ qua kiểm tra SRM và công bố tính năng chiến thắng khi nhóm đối chứng bị mất 20% lượng người dùng do lỗi tracking"]
  ),
  q("DA-PRAC-05", "Data Analyst", "practical_skills", "intermediate", "junior",
    "Khai thác và làm sạch dữ liệu với Python Pandas: Kỹ thuật xử lý giá trị khuyết thiếu (Missing Data Imputation), kiểu dữ liệu thời gian (Datetime), và tối ưu hóa bộ nhớ khi đọc file lớn?",
    ["Xử lý Missing Data: Phân biệt MCAR, MAR, MNAR; lựa chọn phương pháp: Drop dòng (nếu tỷ lệ < 1%), điền Median/Mode, hoặc Forward-fill (`ffill`) cho chuỗi thời gian", "Chuyển đổi kiểu dữ liệu: Chuyển chuỗi phân loại lặp lại sang kiểu `category` để giảm 80% bộ nhớ RAM; ép kiểu số nguyên sang `int32`/`int16`", "Xử lý Datetime: Sử dụng `pd.to_datetime()`, trích xuất các thuộc tính thời gian (`dt.dayofweek`, `dt.hour`), xử lý múi giờ qua `dt.tz_localize` và `dt.tz_convert`", "Đọc dữ liệu lớn: Sử dụng tham số `chunksize` trong `pd.read_csv()` để xử lý từng khối dữ liệu tuần tự, hoặc chuyển sang đọc file Parquet"],
    ["Tại sao không nên điền giá trị trung bình (Mean) vào dữ liệu bị khuyết trong bài toán dự báo tài chính?", "Sự khác biệt giữa hàm `merge()` và `concat()` trong Pandas?"] ,
    ["Python Pandas", "Data Cleaning", "Missing Value Imputation", "Memory Optimization", "Datetime Processing"],
    [DA_SRC.pandas, DA_SRC.internal],
    ["Tải toàn bộ file CSV 10GB vào RAM 8GB khiến máy tính bị crash mà không biết cách đọc theo chunk"]
  ),
  q("DA-PRAC-06", "Data Analyst", "practical_skills", "advanced", "middle",
    "Phân tích Nguyên nhân Gốc rễ (Root Cause Analysis - RCA) cho các biến động chỉ số kinh doanh: Kỹ thuật phân rã chỉ số (Metric Decomposition) và phân tích đóng góp yếu tố (Contribution Analysis)?",
    ["Nguyên lý phân rã chỉ số: Tách một chỉ số cấp cao thành tích của các chỉ số thành phần (vd: `Doanh thu = Lượng truy cập * Tỷ lệ chuyển đổi * Giá trị đơn trung bình AOV`)", "Xác định thành phần suy giảm: Đo lường xem thành phần nào đóng góp phần lớn nhất vào sự sụt giảm tổng thể", "Phân tích đóng góp theo chiều (Dimension Contribution): Sử dụng công thức Mix Effect vs Rate Effect để phân biệt do người dùng thay đổi hành vi hay do dịch chuyển cơ cấu đối tượng", "Đặt giả thuyết và kiểm chứng nhanh: Liệt kê danh sách các nguyên nhân tiềm năng (Lỗi kỹ thuật bản phát hành mới, đối thủ cạnh tranh khuyến mãi, ngày lễ/thời tiết) và kiểm chứng bằng dữ liệu trong 2 giờ"],
    ["Làm thế nào để phân biệt giữa một biến động mang tính mùa vụ (Seasonality) và một sự sụt giảm bất thường thực sự?", "Cách trình bày kết quả RCA cho Ban Giám đốc trong một trang slide súc tích?"] ,
    ["Root Cause Analysis", "Metric Decomposition", "Contribution Analysis", "Seasonality Adjustment", "Business Diagnosis"],
    [DA_SRC.internal],
    ["Báo cáo nguyên nhân một cách mơ hồ 'do thị trường chung khó khăn' mà không có số liệu phân rã chi tiết chứng minh"]
  ),
  q("DA-PRAC-07", "Data Analyst", "practical_skills", "advanced", "middle",
    "Thiết kế Theo dõi Sự kiện Người dùng (Tracking Plan & Event Taxonomy): Cách định nghĩa sự kiện (Event), thuộc tính (Properties) và phối hợp với đội kỹ sư phần mềm để đảm bảo dữ liệu thu thập chuẩn xác?",
    ["Cấu trúc danh pháp chuẩn: Quy tắc đặt tên `Object + Action` (vd: `button_clicked`, `order_completed`, `item_added_to_cart`)", "Phân biệt Event vs Properties: Event đại diện cho hành động người dùng; Properties mô tả chi tiết ngữ cảnh (`product_id`, `category`, `price`, `screen_name`, `source_campaign`)", "Tracking Plan Spreadsheet: Tài liệu sống ghi rõ Tên sự kiện, Trigger điều kiện kích hoạt, Danh sách thuộc tính, Kiểu dữ liệu, Ví dụ giá trị và trạng thái triển khai", "Kiểm thử QA sự kiện: Sử dụng công cụ proxy/debugger (Charles Proxy, Chrome DevTools Network tab, Segment Debugger) để kiểm tra payload trước khi tính năng ra mắt"],
    ["Tại sao việc không có Tracking Plan chuẩn ngay từ đầu sẽ biến kho dữ liệu thành một 'bãi rác' không thể phân tích được?", "Làm thế nào để ngăn chặn tình trạng một hành động bị gửi hai lần (Duplicate event firing)?"] ,
    ["Tracking Plan", "Event Taxonomy", "Event QA", "Product Analytics Instrumentation"],
    [DA_SRC.internal],
    ["Giao toàn quyền cho lập trình viên tự đặt tên sự kiện tùy ý dẫn đến cùng một hành động có 4 tên gọi khác nhau"]
  ),
  q("DA-PRAC-08", "Data Analyst", "practical_skills", "advanced", "senior_lead",
    "Kể chuyện bằng Dữ liệu (Data Storytelling) và Trình bày Báo cáo Chiến lược: Cấu trúc bài thuyết trình từ Insight đến Đề xuất Hành động (Actionable Recommendations) cho Ban Điều hành?",
    ["Cấu trúc kim tự tháp (Minto Pyramid Principle): Bắt đầu bằng Kết luận / Khuyến nghị then chốt trước, sau đó mới đến các luận điểm hỗ trợ và dữ liệu chi tiết", "Phân biệt Data -> Information -> Insight -> Action: 'Tỷ lệ rời bỏ là 15%' là Data; 'Tỷ lệ rời bỏ tập trung ở nhóm người dùng không dùng tính năng X trong 7 ngày đầu' là Insight; 'Thiết kế onboarding tour hướng dẫn dùng tính năng X' là Action", "Thiết kế slide tinh giản: Mỗi slide chỉ truyền tải đúng một thông điệp cốt lõi (One slide, one key takeaway); loại bỏ bảng số liệu dày đặc", "Dự đoán câu hỏi phản biện: Chuẩn bị sẵn phụ lục (Appendix) với các lát cắt số liệu chi tiết để giải đáp thắc mắc của các Giám đốc"],
    ["Làm thế nào để giữ được sự chú ý của các Giám đốc bận rộn trong 10 phút đầu tiên của buổi họp?", "Cách xử lý khi một stakeholder cấp cao bác bỏ insight của em vì nó đi ngược lại trực giác kinh nghiệm của họ?"] ,
    ["Data Storytelling", "Minto Pyramid Principle", "Executive Presentation", "Actionable Insights"],
    [DA_SRC.internal],
    ["Trình chiếu một bảng dữ liệu Excel 20 cột 50 dòng và đọc lại từng con số trước Ban Giám đốc"]
  ),

  // Scenario (6)
  q("DA-SCEN-01", "Data Analyst", "scenario", "advanced", "middle",
    "Tình huống: Vào sáng thứ Hai, dashboard kinh doanh ghi nhận Tỷ lệ Chuyển đổi (Conversion Rate) của toàn bộ sàn thương mại điện tử giảm đột ngột 25% trong ngày Chủ Nhật. Trưởng phòng Kinh doanh yêu cầu em giải thích nguyên nhân gấp trong 1 giờ. Em tiến hành điều tra các bước như thế nào?",
    ["Bước 1: Xác thực dữ liệu (Sanity Check): Kiểm tra xem có lỗi pipeline dữ liệu thu thập không (số lượng sự kiện tracking có bị mất không? Dữ liệu đã load đủ 24 giờ chưa?)", "Bước 2: Phân tách tử số và mẫu số: `Conversion Rate = Transactions / Visitors`. Kiểm tra xem Transactions giảm hay Visitors tăng đột biến (do chiến dịch quảng cáo kéo traffic rác)", "Bước 3: Cắt lát đa chiều (Dimension Slicing): Chia nhỏ theo Nền tảng (Web vs iOS vs Android), Trình duyệt, Kênh tiếp thị, Danh mục ngành hàng và Cổng thanh toán", "Bước 4: Định vị thủ phạm: Nếu chỉ giảm trên Android phiên bản mới phát hành -> Báo ngay cho đội Mobile lỗi crash checkout; Nếu chỉ giảm ở cổng thanh toán thẻ Z -> Báo lỗi đối tác ngân hàng", "Bước 5: Gửi thông báo ngắn gọn: Xác định rõ nguyên nhân, phạm vi ảnh hưởng và bộ phận đang phụ trách sửa lỗi"],
    ["Nếu tất cả các lát cắt đều giảm đồng đều 25%, em sẽ tìm kiếm nguyên nhân ở đâu tiếp theo?", "Làm thế nào để tránh việc kết luận vội vàng khi chưa phân tích kỹ các yếu tố bên ngoài (sự kiện quốc gia, ngày lễ)?"] ,
    ["Conversion Rate Drop", "Emergency Investigation", "Sanity Check", "Dimension Slicing", "Crisis Communication"],
    [DA_SRC.internal],
    ["Vội vàng báo cáo 'do người dùng không thích sản phẩm nữa' mà không kiểm tra lỗi kỹ thuật cổng thanh toán"]
  ),
  q("DA-SCEN-02", "Data Analyst", "scenario", "advanced", "senior_lead",
    "Tình huống: Một cuộc thử nghiệm A/B test cho tính năng Gợi ý Sản phẩm mới kéo dài 2 tuần cho kết quả: Tỷ lệ Click (CTR) tăng 18% có ý nghĩa thống kê (p < 0.01), nhưng Tổng Giá trị Đơn hàng (GMV) lại giảm 5% (p = 0.08). Product Manager muốn tung tính năng này ra toàn bộ người dùng vì CTR tăng rất đẹp. Em đưa ra khuyến nghị gì và thuyết phục PM ra sao?",
    ["Khuyến nghị kiên quyết: TẠM DỪNG việc triển khai tính năng ra 100% người dùng ngay lập tức", "Phân tích nghịch lý: CTR tăng nhưng GMV giảm là dấu hiệu kinh điển của việc thuật toán đang gợi ý các sản phẩm rẻ tiền, clickbait gây tò mò nhưng không dẫn đến đơn hàng giá trị cao, hoặc làm người dùng phân tâm khỏi sản phẩm chính", "Mối liên hệ kinh doanh: Mục tiêu tối thượng của công ty là Doanh thu (North Star Metric: GMV), CTR chỉ là một chỉ số ủy nhiệm bậc thấp (Proxy metric); tăng CTR mà mất doanh thu là thất bại", "Kế hoạch tiếp theo: Phân tích sâu phân phối giá của các sản phẩm được gợi ý; tinh chỉnh thuật toán gợi ý tối ưu hóa cho GMV thay vì CTR thuần túy và chạy lại A/B test vòng 2"],
    ["Làm thế nào để thuyết phục PM mà không làm họ cảm thấy công sức phát triển tính năng bị đổ sông đổ biển?", "Khái niệm Guardrail Metrics trong bài toán này bảo vệ doanh nghiệp như thế nào?"] ,
    ["A/B Test Trade-off", "Proxy Metric vs Business Metric", "Clickbait Algorithm Discovery", "Product Recommendation Evaluation"],
    [DA_SRC.stats, DA_SRC.internal],
    ["Đồng ý cho ra mắt tính năng chỉ vì thấy một chỉ số CTR tăng màu xanh mà bỏ qua sự sụt giảm doanh thu cốt lõi"]
  ),
  q("DA-SCEN-03", "Data Analyst", "scenario", "advanced", "middle",
    "Tình huống: Giám đốc Marketing muốn chứng minh rằng chiến dịch quảng cáo TikTok vừa qua rất thành công vì số lượng khách hàng cài app tăng 50%. Tuy nhiên, sau khi phân tích Cohort, em nhận thấy tỷ lệ giữ chân ngày 7 (D7 Retention) của nhóm người dùng TikTok này chỉ đạt 2% (so với 18% của các kênh tự nhiên khác). Em trình bày sự thật này với Giám đốc Marketing ra sao?",
    ["Công nhận nỗ lực ban đầu: Ghi nhận chiến dịch TikTok đã làm rất tốt việc tạo nhận thức thương hiệu (Brand Awareness) và kéo lượng tải app ban đầu (Top of Funnel)", "Chỉ ra bức tranh toàn diện: Trình bày biểu đồ so sánh chi phí thu hút khách hàng thực tế (Effective CAC): Lấy chi phí chia cho số khách hàng thực sự giữ lại sau 30 ngày thay vì chia cho số lượt tải app rác", "Tính toán thiệt hại tài chính: Chứng minh rằng công ty đang chi tiền thu hút người dùng nhưng 98% trong số họ xóa app sau 7 ngày, dẫn đến LTV không bao giờ bù đắp được CAC", "Đề xuất giải pháp hợp tác: Không yêu cầu dừng quảng cáo TikTok hoàn toàn; đề xuất thay đổi nội dung thông điệp quảng cáo nhắm đúng đối tượng mục tiêu có nhu cầu thực tế hơn thay vì chạy theo số lượng cài đặt ảo"],
    ["Làm thế nào để xây dựng mối quan hệ đồng hành (trusted partner) với đội Marketing thay vì bị xem là 'kẻ soi mói'?", "Khái niệm 'Vanity Metrics' (chỉ số phù phiếm) vs 'Actionable Metrics' được áp dụng thế nào ở đây?"] ,
    ["Vanity vs Actionable Metrics", "Retention vs Acquisition", "Marketing ROI Truth", "Constructive Stakeholder Communication"],
    [DA_SRC.internal],
    ["Nói thẳng với Giám đốc Marketing rằng 'chiến dịch của anh hoàn toàn lãng phí tiền bạc' gây ra xung đột gay gắt"]
  ),
  q("DA-SCEN-04", "Data Analyst", "scenario", "advanced", "middle",
    "Tình huống: Em nhận được một yêu cầu phân tích đột xuất (Ad-hoc Request) từ CEO: 'Hãy cho tôi biết người dùng nào có nguy cơ rời bỏ cao nhất và danh sách này cần trước 5h chiều nay'. Dữ liệu hành vi người dùng hiện tại nằm rải rác ở nhiều bảng thô chưa chuẩn hóa. Em xử lý yêu cầu gấp này như thế nào?",
    ["Bước 1: Làm rõ mục tiêu hành động: Hỏi nhanh CEO hoặc trợ lý: 'Danh sách này sẽ được dùng để làm gì?' (vd: Gửi email tặng voucher chiều nay, hay để trình chiếu báo cáo?) để xác định mức độ chi tiết cần thiết", "Bước 2: Xác định định nghĩa Churn đơn giản, thực tế: Trong thời gian gấp 4 tiếng, không thể xây dựng mô hình Machine Learning phức tạp; áp dụng định nghĩa heuristic dựa trên quy luật RFM: 'Người dùng từng mua ít nhất 2 lần nhưng không có bất kỳ hành vi mở app/mua hàng nào trong 45 ngày qua'", "Bước 3: Truy vấn nhanh và trích xuất: Viết câu lệnh SQL ngắn gọn, xuất danh sách Top 1000 khách hàng chi tiêu nhiều nhất thuộc nhóm trên", "Bước 4: Bàn giao kèm khuyến nghị rõ ràng: Gửi danh sách đúng hạn kèm ghi chú rõ ràng về phương pháp luận đơn giản đã dùng và hẹn một phân tích sâu hơn sau 3 ngày"],
    ["Làm thế nào để cân bằng giữa tốc độ (Speed) và độ chính xác hoàn hảo (Accuracy) trong các tình huống khẩn cấp?", "Cách quản lý kỳ vọng khi stakeholder yêu cầu một giải pháp AI phức tạp trong vài giờ?"] ,
    ["Urgent Ad-hoc Request", "Heuristic Churn Definition", "Speed vs Perfection", "Executive Delivery"],
    [DA_SRC.internal],
    ["Cố gắng xây dựng mô hình Random Forest phức tạp đến nửa đêm không kịp giao và làm trễ kế hoạch của CEO"]
  ),
  q("DA-SCEN-05", "Data Analyst", "scenario", "advanced", "senior_lead",
    "Tình huống: Công ty triển khai một chính sách miễn phí vận chuyển (Freeship) cho đơn hàng từ 200.000đ trở lên. Sau một tháng, doanh số đơn hàng tăng 20% nhưng Lợi nhuận gộp (Gross Profit) của công ty lại sụt giảm 8%. Em phân tích dữ liệu để tìm ra lý do nghịch lý này và đề xuất mức ngưỡng Freeship mới tối ưu ra sao?",
    ["Phân tích phân phối giá trị giỏ hàng (Basket Size Distribution): Vẽ biểu đồ tần suất giá trị đơn hàng trước và sau chính sách; phát hiện hiện tượng dồn đơn ngay sát ngưỡng 200K (khách hàng chỉ mua vừa đúng 200K để hưởng freeship)", "Phân tích cơ cấu biên lợi nhuận: Biên lợi nhuận của các sản phẩm khách hàng chọn để 'gom đủ 200K' là rất thấp (chỉ 10-15%), trong khi chi phí công ty bù tiền vận chuyển là 25K/đơn -> Mỗi đơn hàng 200K công ty đang phải bù lỗ", "Mô phỏng kịch bản (Scenario Modeling): Chạy mô hình giả lập dữ liệu với các ngưỡng freeship khác nhau (250K, 300K, 350K) kết hợp với độ co giãn của cầu theo giá (Price Elasticity)", "Đề xuất chiến lược tối ưu: Nâng ngưỡng freeship lên 280.000đ hoặc chỉ áp dụng freeship cho các danh mục ngành hàng có biên lợi nhuận gộp trên 35%"],
    ["Làm thế nào để đo lường hành vi gom đơn của khách hàng?", "Cách kiểm tra xem chính sách freeship có làm tăng tỷ lệ giữ chân khách hàng lâu dài để bù đắp lỗ trước mắt không?"] ,
    ["Promotion Economics", "Gross Margin Analysis", "Price Elasticity", "Freeship Threshold Optimization", "Scenario Modeling"],
    [DA_SRC.internal],
    ["Chúc mừng đội kinh doanh vì doanh số tăng mà không kiểm tra dòng tiền lợi nhuận thực tế"]
  ),
  q("DA-SCEN-06", "Data Analyst", "scenario", "advanced", "senior_lead",
    "Tình huống: Em phát hiện một trường dữ liệu cốt lõi về 'Nguồn tiếp thị người dùng' (Utm_source) trong hệ thống bị lỗi ghi nhận thành `null` hoặc `direct` cho hơn 40% người dùng trong suốt 3 tháng qua do lỗi code tracking. Dữ liệu này không thể khôi phục lại trực tiếp từ database. Em giải quyết bài toán phân tích phân bổ kênh (Attribution Modeling) trong tình trạng dữ liệu khiếm khuyết này ra sao?",
    ["Bước 1: Cô lập và đánh giá mức độ méo mó: Đo lường chính xác tỷ lệ và thời gian bắt đầu xảy ra lỗi; thông báo cho đội Data/Product fix ngay lập tức lỗi tracking cho tương lai", "Bước 2: Tìm kiếm nguồn dữ liệu thay thế bổ trợ (Data Imputation via Proxies): Đối chiếu với log truy cập webserver Nginx (đọc trường `Referer`), dữ liệu click-ID từ Facebook Pixel / Google Ads API (fbclid, gclid còn sót lại trong bảng giao dịch)", "Bước 3: Sử dụng kỹ thuật nội suy thống kê: Xây dựng mô hình phân loại dựa trên các đặc điểm hành vi còn lại (thiết bị, giờ truy cập, danh mục landing page) để gán nhãn xác suất kênh cho tập dữ liệu bị mất", "Bước 4: Minh bạch về sai số: Khi trình bày báo cáo tiếp thị quý, luôn kèm theo khoảng dao động tin cậy (Confidence Band) và nêu rõ giả định mô hình thay vì coi dữ liệu đã phục hồi là sự thật tuyệt đối"],
    ["Làm thế nào để thiết lập hệ thống cảnh báo sớm phát hiện tỷ lệ NULL tăng bất thường trong vòng 24 giờ?", "Cách giải thích cho các bên liên quan hiểu về mức độ rủi ro khi đưa ra quyết định trên dữ liệu được mô hình hóa?"] ,
    ["Dirty Data Recovery", "Proxy Data Imputation", "Attribution Modeling", "Tracking Regression", "Uncertainty Communication"],
    [DA_SRC.internal],
    ["Tự ý xóa bỏ toàn bộ 40% dữ liệu bị NULL và chỉ phân tích 60% dữ liệu còn lại dẫn đến kết luận hoàn toàn sai lệch"]
  ),

  // CV Validation (5)
  q("DA-CV-01", "Data Analyst", "cv_validation", "advanced", "middle",
    "Trong dự án phân tích dữ liệu nổi bật nhất được ghi trong CV, câu hỏi kinh doanh cốt lõi (Core Business Question) mà em cần trả lời là gì? Phân tích của em đã trực tiếp dẫn đến quyết định thay đổi sản phẩm hoặc hành động kinh doanh cụ thể nào?",
    ["Nêu bật câu hỏi nghiệp vụ rõ ràng, không chỉ kể về mặt kỹ thuật", "Phương pháp phân tích đã sử dụng và những rào cản dữ liệu đã vượt qua", "Tác động kinh doanh có thể định lượng được: Tăng doanh thu X%, giảm tỷ lệ rời bỏ Y%, hoặc tiết kiệm chi phí marketing Z đồng"],
    ["Nếu lãnh đạo không đồng ý với đề xuất của em lúc đó, em đã làm gì?", "Điều gì trong dự án đó mà nếu làm lại, em sẽ tiếp cận theo cách khác hiệu quả hơn?"],
    ["Business Impact Walkthrough", "Data to Decision", "Quantifiable Results", "Analytical Thinking"],
    [DA_SRC.internal],
    ["Chỉ liệt kê đã viết bao nhiêu câu lệnh SQL, vẽ bao nhiêu biểu đồ mà không nêu được tác động kinh doanh nào"]
  ),
  q("DA-CV-02", "Data Analyst", "cv_validation", "advanced", "middle",
    "Em ghi nhận trên CV về kinh nghiệm thiết kế và phân tích thử nghiệm A/B Testing. Hãy chia sẻ về một bài test cụ thể mà kết quả thực tế đi ngược lại hoàn toàn với dự đoán ban đầu của cả đội (Counter-intuitive result)? Em đã điều tra và học được điều gì từ đó?",
    ["Bối cảnh thử nghiệm và giả thuyết ban đầu của đội ngũ", "Kết quả thực tế bất ngờ và quá trình điều tra nguyên nhân sâu xa đằng sau hành vi người dùng", "Bài học rút ra về tâm lý học người dùng và việc tôn trọng dữ liệu khách quan thay vì niềm tin chủ quan"],
    ["Làm thế nào để thuyết phục các bên liên quan chấp nhận một kết quả thất bại mà không nản lòng?", "Sau thử nghiệm đó, quy trình A/B test của đội có được cải tiến thêm bước nào không?"],
    ["A/B Testing Deepdive", "Counter-Intuitive Insight", "User Psychology", "Experimentation Culture"],
    [DA_SRC.stats, DA_SRC.internal],
    ["Nói rằng tất cả các bài A/B test mình từng làm đều thành công 100% như dự kiến (thiếu thực tế)"]
  ),
  q("DA-CV-03", "Data Analyst", "cv_validation", "advanced", "middle",
    "Trong CV em có liệt kê kỹ năng Python (Pandas/Numpy) cho phân tích dữ liệu. Hãy phân tích sự khác nhau về trường hợp sử dụng (Use Cases) khi nào em quyết định dùng SQL thuần và khi nào bắt buộc phải kéo dữ liệu về phân tích bằng Python?",
    ["SQL: Tối ưu cho việc lọc, kết hợp, tổng hợp dữ liệu trên tập dữ liệu lớn hàng triệu dòng trực tiếp trong Data Warehouse; nhanh, rẻ, tận dụng compute phân tán", "Python: Sử dụng khi cần thống kê phức tạp (Bootstrapping, phân phối phi tham số), xử lý chuỗi văn bản nâng cao (NLP/Regex), vẽ đồ thị chuyên sâu (Seaborn/Plotly), hoặc chuẩn bị dữ liệu cho Machine Learning", "Quy tắc phối hợp: Luôn đẩy tối đa logic tổng hợp thô về SQL trong kho, chỉ kéo tập dữ liệu nhỏ gọn đã aggregate về Python trên máy local để phân tích chuyên sâu"],
    ["Một đoạn script Python tự động hóa phân tích nào em từng viết giúp tiết kiệm nhiều thời gian nhất cho đội?", "Cách quản lý môi trường ảo (Virtualenv/Conda) và đảm bảo code phân tích có thể tái lập (Reproducibility)?"] ,
    ["SQL vs Python", "Tool Selection Trade-offs", "Data Analysis Workflow", "Reproducible Research"],
    [DA_SRC.pandas, DA_SRC.internal],
    ["Kéo 5 triệu dòng dữ liệu thô về Jupyter Notebook trên laptop để chạy groupby khiến máy tính bị đơ"]
  ),
  q("DA-CV-04", "Data Analyst", "cv_validation", "intermediate", "junior",
    "Em ghi có kinh nghiệm làm việc với các hệ thống Product Analytics (Amplitude, Mixpanel, hoặc Google Analytics 4). Em đã sử dụng công cụ này như thế nào để khám phá một hành vi bất thường của người dùng mà dashboard SQL thông thường không thấy được?",
    ["Nêu rõ tính năng chuyên sâu đã khai thác: Funnel Conversion, Retention Matrix, Compass / Correlation analysis, hoặc Pathfinder / User Journeys", "Phát hiện hành vi cụ thể: Tìm thấy một chuỗi hành động ngách mà người dùng thành công thường làm (Aha! Moment) nhưng không nằm trong thiết kế ban đầu", "Chuyển hóa phát hiện từ công cụ thành đề xuất cải tiến sản phẩm"],
    ["Hạn chế lớn nhất của các công cụ Product Analytics sẵn có so với việc tự truy vấn trên Data Warehouse?", "Cách đối soát số liệu giữa Amplitude/Mixpanel và Database nội bộ của công ty?"],
    ["Product Analytics Tools", "Amplitude Mixpanel", "User Journey Discovery", "Aha Moment"],
    [DA_SRC.internal],
    ["Chỉ biết xem các biểu đồ mặc định có sẵn mà không biết tạo Custom Funnel hay Behavioral Cohort"]
  ),
  q("DA-CV-05", "Data Analyst", "cv_validation", "advanced", "senior_lead",
    "Trong CV em có ghi vai trò định nghĩa chỉ số đo lường (North Star Metric & KPI Framework) cho dự án. Em hãy giải thích quy trình em cùng các bên liên quan xây dựng cây chỉ số (KPI Tree) cho một sản phẩm cụ thể?",
    ["Xác định North Star Metric phản ánh đúng giá trị cốt lõi mà khách hàng nhận được từ sản phẩm", "Bẻ nhỏ thành các chỉ số cấp 1 (Input Metrics: Acquisition, Activation, Retention, Referral, Revenue)", "Phân rã tiếp thành các chỉ số hành động cấp 2 và 3 cho từng đội ngũ phụ trách cụ thể", "Đảm bảo tính cân bằng: Luôn có các Counter-metrics / Guardrail metrics để ngăn chặn việc tối ưu hóa cục bộ làm hại hệ thống"],
    ["Làm thế nào để xử lý khi các phòng ban tranh cãi xem chỉ số nào mới là quan trọng nhất?", "Sau khi áp dụng cây KPI đó, hiệu quả vận hành của công ty được cải thiện như thế nào?"],
    ["KPI Tree", "North Star Metric", "Metric Framework", "Counter-metrics", "Strategic Alignment"],
    [DA_SRC.internal],
    ["Chọn Doanh thu làm North Star Metric duy nhất cho mọi loại sản phẩm mà không có chỉ số đo lường giá trị người dùng"]
  ),

  // Behavioral (5)
  q("DA-BEHAV-01", "Data Analyst", "behavioral", "intermediate", "middle",
    "Khi kết quả phân tích số liệu của em đưa ra đi ngược lại hoàn toàn với ý kiến chủ quan của một Giám đốc cấp cao (HiPPO - Highest Paid Person's Opinion), em bảo vệ tính trung thực của dữ liệu và thuyết phục lãnh đạo như thế nào?",
    ["Tôn trọng kinh nghiệm và trực giác của lãnh đạo nhưng kiên định với sự thật khách quan của dữ liệu", "Tiếp cận mềm mỏng: Mời lãnh đạo cùng xem qua phương pháp luận, các giả định và các bước kiểm tra đối soát để họ thấy dữ liệu không bị định kiến", "Đưa ra giải pháp an toàn để kiểm chứng: Đề xuất một thử nghiệm quy mô nhỏ (Pilot test hoặc 5% A/B test) thay vì tranh cãi lý thuyết, để thực tế chứng minh"],
    ["Nếu lãnh đạo vẫn kiên quyết gạt bỏ số liệu và ra quyết định theo cảm tính, em sẽ phản ứng thế nào?", "Làm thế nào để duy trì sự độc lập khách quan của người làm phân tích mà không trở thành 'kẻ đối đầu' trong công ty?"] ,
    ["Managing HiPPO", "Data Integrity", "Diplomatic Persuasion", "Objective Analysis"],
    [DA_SRC.internal],
    ["Sửa đổi số liệu hoặc bóp méo kết luận phân tích để chiều lòng lãnh đạo, hoặc phản ứng tiêu cực chống đối"]
  ),
  q("DA-BEHAV-02", "Data Analyst", "behavioral", "advanced", "senior_lead",
    "Một Data Analyst giỏi không chỉ ngồi chờ nhận yêu cầu (Ticket Taker) mà phải chủ động đề xuất giải pháp (Proactive Problem Solver). Hãy chia sẻ về một dự án phân tích mà em tự khởi xướng vì phát hiện ra cơ hội/vấn đề từ dữ liệu mà không ai yêu cầu trước đó?",
    ["Kể về bối cảnh tự phát hiện vấn đề qua việc quan sát xu hướng hoặc đào sâu dữ liệu thường ngày", "Chủ động xây dựng phân tích, định lượng cơ hội tài chính hoặc rủi ro tiềm tàng", "Trình bày chủ động với các bên liên quan và thúc đẩy dự án biến thành hành động thực tế"],
    ["Em đã sắp xếp thời gian làm việc như thế nào để vừa hoàn thành nhiệm vụ hàng ngày vừa theo đuổi dự án tự khởi xướng này?", "Tác động kinh doanh cuối cùng của sáng kiến đó là gì?"],
    ["Proactive Analytics", "Business Initiative", "Value Creation", "Self-Driven Mindset"],
    [DA_SRC.internal],
    ["Thừa nhận chỉ làm khi có ticket giao và chưa bao giờ tự mình khởi xướng phân tích mới"]
  ),
  q("DA-BEHAV-03", "Data Analyst", "behavioral", "intermediate", "junior",
    "Khi làm việc với các stakeholder phi kỹ thuật (Sales, CS, Vận hành), họ thường diễn đạt yêu cầu rất mơ hồ (vd: 'Cho anh xem tình hình khách hàng gần đây thế nào'). Em làm thế nào để bóc tách yêu cầu mơ hồ đó thành một bài toán phân tích cụ thể, có thể đo lường được?",
    ["Đặt các câu hỏi gợi mở để tìm ra 'câu hỏi đằng sau câu hỏi': 'Vấn đề cụ thể anh đang muốn giải quyết hôm nay là gì?', 'Nếu có dữ liệu này, quyết định tiếp theo của anh sẽ là gì?'", "Cùng stakeholder thống nhất định nghĩa rõ ràng: Khách hàng nào? Khoảng thời gian nào? Tiêu chí đánh giá tốt/xấu là gì?", "Tóm tắt lại thành một bản tóm tắt yêu cầu (Analytics Brief) ngắn gọn và xác nhận lại trước khi bắt tay vào viết code"],
    ["Làm thế nào để tránh tình trạng phân tích xong giao việc thì đối tác bảo 'Đây không phải thứ tôi cần'?", "Cách đào tạo các đối tác nghiệp vụ nâng cao năng lực đặt câu hỏi dựa trên dữ liệu (Data Literacy)?"] ,
    ["Requirement Elicitation", "Stakeholder Communication", "Analytics Brief", "Active Listening"],
    [DA_SRC.internal],
    ["Lập tức mở máy tính viết câu lệnh SQL ngay khi nghe câu hỏi mơ hồ mà không làm rõ ngữ cảnh"]
  ),
  q("DA-BEHAV-04", "Data Analyst", "behavioral", "intermediate", "middle",
    "Kể về một tình huống em phát hiện ra một phát hiện (insight) dữ liệu rất thú vị về mặt kỹ thuật nhưng sau đó nhận ra nó hoàn toàn không có giá trị hành động (Not Actionable) đối với doanh nghiệp. Em đã rút ra bài học gì về việc cân bằng giữa sự tò mò kỹ thuật và giá trị thực tế?",
    ["Thẳng thắn chia sẻ về trải nghiệm đào sâu dữ liệu nhưng kết quả không giải quyết được vấn đề gì", "Bài học sâu sắc: Một insight chỉ thực sự có giá trị khi nó có thể dẫn đến một quyết định kinh doanh hoặc hành động cụ thể", "Hình thành thói quen 'So What?' (Thì sao?): Luôn tự hỏi bản thân câu hỏi này trước khi đưa bất kỳ biểu đồ nào vào báo cáo"],
    ["Làm thế nào để kiềm chế bản thân không sa đà vào 'hang thỏ' (rabbit hole) phân tích lan man không hồi kết?", "Cách xác định điểm dừng hợp lý cho một bài toán phân tích?"] ,
    ["Actionable Insights", "So What Test", "Analytical Discipline", "Focus on Value"],
    [DA_SRC.internal],
    ["Trình bày một bài phân tích dài 30 trang đầy những biểu đồ đẹp mắt nhưng khi hỏi 'Vậy công ty cần làm gì tiếp theo?' thì không trả lời được"]
  ),
  q("DA-BEHAV-05", "Data Analyst", "behavioral", "advanced", "senior_lead",
    "Data Analyst thường xuyên phải đối mặt với tình trạng 'Quá tải yêu cầu số liệu' (Request Overload) từ khắp các phòng ban. Em đã xây dựng cơ chế nào để tự động hóa và trao quyền (Self-service enablement) cho các phòng ban tự tra cứu số liệu cơ bản, giúp giải phóng thời gian cho các phân tích chiến lược?",
    ["Xây dựng hệ thống báo cáo tự phục vụ (Self-service BI Dashboards) với các bộ lọc linh hoạt cho các câu hỏi thường gặp", "Tổ chức các khóa đào tạo nội bộ 'Data Literacy': Hướng dẫn các bạn Sales, Marketing cách dùng dashboard và tra cứu số liệu", "Xây dựng cổng tiếp nhận yêu cầu (Analytics Request Intake Form) có quy định rõ độ ưu tiên và SLA phản hồi"],
    ["Làm thế nào để kiểm soát chất lượng khi người dùng tự lấy dữ liệu và diễn giải sai số liệu?", "Tỷ lệ thời gian của em dành cho Ad-hoc vs Strategic Analysis thay đổi như thế nào sau khi triển khai?"] ,
    ["Self-Service Enablement", "Data Literacy Training", "Workload Management", "Strategic Impact"],
    [DA_SRC.internal],
    ["Ôm đồm tự mình trả lời từng câu hỏi nhỏ hàng ngày qua tin nhắn chat và biến mình thành nút thắt cổ chai của công ty"]
  )
];

// 4. BUSINESS INTELLIGENCE (BI) (30 questions)
const biQuestions = [
  // Foundation (6)
  q("BI-FOUND-01", "Business Intelligence (BI)", "foundation", "intermediate", "junior",
    "Kiến trúc hệ thống Business Intelligence (BI) doanh nghiệp hiện đại: Phân biệt vai trò của Data Warehouse, Data Marts, Semantic Layer và BI Presentation Tools?",
    ["Data Warehouse: Kho lưu trữ dữ liệu trung tâm chuẩn hóa của toàn doanh nghiệp; tích hợp dữ liệu từ nhiều hệ thống nguồn (ERP, CRM, Web)", "Data Marts: Phân vùng dữ liệu chuyên biệt phục vụ riêng cho từng phòng ban (Finance Mart, Sales Mart, HR Mart); tối ưu cho nhu cầu truy vấn cụ thể", "Semantic Layer: Tầng mô hình hóa dữ liệu trừu tượng hóa các bảng vật lý thành các khái niệm kinh doanh thân thiện (Business terms, KPIs, Hierarchies, RLS)", "BI Presentation Tools: Công cụ trực quan hóa (Power BI, Tableau, Looker) cho phép người dùng tương tác, drill-down và khám phá thông tin"],
    ["Tại sao việc kết nối trực tiếp công cụ BI vào Production Database là một anti-pattern nghiêm trọng?", "Khái niệm Enterprise BI vs Self-service BI có những điểm khác biệt cốt lõi nào về mặt quản trị (Governance)?"],
    ["BI Architecture", "Data Warehouse", "Data Marts", "Semantic Layer", "Enterprise BI Governance"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Nghĩ rằng BI chỉ đơn thuần là việc vẽ biểu đồ đẹp trên Power BI mà không hiểu kiến trúc dữ liệu bên dưới"]
  ),
  q("BI-FOUND-02", "Business Intelligence (BI)", "foundation", "advanced", "middle",
    "Mô hình dữ liệu cho BI: Tại sao Star Schema là chuẩn mực vàng cho hiệu năng tính toán BI so với Snowflake Schema và Bảng phẳng đơn nhất (One Big Table - OBT)?",
    ["Star Schema: Giảm thiểu số lượng join, các bảng Dimension liên kết trực tiếp với Fact; tối ưu hoàn hảo cho công nghệ lưu trữ theo cột và bộ nhớ đệm (In-memory Inverted Index)", "Quan hệ trong BI Engine: VertiPaq (Power BI) và Tableau tối ưu hóa mối quan hệ 1-N giữa Dimension và Fact; Snowflake Schema tạo ra chuỗi join bắc cầu làm giảm tốc độ lọc", "One Big Table (OBT): Tốt cho Cloud Data Warehouse nhưng làm tăng kích thước bộ nhớ RAM trong BI tool do dữ liệu trùng lặp text lớn và làm phức tạp các phép tính DAX đa chiều", "Mối quan hệ Active vs Inactive: Xử lý nhiều liên kết thời gian (Order Date, Ship Date) qua hàm `USERELATIONSHIP`"],
    ["Tại sao quan hệ Many-to-Many (N-N) trong Power BI là mối nguy hiểm tiềm tàng về mặt hiệu năng và tính chính xác?", "Cơ chế lọc hai chiều (Bi-directional Cross-filtering) gây ra những hệ lụy gì nếu dùng không kiểm soát?"],
    ["Star Schema for BI", "VertiPaq Optimization", "Active vs Inactive Relationships", "Bi-directional Filtering Risk"],
    [DA_SRC.powerbi, DA_SRC.dax],
    ["Lạm dụng lọc hai chiều (Both cross-filtering) trên toàn bộ mô hình gây ra hiện tượng tính toán vòng lặp và làm chậm dashboard"]
  ),
  q("BI-FOUND-03", "Business Intelligence (BI)", "foundation", "advanced", "middle",
    "Nguyên lý tính toán DAX trong Power BI: Phân biệt triệt để giữa Row Context và Filter Context. Cơ chế Context Transition diễn ra khi nào và cách hoạt động của hàm `CALCULATE`?",
    ["Row Context: Tồn tại trong Calculated Columns hoặc các hàm lặp (Iterator functions: `SUMX`, `AVERAGEX`); duyệt qua từng dòng riêng lẻ của bảng mà không biết về các bộ lọc bên ngoài", "Filter Context: Tập hợp tất cả các bộ lọc đang tác động lên visual (Slicers, Rows/Columns trong Matrix, Filter Pane, Page Filters); quyết định tập dữ liệu nào được truyền vào Measure", "`CALCULATE`: Hàm mạnh nhất trong DAX; là hàm DUY NHẤT có khả năng sửa đổi, ghi đè hoặc mở rộng Filter Context hiện tại", "Context Transition: Quá trình chuyển đổi tự động từ Row Context sang Filter Context tương đương khi một Measure được gọi bên trong một Row Context (hoặc dùng `CALCULATE`)"],
    ["Điều gì xảy ra khi viết `SUM(Table[Column])` trong Calculated Column mà không có `CALCULATE`?", "Hàm `ALL()`, `ALLEXCEPT()` và `REMOVEFILTERS()` tương tác với Filter Context ra sao?"] ,
    ["DAX Fundamentals", "Row Context", "Filter Context", "CALCULATE", "Context Transition"],
    [DA_SRC.dax, DA_SRC.powerbi],
    ["Nhầm lẫn giữa Calculated Column (tính lúc refresh, ngốn RAM) và Measure (tính lúc render query)"]
  ),
  q("BI-FOUND-04", "Business Intelligence (BI)", "foundation", "advanced", "middle",
    "Cơ chế tính toán LOD (Level of Detail) trong Tableau: Phân biệt chi tiết giữa `FIXED`, `INCLUDE`, và `EXCLUDE`. Thứ tự thực thi bộ lọc (Tableau Order of Operations) tác động đến LOD ra sao?",
    ["`FIXED`: Tính toán giá trị tại mức độ chi tiết được chỉ định độc lập hoàn toàn với các chiều có mặt trên màn hình (được tính trước Dimension Filters, chỉ đứng sau Context Filters)", "`INCLUDE`: Tính toán tại mức độ chi tiết có trên màn hình CỘNG THÊM các chiều được chỉ định bổ sung (hữu ích cho bài toán trung bình của các tổng)", "`EXCLUDE`: Tính toán tại mức độ chi tiết có trên màn hình nhưng LOẠI BỎ một chiều cụ thể (hữu ích cho bài toán tính tỷ lệ phần trăm trên tổng)", "Order of Operations: Extract Filters -> Data Source Filters -> Context Filters -> FIXED LOD -> Dimension Filters -> INCLUDE/EXCLUDE LOD -> Measure Filters -> Table Calculations"],
    ["Tại sao việc chuyển một Dimension Filter thành Context Filter lại thay đổi kết quả của phép tính `FIXED` LOD?", "Khác biệt về hiệu năng giữa Tableau Table Calculations và LOD Expressions?"] ,
    ["Tableau LOD", "FIXED INCLUDE EXCLUDE", "Tableau Order of Operations", "Context Filters"],
    [DA_SRC.tableau, DA_SRC.internal],
    ["Không nắm vững Order of Operations dẫn đến việc bộ lọc trên dashboard không tác động đúng vào biểu thức FIXED LOD"]
  ),
  q("BI-FOUND-05", "Business Intelligence (BI)", "foundation", "intermediate", "junior",
    "Bảo mật cấp dòng (Row-Level Security - RLS) trong BI: Phân biệt Static RLS và Dynamic RLS. Cách triển khai phân quyền động theo tài khoản người dùng (`USERPRINCIPALNAME()`) và bảng quan hệ bảo mật?",
    ["Static RLS: Tạo các vai trò (Roles) cố định với bộ lọc cứng (vd: Role 'MienBac' lọc `Region = 'Bắc'`); phải gán thủ công từng người dùng vào role trong BI Service", "Dynamic RLS: Sử dụng một Role duy nhất kết hợp với hàm `USERPRINCIPALNAME()` (hoặc `USERNAME()`) để tự động lấy email của người đang đăng nhập", "Bảng quan hệ phân quyền (Security Table): Tạo bảng ánh xạ giữa Email người dùng và các Mã phòng ban/Chi nhánh được phép xem; liên kết bảng này với Dimension chính bằng lọc một chiều", "Hierarchy RLS: Phân quyền dạng cây tổ chức (Quản lý cấp trên xem được toàn bộ dữ liệu của nhân viên cấp dưới) sử dụng các hàm DAX phân cấp (`PATH`, `PATHCONTAINS`)"],
    ["Làm thế nào để kiểm tra và thử nghiệm (Test as role) RLS trước khi xuất bản dashboard lên Production?", "RLS có hoạt động khi chia sẻ báo cáo dạng Export PDF/Excel hoặc nhúng qua Publish to Web không?"] ,
    ["Row-Level Security", "Dynamic RLS", "USERPRINCIPALNAME", "Data Security Governance", "Hierarchy Security"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Dùng Static RLS tạo 100 roles thủ công cho 100 chi nhánh cửa hàng gây ác mộng quản trị"]
  ),
  q("BI-FOUND-06", "Business Intelligence (BI)", "foundation", "intermediate", "junior",
    "Thiết kế Bảng điều khiển Điều hành (Executive Dashboard Design): Nguyên tắc phân cấp thị giác (Visual Hierarchy), Thiết kế theo mô hình chữ F/Z, và lựa chọn KPI Cards phản ánh sức khỏe doanh nghiệp?",
    ["Visual Hierarchy: Đặt các thông tin quan trọng nhất ở góc trên cùng bên trái (nơi mắt người quét đầu tiên theo mô hình đọc F/Z)", "Cấu trúc 3 tầng chuẩn: Tầng 1 (High-level KPIs tóm tắt: Doanh thu, Lợi nhuận, Khách hàng kèm % hoàn thành kế hoạch và sparklines); Tầng 2 (Phân tích xu hướng và cơ cấu); Tầng 3 (Bảng dữ liệu chi tiết có khả năng drill-through)", "Quy tắc 5 giây: Một Giám đốc phải nắm bắt được tình hình kinh doanh tốt hay xấu trong vòng 5 giây sau khi mở dashboard", "Hạn chế quá tải thông tin: Không đặt quá 6-8 visual trên một trang; sử dụng tính năng Tooltips, Drill-down và Bookmarks để ẩn/hiện thông tin phụ"],
    ["Tại sao việc đưa quá nhiều bộ lọc (15 slicers) trên một trang dashboard lại phản tác dụng đối với người dùng điều hành?", "Làm thế nào để chuẩn hóa bảng màu doanh nghiệp (Corporate Color Palette) tránh việc mỗi dashboard mang một màu sắc khác nhau?"] ,
    ["Executive Dashboard Design", "Visual Hierarchy", "Rule of 5 Seconds", "Information Architecture", "Cognitive Load"],
    [DA_SRC.internal],
    ["Nhồi nhét 20 biểu đồ và bảng tính chi tiết vào một trang duy nhất khiến người dùng bị choáng ngợp và không biết nhìn vào đâu"]
  ),

  // Practical Skills (8)
  q("BI-PRAC-01", "Business Intelligence (BI)", "practical_skills", "advanced", "middle",
    "Tối ưu hóa hiệu năng động cơ VertiPaq trong Power BI: Sử dụng DAX Studio và Tabular Editor để phân tích Kích thước Cardinality, nén dữ liệu và giảm thời gian tải báo cáo?",
    ["Nguyên lý nén VertiPaq: Nén dữ liệu theo cột dựa trên số lượng giá trị duy nhất (Cardinality); cột có Cardinality càng thấp thì tỷ lệ nén càng cao và tốn càng ít RAM", "Sử dụng VertiPaq Analyzer trong DAX Studio: Xác định các cột tốn dung lượng RAM nhất trong mô hình (thường là cột ID số thực, cột Datetime có cả giờ phút giây)", "Kỹ thuật tối ưu hóa: Tách cột Datetime thành 2 cột riêng biệt (Date và Time); loại bỏ các cột Surrogate Keys không dùng cho hiển thị; chuyển đổi kiểu dữ liệu Decimal sang Fixed Decimal (Currency)", "Xóa bỏ các cột không sử dụng (Column Pruning): Giữ nguyên tắc 'Chỉ nạp những cột thực sự xuất hiện trong visuals hoặc calculations'"],
    ["Tại sao việc tự động tạo bảng Auto Date/Time trong Power BI Desktop lại làm phình to kích thước file một cách vô ích?", "Làm thế nào để đo lường Server Timings (Storage Engine vs Formula Engine) để tối ưu câu lệnh DAX bị chậm?"] ,
    ["VertiPaq Engine", "DAX Studio", "Cardinality Reduction", "Tabular Editor", "Power BI Optimization"],
    [DA_SRC.powerbi, DA_SRC.dax],
    ["Giữ nguyên cột Timestamp chi tiết đến mili-giây cho bảng 50 triệu dòng khiến file Power BI ngốn 4GB RAM"]
  ),
  q("BI-PRAC-02", "Business Intelligence (BI)", "practical_skills", "advanced", "middle",
    "Thành thạo DAX Time Intelligence nâng cao: Xây dựng các phép tính YTD, MTD, QTD, So sánh cùng kỳ năm trước (YoY Growth), và xử lý Lịch tài chính tùy biến (Custom 4-4-5 Fiscal Calendar)?",
    ["Bảng Date chuẩn: Yêu cầu bắt buộc phải liên tục không ngắt quãng (Contiguous dates), bao phủ toàn bộ phạm vi dữ liệu và được đánh dấu là 'Mark as Date Table'", "Hàm Time Intelligence chuẩn: `TOTALYTD()`, `SAMEPERIODLASTYEAR()`, `DATEADD()`, `PARALLELPERIOD()`; tính % tăng trưởng cùng kỳ: `DIVIDE(Sales_Current - Sales_PY, Sales_PY)`", "Custom Fiscal Calendar (Lịch 4-4-5 / 13 tuần): Các hàm Time Intelligence chuẩn của DAX không hoạt động trên lịch tùy biến; phải xây dựng logic tùy biến bằng cách lọc theo cột `Fiscal_Period_Offset` hoặc `Fiscal_Year_Number` trong bảng Dim_Date", "Xử lý ngày cuối cùng có dữ liệu (Last Date with Sales): Ngăn chặn biểu đồ YTD vẽ đường ngang vô nghĩa cho các tháng tương lai trong năm"],
    ["Tại sao việc dùng hàm `DATESYTD` mà không đánh dấu 'Mark as Date Table' có thể dẫn đến kết quả sai lệch?", "Cách xây dựng một bộ chọn thời gian động (Dynamic Period Slicer: MTD, QTD, YTD, Trailing 12 Months) chỉ bằng 1 Slicer và Calculation Groups?"] ,
    ["DAX Time Intelligence", "YoY Growth", "Fiscal Calendar 4-4-5", "Calculation Groups", "Mark as Date Table"],
    [DA_SRC.dax, DA_SRC.powerbi],
    ["Dùng bảng ngày có khoảng trống (missing dates) khiến các hàm Time Intelligence trả về kết quả rỗng hoặc sai lệch"]
  ),
  q("BI-PRAC-03", "Business Intelligence (BI)", "practical_skills", "advanced", "senior_lead",
    "Sử dụng Calculation Groups trong Tabular Editor: Cách giảm thiểu hàng trăm Measures lặp lại thành một cấu trúc tính toán thông minh duy nhất?",
    ["Vấn đề nhân bản Measure: Nếu có 10 chỉ số (Doanh thu, Chi phí, Lợi nhuận, Số đơn...) và cần tính Actual, YTD, YoY, YoY% -> Phải viết 40 Measures riêng rẽ", "Giải pháp Calculation Groups: Tạo một bảng ảo chứa các Calculation Items (vd: `Current`, `YTD`, `PY`, `YoY %`); mỗi item áp dụng công thức biến đổi trên hàm `SELECTEDMEASURE()`", "Ứng dụng định dạng chuỗi động (Dynamic Format Strings): Tự động đổi định dạng hiển thị sang tiền tệ `$#,##0` cho Actual và phần trăm `0.0%` cho YoY%", "Kiểm soát độ ưu tiên (Precedence): Quản lý thứ tự thực thi khi nhiều Calculation Groups cùng được áp dụng trên một visual"],
    ["Calculation Groups giải quyết bài toán chuyển đổi tiền tệ động (Dynamic Currency Conversion) như thế nào?", "Hạn chế của Calculation Groups đối với các mô hình Power BI có quan hệ Many-to-Many?"] ,
    ["Calculation Groups", "Tabular Editor", "SELECTEDMEASURE", "Dynamic Format Strings", "Scalable DAX Modeling"],
    [DA_SRC.dax, DA_SRC.powerbi],
    ["Ngồi viết thủ công 150 measures tương tự nhau bằng cách copy-paste thay vì dùng Calculation Groups"]
  ),
  q("BI-PRAC-04", "Business Intelligence (BI)", "practical_skills", "advanced", "middle",
    "Xây dựng Báo cáo Đa chế độ (Composite Models & Hybrid Tables): Kết hợp Import Mode, DirectQuery và Dual Mode để cân bằng giữa Tốc độ siêu nhanh và Dữ liệu thời gian thực?",
    ["Import Mode: Tải toàn bộ dữ liệu vào RAM; hiệu năng nhanh nhất nhưng giới hạn dung lượng và dữ liệu có độ trễ refresh", "DirectQuery: Không lưu dữ liệu trong BI; mỗi thao tác tương tác của người dùng sẽ gửi câu lệnh SQL trực tiếp về kho dữ liệu; dữ liệu tức thời nhưng phụ thuộc tốc độ DB", "Dual Mode: Chế độ thông minh cho các bảng Dimension; tự động hoạt động như Import khi join với bảng Import, và hoạt động như DirectQuery khi join với bảng DirectQuery", "Hybrid Tables: Trong cùng một bảng Fact, dữ liệu lịch sử nhiều năm lưu ở Import Mode, dữ liệu của ngày hôm nay lưu ở DirectQuery Mode -> Đạt cả hai mục tiêu siêu nhanh và real-time"],
    ["Cơ chế Tổng hợp do Người dùng xác định (User-defined Aggregations) giúp tăng tốc DirectQuery lên 100 lần như thế nào?", "Lỗ hổng bảo mật tiềm ẩn khi kết hợp nhiều nguồn dữ liệu trong Composite Model (Data Source Privacy Levels)?"] ,
    ["Composite Models", "DirectQuery vs Import", "Dual Storage Mode", "Hybrid Tables", "User-Defined Aggregations"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Dùng DirectQuery cho toàn bộ bảng báo cáo phức tạp khiến người dùng phải chờ 45 giây mỗi lần bấm slicer"]
  ),
  q("BI-PRAC-05", "Business Intelligence (BI)", "practical_skills", "advanced", "middle",
    "Thiết kế Cây Chỉ số Tài chính (DuPont Analysis KPI Tree) và Biểu đồ Phân tích Biến động (Variance Watermark Chart) trên Power BI / Tableau?",
    ["Cây Chỉ số DuPont: Phân rã Tỷ suất Sinh lời trên Vốn chủ sở hữu (`ROE = Biên lợi nhuận ròng * Vòng quay tài sản * Đòn bẩy tài chính`); trực quan hóa dạng cây phân cấp (Decomposition Tree visual)", "Variance Analysis: Phân tích chênh lệch giữa Thực tế (Actual) vs Kế hoạch (Budget) vs Cùng kỳ (Forecast)", "Biểu đồ Thác nước (Waterfall Chart): Minh họa trực quan các yếu tố làm tăng và các yếu tố làm giảm lợi nhuận từ đầu kỳ đến cuối kỳ", "Tích hợp bình luận thông minh (Smart Narratives): Tự động sinh văn bản tóm tắt nguyên nhân biến động chính bằng ngôn ngữ tự nhiên dựa trên số liệu động"],
    ["Làm thế nào để xử lý số âm và nghịch đảo màu sắc (Tăng chi phí là màu ĐỎ, giảm chi phí là màu XANH) trong biểu đồ Variance?", "Cách tạo tính năng phân tích kịch bản 'Nếu - Thì' (What-If Parameters) cho phép Ban Giám đốc điều chỉnh tỷ lệ chiết khấu để xem tác động lợi nhuận?"] ,
    ["DuPont Analysis", "Decomposition Tree", "Waterfall Chart", "Variance Analysis", "What-If Parameters"],
    [DA_SRC.powerbi, DA_SRC.tableau],
    ["Vẽ biểu đồ chi phí tăng bằng màu xanh lá cây vì nghĩ rằng 'tăng trưởng luôn là màu xanh'"]
  ),
  q("BI-PRAC-06", "Business Intelligence (BI)", "practical_skills", "advanced", "senior_lead",
    "Quản trị và Vận hành Nền tảng BI Doanh nghiệp (BI Enterprise Governance): Quản lý Power BI Workspaces / Tableau Projects, Triển khai Deployment Pipelines (Dev-Test-Prod), và Shared Datasets?",
    ["Tách biệt Mô hình Dữ liệu và Báo cáo (Decoupled Architecture): Một file Dataset trung tâm (Golden Semantic Model) được quản lý và bảo trì độc lập; hàng chục file Report mỏng (Thin Reports) chỉ kết nối Live Connection vào dataset này", "Deployment Pipelines: Quy trình 3 môi trường chuẩn (Development -> Test/UAT -> Production); tự động ánh xạ nguồn dữ liệu (Data Source Rules) và tham số khi thăng hạng (promote)", "Power BI Apps: Đóng gói báo cáo phát hành cho người dùng cuối qua App thay vì cấp quyền trực tiếp vào Workspace để tránh người dùng vô tình sửa hỏng", "Giám sát tài nguyên: Theo dõi Capacity Metrics App (Fabric/Premium Capacity), thời gian refresh, người dùng tích cực và cảnh báo thất bại qua webhook"],
    ["Làm thế nào để quản lý phiên bản mã nguồn (Version Control) cho file Power BI bằng định dạng PBIP và Git integration?", "Chiến lược chứng thực Dataset (Endorsement: Promoted vs Certified) giúp người dùng tin tưởng dữ liệu ra sao?"] ,
    ["BI Enterprise Governance", "Deployment Pipelines", "Thin Reports", "PBIP Git Integration", "Fabric Capacity Metrics"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Cho phép mọi người tải lên các file PBIX độc lập chứa cùng một tập dữ liệu dẫn đến 50 dataset giống nhau ngốn sạch RAM cụm máy chủ"]
  ),
  q("BI-PRAC-07", "Business Intelligence (BI)", "practical_skills", "intermediate", "junior",
    "Cấu hình Cổng dữ liệu Doanh nghiệp (On-premises Data Gateway) và Tự động hóa Lịch làm mới dữ liệu (Scheduled Refresh): Cách khắc phục lỗi Timeout, Xung đột tài nguyên và Cảnh báo thất bại?",
    ["Kiến trúc Gateway: Hoạt động như cầu nối an toàn mã hóa giữa Power BI Cloud Service và các cơ sở dữ liệu nội bộ (SQL Server, Oracle, SAP) nằm sau tường lửa doanh nghiệp", "Standard Gateway vs Personal Gateway: Standard hỗ trợ nhiều người dùng, phân quyền truy cập và DirectQuery; Personal chỉ hỗ trợ Import mode cho cá nhân", "Xử lý lỗi Refresh Timeout (vượt quá 2 giờ trên Pro / 5 giờ trên Premium): Tối ưu hóa query nguồn qua Query Folding trong Power Query, giảm bớt số dòng, hoặc bật Incremental Refresh", "Thiết lập cảnh báo tự động: Cấu hình gửi email thông báo thất bại ngay lập tức cho Quản trị viên BI và tích hợp webhook gửi tin nhắn tới Microsoft Teams / Slack"],
    ["Query Folding trong Power Query là gì và tại sao việc mất Query Folding lại là nguyên nhân hàng đầu khiến Refresh bị timeout?", "Cách cấu hình Gateway Cluster phân tải và tự động chuyển đổi dự phòng (High Availability) ra sao?"] ,
    ["On-premises Data Gateway", "Scheduled Refresh", "Query Folding", "Gateway Cluster", "Timeout Remediation"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Cài đặt Personal Gateway trên laptop cá nhân của nhân viên rồi tắt máy tính đi ngủ khiến hệ thống báo cáo sáng hôm sau bị lỗi refresh"]
  ),
  q("BI-PRAC-08", "Business Intelligence (BI)", "practical_skills", "advanced", "senior_lead",
    "Thúc đẩy Văn hóa Dữ liệu Tự phục vụ (Self-Service BI Adoption) và Đào tạo Người dùng Cuối: Cách xây dựng Thư viện Mẫu chuẩn (BI Template Apps), Data Dictionary, và Kiểm soát Tránh Hỗn loạn (Sprawl Control)?",
    ["Thực trạng hỗn loạn (BI Sprawl): Hàng trăm báo cáo rác do người dùng tự tạo bị bỏ hoang, số liệu sai lệch tràn lan trên hệ thống", "Xây dựng Thư viện Mẫu (Templates): Cung cấp file `.pbit` chuẩn hóa sẵn logo, font chữ, bảng màu, trang bìa và các visual đo lường chuẩn mực", "Data Dictionary & Catalog: Cung cấp tài liệu mô tả tường minh từng chỉ số đo lường, công thức tính và nguồn dữ liệu ngay trong giao diện báo cáo", "Chương trình BI Champions: Đào tạo các 'siêu người dùng' (Power Users) tại từng phòng ban làm tuyến hỗ trợ đầu tiên; tổ chức các buổi 'Data Jam' / 'Dashboard Hackathon' nội bộ"],
    ["Làm thế nào để phát hiện và dọn dẹp các báo cáo không có ai mở trong 90 ngày qua?", "Chính sách kiểm duyệt (Audit Process) trước khi một báo cáo tự phục vụ được 'chứng nhận' (Certified) để chia sẻ toàn công ty?"] ,
    ["Self-Service BI", "BI Sprawl Management", "Certified Datasets", "Data Culture", "Dashboard Templates"],
    [DA_SRC.powerbi, DA_SRC.tableau],
    ["Thả lỏng cho toàn công ty tự tạo báo cáo không kiểm soát rồi bất lực khi xuất hiện 20 báo cáo doanh thu với 20 con số khác nhau"]
  ),

  // Scenario (6)
  q("BI-SCEN-01", "Business Intelligence (BI)", "scenario", "advanced", "middle",
    "Tình huống: Một dashboard Power BI quan trọng phục vụ Ban Giám đốc mất hơn 35 giây để tải trang mỗi lần mở, khiến các Giám đốc rất bực bội. Em được giao nhiệm vụ tối ưu hóa để thời gian tải trang giảm xuống dưới 3 giây. Em tiến hành chẩn đoán và xử lý theo từng bước như thế nào?",
    ["Bước 1: Bật Performance Analyzer trong Power BI Desktop: Ghi lại thời gian của từng visual để bóc tách: DAX Query time, Visual Display time, và Other (chờ đợi)", "Bước 2: Phân tích Visual nặng nhất: Nếu DAX Query > 2 giây, mở DAX Studio copy câu lệnh query để kiểm tra Server Timings (Formula Engine vs Storage Engine)", "Bước 3: Tối ưu hóa DAX: Thay thế các hàm lặp nặng (`FILTER(ALL(Table))` -> `KEEPFILTERS` hoặc filter trên cột), loại bỏ việc lặp phép tính nhiều lần bằng cách gán `VAR`", "Bước 4: Tối ưu hóa tầng giao diện: Giảm số lượng visual trên 1 trang từ 25 visual xuống 8 visual; gộp nhiều thẻ KPI nhỏ vào một visual Matrix hoặc New Card visual", "Bước 5: Tối ưu mô hình: Dùng VertiPaq Analyzer xóa bỏ các cột không dùng và giảm Cardinality"],
    ["Sự khác biệt giữa Formula Engine (FE - đơn luồng) và Storage Engine (SE - đa luồng nén) trong DAX?", "Tại sao việc có quá nhiều slicers tương tác chéo lại làm chậm thời gian render tổng thể?"] ,
    ["Dashboard Performance Optimization", "Performance Analyzer", "DAX Studio Server Timings", "Formula Engine vs Storage Engine", "Visual Consolidation"],
    [DA_SRC.powerbi, DA_SRC.dax],
    ["Khuyên Ban Giám đốc đổi sang dùng máy tính cấu hình mạnh hơn thay vì tối ưu hóa mã DAX và giao diện"]
  ),
  q("BI-SCEN-02", "Business Intelligence (BI)", "scenario", "advanced", "senior_lead",
    "Tình huống: Công ty là một tập đoàn bán lẻ có 500 cửa hàng trên toàn quốc. Yêu cầu đặt ra là xây dựng một hệ thống báo cáo phân tích bán hàng duy nhất, nhưng mỗi Cửa hàng trưởng chỉ được xem dữ liệu của cửa hàng mình, Giám đốc Vùng xem được các cửa hàng trong vùng, và Ban Giám đốc xem được toàn quốc. Em thiết kế giải pháp Dynamic RLS này ra sao?",
    ["Mô hình hóa dữ liệu bảo mật: Tạo bảng phân cấp tổ chức `Dim_Store_Hierarchy` chứa các cấp: `Store_ID`, `Area_ID`, `Region_ID`", "Bảng phân quyền người dùng: Bảng `Security_User_Access` chứa `User_Email`, `Access_Level` ('STORE', 'REGION', 'NATIONAL'), và `Access_Value` (Mã store hoặc mã region tương ứng)", "Viết bộ lọc DAX Dynamic RLS trên bảng Dimension: Sử dụng biến `VAR CurrentUser = USERPRINCIPALNAME()` để lấy email người đăng nhập; kiểm tra nếu `Access_Level = 'NATIONAL'` thì cho qua toàn bộ (`TRUE()`), ngược lại lọc theo Store_ID hoặc Region_ID tương ứng", "Hiệu năng: Đảm bảo mối quan hệ giữa bảng Security và bảng Dim_Store là 1-N lọc 1 chiều để không làm chậm các phép tính Fact bán hàng"],
    ["Làm thế nào để xử lý trường hợp một Quản lý vùng được tạm thời ủy quyền quản lý thêm một vùng khác trong 1 tháng?", "Cách kiểm thử tự động quyền xem dữ liệu của 500 người dùng mà không cần đăng nhập thủ công từng tài khoản?"] ,
    ["Enterprise Dynamic RLS", "Multi-level Hierarchy Security", "Retail Store Access Control", "USERPRINCIPALNAME DAX", "Scalable Security Architecture"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Tạo 500 file báo cáo riêng biệt cho 500 cửa hàng và gửi qua email thủ công mỗi ngày"]
  ),
  q("BI-SCEN-03", "Business Intelligence (BI)", "scenario", "advanced", "middle",
    "Tình huống: Sau khi làm mới dữ liệu tự động vào 7h sáng, một Measure tính 'Tỷ lệ Lợi nhuận gộp' (Gross Margin %) trên toàn bộ báo cáo bất ngờ hiển thị giá trị trống (`(Blank)`) hoặc lỗi chia cho 0 (`Infinity`), khiến các chỉ số KPI bị sập. Em xử lý sự cố nóng này trong vòng 15 phút như thế nào?",
    ["Bước 1: Xác định nguyên nhân tức thời: Hàm tính toán đang sử dụng toán tử chia `/` thông thường (`Sales / Cost`) hoặc hàm `DIVIDE` nhưng mẫu số bị NULL/0 do bảng dữ liệu nguồn mới nạp có bản ghi bất thường", "Bước 2: Hotfix khẩn cấp: Sửa công thức DAX sang chuẩn an toàn tuyệt đối: `DIVIDE(Gross_Profit, Total_Revenue, 0)` để luôn trả về 0 thay vì Blank hoặc lỗi chia cho 0", "Bước 3: Kiểm tra dữ liệu nguồn: Truy vấn ngược lại bảng nguồn để tìm lý do tại sao `Total_Revenue` lại bằng 0 hoặc NULL (lỗi pipeline ETL chưa nạp xong, hoặc có dòng giao dịch hoàn trả âm)", "Bước 4: Xuất bản bản vá (Publish hotfix) lên BI Service và thông báo cho người dùng rằng sự cố hiển thị đã được khắc phục"],
    ["Tại sao trong DAX luôn luôn phải dùng hàm `DIVIDE()` thay vì toán tử `/`?", "Làm thế nào để cấu hình Data Alerts thông báo tự động khi một chỉ số quan trọng rơi về 0 bất thường?"] ,
    ["DAX Hotfix", "DIVIDE Safe Division", "Divide by Zero Remediation", "Production Incident Triage"],
    [DA_SRC.dax, DA_SRC.powerbi],
    ["Hoảng loạn rollback toàn bộ database trong khi lỗi chỉ là một phép chia thiếu kiểm tra mẫu số trong DAX"]
  ),
  q("BI-SCEN-04", "Business Intelligence (BI)", "scenario", "advanced", "senior_lead",
    "Tình huống: Doanh nghiệp muốn chuyển đổi nền tảng BI từ các file Excel phân tán và hệ thống báo cáo cũ (SSRS/Crystal Reports) sang Microsoft Fabric / Power BI hiện đại. Các phòng ban đang quen dùng Excel phản ứng rất dữ dội và sợ mất thói quen làm việc cũ. Em lập kế hoạch chuyển đổi và quản trị sự thay đổi (Change Management) như thế nào?",
    ["Chiến lược 'Không cướp đi Excel': Không ép buộc bỏ Excel ngay; giới thiệu tính năng 'Analyze in Excel' kết nối trực tiếp vào Power BI Dataset -> Người dùng vẫn dùng PivotTable Excel quen thuộc nhưng số liệu được lấy từ nguồn chuẩn duy nhất, không phải copy-paste thủ công", "Chứng minh giá trị vượt trội (Quick Wins): Xây dựng một dashboard thí điểm tự động hóa hoàn toàn báo cáo mất nhiều thời gian nhất của họ (tiết kiệm cho họ 4 tiếng làm thủ công mỗi ngày)", "Đào tạo đồng hành: Tổ chức các buổi workshop thực hành 'Cầm tay chỉ việc', giải thích lợi ích cụ thể cho công việc của chính họ chứ không nói về công nghệ", "Lộ trình tắt dần hệ thống cũ: Đặt thời hạn chuyển giao rõ ràng (sau 3 tháng chạy song song) và được sự bảo trợ chính thức từ Ban Tổng Giám đốc"],
    ["Làm thế nào để xử lý khi người dùng vẫn cố tình xuất toàn bộ dữ liệu ra Excel để tính toán lại?", "Cách thiết lập chính sách chống rò rỉ dữ liệu (Information Protection Labels / Purview) khi xuất dữ liệu từ BI sang Excel?"] ,
    ["BI Change Management", "Excel to Power BI Migration", "Analyze in Excel", "User Adoption Strategy", "Executive Sponsorship"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Đột ngột cắt toàn bộ quyền truy cập hệ thống cũ và ra lệnh cấm dùng Excel khiến nhân viên phản đối kịch liệt"]
  ),
  q("BI-SCEN-05", "Business Intelligence (BI)", "scenario", "advanced", "middle",
    "Tình huống: Trong một cuộc họp đánh giá kết quả kinh doanh, Tổng Giám đốc chỉ trích một dashboard BI được thiết kế rất bắt mắt nhưng 'chỉ toàn đưa ra số liệu quá khứ mà không giúp ích gì cho việc ra quyết định ngày mai'. Em tiếp thu phản hồi này và tái thiết kế dashboard sang mô hình Phân tích Hành động (Actionable & Prescriptive Analytics) như thế nào?",
    ["Chuyển dịch tư duy: Chuyển từ Báo cáo Mô tả (Descriptive: Chuyện gì đã xảy ra?) sang Báo cáo Dự báo và Đề xuất (Prescriptive: Cần làm gì tiếp theo?)", "Tích hợp chỉ số Dự báo (Forecasting): Sử dụng tính năng phân tích chuỗi thời gian tích hợp sẵn trong BI để vẽ đường dự báo doanh số các tháng tới kèm khoảng tin cậy 95%", "Cung cấp nút hành động trực tiếp (Power Automate / Power Apps Visual): Cho phép Giám đốc bấm nút 'Kích hoạt chiến dịch khuyến mãi' hoặc 'Gửi cảnh báo tới kho hàng' ngay trên giao diện dashboard", "Bổ sung phân tích khoảng cách mục tiêu (Goal Tracking & Milestones): Luôn thể hiện rõ khoảng cách còn thiếu để đạt KPI tháng và tốc độ cần đạt (Run-rate required) trong những ngày còn lại"],
    ["Làm thế nào để đo lường tỷ lệ các quyết định kinh doanh được đưa ra trực tiếp dựa trên dashboard?", "Cách tích hợp mô hình Machine Learning dự báo điểm rủi ro khách hàng rời bỏ vào visual BI?"] ,
    ["Actionable BI Design", "Descriptive to Prescriptive", "Forecasting in BI", "Power Automate Integration", "Run-Rate Tracking"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Phản bác lại Tổng Giám đốc rằng 'nhiệm vụ của BI chỉ là hiển thị số liệu lịch sử'"]
  ),
  q("BI-SCEN-06", "Business Intelligence (BI)", "scenario", "advanced", "senior_lead",
    "Tình huống: Khi kiểm toán hệ thống Power BI Premium Capacity của công ty, em phát hiện chi phí license hàng tháng rất lớn nhưng có hơn 60% báo cáo đã không được mở trong 6 tháng qua, và nhiều báo cáo đang chạy refresh 48 lần/ngày dù dữ liệu nguồn chỉ cập nhật 1 lần/ngày. Em thiết kế chương trình tối ưu hóa tài nguyên và dọn dẹp hệ thống ra sao?",
    ["Bước 1: Kiểm toán toàn diện bằng Fabric/Power BI Activity Logs: Trích xuất lịch sử sử dụng qua API quản trị (`Get-PowerBIAuditEvent`) để lập danh sách tất cả các báo cáo, tác giả, lần truy cập cuối cùng và tần suất refresh", "Bước 2: Phân loại dọn dẹp (Triage): Gom các báo cáo không dùng vào nhóm 'Deprecation'; gửi email thông báo tự động cho tác giả: sau 30 ngày không có phản hồi sẽ chuyển sang trạng thái Archive", "Bước 3: Tối ưu lịch Refresh: Điều chỉnh lại lịch refresh của tất cả các dataset phù hợp với tần suất cập nhật thực tế của nguồn dữ liệu (từ 48 lần/ngày xuống 1-2 lần/ngày); giãn giờ refresh để tránh nghẽn đỉnh điểm 8h sáng", "Bước 4: Ban hành chính sách quản trị vòng đời (BI Lifecycle Policy): Tự động gắn tag và lưu trữ các workspace không hoạt động, yêu cầu phê duyệt khi đăng ký lịch refresh tần suất cao"],
    ["Cách đo lường dung lượng bộ nhớ RAM và CPU tiết kiệm được sau đợt dọn dẹp?", "Làm thế nào để thiết lập quy trình tự động hóa dọn dẹp (Automated Housekeeping script) qua PowerShell?"] ,
    ["BI Capacity Optimization", "Power BI Audit Logs", "Refresh Schedule Rationalization", "BI Lifecycle Management", "Cost Reduction"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Để mặc hệ thống phình to vô tận và yêu cầu công ty mua thêm dung lượng Premium tốn kém hàng chục ngàn USD"]
  ),

  // CV Validation (5)
  q("BI-CV-01", "Business Intelligence (BI)", "cv_validation", "advanced", "middle",
    "Trong các dự án BI em liệt kê trong CV, mô hình dữ liệu (Data Model) phức tạp nhất mà em từng thiết kế có bao nhiêu bảng Fact và Dimension? Em đã xử lý các thách thức về độ chi tiết dữ liệu (Granularity mismatch) giữa các bảng như thế nào?",
    ["Nêu rõ quy mô mô hình: Số lượng bảng Fact, Dimension, tổng số dòng của bảng Fact lớn nhất", "Giải quyết Granularity mismatch: Ví dụ bảng Kế hoạch (Budget) ở cấp độ Tháng/Phòng ban, nhưng bảng Thực tế (Actual) ở cấp độ Ngày/Giao dịch", "Giải pháp kỹ thuật: Tạo bảng Dimension ngày và Dimension phòng ban làm cầu nối (Conformed Dimensions) và xử lý DAX measure chuẩn xác ở cấp độ tháng"],
    ["Nếu phải thêm một chiều phân tích mới vào mô hình đó hôm nay, cấu trúc có dễ dàng mở rộng không?", "Thách thức lớn nhất trong việc tối ưu hóa mối quan hệ giữa các bảng trong dự án đó là gì?"],
    ["Data Model Complexity", "Granularity Mismatch", "Conformed Dimensions", "Architectural Scaling"],
    [DA_SRC.powerbi, DA_SRC.dax],
    ["Mô tả mô hình chỉ có 1 bảng phẳng duy nhất kéo từ Excel mà tự nhận là mô hình dữ liệu phức tạp"]
  ),
  q("BI-CV-02", "Business Intelligence (BI)", "cv_validation", "advanced", "senior_lead",
    "Em ghi nhận trên CV về kinh nghiệm viết các công thức DAX hoặc Tableau Calculations phức tạp. Hãy trình bày về một Measure thách thức nhất mà em từng viết (vd: Basket Analysis, Retention Cohort, hoặc Dynamic Currency)? Em đã giải quyết logic đó ra sao?",
    ["Bối cảnh nghiệp vụ của phép tính và lý do tại sao không thể tính đơn giản bằng các hàm cơ bản", "Bóc tách logic kỹ thuật: Cách sử dụng các biến `VAR`, can thiệp Filter Context, chuyển đổi bảng ảo trong bộ nhớ", "Đo lường hiệu năng: Cách tối ưu công thức đó để không làm đơ giao diện người dùng"],
    ["Có giải pháp nào khác ngoài DAX (như đẩy tính toán về tầng SQL/ETL trước) để tối ưu hơn không?", "Làm thế nào để chú thích (comment) và tài liệu hóa công thức phức tạp đó cho người kế thừa?"] ,
    ["Complex DAX Walkthrough", "Virtual Tables in DAX", "Performance Considerations", "Analytical Mastery"],
    [DA_SRC.dax, DA_SRC.powerbi],
    ["Nói rằng mình rất thành thạo DAX nhưng chỉ kể được các hàm `SUM`, `CALCULATE(SUM(...))` cơ bản"]
  ),
  q("BI-CV-03", "Business Intelligence (BI)", "cv_validation", "advanced", "middle",
    "Trong CV em có đề cập đến việc xây dựng hệ thống báo cáo cho các Giám đốc cấp cao (C-level). Em hãy chia sẻ về triết lý thiết kế UI/UX của mình khi tạo dashboard cho lãnh đạo? Làm thế nào để cân bằng giữa sự đơn giản và độ sâu thông tin?",
    ["Triết lý thiết kế hướng tới người dùng bận rộn: Tinh giản, không màu mè, tập trung vào hành động", "Áp dụng cấu trúc phân tầng: Tổng quan -> Xu hướng -> Chi tiết (Overview first, zoom and filter, details on demand)", "Sử dụng tính năng Drill-through và Tooltips tùy biến để người dùng chỉ thấy chi tiết khi họ thực sự muốn tìm hiểu sâu"],
    ["Phản hồi khó tính nhất từ một lãnh đạo cấp cao mà em từng nhận được về giao diện báo cáo là gì?", "Em đã chỉnh sửa thiết kế đó ra sao để họ hoàn toàn hài lòng?"] ,
    ["Executive UI/UX Philosophy", "Information Hierarchy", "Drill-through Design", "User-Centric BI"],
    [DA_SRC.internal],
    ["Thiết kế dashboard như một bức tranh nghệ thuật sặc sỡ nhưng lãnh đạo không tìm thấy thông tin kinh doanh cần thiết"]
  ),
  q("BI-CV-04", "Business Intelligence (BI)", "cv_validation", "advanced", "senior_lead",
    "Em ghi nhận có kinh nghiệm triển khai Power BI Service / Tableau Server ở quy mô doanh nghiệp. Em đã tổ chức cấu trúc Workspace, phân quyền (Viewer, Contributor, Member, Admin) và quản lý Gateway như thế nào để đảm bảo tính an toàn dữ liệu?",
    ["Tổ chức Workspace theo miền nghiệp vụ hoặc dự án, không theo cá nhân", "Phân quyền nghiêm ngặt theo nguyên tắc đặc quyền tối thiểu (Least Privilege): Người dùng cuối chỉ có quyền Viewer trong App, Contributor chỉ dành cho dev phát triển", "Bảo vệ dữ liệu nhạy cảm: Tách riêng Semantic Model ở Workspace bảo mật và chia sẻ quyền Build có kiểm soát cho các báo cáo khác", "Quản trị Gateway: Thiết lập cluster dự phòng, giám sát log hoạt động và quản lý kết nối an toàn"],
    ["Sự khác biệt giữa quyền Viewer và quyền Build trong Power BI Service?", "Cách xử lý khi một nhân viên phát triển nghỉ việc để thu hồi toàn bộ quyền truy cập và chuyển giao quyền sở hữu dataset?"] ,
    ["Enterprise BI Administration", "Role-Based Access Control", "Gateway Architecture", "Data Security Policy"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Cấp quyền Admin workspace cho tất cả mọi người để 'tiện làm việc'"]
  ),
  q("BI-CV-05", "Business Intelligence (BI)", "cv_validation", "intermediate", "junior",
    "Em liệt kê thành thạo Power Query (M Language) trong CV. Em đã sử dụng Power Query để thực hiện các phép biến đổi dữ liệu nâng cao nào (Unpivot, Phân tách chuỗi phức tạp, Gọi Web API) trước khi nạp vào mô hình?",
    ["Các phép biến đổi thực tế: Unpivot các cột tháng từ bảng Excel ngang thành cấu trúc dọc chuẩn cơ sở dữ liệu; gộp và hợp nhất nhiều file từ thư mục tự động", "Sử dụng M code tùy biến: Viết Custom Functions để lặp qua nhiều trang của REST API; xử lý lỗi từng dòng qua cấu hình `try ... otherwise`", "Tôn trọng Query Folding: Đảm bảo các bước biến đổi trong Power Query được chuyển dịch thành SQL đẩy về nguồn xử lý thay vì kéo dữ liệu thô về máy cục bộ"],
    ["Khi nào nên thực hiện biến đổi dữ liệu trong SQL của kho dữ liệu thay vì làm trong Power Query?", "Cách xem mã M Language nâng cao trong Advanced Editor của Power Query?"] ,
    ["Power Query M Language", "Query Folding Preservation", "Unpivot Transformations", "API Ingestion in M"],
    [DA_SRC.powerbi, DA_SRC.internal],
    ["Chỉ biết dùng các nút bấm chuột cơ bản và không hiểu bản chất mã ngôn ngữ M phía sau"]
  ),

  // Behavioral (5)
  q("BI-BEHAV-01", "Business Intelligence (BI)", "behavioral", "intermediate", "middle",
    "Khi người dùng cuối phản hồi rằng 'Báo cáo mới này khó dùng quá, tôi vẫn muốn quay lại dùng file Excel cũ của tôi', em tiếp nhận và xử lý sự kháng cự đó như thế nào?",
    ["Không nản lòng hay tự ái; xem đây là phản hồi tự nhiên trong quá trình chuyển đổi thói quen làm việc", "Lắng nghe trực tiếp: Ngồi cạnh người dùng quan sát họ thao tác với file Excel cũ để hiểu chính xác họ đang tìm kiếm điều gì và gặp khó khăn gì ở báo cáo mới", "Tinh chỉnh giao diện và đào tạo kèm cặp: Sửa lại các điểm gây bối rối, bổ sung các góc nhìn họ quen thuộc, và hướng dẫn họ cách thao tác nhanh hơn Excel"],
    ["Làm thế nào để tạo động lực cho họ chủ động sử dụng hệ thống mới?", "Khi nào thì việc giữ lại một phần xuất file Excel là cần thiết và hợp lý?"] ,
    ["User Empathy", "Overcoming Change Resistance", "User Feedback Loop", "Change Enablement"],
    [DA_SRC.internal],
    ["Đổ lỗi cho người dùng là bảo thủ, lười học hỏi và bỏ mặc họ không hỗ trợ"]
  ),
  q("BI-BEHAV-02", "Business Intelligence (BI)", "behavioral", "advanced", "senior_lead",
    "Trong một tổ chức lớn, các phòng ban thường có xu hướng yêu cầu làm dashboard riêng theo ý thích cá nhân (Dashboard Silos), dẫn đến tình trạng hàng chục dashboard trùng lặp và phân mảnh. Em xử lý bài toán chuẩn hóa và thuyết phục các phòng ban dùng chung sản phẩm chuẩn mực như thế nào?",
    ["Tổ chức buổi đối thoại đa phòng ban: Mời đại diện các bên cùng ngồi lại, chỉ ra điểm tương đồng trong nhu cầu của họ (thường giống nhau đến 80%)", "Thiết kế sản phẩm dữ liệu dùng chung linh hoạt (Core + Custom): Xây dựng một Master Dashboard chuẩn hóa các chỉ số cốt lõi, đồng thời cung cấp các bộ lọc và trang chi tiết đáp ứng nhu cầu đặc thù của từng bên", "Thiết lập quy trình xét duyệt yêu cầu mới: Nếu yêu cầu mới trùng lặp với báo cáo sẵn có thì hướng dẫn sử dụng thay vì làm mới"],
    ["Làm thế nào để dung hòa khi hai phòng ban nhất quyết không chịu nhường nhịn về định nghĩa một chỉ số?", "Cách xây dựng tinh thần cộng tác cùng sở hữu sản phẩm (Co-ownership) giữa BI và các phòng ban?"] ,
    ["De-siloing Data", "Cross-Departmental Consensus", "Standardization vs Customization", "Product Governance"],
    [DA_SRC.internal],
    ["Ai yêu cầu gì làm nấy mà không kiểm soát, biến hệ thống thành một mớ hỗn độn hàng trăm dashboard trùng lặp"]
  ),
  q("BI-BEHAV-03", "Business Intelligence (BI)", "behavioral", "intermediate", "junior",
    "Kể về một tình huống em phải làm việc dưới áp lực thời gian rất gấp để hoàn thành một bộ báo cáo phục vụ cuộc họp Đại hội Cổ đông hoặc Họp Ban Điều hành khẩn cấp. Em đã quản lý áp lực, phân bổ thời gian và đảm bảo độ chính xác dữ liệu ra sao?",
    ["Giữ bình tĩnh, xác định rõ phạm vi tối thiểu khả dụng (MVP): Tập trung vào 3-5 chỉ số quan trọng nhất bắt buộc phải có cho cuộc họp", "Quy trình kiểm tra chéo (Double-check): Dù thời gian gấp, vẫn kiên quyết dành ra ít nhất 30 phút để đối soát tổng số liệu với báo cáo tài chính đã chốt", "Thông báo tiến độ liên tục cho người yêu cầu để họ an tâm và chuẩn bị bài phát biểu"],
    ["Sau khi cuộc họp kết thúc thành công, em đã làm gì để hoàn thiện nốt các phần còn lại của báo cáo?", "Bài học rút ra về việc chuẩn bị sẵn dữ liệu nền tảng để không bị động trong các tình huống khẩn cấp tương tự?"] ,
    ["Working Under Pressure", "High-Stakes Delivery", "MVP Prioritization", "Data Accuracy Verification"],
    [DA_SRC.internal],
    ["Làm vội vàng trong hoảng loạn và nộp báo cáo sai lệch số liệu trong cuộc họp Đại hội Cổ đông"]
  ),
  q("BI-BEHAV-04", "Business Intelligence (BI)", "behavioral", "advanced", "senior_lead",
    "Chuyên viên BI thường nhận được những yêu cầu thay đổi màu sắc, font chữ hoặc bố cục mang tính cảm tính cá nhân từ các sếp ('Anh thấy màu này không hợp phong thủy', 'Đổi hết các biểu đồ sang hình tròn cho anh'). Em phản hồi và điều hướng những yêu cầu này như thế nào dựa trên nguyên tắc chuyên môn?",
    ["Tôn trọng ý kiến của lãnh đạo nhưng kiên định giải thích dựa trên các nguyên tắc khoa học về thị giác và nhận thức (Visual Perception & Cognitive Load)", "Giải thích lý do chuyên môn một cách khách quan: 'Biểu đồ thanh giúp mắt người so sánh chiều dài chính xác hơn góc nghiêng của biểu đồ tròn', 'Màu đỏ theo quy chuẩn quốc tế thể hiện cảnh báo rủi ro'", "Đưa ra phương án dung hòa: Tuân thủ bảng màu nhận diện thương hiệu của công ty và cho phép người dùng tùy biến một số góc nhìn cá nhân nếu phù hợp"],
    ["Làm thế nào để thiết lập một bộ Hướng dẫn Thiết kế BI (BI Design System & Style Guide) được công ty chính thức phê duyệt để làm căn cứ chuẩn mực?", "Cách từ chối khéo léo một yêu cầu phi lý mà không làm mất lòng lãnh đạo?"] ,
    ["Design System Defense", "Diplomatic Communication", "Cognitive Science in BI", "Professional Standards"],
    [DA_SRC.internal],
    ["Tuân theo mọi yêu cầu cảm tính kỳ quặc của từng sếp biến báo cáo thành một thảm họa thẩm mỹ, hoặc cãi tay đôi bướng bỉnh"]
  ),
  q("BI-BEHAV-05", "Business Intelligence (BI)", "behavioral", "intermediate", "middle",
    "Thế giới Business Intelligence đang chuyển dịch mạnh mẽ với sự xuất hiện của Generative AI và Copilot (tự động sinh báo cáo qua câu lệnh ngôn ngữ tự nhiên). Em nhìn nhận sự thay đổi này như thế nào và em chủ động chuẩn bị những kỹ năng gì để nâng tầm giá trị bản thân trong kỷ nguyên mới?",
    ["Tư duy cởi mở và chủ động: Xem AI là trợ thủ đắc lực giúp giải phóng khỏi các tác vụ viết code lặp lại, không xem AI là mối đe dọa thay thế", "Nâng cao các kỹ năng mà AI không thể thay thế: Năng lực thấu cảm nghiệp vụ, kỹ năng giải quyết bài toán phức tạp của con người, kỹ năng kiến trúc dữ liệu và đảm bảo chất lượng ngữ nghĩa (Semantic Integrity)", "Học hỏi và làm chủ công cụ mới: Thử nghiệm Microsoft Copilot for Power BI, học cách tối ưu hóa Semantic Model để AI đọc hiểu và trả lời chính xác cho người dùng doanh nghiệp"],
    ["Tại sao một mô hình dữ liệu chuẩn mực và có tài liệu hóa rõ ràng lại là điều kiện tiên quyết để AI Copilot hoạt động hiệu quả?", "Định hướng phát triển nghề nghiệp của em trong 3-5 năm tới trong lĩnh vực dữ liệu và BI?"] ,
    ["Future of BI", "AI Copilot Adoption", "Semantic Integrity", "Continuous Adaptation", "Career Vision"],
    [DA_SRC.internal],
    ["Sợ hãi công nghệ mới hoặc ngược lại, tin tưởng mù quáng rằng AI sẽ tự làm hết mà không cần con người hiểu mô hình dữ liệu"]
  )
];

module.exports = {
  dataAnalystQuestions,
  biQuestions
};
