const { q } = require('./fe_data.cjs');

const DE_SRC = {
  spark: "https://spark.apache.org/docs/latest/",
  kafka: "https://kafka.apache.org/documentation/",
  airflow: "https://airflow.apache.org/docs/",
  dbt: "https://docs.getdbt.com/docs/introduction",
  iceberg: "https://iceberg.apache.org/docs/latest/",
  delta: "https://docs.delta.io/latest/index.html",
  snowflake: "https://docs.snowflake.com/",
  bigquery: "https://cloud.google.com/bigquery/docs",
  kimball: "https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/",
  internal: "Tình huống nghiệp vụ và phỏng vấn thực tế - JobReady AI"
};

// 1. DATA ENGINEER (30 questions)
const dataEngineerQuestions = [
  // Foundation (6)
  q("DE-FOUND-01", "Data Engineer", "foundation", "intermediate", "junior",
    "Kiến trúc bộ nhớ và nguyên lý phân tán của Apache Spark: Phân biệt RDD, DataFrame, Dataset và cơ chế hoạt động của Catalyst Optimizer và Tungsten Engine?",
    ["RDD là cấu trúc phân tán cấp thấp bất biến; DataFrame là tập dữ liệu có schema được tổ chức theo cột; Dataset cung cấp type-safety compile-time", "Catalyst Optimizer: Tối ưu hóa truy vấn qua 4 giai đoạn (Analysis, Logical Optimization, Physical Planning, Code Generation)", "Tungsten Engine: Tối ưu hóa phần cứng, quản lý bộ nhớ off-heap (Unsafe Memory Management) tránh overhead của JVM GC, sinh mã nhị phân Whole-Stage Code Generation"],
    ["Tại sao DataFrame thường có hiệu năng cao hơn RDD thuần trong Spark?", "Bộ nhớ Spark chia thành các vùng nào (Storage memory, Execution memory, User memory)?"],
    ["Apache Spark", "Catalyst Optimizer", "Tungsten Engine", "RDD vs DataFrame", "Distributed Computing"],
    [DE_SRC.spark, DE_SRC.internal],
    ["Nghĩ rằng RDD nhanh hơn DataFrame vì RDD là API bậc thấp hơn"]
  ),
  q("DE-FOUND-02", "Data Engineer", "foundation", "advanced", "middle",
    "Nguyên lý Shuffling và Partitioning trong xử lý dữ liệu lớn: Phân biệt Narrow Transformation và Wide Transformation trong Spark, cùng cách khắc phục Data Skew?",
    ["Narrow Transformation: Dữ liệu ở một partition đầu vào chỉ phụ thuộc vào một partition đầu ra (map, filter); không cần chuyển dữ liệu qua mạng", "Wide Transformation: Yêu cầu hoán đổi dữ liệu giữa các node mạng (groupByKey, reduceByKey, join); gây ra Shuffle Write/Read tốn I/O mạng và đĩa", "Data Skew: Một vài task xử lý lượng dữ liệu vượt trội so với các task khác (chạy 99% rồi treo); giải pháp: Salt keys (thêm tiền tố ngẫu nhiên), Broadcast Hash Join nếu bảng nhỏ, Adaptive Query Execution (AQE skew join optimization)"],
    ["Tại sao nên dùng `reduceByKey` thay vì `groupByKey` trong Spark?", "Adaptive Query Execution (AQE) trong Spark 3.x tự động giải quyết skew partition như thế nào?"],
    ["Spark Shuffling", "Data Skew", "Wide vs Narrow Transformation", "Salting Keys", "AQE"],
    [DE_SRC.spark, DE_SRC.internal],
    ["Không hiểu shuffle là gì và cho rằng tăng CPU node sẽ giải quyết được Data Skew"]
  ),
  q("DE-FOUND-03", "Data Engineer", "foundation", "intermediate", "junior",
    "Kiến trúc Apache Kafka: Phân biệt Topics, Partitions, Consumer Groups, cơ chế phân bổ Offset và bảo đảm thứ tự gửi tin (Message Ordering)?",
    ["Topic được chia thành nhiều Partition song song; Partition là đơn vị phân tán và scale-out cơ bản trong Kafka", "Consumer Group: Mỗi partition trong một topic chỉ được đọc bởi duy nhất một consumer trong cùng một group tại một thời điểm", "Bảo đảm thứ tự: Kafka chỉ cam kết thứ tự tin nhắn (FIFO) trong phạm vi cùng một Partition, không cam kết thứ tự trên toàn bộ Topic", "Key-based Partitioning: Các bản ghi có cùng Record Key sẽ luôn được băm vào cùng một Partition"],
    ["Điều gì xảy ra nếu số lượng consumers trong group lớn hơn số lượng partitions của topic?", "Cơ chế Controller và Zookeeper (hoặc KRaft metadata quorum) vận hành ra sao?"],
    ["Apache Kafka", "Partitions", "Consumer Groups", "Offsets", "Message Ordering"],
    [DE_SRC.kafka, DE_SRC.internal],
    ["Nhầm lẫn rằng Kafka cam kết thứ tự thông điệp trên toàn bộ Topic"]
  ),
  q("DE-FOUND-04", "Data Engineer", "foundation", "advanced", "middle",
    "Ngữ nghĩa chuyển giao thông điệp (Message Delivery Semantics): So sánh At-least-once, At-most-once và Exactly-once Processing (EOS) trong Kafka và Flink/Spark Streaming?",
    ["At-most-once: Gửi một lần không retry; có thể mất dữ liệu nhưng không trùng lặp (offset commit trước khi xử lý)", "At-least-once: Retry liên tục đến khi thành công; không mất dữ liệu nhưng có thể tạo bản ghi trùng lặp (xử lý xong mới commit offset)", "Exactly-once (EOS): Kafka Idempotent Producer kết hợp Two-phase Commit Transaction Coordinator đảm bảo ghi chính xác một lần trên toàn bộ chuỗi Read-Process-Write", "Tính lũy biến (Idempotence) ở tầng downstream sink là chìa khóa then chốt để đạt được end-to-end exactly-once"],
    ["Làm thế nào để thiết kế một database sink có tính chất Idempotent (Upsert, Deduplication key)?", "Chỉ số `acks=all` và `min.insync.replicas` trong Kafka Producer có tác động thế nào đến độ bền dữ liệu?"],
    ["Message Semantics", "Exactly-Once Processing", "Idempotence", "Two-Phase Commit", "Kafka Transactions"],
    [DE_SRC.kafka, DE_SRC.spark],
    ["Tuyên bố hệ thống đạt Exactly-once mà không có cơ chế dedup tại tầng đích (consumer/sink)"]
  ),
  q("DE-FOUND-05", "Data Engineer", "foundation", "advanced", "middle",
    "Định dạng lưu trữ hướng cột (Columnar Storage) và Table Formats hiện đại: Tại sao Parquet và ORC tối ưu cho OLAP so với CSV/JSON? So sánh các Open Table Formats: Apache Iceberg, Delta Lake và Apache Hudi?",
    ["Columnar Storage: Chỉ đọc các cột cần thiết (Column Pruning), nén dữ liệu cực tốt (Dictionary, RLE, Snappy), lưu thống kê min/max ở cấp row group/stripe để Predicate Pushdown", "Open Table Formats: Bổ sung khả năng ACID transactions, Time Travel (truy vấn snapshot lịch sử), Schema Evolution và Hidden Partitioning trên nền Object Storage (S3/GCS/MinIO)", "Iceberg: Siết chặt metadata layer độc lập công cụ xử lý; Delta Lake: Gắn chặt với Databricks và Spark engine; Hudi: Tối ưu cho streaming ingestion với Upsert/Merge-on-Read"],
    ["Khác biệt giữa Copy-on-Write (CoW) và Merge-on-Read (MoR) trong Apache Hudi?", "Tại sao việc có quá nhiều file nhỏ (Small File Problem) lại làm giảm hiệu năng nghiêm trọng trên Data Lake?"],
    ["Apache Parquet", "Columnar Storage", "Apache Iceberg", "Delta Lake", "ACID on Lakehouse"],
    [DE_SRC.iceberg, DE_SRC.delta],
    ["Lưu trữ hàng terabyte dữ liệu phân tích dạng CSV/JSON trên S3 và phàn nàn truy vấn Athena chậm"]
  ),
  q("DE-FOUND-06", "Data Engineer", "foundation", "intermediate", "junior",
    "Mô hình dữ liệu kho (Data Warehousing Modeling): Phân biệt Mô hình Star Schema và Snowflake Schema theo triết lý Ralph Kimball. Khái niệm Fact table và Dimension table (SCD Type 1, 2, 3)?",
    ["Star Schema: Bảng Fact trung tâm liên kết trực tiếp với các bảng Dimension không chuẩn hóa (denormalized); tối ưu tốc độ join truy vấn", "Snowflake Schema: Bảng Dimension được chuẩn hóa (normalized) thành nhiều cấp bậc bảng con; tiết kiệm dung lượng nhưng tăng chi phí multi-table join", "Fact Table: Chứa các chỉ số đo lường định lượng (metrics: doanh thu, số lượng) và khóa ngoại trỏ tới dimensions", "SCD (Slowly Changing Dimensions): Type 1 (ghi đè mất lịch sử), Type 2 (thêm dòng mới kèm cột valid_from, valid_to, is_current để giữ toàn bộ lịch sử), Type 3 (thêm cột lưu giá trị cũ)"],
    ["Khi nào bắt buộc phải dùng SCD Type 2 thay vì Type 1 trong bài toán tài chính/bảo hiểm?", "Khái niệm Conformed Dimension trong Kimball Architecture là gì?"],
    ["Kimball Modeling", "Star Schema", "Snowflake Schema", "SCD Type 2", "Fact vs Dimension"],
    [DE_SRC.kimball, DE_SRC.internal],
    ["Không phân biệt được Fact và Dimension, hoặc dùng SCD Type 1 cho thông tin nhạy cảm cần truy vết lịch sử"]
  ),

  // Practical Skills (8)
  q("DE-PRAC-01", "Data Engineer", "practical_skills", "advanced", "middle",
    "Tối ưu hóa truy vấn và hiệu năng trong Apache Spark: Cách phân tích Spark UI (Event Timeline, DAG Visualization, Executor Metrics) để phát hiện Spill to Disk, Shuffle quá tải và Garbage Collection overhead?",
    ["Spark UI Event Timeline: Xác định task straggler (nhiệm vụ chạy lâu bất thường so với phần còn lại của stage)", "Spill to Disk (Memory vs Disk Spill): Xảy ra khi partition dữ liệu vượt quá dung lượng execution memory của executor; giải pháp: tăng số partition (`spark.sql.shuffle.partitions`), tăng `spark.executor.memory`", "GC Overhead: Thời gian Garbage Collection chiếm > 10% runtime; xử lý bằng cách chuyển sang Off-heap memory hoặc tune G1GC parameters", "DAG Visualization: Phát hiện các stage bị chia cắt do Wide Transformation không cần thiết"],
    ["Cách tính toán số lượng cores và memory tối ưu cho mỗi Spark Executor trong cụm YARN/K8s?", "Khi nào nên bật `spark.speculation` để xử lý các task bị nghẽn ngẫu nhiên trên worker chậm?"],
    ["Spark UI", "Spark Tuning", "Spill to Disk", "GC Tuning", "Executor Allocation"],
    [DE_SRC.spark, DE_SRC.internal],
    ["Gặp lỗi OOM (Out Of Memory) chỉ biết tăng RAM cụm lên gấp đôi mà không kiểm tra Spark UI tìm nguyên nhân"]
  ),
  q("DE-PRAC-02", "Data Engineer", "practical_skills", "advanced", "middle",
    "Thiết kế luồng điều phối DAG (Directed Acyclic Graph) phức tạp với Apache Airflow: Quản lý dependencies, Task Isolation qua KubernetesPodOperator, Dynamic Task Mapping và Backfilling?",
    ["Airflow Architecture: Webserver, Scheduler, Metadata Database, Triggerer và Executor (Celery/Kubernetes)", "KubernetesPodOperator: Cách ly tài nguyên và môi trường dependency của từng task; mỗi task chạy trong một Docker container độc lập, tránh xung đột thư viện Python", "Dynamic Task Mapping (`expand()`): Tự động sinh số lượng tasks song song dựa trên kết quả runtime của task trước mà không cần hardcode", "Backfilling & Catchup: Cơ chế chạy bù dữ liệu quá khứ; quản lý biến `execution_date` (`logical_date`) và `data_interval_start/end` chuẩn xác để bảo đảm Idempotency"],
    ["Tại sao việc truyền dữ liệu lớn qua Airflow XCom là một anti-pattern?", "Làm thế nào để ngăn chặn Scheduler bị treo khi có hàng trăm DAGs định nghĩa top-level code nặng?"],
    ["Apache Airflow", "DAG Design", "KubernetesPodOperator", "Backfilling", "Dynamic Task Mapping"],
    [DE_SRC.airflow, DE_SRC.internal],
    ["Viết câu lệnh kết nối database hoặc tải dữ liệu nặng ngay tại top-level của file DAG Python"]
  ),
  q("DE-PRAC-03", "Data Engineer", "practical_skills", "advanced", "middle",
    "Xử lý dữ liệu dạng luồng thời gian thực (Real-time Stream Processing) bằng Apache Flink hoặc Spark Structured Streaming: Quản lý Watermarks, Late Data Handling, State Backing và Windowing?",
    ["Event Time vs Processing Time vs Ingestion Time: Event Time dựa vào timestamp gắn trên sự kiện tại nơi phát sinh", "Watermark: Thước đo đánh dấu thời gian tiến độ của Event Time; thông báo cho hệ thống biết không còn sự kiện nào có timestamp trước mốc Watermark gửi tới", "Late Data: Xử lý qua Allowed Lateness, cập nhật window trước đó hoặc đẩy vào Dead Letter Queue (DLQ) / Side Output", "Stateful Processing: Quản lý state của các phép tính lũy kế (Tumbling/Sliding/Session window); Flink RocksDB StateBackend cho phép lưu trữ hàng Terabyte state phân tán"],
    ["Sự khác biệt giữa Checkpointing và Savepointing trong Flink?", "Cách khắc phục hiện tượng mất đồng bộ Watermark khi có một partition Kafka bị nhàn rỗi (Idle Partition)?"],
    ["Stream Processing", "Apache Flink", "Spark Streaming", "Watermarks", "Stateful Stream"],
    [DE_SRC.spark, DE_SRC.internal],
    ["Dùng Processing Time cho các báo cáo tài chính cần độ chính xác tuyệt đối theo giờ giao dịch"]
  ),
  q("DE-PRAC-04", "Data Engineer", "practical_skills", "advanced", "middle",
    "Kỹ thuật Change Data Capture (CDC) với Debezium và Kafka Connect: Cách đồng bộ dữ liệu giao dịch từ PostgreSQL/MySQL sang Data Lake/Warehouse theo thời gian thực mà không làm nghẽn Database nguồn?",
    ["Nguyên lý CDC: Đọc trực tiếp Transaction Log (Write-Ahead Log - WAL trong PostgreSQL, Binlog trong MySQL) thay vì truy vấn định kỳ `SELECT * WHERE updated_at > ...`", "Lợi ích: Zero performance impact trên bảng dữ liệu, bắt trọn vẹn cả sự kiện DELETE (điều mà truy vấn cột updated_at không làm được)", "Kafka Connect Architecture: Distributed Workers, Source Connector (Debezium), SMT (Single Message Transforms), Sink Connector (Snowflake/BigQuery/Iceberg)", "Xử lý Schema Evolution: Tích hợp Confluent Schema Registry (Avro/Protobuf) để bảo đảm tương thích tiến/lùi (Backward/Forward compatibility)"],
    ["Điều gì xảy ra với Debezium khi Database nguồn thực hiện DDL thay đổi cấu trúc bảng?", "Cách xử lý Initial Snapshot trên database có hàng tỷ bản ghi mà không khóa bảng (Lock table)?"],
    ["Change Data Capture", "Debezium", "Kafka Connect", "WAL Binlog", "Schema Registry"],
    [DE_SRC.kafka, DE_SRC.internal],
    ["Sử dụng cronjob chạy `SELECT * FROM orders WHERE updated_at > NOW() - 5m` làm sập database production"]
  ),
  q("DE-PRAC-05", "Data Engineer", "practical_skills", "advanced", "senior_lead",
    "Kiến trúc Medallion (Bronze - Silver - Gold) trên Lakehouse: Cách tổ chức luồng ETL/ELT chuẩn hóa dữ liệu, quản lý chất lượng và tối ưu hóa chi phí lưu trữ?",
    ["Bronze Layer (Raw): Lưu trữ toàn bộ dữ liệu thô nguyên bản kèm metadata (ingestion timestamp, source file name); append-only, schema-on-read", "Silver Layer (Cleansed/Enriched): Làm sạch, chuẩn hóa kiểu dữ liệu, deduplication, giải mã JSON nested, validate chất lượng dữ liệu cơ bản", "Gold Layer (Curated/Business-level): Tổng hợp theo mô hình Star Schema (Facts & Dimensions) phục vụ trực tiếp cho BI dashboards và ML feature sets", "Compaction & Retention: Tự động chạy OPTIMIZE (Bin-packing) và VACUUM để dọn dẹp các tệp tin nhỏ và snapshot cũ"],
    ["Làm thế nào để đảm bảo tính Idempotent khi chạy lại (reprocess) một khoảng thời gian trên Silver layer?", "Chiến lược lưu trữ phân tầng (Hot - Warm - Cold tiering) trên S3/Blob Storage giúp tiết kiệm bao nhiêu chi phí?"],
    ["Medallion Architecture", "Lakehouse", "Bronze Silver Gold", "Compaction VACUUM", "Data Layering"],
    [DE_SRC.delta, DE_SRC.iceberg],
    ["Cho phép người dùng BI truy vấn trực tiếp trên tầng Bronze lộn xộn chứa cả dữ liệu lỗi"]
  ),
  q("DE-PRAC-06", "Data Engineer", "practical_skills", "intermediate", "junior",
    "Tối ưu hóa truy vấn SQL trên Cloud Data Warehouses (Snowflake / BigQuery): Cơ chế Micro-partitioning, Clustering Keys, Partitioning và Caching hoạt động ra sao?",
    ["Snowflake Micro-partitioning: Tự động chia nhỏ dữ liệu thành các khối 50-500MB nén; lưu trữ metadata phong phú để thực hiện Partition Pruning mà không cần index thủ công", "BigQuery Partitioning & Clustering: Partition theo ngày (Date/Ingestion-time), Cluster theo 1-4 cột thường xuyên lọc/nhóm để gom các bản ghi liên quan vào cùng storage block", "Chi phí truy vấn: BigQuery tính tiền dựa trên lượng bytes quét (Bytes Scanned); tránh tuyệt đối `SELECT *` và luôn lọc theo partition column", "Query Caching: Tận dụng Result Cache nếu câu lệnh và dữ liệu không thay đổi trong 24 giờ"],
    ["Làm thế nào để nhận biết một bảng Snowflake cần được định nghĩa Clustering Key tường minh?", "Search Optimization Service trong Snowflake giải quyết bài toán tra cứu điểm (Point lookup) như thế nào?"],
    ["Snowflake", "BigQuery", "Micro-partitioning", "Partition Pruning", "Bytes Scanned Optimization"],
    [DE_SRC.snowflake, DE_SRC.bigquery],
    ["Chạy `SELECT *` trên bảng 50TB của BigQuery chỉ để lấy 5 dòng dữ liệu mẫu và tiêu tốn hàng trăm USD"]
  ),
  q("DE-PRAC-07", "Data Engineer", "practical_skills", "advanced", "middle",
    "Kiểm soát chất lượng dữ liệu tự động (Data Quality & Observability): Triển khai Great Expectations, Soda Core hoặc dbt tests để ngăn ngừa dữ liệu rác lan truyền trong pipeline?",
    ["Expectation Suites: Định nghĩa các ràng buộc dữ liệu tường minh (non-null, uniqueness, value range, regex format, referential integrity)", "Automated Validation Gates: Chạy kiểm tra chất lượng ngay sau bước Ingestion; nếu vi phạm Critical Assertions thì dừng pipeline, gửi cảnh báo PagerDuty/Slack", "Anomaly Detection: Phát hiện bất thường về số lượng dòng (Row count drop), độ trễ dữ liệu (Data Freshness/SLA delay), và phân phối giá trị (Distribution drift)", "Data Lineage: Truy vết nguồn gốc lỗi dữ liệu từ Gold ngược về Bronze để xác định phạm vi bảng bị ảnh hưởng"],
    ["Sự khác biệt giữa Blocking Test (dừng pipeline) và Warning Test (chỉ gửi thông báo)?", "Làm thế nào để đo lường độ tin cậy dữ liệu (Data Reliability SLA) đối với các bảng Gold quan trọng?"],
    ["Data Quality", "Great Expectations", "Soda Core", "Data Observability", "Data Lineage"],
    ["https://docs.greatexpectations.io/", DE_SRC.internal],
    ["Để dữ liệu sai sót lọt vào bảng báo cáo tài chính rồi mới phát hiện qua khiếu nại của Giám đốc"]
  ),
  q("DE-PRAC-08", "Data Engineer", "practical_skills", "advanced", "senior_lead",
    "Bảo mật và Quản trị dữ liệu (Data Governance & Security): Triển khai Row-level Security (RLS), Column-level Masking, Tokenization và kiểm soát RBAC/ABAC trên Data Platform?",
    ["Phân loại dữ liệu nhạy cảm (PII/PHI): Tự động gắn tag metadata cho các cột căn cước, số thẻ ngân hàng, email, số điện thoại", "Dynamic Data Masking: Hiển thị `***-***-1234` cho analyst thông thường, giải mã đầy đủ chỉ cho người có quyền hạn đặc biệt", "Row-level Security: Nhân viên khu vực miền Nam chỉ truy vấn được các dòng có `region = 'SOUTH'`, áp dụng trong suốt ở tầng catalog", "Access Control: Chuyển dịch từ RBAC (Role-based) sang ABAC (Attribute-based) kết hợp với các công cụ Data Governance như Apache Ranger, Immuta, hoặc Unity Catalog"],
    ["Quy định quyền được lãng quên (Right to be Forgotten - GDPR) được thực hiện như thế nào trên Lakehouse lưu trữ Parquet bất biến?", "Chiến lược quản lý mã hóa dữ liệu tại chỗ (Encryption at rest via KMS) và truyền tải (TLS) ra sao?"],
    ["Data Governance", "PII Masking", "Row-Level Security", "GDPR Compliance", "Unity Catalog"],
    [DE_SRC.snowflake, DE_SRC.internal],
    ["Lưu trữ số điện thoại và email khách hàng dưới dạng plaintext trong bảng dữ liệu chung cho toàn bộ công ty"]
  ),

  // Scenario (6)
  q("DE-SCEN-01", "Data Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một pipeline Spark xử lý dữ liệu giao dịch 10TB hàng ngày bất ngờ bị chậm gấp 4 lần (từ 1 giờ lên hơn 4 giờ) và thường xuyên chết vì lỗi `ExecutorLostFailure: Container killed by YARN for exceeding memory limits`. Em phân tích và xử lý sự cố này theo từng bước như thế nào?",
    ["Bước 1: Mở Spark UI kiểm tra Stage bị lỗi: Quan sát đồ thị Task Duration và Shuffle Read Size giữa các tasks để kiểm tra Data Skew", "Bước 2: Nếu có 1 task đọc 50GB trong khi các task khác đọc 500MB -> Khẳng định Data Skew do lệch key join/group; áp dụng kỹ thuật Salting key hoặc Broadcast Join nếu có bảng nhỏ", "Bước 3: Kiểm tra Off-heap memory: Tăng `spark.yarn.executor.memoryOverhead` từ mặc định 10% lên 20-25% nếu lỗi liên quan đến bộ nhớ native C++/PySpark", "Bước 4: Bật Adaptive Query Execution (`spark.sql.adaptive.enabled = true`) và `spark.sql.adaptive.skewJoin.enabled = true` để Spark tự chia nhỏ skewed partitions"],
    ["Làm thế nào để giám sát và cảnh báo sớm tình trạng dữ liệu phình to bất thường trước khi pipeline kích hoạt?", "Sự khác biệt giữa Memory Spill và Disk Spill trong Spark UI?"],
    ["Spark Troubleshooting", "OOM Error", "Data Skew Resolution", "Memory Overhead", "AQE Skew Join"],
    [DE_SRC.spark, DE_SRC.internal],
    ["Chỉ biết khởi động lại job và cầu may nó sẽ không bị lỗi mà không mở Spark UI phân tích"]
  ),
  q("DE-SCEN-02", "Data Engineer", "scenario", "advanced", "middle",
    "Tình huống: Đội kinh doanh phản ánh bảng số liệu doanh thu hàng ngày trên Dashboard bị sai lệch: dữ liệu ngày hôm qua bị thiếu 30% và xuất hiện các giao dịch bị nhân đôi (duplicate records). Em truy vết và khắc phục sự cố này trong pipeline ELT ra sao?",
    ["Bước 1: Kiểm tra Data Freshness: So sánh timestamp của dữ liệu mới nhất trong bảng Gold với dữ liệu ở Bronze/Source; phát hiện pipeline Airflow chạy bù hoặc bị nghẽn ở bước nào", "Bước 2: Kiểm tra nguyên nhân Duplicate: Do Kafka Producer retry khi gặp timeout mạng (thiếu Idempotent) hoặc do Airflow task chạy lại mà câu lệnh SQL dùng `INSERT INTO` thay vì `MERGE / UPSERT`", "Bước 3: Khắc phục dữ liệu: Viết script làm sạch tạm thời bằng `ROW_NUMBER() OVER (PARTITION BY transaction_id ORDER BY ingested_at DESC) = 1`", "Bước 4: Phòng ngừa lâu dài: Cập nhật câu lệnh đích thành `MERGE INTO` chuẩn Idempotent và bổ sung Great Expectations test kiểm tra uniqueness của primary key trước khi commit sang Gold"],
    ["Làm thế nào để thông báo minh bạch cho các bên liên quan về sự cố dữ liệu mà không làm giảm lòng tin?", "Quy trình Backfilling an toàn để nạp lại dữ liệu 30 ngày bị ảnh hưởng mà không làm gián đoạn dashboard hiện tại?"],
    ["Data Quality Incident", "Deduplication", "Idempotent Merge", "Airflow Retry Bug", "Root Cause Analysis"],
    [DE_SRC.kimball, DE_SRC.internal],
    ["Đổ lỗi cho đội database nguồn mà không kiểm tra lại logic idempotency của chính pipeline mình viết"]
  ),
  q("DE-SCEN-03", "Data Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Công ty quyết định chuyển đổi từ hệ thống Batch processing chạy qua đêm (Daily Batch) sang kiến trúc Near-Real-Time (Streaming) với độ trễ dưới 2 phút cho 50 triệu sự kiện/ngày. Em thiết kế kiến trúc kỹ thuật mới và kế hoạch chuyển giao (Migration Plan) ra sao?",
    ["Kiến trúc: Nguồn CDC (Debezium) -> Apache Kafka -> Stream Processor (Apache Flink / Spark Structured Streaming với micro-batch 30s) -> Iceberg/Delta Lake trên S3 -> Trino / ClickHouse cho truy vấn nhanh", "Dual-Run Strategy: Chạy song song cả pipeline Batch cũ và Streaming mới trong 2-4 tuần; liên tục đối chiếu số liệu đối soát (Reconciliation script) để đảm bảo độ chính xác tuyệt đối", "Quản lý chi phí: Tối ưu kích thước file trên Data Lake bằng streaming compaction engine ngầm để tránh Small File Problem", "Cut-over: Chuyển hướng các dashboard quan trọng sang nguồn mới sau khi tỷ lệ sai lệch đối soát bằng 0"],
    ["Chi phí hạ tầng giữa chạy Batch định kỳ và cụm Streaming 24/7 chênh lệch như thế nào?", "Làm thế nào để xử lý sự cố khi hạ tầng streaming bị gián đoạn trong 4 giờ và cần bắt kịp lượng backlog khổng lồ?"],
    ["Batch to Streaming Migration", "Kafka Flink Architecture", "Reconciliation Dual-Run", "Near-Real-Time Lakehouse"],
    [DE_SRC.kafka, DE_SRC.spark],
    ["Chuyển đổi ngay lập tức trên môi trường production mà không có giai đoạn chạy song song đối soát"]
  ),
  q("DE-SCEN-04", "Data Engineer", "scenario", "advanced", "middle",
    "Tình huống: Chi phí lưu trữ và truy vấn trên Cloud Data Warehouse (Snowflake hoặc BigQuery) tăng vọt 300% trong tháng vừa qua mà khối lượng dữ liệu chỉ tăng 10%. Em tiến hành kiểm toán chi phí (Cost Audit) và đưa ra các giải pháp cắt giảm chi phí ngay lập tức như thế nào?",
    ["Kiểm toán: Truy vấn bảng lịch sử chi phí (`SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY` hoặc BigQuery `INFORMATION_SCHEMA.JOBS_BY_PROJECT`) để tìm Top 10 câu truy vấn tốn kém nhất và người/dashboard kích hoạt", "Phát hiện nguyên nhân phổ biến: Dashboard BI tự động refresh mỗi phút dù không có ai xem; câu query thiếu điều kiện lọc partition khiến full-table scan liên tục; cấu hình Warehouse size quá lớn cho các tác vụ nhỏ", "Giải pháp tức thời: Đặt Auto-suspend cho Snowflake Warehouse về 60 giây; đặt Maximum Bytes Billed cho BigQuery queries; hạ tần suất refresh dashboard ngoài giờ hành chính", "Giải pháp lâu dài: Tối ưu Clustering/Partitioning; tạo Materialized Views hoặc Aggregate Tables phục vụ các dashboard có tần suất truy vấn cao"],
    ["Cách thiết lập Budget Alert và Quota hard-limit để ngăn chặn một câu query chạy lỗi ngốn hàng ngàn USD?", "Sự khác biệt về mô hình chi phí giữa On-demand Pricing và Flat-rate / Capacity Commitments?"],
    ["FinOps for Data", "Snowflake Cost Optimization", "BigQuery Query Cost", "Partition Pruning", "Auto-Suspend"],
    [DE_SRC.snowflake, DE_SRC.bigquery],
    ["Đề xuất xin tăng ngân sách công ty mà không phân tích bảng thống kê query history để tìm nguyên nhân lãng phí"]
  ),
  q("DE-SCEN-05", "Data Engineer", "scenario", "advanced", "middle",
    "Tình huống: Một bảng giao dịch trên Data Lake (Delta Lake/Iceberg) chứa hơn 500 triệu bản ghi bị lỗi 'Small File Problem' với hơn 2 triệu file có kích thước chỉ vài chục KB. Hệ thống truy vấn Athena/Spark bị nghẽn nghiêm trọng khi đọc bảng này. Em giải quyết dứt điểm vấn đề này ra sao?",
    ["Nguyên nhân: Do streaming job ghi micro-batch quá thường xuyên với nhiều partition; mỗi batch tạo ra hàng ngàn file nhỏ rải rác", "Xử lý tức thời: Chạy lệnh Compaction (trong Delta: `OPTIMIZE table ZORDER BY (user_id, date)`; trong Iceberg: `rewrite_data_files`) để gom các file nhỏ thành các file lớn kích thước lý tưởng (128MB - 512MB)", "Dọn dẹp snapshot: Chạy `VACUUM` với retention phù hợp để xóa bỏ vĩnh viễn các file cũ không còn được tham chiếu trong metadata", "Cấu hình phòng ngừa: Cấu hình Auto-compaction trong streaming write, hoặc gom batch lớn hơn tại memory buffer trước khi ghi đĩa"],
    ["Tại sao Z-Ordering lại tăng tốc truy vấn đa chiều tốt hơn so với Partitioning thông thường?", "Rủi ro khi chạy VACUUM với retention period quá ngắn trong khi các câu query dài hạn đang chạy?"],
    ["Small File Problem", "Delta Lake OPTIMIZE", "Iceberg Compaction", "VACUUM Cleanup", "Z-Ordering"],
    [DE_SRC.delta, DE_SRC.iceberg],
    ["Cố gắng tăng số lượng worker nodes lên để đọc 2 triệu file nhỏ thay vì gom file"]
  ),
  q("DE-SCEN-06", "Data Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Hệ thống yêu cầu tuân thủ quyền bảo vệ dữ liệu cá nhân (GDPR Article 17 - Quyền được lãng quên). Một người dùng gửi yêu cầu xóa toàn bộ thông tin cá nhân trên toàn bộ hệ thống Data Lake (chứa hàng petabyte dữ liệu phân tán bất biến Parquet). Em thiết kế giải pháp xóa dữ liệu tuân thủ chuẩn pháp lý mà vẫn đảm bảo hiệu năng ra sao?",
    ["Thách thức: File Parquet trên Object Storage là bất biến (Immutable); việc cập nhật hoặc xóa một dòng đòi hỏi phải đọc và ghi lại toàn bộ file", "Giải pháp Crypto-Shredding: Mã hóa dữ liệu PII của mỗi người dùng bằng một mã khóa riêng biệt (User-specific Key) lưu trong Key Management Service; khi người dùng yêu cầu xóa, chỉ cần hủy khóa mã hóa đó -> Dữ liệu trên Parquet lập tức trở thành rác không thể giải mã", "Giải pháp Lakehouse Mutation: Sử dụng Copy-on-Write hoặc Merge-on-Read của Iceberg/Delta để đánh dấu xóa (Delete Vector) theo đợt (Batch Deletion định kỳ hàng tuần), gom nhiều yêu cầu xóa lại để chạy một lần", "Audit Log: Lưu giữ bằng chứng xóa dữ liệu ẩn danh để phục vụ kiểm toán pháp lý mà không lưu lại thông tin PII"],
    ["Khác biệt giữa Hard Delete và Soft Delete trong môi trường dữ liệu phân tán?", "Làm thế nào để xử lý dữ liệu người dùng nằm trong các bản sao lưu (Cold Backups / Tape storage)?"],
    ["GDPR Compliance", "Right to be Forgotten", "Crypto-Shredding", "Delete Vectors", "Data Privacy Engineering"],
    [DE_SRC.iceberg, DE_SRC.internal],
    ["Từ chối thực hiện yêu cầu xóa vì lý do kỹ thuật 'Data Lake là file bất biến không thể xóa được'"]
  ),

  // CV Validation (5)
  q("DE-CV-01", "Data Engineer", "cv_validation", "advanced", "middle",
    "Trong dự án xây dựng Data Pipeline gần nhất mà em ghi trong CV, em hãy vẽ lại kiến trúc từ Data Ingestion, Storage, Processing đến Data Serving. Khối lượng dữ liệu (Data Volume, Velocity) và SLA độ trễ của hệ thống là bao nhiêu?",
    ["Mô tả mạch lạc luồng dữ liệu end-to-end với các công nghệ thực tế đã sử dụng", "Nêu chính xác số liệu: Dung lượng (GB/TB/ngày), số lượng sự kiện/giây (EPS/RPS), thời gian hoàn thành pipeline", "Giải thích lý do lựa chọn từng công cụ trong stack thay vì các giải pháp thay thế"],
    ["Thách thức kỹ thuật lớn nhất em trực tiếp gặp phải và cách em giải quyết trong dự án đó?", "Nếu khối lượng dữ liệu tăng gấp 10 lần vào năm sau, kiến trúc này sẽ gặp nút thắt cổ chai ở đâu đầu tiên?"],
    ["Architecture Walkthrough", "Data Volume SLA", "Technology Selection", "Production Scale"],
    [DE_SRC.spark, DE_SRC.internal],
    ["Mô tả kiến trúc chung chung giống sách giáo khoa, không nhớ được số liệu tải thực tế của dự án mình làm"]
  ),
  q("DE-CV-02", "Data Engineer", "cv_validation", "advanced", "middle",
    "Em ghi trong CV có kinh nghiệm tối ưu hóa chi phí hoặc tăng tốc pipeline dữ liệu. Em đã sử dụng công cụ đo lường nào để định lượng kết quả trước và sau khi tối ưu? Kết quả đo lường cụ thể đạt được là gì?",
    ["Chỉ ra metrics đo lường cụ thể: Thời gian chạy giảm từ X phút xuống Y phút, chi phí Cloud giảm $Z/tháng, số lượng node compute giảm", "Phương pháp tối ưu cốt lõi: Tối ưu phân vùng, loại bỏ shuffle, tuning tham số bộ nhớ, hay đổi mô hình dữ liệu", "Bằng chứng khách quan: Dashboard giám sát, hóa đơn Cloud, hoặc kết quả benchmark"],
    ["Có tác dụng phụ (trade-offs) nào phát sinh sau khi tối ưu không?", "Làm thế nào để duy trì mức hiệu năng tối ưu này khi codebase tiếp tục phát triển?"],
    ["Performance Optimization Proof", "FinOps Results", "Benchmarking", "Quantifiable Impact"],
    [DE_SRC.spark, DE_SRC.snowflake],
    ["Tuyên bố tối ưu được 50% hiệu năng nhưng không giải thích được cơ chế kỹ thuật bên dưới đã làm những gì"]
  ),
  q("DE-CV-03", "Data Engineer", "cv_validation", "advanced", "senior_lead",
    "CV của em đề cập đến việc triển khai Kafka hoặc Streaming Engine. Em đã thiết lập cơ chế giám sát độ trễ Consumer Lag như thế nào? Khi Consumer Lag tăng đột biến trong giờ cao điểm, hệ thống phản ứng ra sao?",
    ["Sử dụng công cụ giám sát chuyên biệt: Prometheus + Grafana với Kafka Exporter hoặc Burrow", "Xác định nguyên nhân lag: Lưu lượng đột biến, consumer bị chết, xử lý downstream bị nghẽn (DB write bottleneck), hoặc rebalance liên tục", "Cơ chế ứng phó: Tăng số lượng partitions và scale out consumers, tối ưu batch processing size trong consumer, hoặc thiết lập autoscaling KEDA"],
    ["Khi nào việc tăng số lượng consumers không giải quyết được vấn đề Consumer Lag?", "Cơ chế Rebalance storm trong Kafka xảy ra khi nào và cách phòng ngừa?"],
    ["Kafka Consumer Lag", "Monitoring Grafana", "Kafka Autoscaling", "Rebalance Storm"],
    [DE_SRC.kafka, DE_SRC.internal],
    ["Không biết Consumer Lag là gì hoặc chỉ phát hiện ra lag khi người dùng gọi điện phàn nàn thiếu dữ liệu"]
  ),
  q("DE-CV-04", "Data Engineer", "cv_validation", "intermediate", "junior",
    "Trong các dự án sử dụng Airflow hoặc Orchestration tool được liệt kê trong CV, em đã quản lý mã nguồn DAG, kiểm thử tự động (Unit Test / Integration Test cho pipeline) và triển khai CI/CD như thế nào?",
    ["Tổ chức Git repo: Tách biệt mã nguồn logic xử lý (Python packages) và file định nghĩa DAG orchestration", "Kiểm thử tự động: Chạy `dag.test()` hoặc `pytest` kiểm tra tính hợp lệ cú pháp DAG, không có chu trình (cycle-free), và schema data contracts", "CI/CD Pipeline: Kiểm tra linter (flake8/black), chạy automated tests, đóng gói Docker image hoặc đồng bộ DAGs vào bucket S3/GCS"],
    ["Làm thế nào để test một DAG trên môi trường Staging mà không làm ảnh hưởng đến dữ liệu sản xuất?", "Cách quản lý biến môi trường và Airflow Connections an toàn không lộ mật khẩu?"],
    ["CI/CD for Data", "Airflow Testing", "DAG Best Practices", "Pytest for Data"],
    [DE_SRC.airflow, DE_SRC.internal],
    ["Sửa code DAG trực tiếp trên máy chủ production qua giao diện web hoặc terminal"]
  ),
  q("DE-CV-05", "Data Engineer", "cv_validation", "advanced", "senior_lead",
    "Em ghi nhận có kinh nghiệm thiết kế Data Lakehouse / Data Warehouse. Em hãy phân tích một quyết định thiết kế mô hình dữ liệu (Data Modeling decision) quan trọng mà em đã chọn trong dự án và lý do tại sao em chọn hướng đó thay vì các phương án khác?",
    ["Bối cảnh nghiệp vụ cụ thể và yêu cầu truy vấn của các bên liên quan", "So sánh khách quan giữa các lựa chọn: Star Schema vs OBT (One Big Table) vs Snowflake Schema, hoặc Delta Lake vs Iceberg", "Lý do lựa chọn gắn liền với đặc thù truy vấn thực tế, chi phí compute và tần suất cập nhật dữ liệu"],
    ["Sau 6 tháng vận hành, quyết định thiết kế đó bộc lộ những điểm hạn chế gì cần cải tiến?", "Nếu có cơ hội làm lại từ đầu, em sẽ thay đổi điều gì trong thiết kế đó?"],
    ["Data Modeling Decision", "Star Schema vs OBT", "Architecture Retrospective", "Trade-off Evaluation"],
    [DE_SRC.kimball, DE_SRC.internal],
    ["Chọn công nghệ hoặc kiến trúc chỉ vì thấy nó đang 'hot' trên mạng mà không căn cứ vào bài toán thực tế"]
  ),

  // Behavioral (5)
  q("DE-BEHAV-01", "Data Engineer", "behavioral", "intermediate", "middle",
    "Khi một sự cố đường ống dữ liệu (Data Pipeline Breakdown) xảy ra vào lúc nửa đêm làm gián đoạn báo cáo điều hành của Ban Giám đốc vào sáng hôm sau, em tiếp nhận và xử lý áp lực đó như thế nào?",
    ["Giữ bình tĩnh, kích hoạt quy trình ứng cứu sự cố chuẩn hóa (Triage, Containment, Communication)", "Thông báo ngắn gọn, rõ ràng cho các bên liên quan về sự cố và thời gian dự kiến khắc phục (ETA)", "Tập trung khôi phục dịch vụ trước (Workaround/Hotfix), sau đó mới điều tra nguyên nhân gốc rễ (RCA) trong giờ làm việc"],
    ["Sau sự cố, em tổ chức buổi Post-Mortem không đổ lỗi (Blameless Post-Mortem) với đội ngũ như thế nào?", "Những hành động cụ thể nào được triển khai để ngăn chặn lỗi tương tự tái diễn?"],
    ["Incident Response", "Communication under Pressure", "Blameless Post-Mortem", "SLA Accountability"],
    [DE_SRC.internal],
    ["Hoảng loạn, giấu giếm thông tin sự cố hoặc đổ lỗi cho bên cung cấp hạ tầng/database nguồn"]
  ),
  q("DE-BEHAV-02", "Data Engineer", "behavioral", "advanced", "senior_lead",
    "Đội Data Analytics và Data Science liên tục phàn nàn rằng dữ liệu cung cấp quá chậm và yêu cầu cấp quyền truy cập trực tiếp vào Production Database để tự lấy dữ liệu. Em giải quyết xung đột này như thế nào?",
    ["Thấu hiểu nhu cầu cấp bách của đồng nghiệp nhưng kiên quyết bảo vệ an toàn và hiệu năng của Production DB", "Giải thích rõ rủi ro bảo mật và nguy cơ làm sập dịch vụ người dùng nếu cấp quyền trực tiếp", "Đưa ra giải pháp dung hòa: Tạo Read Replica, thiết lập CDC stream sang Data Lake với độ trễ thấp, hoặc xây dựng Data Mart phục vụ tự phục vụ (Self-service analytics)"],
    ["Làm thế nào để xây dựng một bản thỏa thuận dịch vụ dữ liệu (Data SLA) rõ ràng giữa DE và Data Consumers?", "Cách đo lường mức độ hài lòng của các đội ngũ sử dụng dữ liệu nội bộ?"],
    ["Cross-team Collaboration", "Conflict Resolution", "Data SLA", "Self-service Data Platform"],
    [DE_SRC.internal],
    ["Dễ dãi cấp quyền admin database cho các đội khác, hoặc ngược lại, từ chối thô bạo mà không đưa ra giải pháp thay thế"]
  ),
  q("DE-BEHAV-03", "Data Engineer", "behavioral", "intermediate", "junior",
    "Kể về một tình huống em phát hiện một đồng nghiệp trong đội viết câu lệnh SQL hoặc mã Spark rất kém hiệu năng (gây tốn tài nguyên cụm máy chủ chung). Em đã trao đổi và hỗ trợ đồng nghiệp đó cải thiện như thế nào?",
    ["Tôn trọng đồng nghiệp, tiếp cận trên tinh thần xây dựng và chia sẻ kiến thức (Code Review mang tính giáo dục)", "Chỉ ra số liệu cụ thể từ Spark UI / Query Plan chứng minh điểm nghẽn thay vì phán xét cảm tính", "Cùng đồng nghiệp thực hiện bài test so sánh hiệu năng trước và sau khi refactor mã nguồn"],
    ["Làm thế nào để chuẩn hóa các quy tắc tối ưu hóa thành tài liệu Best Practices chung cho cả đội?", "Cách tạo dựng văn hóa Code Review tích cực và không gây tự ái trong nhóm kỹ thuật?"],
    ["Constructive Code Review", "Knowledge Sharing", "Team Mentorship", "Data Engineering Culture"],
    [DE_SRC.internal],
    ["Chỉ trích gay gắt trong group chat chung hoặc tự ý sửa code của người khác mà không trao đổi"]
  ),
  q("DE-BEHAV-04", "Data Engineer", "behavioral", "advanced", "senior_lead",
    "Lãnh đạo doanh nghiệp yêu cầu triển khai một công nghệ dữ liệu mới đang rất thịnh hành (như Real-time AI Feature Store hoặc Graph Database) nhưng em nhận thấy hệ thống hiện tại chưa cần thiết và chi phí vận hành sẽ rất tốn kém. Em thuyết phục cấp trên ra sao?",
    ["Nghiên cứu kỹ lưỡng công nghệ mới, đánh giá khách quan cả ưu điểm và chi phí thực tế (TCO - Total Cost of Ownership)", "Lập bảng phân tích Chi phí - Lợi ích (Cost-Benefit Analysis) dựa trên bài toán kinh doanh hiện tại của công ty", "Đề xuất lộ trình phù hợp: Thử nghiệm Proof of Concept (PoC) nhỏ trước, hoặc chỉ ra giải pháp hiện tại vẫn đáp ứng tốt với chi phí chỉ bằng 1/5"],
    ["Nếu lãnh đạo vẫn bảo lưu quan điểm và yêu cầu triển khai, em sẽ thực hiện nhiệm vụ với thái độ như thế nào?", "Làm thế nào để bảo vệ đội ngũ kỹ sư không bị cuốn vào các trào lưu công nghệ thiếu thực tế?"],
    ["Upward Communication", "Pragmatic Engineering", "TCO Analysis", "Technology Adoption"],
    [DE_SRC.internal],
    ["Tuân lệnh một cách mù quáng gây lãng phí ngân sách lớn, hoặc phản đối gay gắt thiếu căn cứ dữ liệu"]
  ),
  q("DE-BEHAV-05", "Data Engineer", "behavioral", "intermediate", "middle",
    "Lĩnh vực Data Engineering thay đổi rất nhanh chóng với hàng loạt công cụ mới xuất hiện mỗi năm. Em xây dựng phương pháp học tập và cập nhật kiến thức liên tục như thế nào để không bị tụt hậu mà vẫn không bị phân tâm?",
    ["Tập trung nắm vững các nguyên lý cốt lõi bất biến (Distributed Systems, Database Internals, Storage Engines, Data Modeling)", "Theo dõi các nguồn tin uy tín: Kỹ thuật blog của các công ty công nghệ lớn (Uber, Netflix, Airbnb, Databricks), bản tin Data Engineering Weekly", "Thực hành thực tế: Tự xây dựng các mini-project trong homelab/cloud cá nhân để kiểm chứng công nghệ trước khi áp dụng vào công việc"],
    ["Làm thế nào để phân biệt giữa một công nghệ thực sự có giá trị đột phá và một xu hướng nhất thời?", "Cách cân bằng giữa việc học công nghệ mới và việc hoàn thành công việc hiện tại đúng hạn?"],
    ["Continuous Learning", "Core Fundamentals", "Technology Radar", "Professional Growth"],
    [DE_SRC.internal],
    ["Chạy theo học vẹt từng công cụ mà không hiểu nguyên lý hệ thống phân tán bên dưới"]
  )
];

// 2. ANALYTICS ENGINEER (30 questions)
const analyticsEngineerQuestions = [
  // Foundation (6)
  q("AE-FOUND-01", "Analytics Engineer", "foundation", "intermediate", "junior",
    "Vai trò và vị trí của Analytics Engineer trong tổ chức dữ liệu hiện đại: Phân biệt ranh giới trách nhiệm giữa Data Engineer, Analytics Engineer và Data Analyst?",
    ["Data Engineer: Chịu trách nhiệm hạ tầng cốt lõi, trích xuất và nạp dữ liệu thô (Extraction & Loading - EL), độ tin cậy của cụm phân tán và streaming pipelines", "Analytics Engineer: Chuyển đổi dữ liệu (Transformation - T trong ELT), thiết kế mô hình dữ liệu kinh doanh sạch sẽ, áp dụng thực hành công nghệ phần mềm (Software Engineering Best Practices: Git, CI/CD, dbt tests, documentation) vào kho dữ liệu", "Data Analyst: Sử dụng các mô hình dữ liệu sạch do AE tạo ra để thực hiện phân tích chuyên sâu, tạo báo cáo/dashboard và đưa ra các khuyến nghị kinh doanh"],
    ["Tại sao phong trào Modern Data Stack (MDS) lại thúc đẩy sự ra đời của vị trí Analytics Engineer?", "Khái niệm 'Data as Code' được thể hiện như thế nào trong công việc hàng ngày của AE?"],
    ["Analytics Engineering Role", "Data Roles Differentiation", "Modern Data Stack", "Data as Code"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Cho rằng Analytics Engineer chỉ đơn thuần là Data Analyst biết viết câu lệnh SQL phức tạp"]
  ),
  q("AE-FOUND-02", "Analytics Engineer", "foundation", "intermediate", "junior",
    "Khung chuyển đổi dữ liệu dbt (data build tool): Nguyên lý hoạt động cốt lõi của dbt (Jinja templating, Ref macro, DAG generation) và cách dbt chuyển hóa mã SQL thành các đối tượng trong Data Warehouse?",
    ["dbt biên dịch (compile) các file `.sql` chứa Jinja templating thành SQL thuần tương thích với từng dialect kho dữ liệu", "Hàm `{{ ref('model_name') }}`: Khai báo phụ thuộc giữa các models; dbt tự động phân tích và xây dựng đồ thị DAG phụ thuộc tuần tự", "Materializations: Bốn kiểu vật chất hóa chính: View (bảng ảo), Table (tạo bảng vật lý mới), Incremental (chỉ nạp dữ liệu mới/thay đổi), Ephemeral (CTE lồng ghép trong memory)", "dbt không di chuyển dữ liệu ra ngoài kho; toàn bộ phép tính được thực thi trực tiếp trên compute engine của Data Warehouse"],
    ["Sự khác biệt giữa `{{ ref() }}` và `{{ source() }}` trong dbt?", "Tại sao việc dùng `{{ ref() }}` lại giúp loại bỏ hoàn toàn việc hardcode tên schema và database trong SQL?"],
    ["dbt Core", "Jinja Macros", "Materializations", "DAG Lineage", "ref vs source"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Tưởng rằng dbt là một server xử lý dữ liệu độc lập tự kéo dữ liệu về máy để tính toán"]
  ),
  q("AE-FOUND-03", "Analytics Engineer", "foundation", "advanced", "middle",
    "Xây dựng mô hình dữ liệu gia tăng (Incremental Models) trong dbt: Cơ chế hoạt động của `is_incremental()`, chiến lược `merge` vs `delete+insert`, và quản lý `unique_key`?",
    ["Incremental Model: Trong lần chạy đầu tiên, dbt tạo bảng đầy đủ; trong các lần chạy tiếp theo, dbt chỉ truy vấn và biến đổi các dòng mới phát sinh kể từ lần chạy trước", "Macro `is_incremental()`: Điều kiện lọc SQL chỉ áp dụng khi chạy incremental (vd: `WHERE updated_at > (SELECT MAX(updated_at) FROM {{ this }})`)", "Merge Strategy: Sử dụng câu lệnh MERGE trên kho dữ liệu (Snowflake/BigQuery); so sánh theo `unique_key` để cập nhật dòng cũ hoặc chèn dòng mới", "Append Strategy vs Delete+Insert: Dùng cho dữ liệu bất biến không sửa đổi hoặc các kho dữ liệu không hỗ trợ MERGE hiệu quả"],
    ["Cách xử lý dữ liệu cập nhật trễ (Late-arriving data) trong dbt incremental model mà không bỏ sót bản ghi?", "Khi nào cần sử dụng cờ `--full-refresh` để xây dựng lại toàn bộ bảng từ đầu?"],
    ["dbt Incremental", "Merge Strategy", "Unique Key", "is_incremental()", "Late-Arriving Data"],
    [DE_SRC.dbt, DE_SRC.snowflake],
    ["Không khai báo `unique_key` trong incremental merge dẫn đến việc các bản ghi bị nhân đôi sau mỗi lần dbt run"]
  ),
  q("AE-FOUND-04", "Analytics Engineer", "foundation", "advanced", "middle",
    "Kiến trúc phân tầng mô hình dữ liệu trong dbt: Cấu trúc chuẩn Staging, Intermediate và Marts (Fct/Dim). Trách nhiệm và quy ước đặt tên của từng tầng?",
    ["Staging Layer (`stg_`): Làm sạch 1-1 với nguồn dữ liệu; đổi tên cột nhất quán, ép kiểu dữ liệu chuẩn, giải mã JSON thô; không thực hiện join hoặc aggregation phức tạp", "Intermediate Layer (`int_`): Tách nhỏ logic nghiệp vụ phức tạp, tiền xử lý các phép join đa nguồn, gom nhóm trung gian; không cho người dùng cuối truy vấn trực tiếp", "Marts Layer: Tầng phục vụ nghiệp vụ cuối cùng; chia thành Dimension models (`dim_`) và Fact models (`fct_`), tổ chức theo từng miền nghiệp vụ (Marketing, Finance, Product)", "Lợi ích: Giảm thiểu trùng lặp logic SQL (DRY), dễ bảo trì, tăng tốc độ debug và tối ưu chi phí compute"],
    ["Tại sao việc viết một câu query khổng lồ 1000 dòng kết hợp cả staging và marts lại là thảm họa bảo trì?", "Quy tắc quản lý quyền truy cập (Access Control) trên các schema staging vs marts ra sao?"],
    ["dbt Architecture", "Staging Intermediate Marts", "Data Modeling Layers", "DRY Principle"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Trực tiếp join các bảng thô ở Staging thành bảng báo cáo cuối cùng mà không qua tầng cấu trúc chuẩn mực"]
  ),
  q("AE-FOUND-05", "Analytics Engineer", "foundation", "advanced", "middle",
    "Tầng định nghĩa chỉ số thống nhất (Semantic Layer & Metric Layer): Khái niệm 'Define Once, Consume Anywhere' và cách Cube.js, dbt Semantic Layer hoặc LookML giải quyết bài toán sai lệch số liệu doanh nghiệp?",
    ["Thực trạng: Mỗi đội (Marketing, Sales, Finance) tự viết công thức tính Doanh thu (Revenue) hoặc Khách hàng kích hoạt (Active Users) trên tool BI riêng -> Ra 3 con số khác nhau", "Semantic Layer: Định nghĩa các chỉ số đo lường (Metrics/Measures) và các chiều phân tích (Dimensions) tập trung tại một nơi bằng mã nguồn (YAML/LookML)", "Truy vấn thống nhất: Các công cụ BI (Tableau, PowerBI), Excel, Reverse ETL truy vấn chỉ số qua giao diện Semantic Layer API; công thức được đồng bộ tuyệt đối", "Governance: Thay đổi công thức tính chỉ số tại semantic code là tự động cập nhật đồng loạt trên mọi báo cáo của doanh nghiệp"],
    ["Sự khác biệt giữa Metric (chỉ số đo lường) và Dimension (chiều phân tích)?", "Làm thế nào để tích hợp Cache và Pre-aggregation trong Semantic Layer để tăng tốc truy vấn sub-second?"],
    ["Semantic Layer", "Metric Layer", "dbt Metrics", "Cube.js", "LookML", "Single Source of Truth"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Để cho mỗi phòng ban tự định nghĩa công thức tính doanh thu riêng rẽ trên dashboard của họ"]
  ),
  q("AE-FOUND-06", "Analytics Engineer", "foundation", "intermediate", "junior",
    "Phương pháp thiết kế mô hình chiều (Dimensional Modeling) cho E-commerce và SaaS: Phân biệt Accumulating Snapshot Fact, Periodic Snapshot Fact và Transaction Fact?",
    ["Transaction Fact: Ghi nhận từng sự kiện giao dịch đơn lẻ tại một thời điểm tức thời (vd: đặt đơn hàng, thanh toán tiền); số lượng dòng lớn nhất, không bao giờ cập nhật", "Periodic Snapshot Fact: Chụp ảnh trạng thái tích lũy tại các khoảng thời gian cố định đều đặn (vd: số dư tài khoản cuối ngày, tồn kho cuối tuần); phục vụ phân tích xu hướng chuỗi thời gian", "Accumulating Snapshot Fact: Theo dõi tiến trình của một vòng đời quy trình nghiệp vụ có điểm bắt đầu và kết thúc (vd: Đặt hàng -> Đóng gói -> Giao vận -> Hoàn tất); có nhiều mốc thời gian và được cập nhật liên tục khi trạng thái thay đổi"],
    ["Khi nào nên sử dụng Accumulating Snapshot Fact cho bài toán theo dõi phễu tuyển dụng hoặc phễu bảo hiểm?", "Cách thiết kế surrogate key (khóa thay thế) trong bảng chiều bằng hàm băm MD5/SHA256?"] ,
    ["Kimball Dimensional Modeling", "Transaction Fact", "Periodic Snapshot", "Accumulating Snapshot", "Surrogate Keys"],
    [DE_SRC.kimball, DE_SRC.internal],
    ["Dùng Transaction Fact để tính toán số dư tài khoản lịch sử bằng cách cộng dồn hàng triệu dòng mỗi lần truy vấn"]
  ),

  // Practical Skills (8)
  q("AE-PRAC-01", "Analytics Engineer", "practical_skills", "advanced", "middle",
    "Kiểm thử dữ liệu chuyên sâu với dbt Tests: Phân biệt Generic Tests (`unique`, `not_null`, `accepted_values`, `relationships`), Singular Tests, và mở rộng với package `dbt-expectations`?",
    ["Generic Tests: Các bài kiểm tra sẵn có được khai báo trong file `schema.yml`; dbt tự động sinh query kiểm tra tính toàn vẹn", "Singular Tests: Các câu lệnh SQL tùy biến viết trong thư mục `tests/`; bài test được coi là đạt (pass) nếu query trả về 0 dòng kết quả lỗi", "`dbt-expectations`: Thư viện mở rộng lấy cảm hứng từ Great Expectations; cho phép kiểm tra phân phối thống kê, định dạng regex, kiểm tra chênh lệch tỷ lệ phần trăm giữa hai cột", "Test Severity & Stored Failures: Cấu hình `warn_if` vs `error_if`, và lưu vết các bản ghi vi phạm vào bảng lỗi qua cấu hình `--store-failures` để đội audit phân tích"],
    ["Làm thế nào để cấu hình dbt test chặn đứng việc merge Pull Request trong CI/CD pipeline nếu phát hiện vi phạm tính duy nhất?", "Cách viết một Custom Generic Macro Test để tái sử dụng trong toàn bộ dự án dbt?"] ,
    ["dbt Tests", "Generic vs Singular", "dbt-expectations", "Data Integrity", "Store Failures"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Triển khai hàng chục models vào production mà không viết bất kỳ một bài kiểm tra test nào"]
  ),
  q("AE-PRAC-02", "Analytics Engineer", "practical_skills", "advanced", "senior_lead",
    "Thiết lập quy trình CI/CD hoàn chỉnh cho dbt: Tự động hóa kiểm thử trên môi trường tạm thời (Slim CI / Deferral to Production), Slim CI runs và tối ưu hóa thời gian build PR?",
    ["Vấn đề: Chạy toàn bộ dbt project trên môi trường test mỗi khi mở PR mất hàng giờ và tốn chi phí compute khổng lồ", "Giải pháp Slim CI (`state:modified+`): So sánh manifest của PR với `manifest.json` của môi trường Production gần nhất; chỉ build và test những model có code bị thay đổi hoặc model phụ thuộc trực tiếp", "Deferral (`--defer`): Đối với các model tiền nhiệm không bị sửa đổi, dbt tự động trỏ tới bảng dữ liệu sẵn có trên Production thay vì phải build lại trên schema PR", "Tự động dọn dẹp (Ephemeral Schemas): Tự động tạo schema tạm cho mỗi PR và xóa bỏ sau khi PR được merge hoặc đóng"],
    ["Làm thế nào để bảo vệ dữ liệu nhạy cảm trên Production khi kích hoạt tính năng `--defer` cho các lập trình viên mới?", "Cách tích hợp dbt CI với GitHub Actions hoặc GitLab CI để tự động bình luận kết quả test vào PR?"] ,
    ["dbt CI/CD", "Slim CI", "State Modified", "Defer to Prod", "GitHub Actions for Data"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Chạy full-refresh toàn bộ dự án trên môi trường staging cho mỗi commit nhỏ làm tiêu tốn hàng ngàn USD chi phí warehouse"]
  ),
  q("AE-PRAC-03", "Analytics Engineer", "practical_skills", "advanced", "middle",
    "Theo dõi lịch sử thay đổi trạng thái với dbt Snapshots (SCD Type 2): Cơ chế hoạt động của chiến lược `timestamp` vs `check`, quản lý `dbt_valid_from` và `dbt_valid_to`?",
    ["dbt Snapshot: Cơ chế tự động biến bảng dữ liệu trạng thái hiện tại (mutable source) thành bảng lịch sử thay đổi theo chuẩn SCD Type 2", "Chiến lược `timestamp`: Sử dụng cột `updated_at` của bảng nguồn để phát hiện thay đổi; tối ưu hiệu năng tốt nhất khi nguồn có cột thời gian tin cậy", "Chiến lược `check`: So sánh giá trị băm của một danh sách các cột được chỉ định (check_cols); dùng khi bảng nguồn không có cột updated_at", "Cấu hình Snapshot: Định nghĩa `target_schema`, `unique_key`, `strategy`, dbt tự động quản lý các trường `dbt_scd_id`, `dbt_updated_at`, `dbt_valid_from`, `dbt_valid_to`"],
    ["Điều gì xảy ra nếu bảng nguồn bị xóa một dòng (hard delete) đối với dbt snapshot?", "Cách kết hợp dbt snapshot vào các Fact models để truy vấn dữ liệu lịch sử tại đúng thời điểm giao dịch phát sinh (Point-in-time join)?"] ,
    ["dbt Snapshots", "SCD Type 2", "Timestamp Strategy", "Check Strategy", "Point-in-Time Join"],
    [DE_SRC.dbt, DE_SRC.kimball],
    ["Không biết cách theo dõi lịch sử trạng thái đơn hàng và để mất toàn bộ dữ liệu trạng thái quá khứ khi bảng nguồn ghi đè"]
  ),
  q("AE-PRAC-04", "Analytics Engineer", "practical_skills", "advanced", "middle",
    "Tối ưu hóa chi phí và hiệu năng mô hình SQL trên Snowflake / BigQuery: Sử dụng dbt để quản lý Cluster Keys, Partitioning, Liquid Clustering và Materialized Views?",
    ["Cấu hình config block trong dbt: Khai báo `cluster_by`, `partition_by`, `cluster_keys` trực tiếp bên trong file SQL model", "Tránh tái tính toán: Chuyển đổi các bảng tổng hợp nặng được nhiều dashboard truy vấn thường xuyên từ View sang Table hoặc Incremental Table", "Tối ưu câu lệnh SQL: Loại bỏ các phép `SELECT DISTINCT` vô tội vạ (thay bằng phân tích nguyên nhân trùng lặp), thay thế các phép Window Function nặng bằng self-join có điều kiện nếu phù hợp", "Phân tích Query Profile: Đọc biểu đồ thực thi để phát hiện Partitions Scanned vs Total Partitions, xử lý tràn bộ nhớ (Memory Spilling)"],
    ["Khi nào nên dùng Materialized View trong kho dữ liệu thay vì dbt Incremental Table?", "Sự khác biệt giữa dbt Ephemeral model và View thông thường đối với chi phí compute kho dữ liệu?"] ,
    ["dbt Performance Tuning", "Warehouse Cost Optimization", "Query Profile", "Cluster By Config"],
    [DE_SRC.dbt, DE_SRC.snowflake],
    ["Viết câu lệnh dbt model tạo view lồng nhau 15 tầng khiến mỗi lần dashboard load phải chạy lại toàn bộ từ đầu"]
  ),
  q("AE-PRAC-05", "Analytics Engineer", "practical_skills", "advanced", "senior_lead",
    "Triển khai Reverse ETL và Data Activation với Census hoặc Hightouch: Cách đưa dữ liệu sạch từ Data Warehouse ngược trở lại các ứng dụng nghiệp vụ (HubSpot, Salesforce, Zendesk)?",
    ["Khái niệm Data Activation: Chuyển hóa Data Warehouse từ kho lưu trữ báo cáo thụ động thành động cơ điều khiển hoạt động kinh doanh trực tiếp", "Reverse ETL Architecture: Định nghĩa mô hình khách hàng tiềm năng / điểm rủi ro rời bỏ (Churn Score) trong dbt Marts -> Đồng bộ định kỳ qua API vào CRM (Salesforce/HubSpot)", "Quản lý đồng bộ: Cấu hình chế độ đồng bộ (Sync Modes: Upsert, Mirror, Update), xử lý ánh xạ trường (Field Mapping), và kiểm soát giới hạn gọi API (API Rate Limiting)", "Giám sát lỗi đồng bộ: Thiết lập cảnh báo khi đồng bộ thất bại do dữ liệu sai định dạng hoặc token CRM hết hạn"],
    ["Tại sao không nên để các ứng dụng nghiệp vụ tự kết nối trực tiếp vào Data Warehouse mà cần qua công cụ Reverse ETL?", "Cách xử lý xung đột dữ liệu khi cả người dùng trên Salesforce và pipeline Reverse ETL cùng cập nhật một trường thông tin?"] ,
    ["Reverse ETL", "Data Activation", "Hightouch", "Census", "CRM Sync"],
    ["https://www.hightouch.com/docs", DE_SRC.internal],
    ["Viết script Python tùy biến gọi API CRM mà không có cơ chế quản lý rate limit và retry khi gặp lỗi mạng"]
  ),
  q("AE-PRAC-06", "Analytics Engineer", "practical_skills", "intermediate", "junior",
    "Xây dựng tài liệu dữ liệu tự động (Data Documentation & Data Catalog): Triển khai `dbt docs generate`, Markdown descriptions, Data Lineage và tích hợp với Atlan hoặc Castor?",
    ["Tài liệu hóa trong code (Docs as Code): Viết mô tả chi tiết cho từng model và cột trong file `schema.yml`, hỗ trợ cú pháp Markdown và liên kết chéo qua Jinja `doc('block_name')`", "`dbt docs generate` & `serve`: Tự động tạo website tài liệu tĩnh chứa cấu trúc bảng, kiểu dữ liệu, các bài test đang áp dụng và biểu đồ Data Lineage trực quan", "Data Lineage tương tác: Giúp analyst và stakeholder nhìn thấy nguồn gốc dữ liệu bắt đầu từ đâu và các dashboard nào phụ thuộc vào model này", "Tích hợp Data Catalog: Tự động đồng bộ metadata và lineage lên các nền tảng doanh nghiệp (Atlan, Castor, Secoda) để tìm kiếm dữ liệu tự phục vụ"],
    ["Làm thế nào để thiết lập quy định bắt buộc (CI check) mọi cột mới tạo trong dbt đều phải có description trước khi merge PR?", "Cách giải thích biểu đồ Lineage cho người dùng phi kỹ thuật hiểu được tác động của một sự cố dữ liệu?"] ,
    ["dbt Docs", "Data Documentation", "Data Lineage", "Data Catalog", "Metadata Management"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Bàn giao hàng trăm bảng dữ liệu cho phòng ban khác sử dụng mà không có một dòng giải thích ý nghĩa các cột"]
  ),
  q("AE-PRAC-07", "Analytics Engineer", "practical_skills", "advanced", "middle",
    "Tự động hóa phát hiện sai lệch và quản lý hợp đồng dữ liệu (Data Contracts): Cách thiết lập dbt Model Contracts (`contract: enforced`) để bảo đảm cấu trúc schema không bị phá vỡ bởi upstream teams?",
    ["Data Contract: Bản cam kết kỹ thuật giữa bên sản sinh dữ liệu (Software Engineering) và bên tiêu thụ dữ liệu (Analytics/AE) về schema, kiểu dữ liệu và SLA", "dbt Model Contracts: Khai báo `contract: {enforced: true}` trong cấu hình model; dbt sẽ kiểm tra nghiêm ngặt kiểu dữ liệu và tên cột trước khi build", "Ngăn chặn lỗi âm thầm (Silent breaking changes): Nếu upstream database đổi tên cột hoặc đổi kiểu dữ liệu (từ int sang string), pipeline sẽ fail ngay lập tức có kiểm soát thay vì nạp dữ liệu sai vào báo cáo", "Schema Evolution an toàn: Đưa ra quy trình thông báo và deprecation period trước khi bên sản xuất thực hiện thay đổi cấu trúc bảng"],
    ["Tại sao việc thiếu Data Contract là nguyên nhân hàng đầu khiến các pipeline phân tích bị vỡ hạt nhân?", "Cách kết hợp dbt contracts với Protobuf/JSON Schema tại tầng ứng dụng sản xuất?"] ,
    ["Data Contracts", "dbt Model Contracts", "Schema Enforcement", "Upstream Breaking Changes"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Bị động chịu trận khi đội kỹ sư phần mềm đột ngột xóa hoặc đổi tên một cột trên database production"]
  ),
  q("AE-PRAC-08", "Analytics Engineer", "practical_skills", "advanced", "senior_lead",
    "Tái cấu trúc (Refactoring) hệ thống SQL kế thừa (Legacy SQL Sprawls): Quy trình chuyển đổi các câu query khổng lồ hàng ngàn dòng, nhiều subquery lộn xộn sang dbt project module hóa và dễ bảo trì?",
    ["Bước 1: Lập bản đồ phụ thuộc: Đọc mã nguồn cũ, xác định tất cả các bảng nguồn được truy vấn và bảng đích cuối cùng", "Bước 2: Xây dựng bộ test đối soát (Audit Baseline): Chạy query cũ lưu kết quả vào một bảng đối chứng", "Bước 3: Tách nhỏ thành các tầng dbt: Bóc tách từng CTE (Common Table Expression) thành các model Staging và Intermediate độc lập; loại bỏ logic trùng lặp", "Bước 4: Kiểm tra đối soát tự động: Sử dụng package `audit-helper` của dbt để so sánh từng dòng dữ liệu giữa bảng cũ và model dbt mới refactor (đảm bảo độ trùng khớp 100%)", "Bước 5: Chuyển đổi an toàn (Safe Cut-over) và xóa bỏ code cũ"],
    ["Làm thế nào để thuyết phục quản lý cấp thời gian cho việc refactor kỹ thuật khi họ liên tục yêu cầu thêm tính năng mới?", "Cách sử dụng package `dbt-audit-helper` để phát hiện sự khác biệt về độ chính xác số liệu sau refactor?"] ,
    ["SQL Refactoring", "Legacy Code Migration", "dbt Audit Helper", "Modularity", "Technical Debt Reduction"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Viết lại từ đầu toàn bộ hệ thống bằng logic mới mà không có bước đối soát số liệu với hệ thống cũ"]
  ),

  // Scenario (6)
  q("AE-SCEN-01", "Analytics Engineer", "scenario", "advanced", "middle",
    "Tình huống: Giám đốc Tài chính (CFO) và Giám đốc Marketing (CMO) đưa ra hai con số Doanh thu tháng trước lệch nhau 15% trong cuộc họp Ban điều hành. Em được giao nhiệm vụ điều tra nguyên nhân sai lệch và đưa ra giải pháp dứt điểm trong 24 giờ. Em hành động như thế nào?",
    ["Bước 1: Tiếp nhận và thu thập: Lấy chính xác hai câu lệnh SQL và logic đằng sau dashboard của CFO và CMO", "Bước 2: Phân tích nguyên nhân sai lệch phổ biến: Định nghĩa mốc thời gian (CFO tính theo ngày tiền về tài khoản, CMO tính theo ngày khách bấm đặt đơn); Xử lý đơn hàng hủy/hoàn tiền (CFO trừ tiền hoàn, CMO giữ nguyên tổng giá trị đơn GMV); Xử lý múi giờ (UTC vs Local GMT+7)", "Bước 3: Báo cáo minh bạch: Trình bày rõ ràng lý do tại sao có hai con số và cả hai con số đó đều đúng theo góc nhìn riêng của từng phòng ban", "Bước 4: Giải pháp dứt điểm: Tạo một mô hình dbt chuẩn hóa duy nhất với hai chỉ số được đặt tên tường minh: `net_revenue` (cho Finance) và `gross_merchandise_value` (cho Marketing); đưa vào Semantic Layer để không còn sự mập mờ"],
    ["Làm thế nào để giao tiếp khéo léo với hai vị Giám đốc mà không làm ai cảm thấy đội của mình bị 'bắt lỗi'?", "Cách xây dựng một bộ từ điển thuật ngữ dữ liệu (Business Data Glossary) thống nhất cho toàn công ty?"] ,
    ["Revenue Discrepancy", "Data Reconciliation", "Semantic Clarification", "Stakeholder Communication", "Single Source of Truth"],
    [DE_SRC.internal],
    ["Vội vàng kết luận một trong hai bên là sai hoàn toàn mà không tìm hiểu định nghĩa nghiệp vụ bên dưới"]
  ),
  q("AE-SCEN-02", "Analytics Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Lệnh `dbt run` chạy toàn bộ project vào lúc 6h sáng bị kéo dài từ 25 phút lên hơn 2 giờ, khiến các dashboard buổi sáng của các phòng ban bị trễ SLA. Em tiến hành chẩn đoán điểm nghẽn và đưa ra phương án khắc phục như thế nào?",
    ["Bước 1: Phân tích file log `dbt.log` và artifact `run_results.json`: Sắp xếp các model theo thời gian thực thi để tìm ra Top 3 models tốn nhiều thời gian nhất", "Bước 2: Kiểm tra đồ thị DAG: Xem có model nào đang là nút thắt cổ chai (bottleneck) khiến hàng chục model phía sau phải chờ đợi không", "Bước 3: Tối ưu hóa: Chuyển các model dạng `table` nặng thành `incremental`; tăng số lượng luồng thực thi song song (`--threads` từ 4 lên 8 hoặc 16); kiểm tra query profile trong warehouse tìm phép join thiếu index/clustering", "Bước 4: Tách nhỏ lịch chạy: Chạy các model quan trọng phục vụ báo cáo điều hành trước trong một job ưu tiên cao (`dbt run --select tag:p0_executive`), các model phân tích phụ chạy sau"],
    ["Rủi ro khi tăng số lượng `--threads` quá cao trong dbt đối với tài nguyên Data Warehouse?", "Cách thiết lập cảnh báo chủ động (Alert) khi thời gian chạy của một model vượt quá 2 lần thời gian trung bình?"] ,
    ["dbt Performance Bottleneck", "run_results.json", "Threads Tuning", "Incremental Conversion", "SLA Remediation"],
    [DE_SRC.dbt, DE_SRC.snowflake],
    ["Chỉ biết bấm chạy lại hoặc yêu cầu nâng gói Data Warehouse đắt tiền hơn mà không mở log phân tích"]
  ),
  q("AE-SCEN-03", "Analytics Engineer", "scenario", "advanced", "middle",
    "Tình huống: Đội phát triển phần mềm vừa phát hành phiên bản mới của ứng dụng mobile, trong đó họ đã đổi tên trường `user_id` thành `customer_uuid` và thay đổi định dạng dữ liệu cột `event_properties` từ text sang JSON lồng nhau. Toàn bộ pipeline dbt bị gãy đổ ngay trong đêm. Em xử lý khủng hoảng này ra sao?",
    ["Bước 1: Hotfix khôi phục pipeline: Tại tầng Staging model (`stg_app_events`), viết mã xử lý tương thích ngược: sử dụng `COALESCE(customer_uuid, user_id) AS user_id` và hàm parse JSON trích xuất các trường cần thiết", "Bước 2: Chạy lại dbt trên môi trường sản xuất để cập nhật dữ liệu mới nhất cho các dashboards", "Bước 3: Gặp gỡ đội Product/Software Engineering: Giải thích tác động của thay đổi vừa qua đối với toàn bộ hệ thống phân tích và báo cáo kinh doanh", "Bước 4: Thiết lập quy trình phòng ngừa: Triển khai Data Contract và tích hợp bước kiểm tra schema compatibility vào pipeline CI của đội phần mềm trước khi merge code"],
    ["Làm thế nào để thiết kế một macro dbt có khả năng tự động xử lý schema evolution mềm dẻo?", "Cách xây dựng mối quan hệ hợp tác tôn trọng giữa đội Software Engineering và đội Data?"] ,
    ["Breaking Schema Change", "Hotfix Staging Layer", "Coalesce Backwards Compatibility", "Data Contract Enforcement"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Ngồi chờ đội phần mềm rollback code ứng dụng thay vì tự xử lý tương thích tại tầng Staging của mình"]
  ),
  q("AE-SCEN-04", "Analytics Engineer", "scenario", "advanced", "middle",
    "Tình huống: Một bảng Fact trong kho dữ liệu chứa 200 triệu bản ghi bị phát hiện có khoảng 2% dữ liệu bị trùng lặp khóa chính (Duplicate Primary Keys) do một lỗi logic trong pipeline cũ từ 3 tháng trước. Bảng này đang được hàng chục dashboard sử dụng. Em lên kế hoạch làm sạch dữ liệu lịch sử và sửa lỗi pipeline hiện tại như thế nào?",
    ["Bước 1: Đánh giá phạm vi: Viết query thống kê chính xác số lượng bản ghi trùng lặp và các dashboards đang phụ thuộc vào bảng Fact này", "Bước 2: Sửa đổi logic pipeline: Đảm bảo dbt model hiện tại có cấu hình `unique_key` và thêm bài test `unique` trong `schema.yml` để ngăn chặn trùng lặp mới phát sinh", "Bước 3: Kế hoạch làm sạch dữ liệu cũ: Tạo một bảng tạm sạch bằng kỹ thuật Window Function: `QUALIFY ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY updated_at DESC) = 1`", "Bước 4: Chuyển đổi an toàn ngoài giờ cao điểm: Sử dụng lệnh atomic swap (`ALTER TABLE ... SWAP WITH ...` trong Snowflake hoặc thay thế bảng) để người dùng không gặp gián đoạn truy vấn", "Bước 5: Chạy dbt test xác nhận 100% không còn bản ghi trùng"],
    ["Tại sao việc xóa trực tiếp trên bảng sản xuất bằng câu lệnh DELETE thủ công là cực kỳ nguy hiểm?", "Làm thế nào để kiểm tra xem việc làm sạch dữ liệu có làm thay đổi các báo cáo tài chính đã chốt sổ của các tháng trước không?"] ,
    ["Data Cleansing", "Deduplication via QUALIFY", "Atomic Table Swap", "Data Integrity Restoration"],
    [DE_SRC.snowflake, DE_SRC.internal],
    ["Chạy câu lệnh DELETE không có điều kiện backup và làm mất dữ liệu quan trọng của công ty"]
  ),
  q("AE-SCEN-05", "Analytics Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Công ty mở rộng kinh doanh sang thị trường quốc tế, yêu cầu hệ thống phân tích dữ liệu phải hỗ trợ đa múi giờ (Multi-timezone) và đa tiền tệ (Multi-currency). Hiện tại toàn bộ kho dữ liệu đang lưu trữ theo giờ GMT+7 và tiền tệ VND. Em thiết kế giải pháp chuyển đổi kiến trúc dữ liệu này ra sao?",
    ["Chuẩn hóa Múi giờ: Quy định bắt buộc mọi timestamp ở tầng Bronze/Staging phải được chuyển đổi và lưu trữ theo chuẩn UTC (`timestamp_ntz` hoặc epoch timestamp); tạo dimension múi giờ và cung cấp helper macro chuyển đổi sang múi giờ địa phương tại tầng Marts", "Chuẩn hóa Tiền tệ: Tích hợp bảng tỷ giá hối đoái hàng ngày (Daily FX Rates); tại bảng Fact, lưu trữ cả số tiền nguyên tệ gốc (`amount_original`, `currency_original`) và số tiền quy đổi theo đồng tiền chuẩn quốc tế USD (`amount_usd`) dựa trên tỷ giá tại ngày giao dịch", "Tạo các metrics linh hoạt trong Semantic Layer: Cho phép người dùng dashboard chọn xem theo đồng nội tệ hoặc đồng tiền báo cáo tập đoàn USD", "Kiểm thử đối soát: Viết dbt test đảm bảo tỷ giá không bị null hoặc âm cho mọi ngày phát sinh giao dịch"],
    ["Thách thức khi giao dịch phát sinh vào ngày cuối tuần/ngày lễ khi thị trường ngoại hối đóng cửa?", "Cách xử lý sự khác biệt giữa tỷ giá giao dịch thực tế (Transaction Rate) và tỷ giá kế toán trung bình tháng (Accounting Rate)?"] ,
    ["Multi-Currency Architecture", "UTC Normalization", "FX Rates Integration", "Global Data Platform Design"],
    [DE_SRC.kimball, DE_SRC.internal],
    ["Cộng gộp doanh thu VND và USD lại với nhau như cùng một đơn vị tiền tệ trên báo cáo tổng hợp"]
  ),
  q("AE-SCEN-06", "Analytics Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Khi đội ngũ Analytics mở rộng từ 2 người lên 15 người cùng làm việc trên một dbt repository, các xung đột mã nguồn (Merge Conflicts), đè dữ liệu trên môi trường Development, và thời gian review code bị kéo dài nghiêm trọng. Em thiết lập các tiêu chuẩn cộng tác và kiến trúc kho mã (dbt Project Governance) như thế nào?",
    ["Tách biệt môi trường phát triển: Mỗi kỹ sư có schema cá nhân riêng biệt (vd: `dbt_minh_stg`), tuyệt đối không làm việc trên schema chung", "Quy chuẩn mã nguồn (Style Guide): Thiết lập SQLFluff linter tự động kiểm tra định dạng code, chữ hoa/thường, thụt đầu dòng trong pre-commit hook và PR", "Chiến lược phân chia Repository (Multi-project dbt / dbt Mesh): Khi dự án quá lớn, chia thành các sub-projects theo domain (Core Data, Marketing, Finance) và giao tiếp qua Public Models / Model Contracts", "Quy trình Review Code: Thiết lập checklist review rõ ràng (Lineage check, Slim CI pass, Data documentation đầy đủ)"],
    ["Lợi ích và chi phí khi chuyển đổi từ Monolithic dbt project sang dbt Mesh (Multi-project)?", "Cách đào tạo các Data Analyst mới tham gia vào dự án để họ tuân thủ đúng quy trình Git và dbt?"] ,
    ["dbt Governance", "dbt Mesh", "SQLFluff Linter", "Developer Schema Isolation", "Team Scaling"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Cho phép 15 người cùng commit trực tiếp vào branch `main` và build chung trên một schema duy nhất"]
  ),

  // CV Validation (5)
  q("AE-CV-01", "Analytics Engineer", "cv_validation", "advanced", "middle",
    "Trong CV em có ghi kinh nghiệm triển khai và tối ưu hóa dự án dbt. Quy mô dự án dbt lớn nhất mà em từng tham gia có bao nhiêu models? Em đã tổ chức cấu trúc thư mục và quản lý dependencies của dự án đó như thế nào?",
    ["Nêu rõ quy mô cụ thể: Số lượng models (vd: 150-500 models), số lượng nguồn dữ liệu, thời gian chạy toàn bộ", "Cấu trúc thư mục chuẩn: Phân chia rõ ràng `staging/`, `intermediate/`, `marts/`, `macros/`, `tests/`", "Cách quản lý dependencies qua `packages.yml` (dbt-utils, dbt-expectations) và các macro dùng chung"],
    ["Một quyết định tái cấu trúc mã dbt nào mà em tự hào nhất trong dự án đó?", "Khi dự án tăng thêm 100 models nữa, cấu trúc đó có cần thay đổi gì không?"],
    ["dbt Project Scale", "Directory Structure", "dbt Packages", "Engineering Rigor"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Nói dự án có hàng ngàn models nhưng không giải thích được cấu trúc phân tầng thư mục"]
  ),
  q("AE-CV-02", "Analytics Engineer", "cv_validation", "advanced", "middle",
    "Em ghi nhận trên CV về việc thiết kế Data Marts cho các phòng ban nghiệp vụ. Em hãy chọn một Data Mart cụ thể (vd: Marketing Attribution hoặc Customer Retention) và giải thích chi tiết cấu trúc bảng Fact và Dim mà em đã xây dựng?",
    ["Bối cảnh nghiệp vụ và các chỉ số đo lường trọng tâm của Data Mart đó", "Cấu trúc bảng: Khóa chính (Surrogate key), Khóa ngoại liên kết, các cột metrics, và granularity (mức độ chi tiết) của mỗi dòng trong bảng Fact", "Cách xử lý các chiều phân tích biến đổi chậm (SCD) liên quan đến khách hàng hoặc chiến dịch"],
    ["Làm thế nào để đảm bảo bảng Fact không bị phình to dữ liệu vô tận theo thời gian?", "Người dùng nghiệp vụ đã phản hồi thế nào về tính dễ dùng và tốc độ của Data Mart đó?"],
    ["Data Mart Design Walkthrough", "Granularity Definition", "Fact Dim Structure", "Business Impact"],
    [DE_SRC.kimball, DE_SRC.internal],
    ["Mô tả bảng Fact nhưng không xác định được Granularity (mỗi dòng đại diện cho cái gì)"]
  ),
  q("AE-CV-03", "Analytics Engineer", "cv_validation", "advanced", "senior_lead",
    "Trong CV em có đề cập đến việc áp dụng CI/CD cho dữ liệu (DataOps). Em đã tự mình cấu hình pipeline CI/CD đó từ đầu hay kế thừa từ hệ thống có sẵn? Các bước kiểm tra tự động cụ thể trong pipeline bao gồm những gì?",
    ["Mô tả chân thực mức độ tham gia: Tự cấu hình từ file YAML (GitHub Actions / GitLab CI) hay tinh chỉnh hệ thống hiện có", "Các bước kiểm tra tự động tuần tự: Linter (SQLFluff) -> dbt compile -> Slim CI test trên modified models -> Kiểm tra contract -> Tự động sinh documentation", "Cơ chế quản lý bí mật (Secrets management) để kết nối an toàn vào Data Warehouse từ CI runner"],
    ["Thách thức lớn nhất khi triển khai CI/CD cho dữ liệu so với CI/CD cho ứng dụng phần mềm truyền thống?", "Thời gian trung bình để hoàn thành một pipeline CI test cho một PR là bao lâu?"],
    ["DataOps CI/CD", "GitHub Actions for dbt", "Automated Quality Gates", "Real Hands-on Experience"],
    [DE_SRC.dbt, DE_SRC.internal],
    ["Khai báo thành thạo CI/CD nhưng không giải thích được cách thức Slim CI hoạt động trong thực tế"]
  ),
  q("AE-CV-04", "Analytics Engineer", "cv_validation", "intermediate", "junior",
    "Em liệt kê thành thạo SQL nâng cao trong CV. Hãy chia sẻ một tình huống thực tế trong công việc mà em phải sử dụng các kỹ thuật SQL phức tạp (Window Functions, Recursive CTEs, hoặc Dynamic Pivoting) để giải quyết một bài toán dữ liệu hóc búa?",
    ["Bài toán kinh doanh cụ thể cần giải quyết (vd: Tính toán chuỗi phiên người dùng Sessionization, phân tích cohort giữ chân, hoặc duyệt cây tổ chức cha-con)", "Giải thích logic kỹ thuật: Tại sao các phép GROUP BY thông thường không giải quyết được và bắt buộc phải dùng Window Function/Recursive CTE", "Hiệu năng thực thi: Đánh giá chi phí tài nguyên của câu query và cách tối ưu hóa"],
    ["Làm thế nào để viết câu SQL phức tạp đó sao cho các thành viên khác trong đội vẫn đọc hiểu và duy trì được?", "Sự khác biệt giữa `DENSE_RANK()`, `RANK()`, và `ROW_NUMBER()` trong ngữ cảnh bài toán đó?"],
    ["Advanced SQL", "Window Functions", "Recursive CTE", "Sessionization Logic"],
    [DE_SRC.internal],
    ["Chỉ biết các câu lệnh SQL cơ bản SELECT, JOIN, GROUP BY đơn thuần mà không nắm vững Window Functions"]
  ),
  q("AE-CV-05", "Analytics Engineer", "cv_validation", "advanced", "middle",
    "Em ghi có kinh nghiệm làm việc với các công cụ BI (Tableau, PowerBI, Metabase, Preset). Khi thiết kế mô hình dữ liệu trên kho, em đã tối ưu hóa như thế nào để các dashboard BI có thể tải nhanh dưới 3 giây?",
    ["Hiểu rõ cách thức công cụ BI tương tác với kho dữ liệu (Live Connection vs Import/Extract mode)", "Chiến lược tối ưu hóa: Đẩy toàn bộ các phép tính toán phức tạp về dbt và kho dữ liệu xử lý trước (Pre-computation), tránh tạo các calculated fields nặng trên tool BI", "Thiết kế bảng OBT (One Big Table) hoặc Aggregate tables chuyên dụng cho các biểu đồ high-level tóm tắt", "Kiểm soát số lượng visuals trên một trang dashboard để tránh gửi hàng chục query đồng thời vào kho dữ liệu"],
    ["Khi nào nên dùng chế độ DirectQuery/Live Connection và khi nào nên dùng Import Mode?", "Cách phát hiện các câu query ngầm do tool BI tự sinh ra gây nghẽn Data Warehouse?"] ,
    ["BI Performance Optimization", "Pre-computation", "One Big Table", "DirectQuery vs Import"],
    [DE_SRC.internal],
    ["Đổ lỗi cho tool BI chậm trong khi nguyên nhân là câu query kéo hàng triệu dòng dữ liệu thô về trình duyệt"]
  ),

  // Behavioral (5)
  q("AE-BEHAV-01", "Analytics Engineer", "behavioral", "intermediate", "middle",
    "Analytics Engineer thường là cầu nối đứng giữa đội Kỹ thuật phần mềm (Data Engineers) và đội Kinh doanh (Data Analysts, PMs). Khi hai bên có kỳ vọng trái ngược nhau về thời gian và phạm vi dự án dữ liệu, em điều phối giao tiếp như thế nào?",
    ["Lắng nghe và thấu cảm với cả hai bên: Hiểu áp lực kinh doanh cần số liệu gấp của PM, đồng thời hiểu sự khắt khe về chất lượng mã nguồn và hạ tầng của DE", "Đóng vai trò 'phiên dịch viên': Chuyển hóa các yêu cầu kinh doanh trừu tượng thành các thông số kỹ thuật rõ ràng, khả thi", "Đàm phán giải pháp phân kỳ (Phased delivery): Cung cấp bảng dữ liệu tạm thời có phạm vi hẹp để giải quyết nhu cầu trước mắt, kèm cam kết hoàn thiện mô hình chuẩn mực sau đó"],
    ["Kể về một tình huống thực tế em đã giải quyết thành công một hiểu lầm kỹ thuật giữa hai bên?", "Làm thế nào để tạo dựng sự tin tưởng lâu dài từ các stakeholder kinh doanh?"] ,
    ["Cross-Functional Bridge", "Empathy in Communication", "Phased Delivery", "Stakeholder Expectation"],
    [DE_SRC.internal],
    ["Đứng về một phía và chỉ trích phía còn lại, hoặc né tránh giao tiếp khiến mâu thuẫn leo thang"]
  ),
  q("AE-BEHAV-02", "Analytics Engineer", "behavioral", "advanced", "senior_lead",
    "Khi một Data Analyst liên tục tạo ra các câu lệnh SQL tự do (ad-hoc queries) nặng nề trực tiếp trên bảng sản xuất làm tăng chi phí và ảnh hưởng đến hệ thống, em sẽ tiếp cận và hỗ trợ bạn ấy như thế nào mà không làm bạn ấy cảm thấy bị cấm đoán?",
    ["Tiếp cận với thái độ hỗ trợ và đồng cảm: Tìm hiểu bài toán kinh doanh mà bạn ấy đang cố gắng giải quyết", "Giải thích trực quan tác động: Chỉ cho bạn ấy thấy biểu đồ tài nguyên và hóa đơn compute phát sinh từ câu query đó một cách khách quan", "Hướng dẫn giải pháp tốt hơn: Cùng bạn ấy viết lại câu query hiệu quả hơn, hoặc tạo sẵn một dbt Mart đáp ứng đúng nhu cầu để bạn ấy chỉ việc dùng mà không cần viết query phức tạp nữa"],
    ["Làm thế nào để tổ chức các buổi đào tạo nội bộ (Internal Data Office Hours) cho đội ngũ Analyst?", "Cách thiết lập cơ chế giới hạn tài nguyên (Resource Monitors/Quotas) an toàn trên Data Warehouse?"] ,
    ["Mentorship", "Constructive Feedback", "Empowering Analysts", "Data Office Hours"],
    [DE_SRC.internal],
    ["Chặn quyền truy cập của đồng nghiệp một cách đột ngột mà không giải thích lý do hay hướng dẫn thay thế"]
  ),
  q("AE-BEHAV-03", "Analytics Engineer", "behavioral", "intermediate", "junior",
    "Kể về một lần em mắc sai lầm nghiêm trọng trong việc biến đổi dữ liệu (vd: tính sai một chỉ số kinh doanh quan trọng hoặc ghi đè mất dữ liệu). Em đã thừa nhận sai lầm và xử lý hậu quả như thế nào?",
    ["Dũng cảm thừa nhận sai sót ngay khi phát hiện, không đổ lỗi cho người khác hoặc giấu giếm sự việc", "Hành động khắc phục khẩn cấp: Sửa lỗi code, chạy lại pipeline bù dữ liệu (re-run/backfill) và thông báo minh bạch cho người bị ảnh hưởng", "Rút ra bài học sâu sắc: Viết bài test dbt tự động và bổ sung quy trình review để ngăn chặn sai sót tương tự tái diễn vĩnh viễn"],
    ["Sau sự cố đó, sự tin tưởng của đội ngũ dành cho em thay đổi như thế nào?", "Làm thế nào để xây dựng tư duy phòng ngừa rủi ro (Defensive Engineering) trong công việc hàng ngày?"] ,
    ["Accountability", "Handling Mistakes", "Transparent Communication", "Preventative Mindset"],
    [DE_SRC.internal],
    ["Cố tình giấu lỗi và hy vọng không ai phát hiện ra, hoặc tìm cách đổ lỗi cho hệ thống nguồn"]
  ),
  q("AE-BEHAV-04", "Analytics Engineer", "behavioral", "advanced", "senior_lead",
    "Khi yêu cầu phân tích dữ liệu từ các phòng ban liên tục đổ về dồn dập (Ad-hoc requests overwhelm), làm thế nào em ưu tiên công việc (Prioritization) giữa việc giải quyết yêu cầu khẩn cấp trước mắt và việc xây dựng hạ tầng mô hình dữ liệu bền vững lâu dài?",
    ["Áp dụng ma trận ưu tiên (Impact vs Effort Matrix): Đánh giá tác động tài chính/chiến lược của từng yêu cầu trước khi nhận việc", "Phân bổ thời gian theo tỷ lệ (vd: 70% thời gian cho các dự án kiến trúc nền tảng, 30% cho hỗ trợ đột xuất)", "Chuyển dịch sang mô hình tự phục vụ (Self-service): Nhận diện các yêu cầu có tính lặp lại để xây dựng thành dbt Mart chuẩn mực, trao quyền cho người dùng tự kéo số mà không cần AE can thiệp thủ công"],
    ["Làm thế nào để nói lời 'Từ chối' (Saying No) hoặc 'Chưa phải lúc này' với một stakeholder cấp cao một cách lịch sự?", "Cách đo lường hiệu quả công việc của AE khi chuyển dịch từ làm dịch vụ sang xây dựng sản phẩm dữ liệu?"] ,
    ["Work Prioritization", "Self-Service Enablement", "Stakeholder Management", "Saying No Professionally"],
    [DE_SRC.internal],
    ["Nhận tất cả mọi việc dẫn đến kiệt sức (burnout), code cẩu thả và không bao giờ xây dựng được hạ tầng chuẩn"]
  ),
  q("AE-BEHAV-05", "Analytics Engineer", "behavioral", "intermediate", "middle",
    "Triết lý cốt lõi của Analytics Engineering là mang các chuẩn mực kỹ thuật phần mềm (Software Engineering Standards) vào thế giới phân tích dữ liệu. Em đã làm gì để lan tỏa văn hóa 'Data as Code' và kỷ luật viết test/documentation trong tổ chức của mình?",
    ["Làm gương tiên phong: Viết code sạch, luôn có test, mô tả tài liệu đầy đủ và tạo các template PR chuẩn mực", "Chia sẻ kiến thức thường xuyên: Tổ chức các buổi demo ngắn giới thiệu các công cụ và lợi ích của CI/CD, dbt cho toàn đội", "Ghi nhận và tôn vinh: Khích lệ các đồng nghiệp khi họ đóng góp các bài test tốt hoặc tài liệu hóa xuất sắc mô hình của họ"],
    ["Gặp phải sự phản kháng từ những người đã quen với cách làm thủ công nhanh-tiện kiểu cũ, em thuyết phục họ thế nào?", "Làm thế nào để duy trì kỷ luật chất lượng dữ liệu khi công ty đang trong giai đoạn tăng trưởng nóng?"] ,
    ["Culture Champion", "Data as Code Advocacy", "Change Management", "Engineering Discipline"],
    [DE_SRC.internal],
    ["Áp đặt quy tắc một cách cứng nhắc mà không giải thích cho đồng nghiệp thấy giá trị thực tế mang lại"]
  )
];

module.exports = {
  dataEngineerQuestions,
  analyticsEngineerQuestions
};
