const { q } = require('./fe_data.cjs');

const DS_SRC = {
  sklearn: "https://scikit-learn.org/stable/",
  pytorch: "https://pytorch.org/docs/stable/",
  xgboost: "https://xgboost.readthedocs.io/",
  triton: "https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/",
  onnx: "https://onnxruntime.ai/docs/",
  optuna: "https://optuna.readthedocs.io/",
  shap: "https://shap.readthedocs.io/",
  internal: "Tình huống nghiệp vụ và phỏng vấn thực tế - JobReady AI"
};

// 5. DATA SCIENTIST (30 questions)
const dataScientistQuestions = [
  // Foundation (6)
  q("DS-FOUND-01", "Data Scientist", "foundation", "advanced", "middle",
    "Sự đánh đổi giữa Độ chệch và Độ phương sai (Bias-Variance Tradeoff): Phân tích toán học của hàm mất mát tổng thể (Total Expected Error = Bias^2 + Variance + Irreducible Error) và cách điều tiết qua Regularization (L1 Lasso vs L2 Ridge)?",
    ["Tổng sai số kỳ vọng: Phân rã thành $Bias^2$ (độ lệch do mô hình quá đơn giản, underfitting), $Variance$ (độ nhạy cảm với biến động tập train, overfitting) và $\\sigma^2$ (nhiễu ngẫu nhiên không thể giảm)", "L1 Regularization (Lasso): Thêm số hạng phạt $\\lambda \\sum |w_i|$; gradient không triệt tiêu ở 0 tạo ra nghiệm thưa (Sparse weights), có tác dụng tự động chọn lọc đặc trưng (Feature Selection)", "L2 Regularization (Ridge): Thêm số hạng phạt $\\lambda \\sum w_i^2$; co các trọng số về gần 0 nhưng không triệt tiêu hoàn toàn; xử lý đa cộng tuyến (Multicollinearity) xuất sắc", "ElasticNet: Kết hợp cả L1 và L2 với tham số $l1\\_ratio$; dung hòa giữa chọn lọc đặc trưng và ổn định nhóm biến tương quan cao"],
    ["Tại sao hàm mất mát L1 lại tạo ra nghiệm tại các góc (corners) của miền ràng buộc hình thoi dẫn đến trọng số bằng 0?", "Khi dữ liệu có số chiều $p$ lớn hơn số quan sát $n$ ($p \\gg n$), Ridge hay Lasso hoạt động ổn định hơn?"],
    ["Bias-Variance Tradeoff", "L1 Lasso vs L2 Ridge", "ElasticNet", "Mathematical Regularization", "Underfitting vs Overfitting"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Nhầm lẫn giữa L1 và L2, hoặc không giải thích được tại sao L1 lại tạo ra vector trọng số thưa"]
  ),
  q("DS-FOUND-02", "Data Scientist", "foundation", "advanced", "middle",
    "Nguyên lý hoạt động và sự khác biệt toán học của các thuật toán Tree Ensemble: So sánh Bagging (Random Forest) và Gradient Boosting (XGBoost, LightGBM, CatBoost)?",
    ["Random Forest (Bagging): Xây dựng nhiều cây độc lập song song; mỗi cây huấn luyện trên một mẫu Bootstrap (mẫu có hoàn lại) và tập con ngẫu nhiên của các đặc trưng (Feature Subsampling); mục tiêu giảm Variance", "Gradient Boosting (Boosting): Xây dựng chuỗi các cây tuần tự (Sequential trees); mỗi cây mới cố gắng tối thiểu hóa phần dư sai số (Residuals / Pseudo-residuals) của các cây trước thông qua Gradient Descent của hàm Loss; mục tiêu giảm Bias", "XGBoost: Tối ưu hóa chuỗi Taylor bậc 2 (Second-order Taylor expansion: Gradient $g_i$ và Hessian $h_i$), bổ sung Regularization vào hàm mục tiêu cây", "LightGBM vs CatBoost: LightGBM dùng Histogram-based và Leaf-wise tree growth (tăng tốc độ và tiết kiệm RAM); CatBoost xử lý biến định danh (Categorical features) tự động tối ưu qua Ordered Boosting"],
    ["Tại sao Random Forest rất khó bị Overfitting khi tăng thêm số lượng cây, trong khi Gradient Boosting sẽ Overfitting nếu số lượng cây quá lớn?", "Cơ chế Histogram-based split finding trong LightGBM tăng tốc độ tính toán gấp bao nhiêu lần so với Exact greedy split trong XGBoost?"],
    ["Tree Ensembles", "Random Forest vs Boosting", "XGBoost Second-Order Taylor", "LightGBM Leaf-wise", "CatBoost"],
    [DS_SRC.xgboost, DS_SRC.sklearn],
    ["Nghĩ rằng Random Forest và XGBoost là cùng một thuật toán chỉ khác tên gọi thư viện"]
  ),
  q("DS-FOUND-03", "Data Scientist", "foundation", "advanced", "middle",
    "Đánh giá mô hình học có giám sát: Khi nào nên sử dụng ROC-AUC, PR-AUC, F1-Score (Macro vs Micro vs Weighted), và Log-Loss? Tại sao ROC-AUC có thể gây ảo tưởng trong bài toán mất cân bằng mẫu nghiêm trọng (Extreme Class Imbalance)?",
    ["ROC-AUC: Đồ thị giữa TPR (Recall) và FPR (Fall-out); không đổi khi phân phối nhãn thay đổi; tuy nhiên khi mẫu âm chiếm 99.9%, số lượng False Positive tăng mạnh vẫn khiến FPR rất nhỏ dẫn đến ROC-AUC cao giả tạo (vd: 0.98 nhưng mô hình thực tế rất tệ)", "PR-AUC (Precision-Recall AUC): Tập trung trực tiếp vào lớp thiểu số (Positive class); phản ánh trung thực năng lực mô hình khi dữ liệu mất cân bằng nghiêm trọng (Phát hiện gian lận, chẩn đoán bệnh hiếm)", "F1-Score: Trung bình điều hòa giữa Precision và Recall; Macro F1 tính trung bình đều cho mọi lớp (bảo vệ lớp thiểu số), Micro F1 gộp toàn bộ mẫu (thiên vị lớp chiếm đa số)", "Log-Loss (Cross-Entropy): Đo lường độ tin cậy của xác suất dự đoán (Calibration quality) thay vì chỉ nhìn vào nhãn phân loại nhị phân"],
    ["Tại sao Brier Score lại là thước đo quan trọng để đánh giá mức độ hiệu chuẩn xác suất (Probability Calibration)?", "Cách lựa chọn ngưỡng phân loại (Classification Threshold) tối ưu dựa trên Ma trận Chi phí - Lợi ích (Cost-Benefit Matrix) của doanh nghiệp?"] ,
    ["Evaluation Metrics", "ROC-AUC vs PR-AUC", "Macro vs Micro F1", "Log-Loss", "Class Imbalance"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Tự hào khoe mô hình phát hiện gian lận đạt ROC-AUC 0.99 mà không biết rằng PR-AUC chỉ đạt 0.15 và mô hình báo sai tràn lan"]
  ),
  q("DS-FOUND-04", "Data Scientist", "foundation", "advanced", "senior_lead",
    "Suy luận Nhân quả trong Khoa học Dữ liệu (Causal Inference): Phân biệt Dự báo (Prediction) và Nhân quả (Causation). Các phương pháp ước lượng hiệu ứng nhân quả trong nghiên cứu quan sát: Ghép điểm xu hướng (Propensity Score Matching - PSM), Hiệu số của hiệu số (Difference-in-Differences - DiD) và Biến công cụ (Instrumental Variables)?",
    ["Giới hạn của Machine Learning thông thường: ML tìm kiếm tương quan thống kê ($P(Y|X)$) phục vụ dự báo; Causal Inference trả lời câu hỏi can thiệp 'Nếu chúng ta can thiệp vào $X$, $Y$ sẽ thay đổi thế nào?' ($P(Y|do(X))$)", "Propensity Score Matching (PSM): Dự báo xác suất một đối tượng nhận can thiệp dựa trên các đặc trưng nền; ghép cặp đối tượng nhận can thiệp với đối tượng không nhận can thiệp có cùng điểm xu hướng để loại trừ thiên vị chọn mẫu", "Difference-in-Differences (DiD): So sánh sự thay đổi theo thời gian giữa nhóm can thiệp và nhóm đối chứng; loại trừ các yếu tố cố định không quan sát được qua giả định xu hướng song song (Parallel Trends Assumption)", "Instrumental Variables (IV): Sử dụng biến công cụ $Z$ tác động lên $Y$ chỉ duy nhất thông qua $X$; giải quyết bài toán biến nội sinh (Endogeneity) và biến ẩn gây nhiễu (Unobserved Confounders)"],
    ["Tại sao việc áp dụng mô hình dự báo thuần túy để quyết định chính sách giá có thể dẫn đến thảm họa kinh doanh?", "Làm thế nào để kiểm tra tính hợp lệ của giả định Parallel Trends trong phương pháp DiD?"] ,
    ["Causal Inference", "Propensity Score Matching", "Difference-in-Differences", "Instrumental Variables", "Do-Calculus"],
    [DS_SRC.internal],
    ["Đồng nhất suy luận nhân quả với việc tính độ quan trọng của đặc trưng (Feature Importance) trong Random Forest"]
  ),
  q("DS-FOUND-05", "Data Scientist", "foundation", "intermediate", "junior",
    "Kỹ thuật giảm số chiều (Dimensionality Reduction): So sánh Phân tích thành phần chính (PCA), t-SNE (t-Distributed Stochastic Neighbor Embedding) và UMAP (Uniform Manifold Approximation and Projection)?",
    ["PCA (Tuyến tính): Tìm các trục trực giao (Principal Components) tối đa hóa phương sai dữ liệu thông qua phân rã ma trận hiệp phương sai (Eigenvalue Decomposition / SVD); giữ lại cấu trúc toàn cục (Global structure), nhanh và có thể chuyển đổi ngược", "t-SNE (Phi tuyến): Ánh xạ xác suất tương đồng giữa các điểm từ không gian nhiều chiều sang 2D/3D bằng phân phối Student-t; bảo toàn cấu trúc cục bộ (Local structure/clusters), nhưng không bảo toàn khoảng cách toàn cục và tốn thời gian tính toán", "UMAP: Dựa trên lý thuyết topo đại số; nhanh hơn t-SNE gấp nhiều lần, bảo toàn cấu trúc cục bộ lẫn toàn cục tốt hơn và có thể áp dụng cho các điểm dữ liệu mới (hỗ trợ hàm `transform`)"],
    ["Tại sao bắt buộc phải chuẩn hóa dữ liệu (Standardization: Mean=0, Std=1) trước khi chạy PCA?", "Tại sao không bao giờ nên dùng t-SNE làm bước tiền xử lý feature cho mô hình phân loại mà chỉ nên dùng cho trực quan hóa?"] ,
    ["Dimensionality Reduction", "PCA Eigenvectors", "t-SNE vs UMAP", "Global vs Local Structure", "Data Standardization"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Chạy PCA trên tập dữ liệu chưa chuẩn hóa khiến biến có đơn vị lớn (vd: Lương hàng triệu) chi phối hoàn toàn 100% trục thành phần"]
  ),
  q("DS-FOUND-06", "Data Scientist", "foundation", "advanced", "middle",
    "Khả năng giải thích mô hình (Model Interpretability & Explainability): Phân biệt Global vs Local Interpretability. Cơ chế hoạt động của Giá trị SHAP (Shapley Additive Explanations) dựa trên lý thuyết trò chơi hợp tác và LIME (Local Interpretable Model-agnostic Explanations)?",
    ["Shapley Values: Xuất phát từ lý thuyết trò chơi hợp tác; chia sẻ đóng góp cận biên của từng người chơi (đặc trưng) trên tất cả các tập hợp con liên minh có thể có; đảm bảo 4 tính chất toán học duy nhất: Hiệu quả (Efficiency), Đối xứng (Symmetry), Người chơi giả (Dummy), và Tính cộng (Additivity)", "SHAP (TreeSHAP / KernelSHAP): TreeSHAP tối ưu hóa tính toán giá trị Shapley cho mô hình cây từ độ phức tạp hàm mũ xuống thời gian đa thức $O(TLD^2)$; cung cấp cả giải thích toàn cục (Beeswarm, Feature Importance) và cục bộ (Waterfall plot cho từng dự đoán cá nhân)", "LIME: Xây dựng một mô hình tuyến tính đơn giản (Interpretable Surrogate Model) quanh vùng lân cận của một mẫu dự đoán cụ thể bằng cách tạo nhiễu ngẫu nhiên (Perturbation) và gán trọng số khoảng cách"],
    ["Tại sao Feature Importance mặc định của Random Forest (Gini Importance) lại bị thiên vị nghiêm trọng đối với các biến có nhiều giá trị duy nhất (High-cardinality features)?", "Làm thế nào để sử dụng SHAP Dependence Plot để phát hiện mối quan hệ phi tuyến và tương tác giữa 2 đặc trưng?"] ,
    ["Model Explainability", "SHAP TreeExplainer", "LIME", "Shapley Values Game Theory", "Gini Importance Bias"],
    [DS_SRC.shap, DS_SRC.sklearn],
    ["Chỉ dựa vào Gini Importance mặc định của sklearn và đưa ra kết luận sai lệch về yếu tố quan trọng nhất"]
  ),

  // Practical Skills (8)
  q("DS-PRAC-01", "Data Scientist", "practical_skills", "advanced", "middle",
    "Xử lý Dữ liệu Mất cân bằng Nghiêm trọng (Severe Class Imbalance): Khi tỷ lệ mẫu thiểu số chỉ chiếm 0.1% (Gian lận thẻ tín dụng, lỗi sản xuất), em áp dụng các kỹ thuật Resampling (SMOTE, Tomek Links), Algorithmic Modification (Class Weighting, Focal Loss) và Calibration ra sao?",
    ["Resampling: Không dùng SMOTE ngây thơ trên toàn bộ tập dữ liệu (gây rò rỉ dữ liệu tập test); chỉ áp dụng SMOTE trên tập Train sau khi đã chia Cross-Validation; kết hợp SMOTE + ENN (Edited Nearest Neighbors) để xóa các điểm nhiễu ở biên", "Cost-sensitive Learning (Class Weighting): Tăng trọng số phạt khi dự đoán sai lớp thiểu số (`scale_pos_weight` trong XGBoost, `class_weight='balanced'` trong Sklearn)", "Focal Loss: Điều chỉnh hàm Cross-Entropy bằng cách giảm trọng số của các mẫu dễ phân loại ($p_t \\to 1$) và tập trung vào các mẫu khó phân loại ($FL(p_t) = -\\alpha_t (1-p_t)^\\gamma \\log(p_t)$)", "Probability Calibration: Sau khi dùng kỹ thuật under-sampling làm lệch phân phối gốc, bắt buộc phải hiệu chuẩn lại xác suất bằng Isotonic Regression hoặc Platt Scaling"],
    ["Tại sao việc áp dụng SMOTE trước khi chia tập Train/Test là một lỗi Data Leakage nghiêm trọng?", "Trong bài toán phát hiện gian lận thực tế, tại sao phương pháp Anomaly Detection (Isolation Forest, One-Class SVM) đôi khi vượt trội hơn phân loại có giám sát?"] ,
    ["Class Imbalance", "SMOTE Data Leakage", "Focal Loss", "Scale Pos Weight", "Probability Calibration"],
    [DS_SRC.sklearn, DS_SRC.xgboost],
    ["Chạy SMOTE trên toàn bộ tập dữ liệu trước khi train_test_split làm kết quả đánh giá bị thổi phồng hoàn toàn"]
  ),
  q("DS-PRAC-02", "Data Scientist", "practical_skills", "advanced", "middle",
    "Quy trình Kỹ nghệ Đặc trưng (Feature Engineering) và Lựa chọn Đặc trưng (Feature Selection): Kỹ thuật Target Encoding (và cách chống rò rỉ dữ liệu qua Out-of-fold), Boruta Algorithm, và xử lý biến có tính chu kỳ (Cyclic Features)?",
    ["Target Encoding: Thay thế biến định danh bằng trung bình nhãn mục tiêu của nhóm đó; để chống Overfitting/Data Leakage: Bắt buộc dùng Out-of-Fold (OOF) Target Encoding kết hợp làm mịn Bayes (Bayesian Smoothing / M-estimate smoothing) và thêm nhiễu Gaussian nhẹ", "Biến có tính chu kỳ (Giờ trong ngày 0-23, Tháng trong năm 1-12): Mã hóa bằng hàm lượng giác $\\sin(2\\pi x / T)$ và $\\cos(2\\pi x / T)$ để bảo toàn khoảng cách thực tế giữa giờ 23 và giờ 0", "Boruta Feature Selection: Tạo các đặc trưng bóng ma (Shadow features) bằng cách xáo trộn ngẫu nhiên các cột gốc; so sánh tầm quan trọng của đặc trưng gốc với đặc trưng bóng ma tối đa qua nhiều lần lặp để giữ lại các biến có ý nghĩa thống kê thực sự", "Feature Interaction: Tự động tạo các tổ hợp đặc trưng (nhân, chia, trừ) dựa trên hiểu biết sâu sắc về miền nghiệp vụ"],
    ["Tại sao One-Hot Encoding làm giảm hiệu năng nghiêm trọng đối với các thuật toán dựa trên cây khi biến có hàng ngàn danh mục?", "Cách phát hiện và loại bỏ các đặc trưng gần như không đổi (Variance Threshold) và các cặp đặc trưng có tương quan Spearman > 0.95?"] ,
    ["Feature Engineering", "Target Encoding Out-of-Fold", "Cyclic Encoding Sin Cos", "Boruta Algorithm", "Feature Selection"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Tính Target Encoding trực tiếp trên toàn bộ tập dữ liệu dẫn đến Overfitting trầm trọng mà không hiểu nguyên nhân"]
  ),
  q("DS-PRAC-03", "Data Scientist", "practical_skills", "advanced", "middle",
    "Tối ưu hóa Siêu tham số thông minh (Hyperparameter Tuning) với Optuna: Cơ chế Tree-structured Parzen Estimator (TPE), Tỉa sớm các thử nghiệm kém (Pruning via MedianPruner) và Thiết kế không gian tìm kiếm (Search Space)?",
    ["Giới hạn của Grid Search và Random Search: Grid Search bùng nổ tổ hợp theo cấp số mũ; Random Search không học được từ các lần thử thất bại trước đó", "Optuna & TPE (Bayesian Optimization): Xây dựng mô hình xác suất của hàm mục tiêu; TPE mô hình hóa $p(x|y)$ chia thành 2 phân phối: nhóm điểm tốt (lấy theo quantile $\\gamma$) và nhóm điểm kém; chọn điểm thử nghiệm tiếp theo tối đa hóa Expected Improvement (EI)", "Cơ chế Pruning (Early Stopping): Giám sát metric sau từng epoch/vòng lặp; nếu thử nghiệm hiện tại kém hơn trung vị của các thử nghiệm trước ở cùng mốc thời gian -> Lập tức dừng thử nghiệm (Prune) để tiết kiệm tài nguyên GPU/CPU", "Tích hợp Optuna với Cross-Validation: Luôn tối ưu hóa trên điểm số OOF CV trung bình thay vì một tập validation cố định"],
    ["Làm thế nào để xác định không gian tìm kiếm phù hợp cho các siêu tham số quan trọng của LightGBM (`learning_rate`, `num_leaves`, `colsample_bytree`, `subsample`)?", "Cách lưu trữ lịch sử các thử nghiệm Optuna vào cơ sở dữ liệu PostgreSQL để phục vụ chạy song song trên nhiều máy?"] ,
    ["Optuna", "Bayesian Optimization TPE", "Pruning MedianPruner", "Hyperparameter Search Space", "Resource Efficiency"],
    [DS_SRC.optuna, DS_SRC.sklearn],
    ["Chạy Grid Search với 5 tham số mỗi tham số 10 giá trị khiến máy tính chạy 3 tuần không xong"]
  ),
  q("DS-PRAC-04", "Data Scientist", "practical_skills", "advanced", "senior_lead",
    "Phân tích Chuỗi thời gian (Time Series Forecasting): Phân biệt Mô hình Thống kê cổ điển (ARIMA/SARIMAX), Mô hình Phân rã phụ gia (Prophet) và Mô hình Học sâu / Cây tăng cường (LightGBM với Lags và Rolling Features)?",
    ["Kiểm tra tính Dừng (Stationarity): Chuỗi thời gian phải dừng (Mean, Variance, Autocorrelation không đổi theo thời gian); kiểm định Augmented Dickey-Fuller (ADF test); xử lý chuỗi không dừng bằng lấy sai phân (Differencing) hoặc biến đổi Box-Cox", "ARIMA(p, d, q): p (bậc tự hồi quy AR), d (bậc sai phân I), q (bậc trung bình trượt MA); đọc đồ thị ACF và PACF để chọn bậc", "Biến đổi bài toán chuỗi thời gian thành học có giám sát cho LightGBM: Tạo các đặc trưng Lag ($y_{t-1}, y_{t-7}, y_{t-30}$), Rolling Statistics (Moving Mean 7 ngày, Rolling Std 14 ngày, Min/Max), và Calendar features", "Chia tập kiểm thử Time-series Cross-Validation: Bắt buộc dùng `TimeSeriesSplit` (Rolling Origin / Expanding Window); tuyệt đối không xáo trộn ngẫu nhiên (K-Fold shuffling) vì sẽ gây rò rỉ dữ liệu tương lai"],
    ["Khi nào nên dùng hàm mất mát bất đối xứng (Asymmetric Loss - ví dụ: Phạt nặng hơn khi dự báo thiếu hàng tồn kho so với thừa hàng)?", "Cách xử lý sự kiện bất thường (Holidays, Black Friday) và biến ngoại sinh (Exogenous variables) trong mô hình dự báo?"] ,
    ["Time Series Forecasting", "Stationarity ADF Test", "LightGBM Lag Features", "TimeSeriesSplit No Leakage", "SARIMAX"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Dùng hàm `train_test_split(shuffle=True)` ngẫu nhiên trên dữ liệu chuỗi thời gian gây rò rỉ dữ liệu tương lai vào quá khứ"]
  ),
  q("DS-PRAC-05", "Data Scientist", "practical_skills", "advanced", "middle",
    "Phát hiện và Chẩn đoán Rò rỉ Dữ liệu (Data Leakage & Target Leakage): Các dạng rò rỉ phổ biến nhất trong thực tế (Feature-target temporal leakage, Preprocessing leakage, Group leakage) và cách phòng ngừa?",
    ["Preprocessing Leakage: Thực hiện Standard Scaling, Imputation hoặc PCA trên toàn bộ tập dữ liệu TRƯỚC KHI chia train/test; giải pháp: Luôn đóng gói tiền xử lý vào `sklearn.pipeline.Pipeline`", "Target Leakage: Một đặc trưng vô tình chứa thông tin chỉ xuất hiện SAU KHI biến mục tiêu đã xảy ra (vd: Cột `refund_date` xuất hiện trong mô hình dự đoán khách hàng có hoàn tiền hay không); nhận biết khi mô hình đạt AUC 0.999 bất thường", "Temporal Leakage: Sử dụng thông tin của tương lai để dự báo quá khứ (vd: sử dụng giá đóng cửa ngày mai để dự báo biến động hôm nay)", "Group Leakage: Các bản ghi của cùng một người dùng (hoặc cùng bệnh nhân) xuất hiện ở cả tập Train và Test; giải pháp: Bắt buộc dùng `GroupKFold` theo `user_id`"],
    ["Làm thế nào để kiểm tra tính toàn vẹn của một tập dữ liệu nghi ngờ có rò rỉ trước khi bàn giao cho production?", "Kỹ thuật Adversarial Validation giúp phát hiện sự khác biệt phân phối giữa tập Train và Test như thế nào?"] ,
    ["Data Leakage", "Target Leakage", "Sklearn Pipeline", "GroupKFold", "Adversarial Validation"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Không dùng Pipeline của Sklearn mà tự fit scaler trên toàn bộ dữ liệu khiến kết quả validation bị sai lệch"]
  ),
  q("DS-PRAC-06", "Data Scientist", "practical_skills", "advanced", "middle",
    "Xây dựng Hệ thống Gợi ý (Recommendation Systems): Phân biệt Lọc cộng tác (Collaborative Filtering: User-based vs Item-based), Phân rã ma trận (Matrix Factorization - SVD / ALS) và Two-Tower Deep Learning Models (Retrieval vs Ranking)?",
    ["Collaborative Filtering: Dựa trên hành vi lịch sử người dùng; User-based (tìm người dùng tương đồng) vs Item-based (tìm vật phẩm được cùng mua); thách thức Vấn đề Khởi đầu Lạnh (Cold-Start Problem)", "Matrix Factorization (ALS / SVD): Phân rã ma trận tương tác User-Item thưa $R$ thành hai ma trận embedding tiềm ẩn thấp chiều: Ma trận User $U$ và Ma trận Item $V$ sao cho $R \\approx U \\cdot V^T$", "Kiến trúc Hai Tháp Hiện đại (Two-Tower Model): Tách thành 2 giai đoạn: Giai đoạn 1 - Candidate Generation / Retrieval (Tháp User sinh User Embedding, tháp Item sinh Item Embedding; tìm kiếm Top 1000 qua FAISS/ScaNN trong vài mili-giây); Giai đoạn 2 - Ranking (Mô hình sâu như DLRM/DeepFM xếp hạng chi tiết kết hợp hàng trăm context features)", "Implicit Feedback vs Explicit Feedback: Xử lý dữ liệu nhấp chuột/xem video (Implicit) bằng Alternating Least Squares (iALS) hoặc BPR (Bayesian Personalized Ranking)"],
    ["Làm thế nào để giải quyết bài toán Cold-Start cho người dùng mới hoàn toàn khi chưa có bất kỳ lịch sử tương tác nào?", "Cách đo lường chất lượng hệ gợi ý ngoài độ chính xác (Diversity, Novelty, Serendipity, Coverage)?"] ,
    ["Recommendation Systems", "Matrix Factorization ALS", "Two-Tower Model", "Candidate Retrieval vs Ranking", "Cold-Start Mitigation"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Dùng mô hình phân loại nhị phân thông thường để dự đoán trên hàng triệu sản phẩm khiến thời gian phản hồi mất 10 giây"]
  ),
  q("DS-PRAC-07", "Data Scientist", "practical_skills", "advanced", "senior_lead",
    "Kiểm tra tính Ổn định và Độ lệch Phân phối của Mô hình (Model Drift & Concept Drift): Cơ chế đo lường chỉ số PSI (Population Stability Index), Khoảng cách Wasserstein, KS-Test và Thiết kế Kế hoạch Tái huấn luyện (Retraining Trigger)?",
    ["Phân biệt các dạng Drift: Covariate Shift (Phân phối đầu vào $P(X)$ thay đổi trong khi $P(Y|X)$ giữ nguyên), Concept Drift (Mối quan hệ bản chất $P(Y|X)$ thay đổi, hành vi người dùng đổi khác), Prior Shift ($P(Y)$ thay đổi)", "Population Stability Index (PSI): Đo lường sự dịch chuyển phân phối của một đặc trưng hoặc điểm số mô hình giữa tập Baseline và tập Production: $PSI = \\sum (Actual_i - Expected_i) \\times \\ln(Actual_i / Expected_i)$; Ngưỡng: $<0.1$ Ổn định, $0.1-0.2$ Biến động nhẹ, $>0.2$ Biến động lớn cần tái huấn luyện", "Kiểm định Kolmogorov-Smirnov (KS-Test) & Wasserstein Distance: Đo khoảng cách tối đa giữa hai hàm phân phối tích lũy (CDF) để phát hiện drift trên biến liên tục", "Chiến lược Tái huấn luyện: Kích hoạt dựa trên lịch định kỳ (Scheduled), dựa trên ngưỡng suy giảm hiệu năng thực tế (Performance-based), hoặc dựa trên phát hiện drift dữ liệu (Drift-triggered)"],
    ["Tại sao việc tự động tái huấn luyện (Continuous Retraining) ngay lập tức khi phát hiện drift có thể tiềm ẩn rủi ro nạp dữ liệu độc hại vào mô hình?", "Làm thế nào để phân biệt giữa một biến động drift tạm thời do ngày lễ và một sự thay đổi hành vi vĩnh viễn?"] ,
    ["Model Drift", "Concept Drift", "Population Stability Index", "Wasserstein Distance", "Automated Retraining Trigger"],
    [DS_SRC.internal],
    ["Thả mô hình chạy trên production 2 năm mà không theo dõi drift cho đến khi doanh thu công ty sụt giảm"]
  ),
  q("DS-PRAC-08", "Data Scientist", "practical_skills", "advanced", "middle",
    "Thực hành Lập trình Khoa học Dữ liệu Chuẩn mực: Chuyển đổi từ Jupyter Notebook thử nghiệm sang Python Package hoàn chỉnh (Modular Code, Type Hinting, Dataclasses, Pytest cho Data)?",
    ["Vấn đề của Jupyter Notebook: Khó kiểm thử, thứ tự chạy ô không tuần tự (Out-of-order execution), khó quản lý phiên bản trong Git, dễ ẩn giấu biến toàn cục (Global state)", "Tổ chức Codebase chuẩn: Tách thành các modules chuyên biệt: `features/` (logic trích xuất đặc trưng), `models/` (train/predict wrapper), `data/` (load & validate), `config/` (quản lý tham số qua YAML/Pydantic)", "Sử dụng Type Hinting & Pydantic/Dataclasses: Định nghĩa rõ ràng kiểu dữ liệu đầu vào và đầu ra của từng hàm; kiểm tra tính hợp lệ của schema dữ liệu lúc runtime", "Kiểm thử tự động với Pytest: Viết Unit Test kiểm tra các phép biến đổi dữ liệu (vd: Đảm bảo hàm chuẩn hóa không tạo ra giá trị NaN; kiểm tra ma trận đầu ra có đúng kích thước dự kiến)"],
    ["Làm thế nào để thiết lập pre-commit hook (Black, Flake8, MyPy) cho dự án Data Science?", "Cách sử dụng Cookiecutter Data Science để chuẩn hóa cấu trúc dự án cho toàn đội?"] ,
    ["Production Data Science Code", "Modular Python", "Pydantic Schema Validation", "Pytest for ML", "Jupyter to Production"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Bàn giao nguyên một file Jupyter Notebook 5000 dòng lộn xộn cho đội kỹ thuật để đưa lên production"]
  ),

  // Scenario (6)
  q("DS-SCEN-01", "Data Scientist", "scenario", "advanced", "senior_lead",
    "Tình huống: Một mô hình Chấm điểm Tín dụng (Credit Scoring) do em phát triển đạt ROC-AUC 0.88 trên tập kiểm thử lịch sử. Tuy nhiên, khi triển khai thử nghiệm thực tế (Shadow Run), tỷ lệ nợ xấu được mô hình duyệt lại cao gấp đôi so với các chuyên viên thẩm định truyền thống. Em tiến hành chẩn đoán nguyên nhân và khắc phục sự cố nghiêm trọng này như thế nào?",
    ["Bước 1: Kiểm tra Thiên vị Chọn mẫu (Sample Selection Bias / Survivorship Bias): Dữ liệu huấn luyện lịch sử chỉ chứa những khách hàng ĐÃ ĐƯỢC chuyên viên thẩm định DUYỆT vay trong quá khứ (không có dữ liệu về những người bị từ chối); mô hình chưa từng được học về các mẫu nợ xấu bị chặn từ vòng ngoài (Reject Inference problem)", "Bước 2: Kiểm tra Phân phối Điểm số và Ngưỡng cắt (Cut-off Threshold): Xem xét lại ma trận chi phí thiệt hại (Chi phí của 1 khoản nợ xấu lớn gấp 10 lần lợi nhuận từ 1 khoản vay tốt); có thể ngưỡng phân loại hiện tại đang đặt quá lỏng", "Bước 3: Kỹ thuật Khắc phục: Áp dụng kỹ thuật Suy luận Người bị từ chối (Reject Inference: Sử dụng mô hình hai bước để gán nhãn giả định cho tập bị từ chối); Điều chỉnh ngưỡng cắt an toàn siết chặt hơn", "Bước 4: Thiết lập cơ chế thẩm định kết hợp (Champion-Challenger): Cho mô hình duyệt tự động nhóm điểm số cao an toàn tuyệt đối, nhóm điểm số nằm ở ranh giới chuyển sang chuyên viên thẩm định thủ công"],
    ["Làm thế nào để thu thập dữ liệu về nhóm khách hàng bị từ chối một cách an toàn mà không gây rủi ro tài chính quá lớn cho ngân hàng?", "Quy định pháp lý về tính công bằng và giải trình (Fair Lending & Explainable AI) trong chấm điểm tín dụng?"] ,
    ["Credit Scoring Crisis", "Reject Inference", "Sample Selection Bias", "Cost-Sensitive Thresholding", "Champion-Challenger"],
    [DS_SRC.internal],
    ["Đổ lỗi cho thị trường kinh tế khó khăn thay vì nhận ra lỗi Selection Bias trong dữ liệu huấn luyện của mình"]
  ),
  q("DS-SCEN-02", "Data Scientist", "scenario", "advanced", "middle",
    "Tình huống: Một mô hình Phân loại Gian lận Giao dịch (Fraud Detection) mới được triển khai gặp phải phản ứng dữ dội từ khách hàng vì tỷ lệ Báo động giả (False Positive) quá cao, làm khóa nhầm hàng ngàn thẻ của người dùng bình thường trong dịp Tết. Giám đốc Vận hành yêu cầu em hạ tỷ lệ khóa nhầm xuống 80% ngay trong ngày hôm nay. Em xử lý bài toán đánh đổi này ra sao?",
    ["Bước 1: Hiểu bản chất sự đánh đổi (Precision-Recall Tradeoff): Giảm False Positive đồng nghĩa với việc tăng Precision; điều này bắt buộc phải điều chỉnh Ngưỡng phân loại (Classification Threshold) tăng cao hơn", "Bước 2: Điều chỉnh ngưỡng khẩn cấp có kiểm soát: Dựa trên đường cong Precision-Recall hiện tại, tìm ngưỡng điểm số mới giúp giảm 80% False Positive; tính toán trước mức độ sụt giảm Recall (sẽ bỏ sót thêm bao nhiêu % vụ gian lận thực tế)", "Bước 3: Thiết kế giải pháp phân tầng can thiệp (Tiered Action Strategy) thay vì khóa thẻ cứng: Điểm rủi ro cực cao (> 0.95): Khóa giao dịch tự động; Điểm rủi ro trung bình (0.75 - 0.95): Yêu cầu xác thực sinh trắc học bổ sung (Step-up Authentication / OTP) thay vì khóa thẻ ngay lập tức", "Bước 4: Báo cáo rủi ro cho Ban Giám đốc: Trình bày minh bạch con số tổn thất gian lận ước tính khi nới lỏng ngưỡng và thống nhất kế hoạch bổ sung đặc trưng hành vi tiêu dùng dịp Tết vào mô hình"],
    ["Tại sao hành động của người dùng trong dịp lễ tết luôn gây ra hiện tượng False Positive tăng đột biến?", "Làm thế nào để bổ sung các quy tắc heuristics linh hoạt kết hợp với Machine Learning để xử lý tình huống khẩn cấp?"] ,
    ["Precision-Recall Tradeoff", "Fraud False Positive Crisis", "Step-up Authentication", "Threshold Tuning", "Seasonal Outliers"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Hạ ngưỡng một cách mù quáng làm toàn bộ hệ thống tê liệt và để lọt hàng loạt giao dịch lừa đảo lớn"]
  ),
  q("DS-SCEN-03", "Data Scientist", "scenario", "advanced", "middle",
    "Tình huống: Em xây dựng một mô hình Hồi quy Tuyến tính để dự báo giá bán bất động sản nhằm mục đích giải thích tác động của từng yếu tố cho Ban Giám đốc. Tuy nhiên, hệ số trọng số (Coefficient) của biến 'Số phòng ngủ' lại có giá trị ÂM (nghĩa là càng nhiều phòng ngủ giá nhà càng giảm), hoàn toàn trái ngược với trực giác kinh nghiệm. Em giải thích nguyên nhân và xử lý vấn đề này như thế nào?",
    ["Nguyên nhân gốc rễ: Hiện tượng Đa cộng tuyến nghiêm trọng (Multicollinearity). Biến 'Số phòng ngủ' có tương quan rất cao với biến 'Diện tích nhà' và 'Số phòng tắm'", "Hệ quả toán học của Đa cộng tuyến: Ma trận $X^T X$ gần như suy biến (gần singular); phương sai của ước lượng hệ số trọng số bị thổi phồng cực lớn, khiến dấu của hệ số bị đảo ngược ngẫu nhiên hoặc không ổn định", "Phương pháp chẩn đoán: Tính toán Hệ số Phóng đại Phương sai (Variance Inflation Factor - VIF); nếu $VIF > 5$ hoặc $10$, khẳng định có đa cộng tuyến nặng", "Cách khắc phục: Phương án 1: Loại bỏ biến dư thừa (giữ lại 'Diện tích' vì mang tính bao hàm cao hơn); Phương án 2: Tạo biến tương tác mới (vd: 'Diện tích trung bình mỗi phòng'); Phương án 3: Chuyển sang hồi quy Ridge Regression ($L_2$) để ổn định hệ số"],
    ["Tại sao đa cộng tuyến không ảnh hưởng nhiều đến độ chính xác dự báo (Prediction) nhưng lại phá hủy hoàn toàn tính giải thích (Inference)?", "Khi nào nên sử dụng PCA để giải quyết đa cộng tuyến trước khi hồi quy?"] ,
    ["Multicollinearity", "Variance Inflation Factor VIF", "Coefficient Sign Inversion", "Linear Regression Diagnostics", "Ridge Stabilization"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Trình bày với sếp rằng 'số liệu cho thấy nhà càng nhiều phòng ngủ thì càng rẻ' mà không kiểm tra hiện tượng đa cộng tuyến"]
  ),
  q("DS-SCEN-04", "Data Scientist", "scenario", "advanced", "senior_lead",
    "Tình huống: Một mô hình Phân loại Khách hàng Rời bỏ (Customer Churn) đạt độ chính xác F1-score 0.82 trên tập dữ liệu kiểm thử. Tuy nhiên, khi đội Chăm sóc Khách hàng (CSKH) sử dụng danh sách dự báo để gọi điện chăm sóc và tặng quà, tỷ lệ khách hàng thực sự giữ lại không hề cải thiện so với việc không làm gì. Em phân tích và chuyển đổi bài toán từ Churn Prediction sang Uplift Modeling như thế nào?",
    ["Phát hiện vấn đề cốt lõi: Mô hình Churn Prediction thông thường chỉ dự báo AI CÓ KHẢ NĂNG RỜI BỎ, nhưng không trả lời được AI SẼ THAY ĐỔI HÀNH VI KHI NHẬN ĐƯỢC TÁC ĐỘNG (Can thiệp/Ưu đãi)", "Phân nhóm 4 đối tượng hành vi trong Uplift Modeling: (1) Persuadables (Chỉ ở lại nếu được chăm sóc - ĐÂY LÀ NHÓM CẦN NHẮM TỚI); (2) Sure Things (Dù chăm sóc hay không vẫn ở lại); (3) Lost Causes (Dù chăm sóc hay không vẫn rời bỏ); (4) Sleeping Dogs / Do Not Disturb (Đang yên lành, gọi điện chăm sóc nhắc nhở làm họ nhớ ra và hủy dịch vụ ngay lập tức!)", "Phương pháp Uplift Modeling: Sử dụng phương pháp Hai Mô hình (Two-Model Approach) hoặc Class Transformation (CausalML / EconML) để ước lượng Hiệu ứng Can thiệp Cá thể hóa (Individual Treatment Effect - ITE / CATE)", "Tối ưu hóa ngân sách: Chỉ tập trung toàn bộ nguồn lực và voucher quà tặng vào nhóm Persuadables, loại trừ hoàn toàn nhóm Sleeping Dogs"],
    ["Tại sao việc gọi điện chăm sóc cho nhóm 'Sleeping Dogs' lại gây tổn thất kép cho doanh nghiệp?", "Cách thiết kế một thí nghiệm Randomized Controlled Trial (RCT) để thu thập dữ liệu huấn luyện cho Uplift Model?"] ,
    ["Uplift Modeling", "Causal ML", "Individual Treatment Effect", "Customer Churn Economics", "Sleeping Dogs Effect"],
    [DS_SRC.internal],
    ["Tiếp tục thúc ép CSKH gọi điện theo danh sách xác suất rời bỏ cao nhất mà không hiểu bản chất của Uplift Modeling"]
  ),
  q("DS-SCEN-05", "Data Scientist", "scenario", "advanced", "middle",
    "Tình huống: Em nhận được một tập dữ liệu y tế gồm 50.000 bệnh nhân để dự đoán nguy cơ tái nhập viện. Tuy nhiên, có hơn 40% giá trị trong các cột xét nghiệm máu quan trọng bị khuyết thiếu (Missing Values). Em lập chiến lược xử lý dữ liệu khuyết thiếu chuyên sâu ra sao mà không làm mất mát thông tin quý giá?",
    ["Bước 1: Phân loại cơ chế khuyết thiếu (Rubin's Missing Data Taxonomy): MCAR (Khuyết thiếu hoàn toàn ngẫu nhiên), MAR (Khuyết thiếu ngẫu nhiên phụ thuộc biến khác), hay MNAR (Khuyết thiếu không ngẫu nhiên - vd: Bệnh nhân quá nặng hoặc quá nhẹ nên bác sĩ không chỉ định xét nghiệm đó)", "Bước 2: Khai thác thông tin từ chính sự khuyết thiếu: Trong y tế, việc 'không làm xét nghiệm' chính là một đặc trưng hành vi cực kỳ quan trọng; tạo thêm một cột cờ nhị phân (Missing Indicator: `is_blood_test_missing = 1/0`)", "Bước 3: Lựa chọn kỹ thuật điền khuyết (Imputation): Tránh điền Mean/Median thô bạo; sử dụng Kỹ thuật Điền khuyết Đa biến lặp (MICE - Multivariate Imputation by Chained Equations / `IterativeImputer` trong Sklearn) hoặc dùng KNN Imputer", "Bước 4: Tận dụng các thuật toán tự xử lý Missing Values tự nhiên: Các mô hình cây hiện đại như LightGBM/XGBoost có cơ chế tự tìm hướng rẽ nhánh tối ưu cho giá trị khuyết thiếu (Default split direction) mà không cần điền trước"],
    ["Tại sao việc xóa bỏ các dòng có giá trị khuyết thiếu (Listwise Deletion) trong tập dữ liệu y tế này có thể gây ra thiên vị nghiêm trọng?", "Sự khác biệt giữa Single Imputation và Multiple Imputation trong việc duy trì sai số chuẩn của tham số?"] ,
    ["Missing Data Mechanisms", "MICE Imputation", "Missing Indicator Feature", "MNAR in Healthcare", "LightGBM Missing Handling"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Tự ý điền số 0 hoặc giá trị trung bình vào các chỉ số xét nghiệm y tế làm biến dạng hoàn toàn phân phối sinh học"]
  ),
  q("DS-SCEN-06", "Data Scientist", "scenario", "advanced", "senior_lead",
    "Tình huống: Nhóm Data Science xây dựng xong mô hình dự đoán nhu cầu năng lượng (Electricity Demand Forecasting) và muốn chuyển giao cho đội Vận hành lưới điện áp dụng. Đội Vận hành từ chối sử dụng vì họ cho rằng mô hình là một 'hộp đen bí ẩn' và nếu dự đoán sai gây sập lưới điện thì ai sẽ chịu trách nhiệm. Em giải quyết rào cản niềm tin này như thế nào?",
    ["Bước 1: Tôn trọng chuyên môn miền (Domain Expertise): Thừa nhận sự cẩn trọng chính đáng của đội Vận hành; rủi ro sập lưới điện là vô cùng nghiêm trọng", "Bước 2: Mở hộp đen bằng Explainable AI: Sử dụng SHAP Waterfall Plots cho từng khung giờ dự báo; chứng minh cho các kỹ sư vận hành thấy mô hình đưa ra dự báo dựa trên đúng các yếu tố vật lý hợp lý (Nhiệt độ thời tiết, ngày trong tuần, lịch phát sóng bóng đá)", "Bước 3: Thiết lập Rào chắn An toàn (Safety Guardrails & Sanity Bounds): Bổ sung các quy tắc vật lý cứng (vd: Dự báo không bao giờ được vượt quá công suất định mức hoặc thấp hơn phụ tải nền); nếu mô hình đưa ra con số bất thường, hệ thống tự động rơi về mô hình Heuristic an toàn của họ", "Bước 4: Chế độ Đồng lái (Co-pilot Mode / Human-in-the-loop): Không tự động hóa hoàn toàn; mô hình đóng vai trò gợi ý kèm lý do, quyền bấm nút xác nhận cuối cùng vẫn thuộc về kỹ sư trực ca"],
    ["Làm thế nào để xây dựng một bản đánh giá an toàn rủi ro thuật toán (Algorithmic Risk Assessment) cho các hệ thống hạ tầng trọng yếu?", "Cách đo lường mức độ tin cậy và sự đón nhận của người dùng sau 3 tháng triển khai chế độ Co-pilot?"] ,
    ["Explainable AI Trust", "Human-in-the-Loop", "Safety Guardrails", "Domain Expert Collaboration", "Critical Infrastructure AI"],
    [DS_SRC.shap, DS_SRC.internal],
    ["Tranh cãi rằng 'mô hình của tôi có độ chính xác 98% nên các anh bắt buộc phải nghe theo'"]
  ),

  // CV Validation (5)
  q("DS-CV-01", "Data Scientist", "cv_validation", "advanced", "middle",
    "Trong các dự án Machine Learning mà em ghi trên CV, bài toán kinh doanh cụ thể nào mà em trực tiếp xây dựng mô hình từ khâu định hình vấn đề (Problem Formulation) đến lúc ra quyết định? Em đã chuyển hóa mục tiêu kinh doanh trừu tượng thành hàm mục tiêu toán học (Loss Function / Objective) như thế nào?",
    ["Nêu rõ bài toán nghiệp vụ thực tế và lý do tại sao phương pháp dựa trên luật (Rule-based) trước đó không đáp ứng được", "Cách chuyển hóa mục tiêu kinh doanh thành hàm toán học: Ví dụ không dùng MSE thông thường mà dùng Huber Loss hoặc Asymmetric Pinball Loss cho bài toán chuỗi cung ứng", "Quy trình lựa chọn và đánh giá mô hình khách quan dựa trên tác động kinh doanh thực tế"],
    ["Nếu bây giờ làm lại dự án đó, em sẽ thay đổi điều gì trong cách định hình bài toán ban đầu?", "Thời gian từ lúc bắt đầu nghiên cứu dữ liệu đến khi có mô hình khả dụng đầu tiên (Baseline Model) là bao lâu?"],
    ["Problem Formulation", "Custom Loss Function", "Data to Business Alignment", "Baseline Modeling"],
    [DS_SRC.internal],
    ["Kể về dự án chỉ bằng tên thuật toán (vd: Em dùng XGBoost) mà không giải thích được bài toán kinh doanh bên dưới là gì"]
  ),
  q("DS-CV-02", "Data Scientist", "cv_validation", "advanced", "senior_lead",
    "Em ghi nhận trên CV về việc cải thiện đáng kể hiệu năng mô hình (vd: Tăng AUC từ 0.75 lên 0.84). Em hãy phân tích bóc tách xem sự gia tăng hiệu năng đó đến từ yếu tố nào nhiều nhất: Kỹ nghệ đặc trưng mới (Feature Engineering), Thuật toán mô hình tốt hơn, hay Tối ưu hóa siêu tham số (Hyperparameter Tuning)?",
    ["Phân tích bóc tách đóng góp khách quan (Ablation Study): Thường 70-80% sự cải thiện vượt bậc đến từ việc tạo ra các đặc trưng nghiệp vụ đột phá hoặc làm sạch dữ liệu chất lượng cao", "Đóng góp của việc tinh chỉnh thuật toán và tuning siêu tham số thường chỉ mang lại 5-10% cải thiện biên", "Minh chứng số liệu cụ thể: Trình bày kết quả đo lường từng bước qua bảng theo dõi thử nghiệm (Experiment Tracking log)"],
    ["Một ý tưởng kỹ nghệ đặc trưng nào mà em tâm đắc nhất trong dự án đó?", "Có đặc trưng nào ban đầu em nghĩ sẽ rất hiệu quả nhưng khi đưa vào lại làm giảm hiệu năng mô hình không?"] ,
    ["Ablation Study", "Feature Engineering Impact", "Experiment Tracking", "Performance Breakthrough"],
    [DS_SRC.xgboost, DS_SRC.internal],
    ["Khẳng định việc tăng hiệu năng hoàn toàn là nhờ chạy Grid Search chỉnh tham số mà không tạo thêm đặc trưng nào mới"]
  ),
  q("DS-CV-03", "Data Scientist", "cv_validation", "advanced", "middle",
    "Trong CV em có liệt kê kinh nghiệm giải quyết các bài toán dữ liệu lớn hoặc dữ liệu thưa thớt. Em hãy trình bày về quy trình kiểm thử chéo (Cross-Validation Strategy) mà em đã thiết kế trong dự án đó để đảm bảo mô hình không bị rò rỉ dữ liệu và khái quát hóa tốt?",
    ["Lựa chọn chiến lược CV phù hợp với bản chất dữ liệu: Stratified K-Fold cho dữ liệu mất cân bằng nhãn; GroupKFold cho dữ liệu có nhiều bản ghi của cùng một thực thể; TimeSeriesSplit cho dữ liệu chuỗi thời gian", "Đảm bảo tính độc lập tuyệt đối: Mọi bước tiền xử lý, điền khuyết, mã hóa target đều được thực hiện bên trong từng fold riêng lẻ", "Đo lường độ lệch chuẩn giữa các folds: Nếu điểm số giữa các folds dao động quá lớn -> Dấu hiệu của tập dữ liệu quá nhỏ hoặc mô hình không ổn định"],
    ["Sự khác biệt về điểm số giữa Cross-Validation cục bộ và điểm số trên tập Test độc lập cuối cùng trong dự án đó là bao nhiêu?", "Tại sao không bao giờ nên dùng K-Fold thông thường cho bài toán dự báo người dùng lặp lại?"] ,
    ["Cross-Validation Strategy", "Stratified vs GroupKFold", "Data Leakage Prevention", "Model Generalization"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Chỉ chia 1 lần train_test_split ngẫu nhiên 80/20 rồi dựa vào đó để công bố kết quả mô hình"]
  ),
  q("DS-CV-04", "Data Scientist", "cv_validation", "advanced", "middle",
    "Em ghi có kinh nghiệm làm việc với các công cụ Model Explainability (SHAP, LIME). Hãy trình bày về một tình huống thực tế mà việc phân tích biểu đồ SHAP đã giúp em phát hiện ra một lỗ hổng dữ liệu (Data Bug) hoặc định kiến tiềm ẩn (Bias) trong mô hình mà các chỉ số accuracy/AUC không chỉ ra được?",
    ["Bối cảnh cụ thể: Mô hình đạt điểm số đánh giá rất cao trên giấy tờ", "Phát hiện qua SHAP: Khi xem xét các đặc trưng quan trọng nhất (Top SHAP features), phát hiện một biến bất thường (vd: Mã định danh ID nhân viên, hoặc một trường thông tin bị rò rỉ từ tương lai) đang chi phối hoàn toàn dự đoán", "Hành động khắc phục: Loại bỏ biến rò rỉ, huấn luyện lại mô hình trên các đặc trưng thực chất và xây dựng lại niềm tin với stakeholder"],
    ["Làm thế nào để giải thích biểu đồ SHAP Force Plot cho một khách hàng bị mô hình từ chối vay hiểu lý do cụ thể?", "Chi phí thời gian tính toán của TreeSHAP so với KernelSHAP trên tập dữ liệu lớn?"] ,
    ["SHAP in Practice", "Data Leakage Discovery via SHAP", "Model Debugging", "Ethical AI"],
    [DS_SRC.shap, DS_SRC.internal],
    ["Chỉ đưa biểu đồ SHAP vào slide để cho đẹp mà không phân tích ý nghĩa nghiệp vụ của từng đặc trưng"]
  ),
  q("DS-CV-05", "Data Scientist", "cv_validation", "intermediate", "junior",
    "Em ghi nhận thành thạo các thư viện Machine Learning cốt lõi trong Python (Scikit-Learn, Scipy, Statsmodels). Em hãy phân tích sự khác biệt về triết lý giữa `statsmodels` (tập trung vào suy luận thống kê) và `scikit-learn` (tập trung vào năng lực dự báo)?",
    ["Statsmodels: Tập trung vào suy luận thống kê (Statistical Inference); cung cấp báo cáo chi tiết về bảng tóm tắt hệ số, p-value, sai số chuẩn, khoảng tin cậy 95%, kiểm định F, R-squared; phù hợp cho các nhà kinh tế lượng và nghiên cứu khoa học", "Scikit-Learn: Tập trung vào kỹ thuật phần mềm và năng lực dự báo tổng quát (Predictive Performance); API chuẩn hóa nhất quán (`fit`, `transform`, `predict`); tối ưu cho pipeline tự động hóa và xử lý dữ liệu lớn", "Khi nào dùng cái nào: Dùng Statsmodels khi cần chứng minh biến X có tác động ý nghĩa thống kê lên Y hay không; Dùng Scikit-learn khi cần xây dựng mô hình dự báo chính xác nhất để triển khai vào sản phẩm"],
    ["Tại sao một mô hình có R-squared rất cao trong Statsmodels vẫn có thể dự báo rất tệ trên tập dữ liệu mới?", "Cách kết hợp cả hai thư viện trong quy trình nghiên cứu Data Science?"] ,
    ["Statsmodels vs Scikit-Learn", "Inference vs Prediction", "Statistical Significance", "Software Engineering API"],
    [DS_SRC.sklearn, DS_SRC.internal],
    ["Không biết Statsmodels là gì và cho rằng Scikit-Learn là công cụ duy nhất để làm thống kê"]
  ),

  // Behavioral (5)
  q("DS-BEHAV-01", "Data Scientist", "behavioral", "intermediate", "middle",
    "Khoa học Dữ liệu bản chất là một quá trình nghiên cứu thử nghiệm có tính rủi ro cao: Nhiều giả thuyết và mô hình sau hàng tuần nghiên cứu có thể kết thúc bằng thất bại (không cải thiện hiệu năng). Em đối diện với sự thất bại trong nghiên cứu thử nghiệm và duy trì động lực làm việc như thế nào?",
    ["Tư duy nghiên cứu khoa học chuẩn mực: Thất bại của một giả thuyết không phải là lãng phí thời gian, mà là một phát hiện giá trị giúp loại trừ một hướng đi sai", "Ghi chép và tài liệu hóa có kỷ luật: Luôn ghi lại nhật ký thử nghiệm (Experiment Log) chi tiết lý do tại sao phương pháp đó không hiệu quả để đồng nghiệp không lặp lại sai lầm", "Đặt ra các mốc kiểm tra 'Thất bại nhanh' (Fail Fast): Thiết lập tiêu chí dừng sớm (Stop criteria) sau 3 ngày thay vì theo đuổi một ý tưởng bế tắc trong 1 tháng"],
    ["Làm thế nào để báo cáo một kết quả nghiên cứu không đạt kỳ vọng cho người quản lý mà vẫn thể hiện được giá trị công việc?", "Cách biến một kết quả thất bại thành bài học kinh nghiệm cho cả đội ngũ?"] ,
    ["Research Resilience", "Fail Fast Mindset", "Scientific Discipline", "Experiment Documentation"],
    [DS_SRC.internal],
    ["Che giấu các kết quả thất bại hoặc cố tình nắn chỉnh số liệu để tạo cảm giác mô hình có hiệu quả"]
  ),
  q("DS-BEHAV-02", "Data Scientist", "behavioral", "advanced", "senior_lead",
    "Khi có sự xung đột giữa Mục tiêu Kinh doanh ngắn hạn (cần ra mắt mô hình gấp trong tuần này để kịp chiến dịch bán hàng) và Chuẩn mực Khoa học nghiêm ngặt (cần thêm 3 tuần để kiểm định tính ổn định và chống thiên vị), em đưa ra quyết định và đàm phán với Ban Giám đốc ra sao?",
    ["Thấu hiểu áp lực thương mại của công ty: Một mô hình tốt ra mắt đúng lúc có giá trị hơn một mô hình hoàn hảo ra mắt khi cơ hội kinh doanh đã qua", "Đưa ra giải pháp phân tầng rủi ro: Triển khai một mô hình Heuristic đơn giản hoặc mô hình Baseline an toàn có kiểm soát chặt chẽ cho chiến dịch trước mắt", "Xây dựng cơ chế giám sát rủi ro tăng cường (Enhanced Monitoring): Đặt giới hạn ngân sách tối đa và có sự giám sát của con người trong các giao dịch lớn", "Ký kết cam kết hoàn thiện kỹ thuật (Technical Debt Payback): Thống nhất kế hoạch tiếp tục hoàn thiện mô hình chuẩn mực sau khi chiến dịch kết thúc"],
    ["Làm thế nào để bảo vệ danh tiếng đạo đức nghề nghiệp khi bị cấp trên ép buộc triển khai một thuật toán chưa an toàn?", "Cách lượng hóa rủi ro thuật toán thành tổn thất tài chính để lãnh đạo dễ hình dung?"] ,
    ["Scientific Rigor vs Business Speed", "Pragmatic Trade-offs", "Negotiation with Leadership", "Risk Mitigation"],
    [DS_SRC.internal],
    ["Cứng nhắc từ chối hỗ trợ kinh doanh với lý do hàn lâm, hoặc ngược lại, thỏa hiệp cẩu thả bỏ qua hoàn toàn các bước kiểm tra an toàn"]
  ),
  q("DS-BEHAV-03", "Data Scientist", "behavioral", "intermediate", "junior",
    "Kể về một tình huống em phải giải thích một khái niệm Machine Learning phức tạp (như Gradient Descent, L1/L2 Regularization, hoặc SHAP values) cho một đối tác hoàn toàn phi kỹ thuật (như Giám đốc Marketing hoặc Pháp chế). Em đã dùng phép ẩn dụ (Metaphor) và ngôn ngữ như thế nào để họ hiểu?",
    ["Tránh tuyệt đối biệt ngữ toán học và công thức trừu tượng; sử dụng các hình ảnh tương đồng trong đời sống thực tế", "Ví dụ ẩn dụ: Giải thích Gradient Descent như việc một người leo núi bị bịt mắt đang dò dẫm từng bước chân xuống dốc tìm đáy thung lũng; Giải thích Regularization như chiếc đai an toàn giữ cho mô hình không văng khỏi đường đua khi gặp cua gấp", "Kiểm tra sự thấu hiểu liên tục: Đặt câu hỏi xem người nghe có theo kịp không và khuyến khích họ đặt câu hỏi"],
    ["Làm thế nào để biết đối tác đã thực sự hiểu bản chất hay chỉ gật đầu cho qua?", "Cách biến buổi chia sẻ kỹ thuật thành một cuộc thảo luận kinh doanh hai chiều bổ ích?"] ,
    ["Technical Translation", "Metaphorical Thinking", "Empathy in Communication", "Bridging Tech and Business"],
    [DS_SRC.internal],
    ["Đọc vanh vách các định nghĩa giải tích ma trận khiến đối tác kinh doanh bối rối và mất kiên nhẫn"]
  ),
  q("DS-BEHAV-04", "Data Scientist", "behavioral", "advanced", "senior_lead",
    "Đạo đức trong Trí tuệ Nhân tạo (AI Ethics & Algorithmic Fairness): Nếu em phát hiện ra mô hình tuyển dụng hoặc chấm điểm tín dụng của công ty vô tình có định kiến bất công (Bias) đối với một nhóm giới tính hoặc khu vực địa lý cụ thể, em hành động như thế nào dù mô hình đó mang lại lợi nhuận cao cho công ty?",
    ["Ý thức trách nhiệm xã hội và pháp lý cao: Một mô hình mang lại lợi nhuận nhưng phân biệt đối xử bất công sẽ gây ra rủi ro pháp lý khổng lồ và hủy hoại danh tiếng doanh nghiệp", "Thu thập bằng chứng khách quan: Sử dụng các thước đo công bằng thuật toán (Disparate Impact, Demographic Parity, Equalized Odds) để chứng minh sự thiên vị một cách khoa học", "Đưa ra giải pháp kỹ thuật khắc phục (Fairness-aware ML): Áp dụng kỹ thuật tiền xử lý (Reweighting), can thiệp trong quá trình huấn luyện (Adversarial Debiasing), hoặc hậu xử lý (Equalized Odds post-processing) để triệt tiêu định kiến mà suy giảm tối thiểu hiệu năng", "Trình bày thẳng thắn và xây dựng với Ban Lãnh đạo kèm lộ trình khắc phục"],
    ["Làm thế nào để thuyết phục các bên liên quan khi việc loại bỏ định kiến có thể làm giảm nhẹ 1-2% lợi nhuận ngắn hạn?", "Khung quản trị rủi ro đạo đức AI (AI Ethics Governance Framework) cần có những thành phần nào?"] ,
    ["AI Ethics", "Algorithmic Fairness", "Demographic Parity", "Adversarial Debiasing", "Moral Courage"],
    [DS_SRC.internal],
    ["Nhắm mắt làm ngơ vì sợ mất lòng sếp hoặc cho rằng 'dữ liệu lịch sử sao thì mô hình học vậy, không phải lỗi của tôi'"]
  ),
  q("DS-BEHAV-05", "Data Scientist", "behavioral", "intermediate", "middle",
    "Thế giới Data Science đang chứng kiến sự trỗi dậy mạnh mẽ của các Mô hình Ngôn ngữ Lớn (LLMs) và Nền tảng AutoML. Nhiều người cho rằng các thuật toán Machine Learning truyền thống (Tabular ML) sắp lỗi thời. Em nhìn nhận vị thế của một Data Scientist truyền thống trong thời đại này ra sao và định hình chiến lược phát triển bản thân thế nào?",
    ["Đánh giá thực tế và khách quan: Dữ liệu dạng bảng (Tabular Data: Giao dịch tài chính, hồ sơ y tế, chuỗi cung ứng) chiếm 80% giá trị cốt lõi trong doanh nghiệp, và các mô hình Gradient Boosting (XGBoost/LightGBM) vẫn chứng minh sự vượt trội về độ chính xác, tốc độ và chi phí so với Deep Learning/LLMs trên dữ liệu bảng", "Mở rộng năng lực thích ứng (T-shaped skills): Làm chủ vững chắc nền tảng Thống kê & Suy luận Nhân quả (thứ mà LLMs không thể tự suy luận), đồng thời tích hợp thêm năng lực GenAI/LLM làm công cụ tăng năng suất và xử lý dữ liệu phi cấu trúc", "Tập trung vào giá trị cốt lõi: Năng lực giải quyết bài toán kinh doanh thực tế, đặt đúng câu hỏi dữ liệu và chuyển hóa số liệu thành tác động thực chất"],
    ["Em đã tự mình thử nghiệm ứng dụng LLMs vào các bước nào trong quy trình Data Science hàng ngày của mình?", "Kỹ năng nào em coi là 'vũ khí bất biến' của một Data Scientist dù công nghệ có biến đổi thế nào?"] ,
    ["Future of Data Science", "Tabular ML vs LLMs", "T-Shaped Professional", "Continuous Adaptation", "Core Value Proposition"],
    [DS_SRC.internal],
    ["Phủ nhận hoàn toàn công nghệ mới bảo thủ, hoặc ngược lại, bỏ rơi toàn bộ nền tảng toán thống kê để chạy theo trào lưu hào nhoáng"]
  )
];

// 6. MACHINE LEARNING ENGINEER (30 questions)
const mlEngineerQuestions = [
  // Foundation (6)
  q("MLE-FOUND-01", "Machine Learning Engineer", "foundation", "advanced", "middle",
    "Kiến trúc và Thách thức trong Huấn luyện Phân tán (Distributed Training): Phân biệt Data Parallelism (DDP trong PyTorch), Pipeline Parallelism, Tensor Parallelism (Megatron-LM), và cơ chế đồng bộ gradient AllReduce (NCCL)?",
    ["Distributed Data Parallel (DDP): Mỗi GPU giữ một bản sao đầy đủ của mô hình; mỗi GPU xử lý một micro-batch dữ liệu độc lập; sau bước backward, các GPU đồng bộ gradient qua thuật toán Ring-AllReduce / Tree-AllReduce (thư viện NCCL qua NVLink/InfiniBand)", "Tensor Parallelism (Megatron-LM): Chia nhỏ các ma trận trọng số bên trong từng tầng mạng (vd: chia ma trận trọng số của Multi-Head Attention hoặc MLP) trên nhiều GPU; đòi hỏi băng thông cực cao nội bộ node (NVLink)", "Pipeline Parallelism: Chia các tầng liên tiếp của mạng (Layers) lên các GPU khác nhau tuần tự; thách thức 'Pipeline Bubble' (thời gian GPU nhàn rỗi chờ đợi) giải quyết qua 1F1B schedule", "Fully Sharded Data Parallel (FSDP / ZeRO): Shard toàn bộ Gradients, Optimizer States và Model Parameters trên toàn bộ cụm; gom lại lúc cần thiết để giải phóng bộ nhớ"],
    ["Tại sao PyTorch DDP lại vượt trội hơn hẳn so với DataParallel (DP) cũ vốn dùng đa luồng trên một tiến trình?", "Sự khác biệt giữa ZeRO-Stage 1, Stage 2 và Stage 3 trong DeepSpeed?"] ,
    ["Distributed Training", "PyTorch DDP", "Tensor Parallelism", "Ring-AllReduce NCCL", "FSDP ZeRO"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Dùng `torch.nn.DataParallel` trên cụm nhiều máy và gặp nghẽn GIL của Python làm chậm gấp 5 lần"]
  ),
  q("MLE-FOUND-02", "Machine Learning Engineer", "foundation", "advanced", "senior_lead",
    "Tối ưu hóa Bộ nhớ GPU trong Huấn luyện và Suy luận: Phân biệt các thành phần tiêu thụ VRAM (Model Weights, Optimizer States, Gradients, Activations, KV Cache). Cơ chế Activation Checkpointing và FlashAttention hoạt động ra sao?",
    ["Thành phần VRAM khi Train (Mô hình 7B FP16): Model weights = 14GB; Gradients = 14GB; Adam Optimizer states (FP32 master weights, momentum, variance) = 56GB; Activations phụ thuộc batch size và sequence length", "Activation Checkpointing (Gradient Checkpointing): Không lưu trữ toàn bộ activations ở forward pass; chỉ lưu các mốc ranh giới và tính toán lại (recompute) activations trong backward pass; tiết kiệm 70% VRAM activations với cái giá chỉ tăng ~20-30% thời gian tính toán", "FlashAttention: Tối ưu hóa I/O phần cứng giữa GPU HBM (High Bandwidth Memory) và SRAM; bẻ nhỏ ma trận Attention thành các khối tính toán tại chỗ qua Tiling và Online Softmax; giảm độ phức tạp bộ nhớ từ $O(N^2)$ xuống $O(N)$ mà không làm mất độ chính xác số học", "KV Cache trong Suy luận: Lưu trữ ma trận Key và Value của các token trước để tránh tính toán lại; dung lượng KV Cache tăng tuyến tính theo Batch Size và Context Length"],
    ["Tại sao việc chuyển đổi từ FP32 sang FP16/BF16 lại giải phóng hơn 50% bộ nhớ GPU mà vẫn giữ nguyên độ hội tụ?", "Làm thế nào để ước tính dung lượng VRAM tối thiểu cần thiết để Fine-tune một mô hình qua công thức toán học?"] ,
    ["GPU Memory Hierarchy", "FlashAttention", "Activation Checkpointing", "KV Cache Sizing", "VRAM Breakdown"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Gặp lỗi CUDA Out of Memory (OOM) chỉ biết giảm batch size về 1 mà không biết áp dụng Activation Checkpointing hay FlashAttention"]
  ),
  q("MLE-FOUND-03", "Machine Learning Engineer", "foundation", "advanced", "middle",
    "Lý thuyết Lượng tử hóa Mô hình (Model Quantization): Phân biệt Lượng tử hóa Sau Huấn luyện (Post-Training Quantization - PTQ) và Huấn luyện Nhận thức Lượng tử (Quantization-Aware Training - QAT). Cơ chế ánh xạ từ FP32/FP16 sang INT8/INT4 (Scale factor, Zero-point, Asymmetric vs Symmetric)?",
    ["Nguyên lý ánh xạ lượng tử: Chuyển đổi số thực liên tục $x$ sang số nguyên rời rạc $q$: $q = \\text{clip}\\left(\\text{round}\\left(\\frac{x}{S}\\right) + Z, q_{min}, q_{max}\\right)$; trong đó $S$ là Scale factor, $Z$ là Zero-point", "Symmetric vs Asymmetric: Symmetric đặt $Z = 0$, khoảng giá trị đối xứng quanh 0 (tối ưu tính toán); Asymmetric cho phép $Z \\neq 0$, tối ưu cho các phân phối lệch (như sau hàm kích hoạt ReLU)", "PTQ: Lượng tử hóa trực tiếp trên mô hình đã huấn luyện bằng một tập dữ liệu hiệu chuẩn nhỏ (Calibration Dataset) để tìm min/max; nhanh, không cần train lại nhưng có thể sụt giảm nhẹ độ chính xác", "QAT: Mô phỏng sai số lượng tử hóa ngay trong quá trình huấn luyện bằng toán tử FakeQuantization; gradient được tính qua Straight-Through Estimator (STE); giữ vững độ chính xác gần như nguyên bản"],
    ["Tại sao các kỹ thuật lượng tử hóa hiện đại (như GPTQ, AWQ, SmoothQuant) lại cần bảo vệ các trọng số ngoại lai (Outlier Weights)?", "Khác biệt về hỗ trợ phần cứng giữa INT8 Tensor Cores và FP8 trên các kiến trúc GPU NVIDIA Ada Lovelace / Hopper?"] ,
    ["Model Quantization", "PTQ vs QAT", "Scale Factor Zero Point", "Symmetric vs Asymmetric", "AWQ GPTQ"],
    [DS_SRC.pytorch, DS_SRC.onnx],
    ["Nghĩ rằng lượng tử hóa chỉ là ép kiểu dữ liệu đơn thuần bằng code Python mà không hiểu cơ chế Scale và Zero-point"]
  ),
  q("MLE-FOUND-04", "Machine Learning Engineer", "foundation", "advanced", "middle",
    "Định dạng Tuần tự hóa và Đóng gói Mô hình (Model Serialization & Formats): So sánh Pickle, PyTorch State Dict, TorchScript (Tracing vs Scripting), ONNX (Open Neural Network Exchange), và Safetensors?",
    ["Pickle / `.pt` mặc định: Tiềm ẩn lỗ hổng thực thi mã từ xa (RCE) nguy hiểm khi deserialize; phụ thuộc chặt chẽ vào môi trường Python và cấu trúc mã nguồn gốc", "Safetensors (HuggingFace): Định dạng nhị phân an toàn tuyệt đối (Zero-code execution), hỗ trợ Zero-copy Memory Mapping (`mmap`), nạp mô hình cực nhanh trực tiếp vào RAM/VRAM", "TorchScript: Chuyển đổi mã PyTorch sang đồ thị tĩnh độc lập C++ runtime; `torch.jit.trace` ghi lại luồng thực thi với dữ liệu mẫu (không bắt được câu lệnh rẽ nhánh if/else động); `torch.jit.script` biên dịch trực tiếp AST code Python", "ONNX: Tiêu chuẩn mở trung gian độc lập framework (PyTorch, TensorFlow, Scikit-learn); cho phép tối ưu hóa đồ thị tính toán qua ONNX Runtime trên đa nền tảng phần cứng (CPU, GPU, NPU, Edge)"],
    ["Khi nào bắt buộc phải dùng `torch.jit.script` thay vì `torch.jit.trace`?", "Lợi ích của việc nạp mô hình qua `mmap` trong Safetensors đối với thời gian khởi động container (Pod Startup Time)?"] ,
    ["Model Serialization", "TorchScript Tracing vs Scripting", "ONNX Graph", "Safetensors Zero-Copy", "Model Security"],
    [DS_SRC.onnx, DS_SRC.pytorch],
    ["Tải file checkpoint `.pkl` không rõ nguồn gốc trên mạng về chạy thẳng trên máy chủ sản xuất mà không kiểm tra an toàn"]
  ),
  q("MLE-FOUND-05", "Machine Learning Engineer", "foundation", "intermediate", "junior",
    "Các chỉ số Hiệu năng Triển khai Mô hình (Serving Metrics): Phân biệt Khả năng thông qua (Throughput - RPS / Tokens/s), Độ trễ (Latency: P50, P95, P99), Thời gian phản hồi Token đầu tiên (Time to First Token - TTFT) và Thời gian giữa các Token (Inter-Token Latency - ITL)?",
    ["Throughput: Số lượng yêu cầu (hoặc số token) mà hệ thống xử lý thành công trong một đơn vị thời gian (Requests Per Second - RPS hoặc Tokens Per Second - TPS)", "Latency Percentiles: P50 (thời gian trung vị); P99 (99% người dùng nhận kết quả nhanh hơn mốc này); P99 là chỉ số sống còn phản ánh trải nghiệm người dùng xấu nhất do đuôi dài (Tail Latency)", "TTFT (Time to First Token): Thời gian từ lúc gửi prompt đến khi nhận được token đầu tiên (phụ thuộc vào giai đoạn Prefill / Prompt Processing); ảnh hưởng trực tiếp đến cảm giác phản hồi nhanh", "ITL (Inter-Token Latency): Thời gian sinh ra mỗi token tiếp theo trong giai đoạn Decode; quyết định tốc độ đọc mượt mà của văn bản hiển thị"],
    ["Tại sao tối ưu hóa Throughput thường có sự đánh đổi với P99 Latency?", "Cơ chế Dynamic Batching giúp tăng Throughput lên gấp nhiều lần nhưng ảnh hưởng đến Latency như thế nào?"] ,
    ["Serving Metrics", "P99 Tail Latency", "Throughput vs Latency", "TTFT vs ITL", "Prefill vs Decode"],
    [DS_SRC.triton, DS_SRC.internal],
    ["Chỉ đo lường độ trễ trung bình (Mean Latency) và bỏ qua độ trễ đuôi P99 khiến 1% người dùng phải chờ hàng chục giây"]
  ),
  q("MLE-FOUND-06", "Machine Learning Engineer", "foundation", "advanced", "senior_lead",
    "Kiến trúc Đồ thị Tính toán (Computation Graph Optimization): Phân biệt Eager Execution và Graph Execution. Các kỹ thuật tối ưu hóa đồ thị: Hợp nhất phép tính (Operator Fusion), Cắt tỉa hằng số (Constant Folding), và Phân bổ bộ nhớ tĩnh (Static Memory Allocation)?",
    ["Eager Execution (PyTorch mặc định): Thực thi từng phép toán ngay lập tức khi chạy dòng lệnh Python; cực kỳ thuận tiện cho debug nhưng lãng phí tài nguyên do liên tục gọi kernel GPU độc lập (Kernel Launch Overhead)", "Graph Execution (PyTorch 2.0 `torch.compile`, TensorRT, XLA): Biên dịch toàn bộ mô hình thành một đồ thị tính toán tĩnh trước khi thực thi", "Operator Fusion: Gộp nhiều phép toán liên tiếp (vd: Conv + Bias + ReLU, hoặc LayerNorm + GeLU) thành một Kernel GPU duy nhất; giảm thiểu tối đa việc đọc/ghi dữ liệu trung gian vào bộ nhớ HBM chậm chạp", "Constant Folding & Dead Code Elimination: Tính toán trước các biểu thức hằng số tại thời điểm compile; xóa bỏ các node trong đồ thị không đóng góp vào kết quả cuối cùng"],
    ["`torch.compile` với backend TorchDynamo và AOTAutograd tăng tốc mô hình PyTorch như thế nào mà không cần viết lại mã C++?", "Tại sao Operator Fusion lại là kỹ thuật quan trọng nhất giúp tăng tốc mô hình Transformer?"] ,
    ["Computation Graph", "Operator Fusion", "torch.compile", "Constant Folding", "Kernel Launch Overhead"],
    [DS_SRC.pytorch, DS_SRC.triton],
    ["Cho rằng code Python chạy chậm là do CPU mà không biết rằng gọi quá nhiều kernel GPU nhỏ là nguyên nhân chính gây nghẽn"]
  ),

  // Practical Skills (8)
  q("MLE-PRAC-01", "Machine Learning Engineer", "practical_skills", "advanced", "middle",
    "Triển khai Mô hình với NVIDIA Triton Inference Server: Cách cấu hình tệp `config.pbtxt`, tối ưu hóa Dynamic Batching (`max_queue_delay_microseconds`), Hỗ trợ Đa phiên bản (Model Versioning) và Instance Groups (Chạy song song nhiều mô hình trên nhiều GPU)?",
    ["Cấu hình `config.pbtxt`: Định nghĩa rõ ràng Platform/Backend (`tensorrt_plan`, `onnxruntime_onnx`), Shapes của Inputs/Outputs, và Data Types", "Dynamic Batching: Tự động gom nhiều yêu cầu đơn lẻ đến trong một khoảng thời gian ngắn thành một batch lớn; cấu hình `max_batch_size` và `max_queue_delay_microseconds` (cân bằng hoàn hảo giữa Throughput và Latency)", "Instance Groups: Cấu hình `count: N` và `kind: KIND_GPU` để chạy song song nhiều worker của cùng một mô hình trên một hoặc nhiều GPU, tận dụng tối đa tài nguyên nhàn rỗi", "Model Repository & Dynamic Model Loading: Quản lý thư mục theo chuẩn version; nạp/dỡ mô hình động qua API không cần khởi động lại máy chủ Triton"],
    ["Làm thế nào để cấu hình Triton Ensemble Model nối chuỗi bước tiền xử lý ảnh (Python backend) và bước suy luận TensorRT thành một endpoint duy nhất?", "Sự khác biệt giữa Concurrent Model Execution và Dynamic Batching trong Triton?"] ,
    ["Triton Inference Server", "config.pbtxt", "Dynamic Batching", "Instance Groups", "Ensemble Pipelines"],
    [DS_SRC.triton, DS_SRC.internal],
    ["Deploy mô hình bằng Flask/FastAPI thuần đơn luồng và phàn nàn GPU chỉ hoạt động 5% công suất"]
  ),
  q("MLE-PRAC-02", "Machine Learning Engineer", "practical_skills", "advanced", "middle",
    "Tối ưu hóa và Biên dịch Mô hình bằng NVIDIA TensorRT: Quy trình chuyển đổi từ PyTorch -> ONNX -> TensorRT Engine (`trtexec`), Cấu hình Dynamic Shapes (Min/Opt/Max Profiles) và INT8 Calibration?",
    ["Quy trình chuyển đổi: Xuất mô hình PyTorch sang ONNX với opset tương thích; sử dụng công cụ `trtexec` để phân tích và tối ưu hóa sang định dạng nhị phân `.engine` đặc thù cho kiến trúc GPU mục tiêu", "Dynamic Shapes Optimization Profiles: Khai báo 3 profile kích thước đầu vào (`min`, `opt`, `max` cho batch_size và seq_length); TensorRT sẽ tối ưu hóa kernel GPU tốt nhất cho profile `opt`", "INT8 Calibration: Cung cấp `IInt8EntropyCalibrator2` với tập dữ liệu đại diện để tìm ngưỡng bão hòa (Saturation Threshold), giảm một nửa bộ nhớ và tăng tốc gấp đôi", "Profiling Engine: Phân tích báo cáo layer-by-layer timing từ `trtexec` để phát hiện các layer bị fallback về FP32 hoặc chưa được fuse"],
    ["Tại sao một file TensorRT Engine biên dịch trên GPU RTX 3090 lại không thể chạy được trên GPU A100?", "Cách xử lý các toán tử tùy biến (Custom Operators) trong PyTorch không được TensorRT hỗ trợ sẵn?"] ,
    ["NVIDIA TensorRT", "trtexec", "Dynamic Shapes Profiles", "INT8 Calibration", "Hardware-Specific Engine"],
    [DS_SRC.triton, DS_SRC.onnx],
    ["Biên dịch TensorRT engine trên máy laptop dev rồi copy file nhị phân đó lên server production chạy dẫn đến lỗi crash phần cứng"]
  ),
  q("MLE-PRAC-03", "Machine Learning Engineer", "practical_skills", "advanced", "middle",
    "Chưng cất Tri thức (Knowledge Distillation) và Nén Mô hình: Thiết kế hàm mất mát kết hợp (Distillation Loss = Cross-Entropy + KL Divergence với Temperature $T$) để chuyển giao tri thức từ Teacher Model khổng lồ sang Student Model nhỏ gọn?",
    ["Nguyên lý chưng cất: Student model học từ 'Soft Targets' (phân phối xác suất làm mềm bởi nhiệt độ $T$) của Teacher model; soft targets chứa đựng thông tin về cấu trúc tiềm ẩn và độ tương đồng giữa các lớp (Dark Knowledge)", "Công thức hàm Loss: $\\mathcal{L} = \\alpha \\mathcal{L}_{CE}(y_{true}, \\sigma(z_s)) + (1-\\alpha) T^2 \\mathcal{L}_{KL}(\\sigma(z_s / T), \\sigma(z_t / T))$; trong đó $z_s, z_t$ là logits của Student và Teacher", "Nhiệt độ $T$: Khi $T > 1$, làm phẳng phân phối xác suất giúp Student học được xác suất của các lớp sai nhưng gần đúng (vd: mèo giống chó hơn giống xe tải)", "Cắt tỉa mô hình (Model Pruning): Phân biệt Structured Pruning (xóa toàn bộ channels/heads, tăng tốc phần cứng thực tế) và Unstructured Pruning (đặt trọng số nhỏ về 0, tạo ma trận thưa)"],
    ["Tại sao Unstructured Pruning làm giảm 90% trọng số nhưng thường không giúp tăng tốc độ suy luận trên GPU thông thường?", "Cách áp dụng Task-specific Distillation cho mô hình Transformer (DistilBERT, MobileBERT)?"] ,
    ["Knowledge Distillation", "Soft Targets Dark Knowledge", "KL Divergence Temperature", "Model Pruning", "Model Compression"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Cắt tỉa 80% trọng số của mô hình bằng Unstructured Pruning rồi ngạc nhiên khi thấy thời gian suy luận không hề giảm"]
  ),
  q("MLE-PRAC-04", "Machine Learning Engineer", "practical_skills", "advanced", "senior_lead",
    "Thiết kế Hệ thống Tính năng Thời gian thực (Real-time Feature Store): Kiến trúc Online Store (Redis / DynamoDB) vs Offline Store (Snowflake / Parquet S3), Ngăn chặn Lệch pha Huấn luyện - Phục vụ (Training-Serving Skew) và Truy xuất điểm thời gian (Point-in-Time Joins) với Feast?",
    ["Vấn đề Training-Serving Skew: Sự khác biệt về định nghĩa hoặc cách tính toán đặc trưng giữa lúc huấn luyện (Batch SQL) và lúc suy luận thực tế (Streaming Python/Go); nguyên nhân hàng đầu làm sụt giảm hiệu năng", "Kiến trúc Feature Store: Định nghĩa tính năng tập trung bằng mã nguồn (Feature Definitions as Code); Offline Store lưu trữ lịch sử phục vụ đào tạo mô hình; Online Store lưu giá trị mới nhất (Key-Value) với độ trễ tra cứu dưới 5ms phục vụ suy luận thời gian thực", "Point-in-Time Correctness (Time-travel): Khi tạo tập dữ liệu train, Feature Store phải lấy chính xác giá trị của đặc trưng tại đúng thời điểm sự kiện xảy ra trong quá khứ, tránh rò rỉ dữ liệu tương lai", "Đồng bộ liên tục: Streaming ingestion pipeline (Flink/Kafka -> Redis) cập nhật Online Store ngay khi có sự kiện phát sinh"],
    ["Làm thế nào để xử lý khi Online Store Redis bị mất kết nối trong giờ cao điểm suy luận?", "Cách quản lý TTL (Time-To-Live) và xóa tự động các tính năng của người dùng không còn hoạt động trong Online Store?"] ,
    ["Feature Store", "Feast", "Training-Serving Skew", "Point-in-Time Join", "Online vs Offline Store"],
    ["https://docs.feast.dev/", DS_SRC.internal],
    ["Tự viết code tính toán feature một kiểu trong pipeline train và viết lại bằng code khác trong API serving dẫn đến kết quả sai lệch"]
  ),
  q("MLE-PRAC-05", "Machine Learning Engineer", "practical_skills", "advanced", "middle",
    "Đo đạc và Tối ưu hóa Profiling Mã nguồn PyTorch: Sử dụng PyTorch Profiler và NVIDIA Nsight Systems để định vị điểm nghẽn bộ nhớ, nghẽn I/O nạp dữ liệu (DataLoader Bottleneck) và CPU-GPU Synchronization Overhead?",
    ["Sử dụng PyTorch Profiler: Bọc khối lệnh trong `torch.profiler.profile()`; xuất file trace để phân tích trên giao diện Chrome Tracing (`chrome://tracing`) hoặc TensorBoard", "Phát hiện DataLoader Bottleneck: Quan sát biểu đồ thấy GPU thường xuyên rơi vào trạng thái nhàn rỗi (GPU Idle / Low Utilization) chờ đợi CPU nạp dữ liệu; giải pháp: Tăng `num_workers`, bật `pin_memory=True`, chuyển đổi dữ liệu sang định dạng nhị phân nén (WebDataset, TFRecord)", "Khắc phục CPU-GPU Synchronization Overhead: Loại bỏ các lệnh đồng bộ ngầm làm đứng cụm GPU như gọi `.item()`, `.cpu()`, `print(tensor)` bên trong vòng lặp huấn luyện chính", "Sử dụng Mixed Precision (`torch.cuda.amp.autocast()` và `GradScaler`): Tự động chuyển đổi các phép tính nặng sang FP16 trên Tensor Cores mà không gây tràn số"],
    ["Làm thế nào để nhận biết một mô hình bị nghẽn do Băng thông Bộ nhớ (Memory-bound) hay do Năng lực Tính toán (Compute-bound) trên GPU?", "Khi nào nên sử dụng `torch.cuda.nvtx` để đánh dấu các vùng mã tùy biến trong báo cáo Nsight Systems?"] ,
    ["PyTorch Profiler", "GPU Profiling Nsight", "DataLoader Bottleneck", "Automatic Mixed Precision", "CPU GPU Synchronization"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Đặt câu lệnh `loss.item()` và `print()` ở mọi batch trong vòng lặp huấn luyện làm giảm 70% tốc độ chạy của GPU"]
  ),
  q("MLE-PRAC-06", "Machine Learning Engineer", "practical_skills", "advanced", "senior_lead",
    "Chiến lược Triển khai và Cập nhật Mô hình Không gián đoạn (Zero-Downtime Deployment): Triển khai Shadow Deployment (Dark Launch), Canary Deployment, và A/B Testing ở tầng Hạ tầng phục vụ (Serving Infrastructure với Seldon Core / KServe / Envoy)?",
    ["Shadow Deployment (Dark Launch): Nhân bản lưu lượng thực tế (Traffic Mirroring) gửi đồng thời tới cả mô hình cũ (Champion) và mô hình mới (Shadow); kết quả của mô hình mới được ghi log để đo lường hiệu năng và độ trễ nhưng không trả về cho người dùng; không gây rủi ro kinh doanh", "Canary Deployment: Điều hướng một tỷ lệ nhỏ lưu lượng thực tế (vd: 1% -> 5% -> 20% -> 100%) tới mô hình mới; tự động rollback nếu tỷ lệ lỗi HTTP 5xx tăng hoặc P99 latency vượt ngưỡng SLA", "KServe / vLLM trên Kubernetes: Tận dụng cơ chế Autoscaling (KEDA dựa trên GPU utilization hoặc Request Queue Length), Scale-to-Zero để tiết kiệm chi phí ban đêm", "Quản lý Định tuyến Lưu lượng: Sử dụng Envoy Proxy hoặc Istio Service Mesh để điều hướng linh hoạt dựa trên header HTTP hoặc user ID"],
    ["Làm thế nào để so sánh độ chính xác kinh doanh giữa hai mô hình trong kiến trúc Shadow Deployment khi kết quả shadow không được thực thi?", "Cách giải quyết bài toán Cold Start khi một Pod GPU mới khởi động mất 3 phút để kéo 15GB model weights từ S3?"] ,
    ["Model Deployment Strategies", "Shadow Deployment", "Canary Release", "KServe Seldon", "Traffic Mirroring Envoy"],
    ["https://kserve.github.io/website/", DS_SRC.internal],
    ["Deploy thẳng phiên bản mô hình mới đè lên phiên bản cũ trên 100% người dùng và làm sập toàn bộ hệ thống API"]
  ),
  q("MLE-PRAC-07", "Machine Learning Engineer", "practical_skills", "advanced", "middle",
    "Đóng gói Môi trường và Tối ưu hóa Container Image cho GPU (Docker for ML): Cách xây dựng Multi-stage Dockerfile tinh gọn, quản lý NVIDIA Container Toolkit (CUDA, cuDNN), và giảm kích thước image từ 15GB xuống dưới 3GB?",
    ["Multi-stage Builds: Tách biệt giai đoạn Build (chứa trình biên dịch gcc, header files, công cụ dev nặng) và giai đoạn Runtime (chỉ chứa file nhị phân và thư viện thực thi tối thiểu)", "Lựa chọn Base Image: Sử dụng `nvidia/cuda:x.y.z-base` hoặc `-runtime` thay vì `-devel`; loại bỏ các dependencies không cần thiết; cài đặt bánh xe PyTorch chỉ chứa đúng phiên bản CUDA tương thích", "Tối ưu hóa Docker Layer Caching: Sắp xếp các lệnh ít thay đổi lên trên (cài đặt hệ điều hành, thư viện C), file mã nguồn thay đổi thường xuyên đặt ở tầng dưới cùng", "Bảo vệ bí mật và quyền hạn: Không chạy container dưới quyền `root`; sử dụng Docker secrets để nạp API token khi kéo model từ HuggingFace trong lúc build"],
    ["Làm thế nào để chia sẻ an toàn GPU vật lý giữa các container qua NVIDIA MIG (Multi-Instance GPU)?", "Cách sử dụng `docker-slim` hoặc distroless images để giảm diện tích tấn công an ninh mạng cho container ML?"] ,
    ["Docker for GPU", "Multi-stage Builds", "NVIDIA Container Toolkit", "Container Image Optimization", "Production Container Best Practices"],
    [DS_SRC.internal],
    ["Tạo Docker image chứa nguyên bộ mã nguồn, dữ liệu huấn luyện 20GB và chạy dưới quyền root"]
  ),
  q("MLE-PRAC-08", "Machine Learning Engineer", "practical_skills", "advanced", "senior_lead",
    "Xây dựng Pipeline CI/CD Tự động hóa cho Mô hình Học máy (Continuous Delivery for ML - CD4ML): Tự động hóa quá trình Kiểm thử Mô hình (Model Testing: Invariance tests, Directional tests, Minimum Functionality tests), Đăng ký Mô hình (Model Registry) và Đóng gói Container?",
    ["Bộ ba kiểm thử mô hình theo trường phái CheckList: (1) Minimum Functionality Tests (kiểm tra các ca suy luận cơ bản hiển nhiên); (2) Invariance Tests (thay đổi thông tin không liên quan như tên người mà nhãn dự đoán không được đổi); (3) Directional Expectation Tests (thay đổi đặc trưng theo hướng tăng rủi ro thì xác suất dự đoán bắt buộc phải tăng)", "Automated Quality Gates: Chỉ cho phép tự động đóng gói mô hình nếu vượt qua toàn bộ test chức năng, không bị suy giảm hiệu năng trên tập Golden Dataset, và P99 latency dưới 50ms", "Model Registry (MLflow / W&B): Tự động gán metadata, phiên bản commit Git, mã băm dữ liệu huấn luyện và chuyển trạng thái từ `Staging` sang `Production`", "Tự động kích hoạt Canary Rollout: Pipeline CI/CD sau khi build Docker image sẽ tự động cập nhật Helm Chart hoặc KServe manifest trên cụm Kubernetes"],
    ["Làm thế nào để thiết kế một bài kiểm tra tự động phát hiện rủi ro phân biệt đối xử (Fairness Test) trong pipeline CI/CD trước khi xuất xưởng?", "Quy trình Rollback tự động khi mô hình mới được thăng hạng lên Production gặp lỗi runtime?"] ,
    ["CD4ML", "Model Testing CheckList", "Invariance Tests", "Model Registry MLflow", "Automated Release Gates"],
    [DS_SRC.internal],
    ["Chỉ dựa vào con số test accuracy duy nhất để tự động đưa mô hình lên production mà không kiểm thử biên hành vi"]
  ),

  // Scenario (6)
  q("MLE-SCEN-01", "Machine Learning Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Hệ thống API phục vụ mô hình Gợi ý Sản phẩm thời gian thực đang chạy ổn định ở mức 200 RPS với độ trễ P99 là 45ms. Trong sự kiện Siêu Sale Mega Day, lưu lượng truy cập bất ngờ tăng vọt lên 3.000 RPS, độ trễ P99 vọt lên 2.500ms (timeout liên tục) và GPU Server bắt đầu xuất hiện lỗi OOM. Em thiết lập kế hoạch phản ứng khẩn cấp và tái cấu trúc hệ thống chịu tải ra sao?",
    ["Bước 1: Kích hoạt khẩn cấp cơ chế Thao tác An toàn / Suy giảm Dịch vụ có kiểm soát (Graceful Degradation / Circuit Breaker): Tạm thời chuyển 80% lưu lượng truy cập sang tầng Cache tĩnh (Redis lưu sẵn Top 50 sản phẩm thịnh hành) hoặc mô hình Heuristic quy tắc nhẹ để hạ tải tức thời cho GPU", "Bước 2: Bật Dynamic Batching và Hàng đợi ưu tiên trên Triton: Tối ưu `max_queue_delay_microseconds` thành 5-10ms để gom batch lớn hơn; từ chối các request đã chờ trong hàng đợi quá 100ms (Load Shedding)", "Bước 3: Tự động co giãn cụm suy luận (Autoscaling): Kích hoạt mở rộng số lượng GPU Pods qua KEDA dựa trên độ dài hàng đợi request (Queue Depth) thay vì chỉ nhìn vào CPU/GPU utilization", "Bước 4: Giải pháp dài hạn: Lượng tử hóa mô hình sang INT8 bằng TensorRT, tách rời kiến trúc thành hai tầng (Lightweight Candidate Retrieval qua Vector DB + Heavyweight Ranking phân tán)"],
    ["Tại sao autoscaling dựa trên GPU Utilization thường phản ứng quá trễ trong các đợt lưu lượng tăng đột biến?", "Chiến lược Load Shedding bảo vệ máy chủ AI không bị sập hoàn toàn như thế nào?"] ,
    ["High Traffic Spike Crisis", "Graceful Degradation", "Dynamic Batching Tuning", "Load Shedding", "Triton Autoscaling KEDA"],
    [DS_SRC.triton, DS_SRC.internal],
    ["Ngồi chờ cụm máy chủ tự sập trong sự kiện Mega Day và không có bất kỳ cơ chế fallback hay cache dự phòng nào"]
  ),
  q("MLE-SCEN-02", "Machine Learning Engineer", "scenario", "advanced", "middle",
    "Tình huống: Khi chuyển đổi một mô hình PyTorch thị giác máy tính sang TensorRT Engine để tối ưu hóa tốc độ, em nhận thấy tốc độ suy luận tăng gấp 4 lần (từ 40ms xuống 10ms) nhưng độ chính xác (mAP) của mô hình bị sụt giảm bất thường 12% so với bản gốc. Em tiến hành chẩn đoán từng bước để tìm ra nguyên nhân và khôi phục độ chính xác ra sao?",
    ["Bước 1: Kiểm tra chế độ chính xác (Precision Mode): Kiểm tra xem có đang bật INT8 hay FP16 không; chạy thử nghiệm ở chế độ FP16 trước để xác định xem lỗi do lượng tử hóa INT8 hay do bản thân việc chuyển đổi đồ thị ONNX/TensorRT", "Bước 2: Nếu lỗi xảy ra ở INT8: Kiểm tra tập dữ liệu hiệu chuẩn (Calibration Dataset); tập calibration có thể quá nhỏ (chỉ vài chục ảnh) hoặc phân phối không đại diện cho dữ liệu thực tế; tăng kích thước calibration lên 1.000 ảnh đa dạng", "Bước 3: Kiểm tra các phép tiền xử lý (Preprocessing Discrepancy): Đối chiếu kỹ thuật chuẩn hóa ảnh (BGR vs RGB, dải giá trị $[0, 1]$ vs $[0, 255]$, cách resize và crop ảnh có đúng từng pixel so với code PyTorch gốc không)", "Bước 4: Sử dụng Per-Layer Precision Isolation: Ép một số layer nhạy cảm (như Softmax, LayerNorm hoặc các layer đầu/cuối của mạng) giữ nguyên ở mức FP16/FP32 trong khi các layer Conv/Linear ở giữa chạy INT8"],
    ["Tại sao các phép tính Softmax và LayerNorm thường rất nhạy cảm và dễ bị vỡ số khi lượng tử hóa INT8?", "Cách sử dụng công cụ Polygraphy của NVIDIA để so sánh kết quả từng layer giữa PyTorch và TensorRT?"] ,
    ["TensorRT Accuracy Degradation", "INT8 Calibration Debugging", "Per-Layer Precision Mixed", "Preprocessing Discrepancy", "Polygraphy Tool"],
    [DS_SRC.triton, DS_SRC.onnx],
    ["Chấp nhận mất 12% độ chính xác và đưa mô hình lỗi lên production chỉ để đạt được tốc độ nhanh"]
  ),
  q("MLE-SCEN-03", "Machine Learning Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Khi huấn luyện một mô hình ngôn ngữ lớn (LLM) 13 tỷ tham số trên một cụm 4 máy chủ (mỗi máy 8 GPU A100 kết nối qua mạng InfiniBand), quá trình huấn luyện diễn ra cực kỳ chậm chạp và GPU Utilization chỉ đạt 22%. Em tiến hành chẩn đoán điểm nghẽn hạ tầng và cấu hình song song để đẩy hiệu suất cụm lên trên 65% như thế nào?",
    ["Bước 1: Chẩn đoán điểm nghẽn qua PyTorch Profiler / Nsight Systems: Kiểm tra thời gian tính toán (Compute time) vs thời gian giao tiếp mạng (Communication time AllReduce) vs thời gian nạp dữ liệu (I/O wait)", "Bước 2: Kiểm tra cấu hình phần cứng và mạng: Xác minh xem giao thức InfiniBand / RoCE có đang hoạt động ở tốc độ tối đa không hay đang bị nghẽn do fallback về mạng Ethernet thông thường; kiểm tra biến môi trường `NCCL_DEBUG=INFO`", "Bước 3: Tối ưu hóa Chiến lược Song song (Hybrid Parallelism Strategy): Đối với mô hình 13B trên 32 GPU: Sử dụng Tensor Parallelism (TP = 8) nội bộ trong từng node (tận dụng băng thông cực lớn của NVLink); sử dụng Data Parallelism (FSDP / DDP = 4) qua các node mạng với Gradient Bucketing", "Bước 4: Tối ưu hóa bộ nhớ và tính toán: Bật FlashAttention-2, kích hoạt `torch.compile`, và áp dụng Activation Checkpointing có chọn lọc"],
    ["Tại sao không nên áp dụng Tensor Parallelism xuyên qua các node mạng khác nhau qua đường truyền mạng ngoài?", "Làm thế nào để sử dụng chỉ số TFLOPS (Model FLOPs Utilization - MFU) để định lượng hiệu suất tính toán của cụm phần cứng?"] ,
    ["Distributed Training Bottleneck", "Model FLOPs Utilization MFU", "Hybrid Parallelism TP DDP", "InfiniBand NCCL Debugging", "NVLink Optimization"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Nghĩ rằng GPU chạy chậm là do mô hình quá phức tạp mà không kiểm tra lỗi nghẽn đường truyền mạng giữa các node"]
  ),
  q("MLE-SCEN-04", "Machine Learning Engineer", "scenario", "advanced", "middle",
    "Tình huống: Mô hình phân loại văn bản đa ngôn ngữ phục vụ dịch vụ khách hàng gặp lỗi 'Rò rỉ Bộ nhớ' (Memory Leak) âm thầm: Container suy luận chạy trên Kubernetes bị tăng đều đặn 200MB RAM mỗi giờ và cứ sau khoảng 2 ngày thì bị Kubernetes bắn tỉa (OOMKilled). Em săn lùng và khắc phục nguyên nhân rò rỉ bộ nhớ này như thế nào?",
    ["Bước 1: Phân lập rò rỉ (Isolate Leak Source): Xác định rò rỉ ở tầng Python Heap, tầng C++ Native Runtime (ONNX/Torch backend), hay tầng Web Framework (FastAPI/Gunicorn)", "Bước 2: Sử dụng công cụ Profiling bộ nhớ chuyên biệt: Dùng thư viện `tracemalloc` hoặc `memray` trong Python để chụp ảnh (snapshot) bộ nhớ và so sánh sự gia tăng đối tượng giữa các request", "Bước 3: Nhận diện thủ phạm kinh điển trong mã ML Python: (1) Lưu trữ tensors trong danh sách toàn cục để ghi log mà không gọi `.detach()`; (2) Tích lũy Computation Graph ngầm do thiếu khối lệnh `with torch.no_grad():`; (3) Bộ nhớ đệm không giới hạn của Tokenizer hoặc Regex compilation; (4) Thread pool worker không được giải phóng", "Bước 4: Khắc phục và kiểm thử tải dài hạn: Sửa code, bổ sung `gc.collect()`, chạy bài kiểm thử tải liên tục trong 12 giờ qua Locust để chứng minh đồ thị bộ nhớ hoàn toàn đi ngang"],
    ["Tại sao việc thiếu `with torch.no_grad():` trong hàm suy luận lại làm GPU/RAM phình to không giới hạn?", "Làm thế nào để cấu hình cờ `--max-requests` và `--max-requests-jitter` trong Gunicorn làm phương án phòng thủ tầng cuối tự làm mới worker?"] ,
    ["Memory Leak Debugging", "torch.no_grad OOM", "Memray Profiling", "Kubernetes OOMKilled", "Production Python Stability"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Chỉ biết cấu hình tăng giới hạn RAM của Pod lên gấp 4 lần để kéo dài thời gian sống của container thay vì sửa lỗi rò rỉ bộ nhớ"]
  ),
  q("MLE-SCEN-05", "Machine Learning Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Doanh nghiệp muốn triển khai một mô hình nhận diện khuôn mặt và phát hiện bất thường lên 10.000 thiết bị biên (Edge Devices - NVIDIA Jetson Nano / Raspberry Pi) đặt tại các chi nhánh cửa hàng. Băng thông mạng ở các cửa hàng rất hạn chế và thiết bị có giới hạn khắt khe về công suất điện (5-10 Watts). Em thiết kế kiến trúc triển khai, cập nhật mô hình từ xa (OTA Updates) và tối ưu hóa phần cứng ra sao?",
    ["Tối ưu hóa mô hình cho Edge: Kiến trúc mô hình siêu nhẹ (MobileNetV4, YOLOv8-Nano); Áp dụng kỹ thuật INT8 Quantization qua TensorRT trên Jetson; Tận dụng phần cứng tăng tốc chuyên biệt (NVDLA - Deep Learning Accelerator)", "Kiến trúc Xử lý Cục bộ (Edge Inference): Mô hình chạy suy luận hoàn toàn offline trên thiết bị biên; chỉ gửi siêu dữ liệu kết quả (Metadata JSON: ID, tọa độ, timestamp) về máy chủ đám mây qua kết nối MQTT/gRPC nhẹ, không truyền video thô", "Cơ chế Cập nhật Mô hình qua mạng (Over-The-Air - OTA): Đóng gói mô hình dưới dạng các container Docker nhẹ; sử dụng nền tảng quản lý thiết bị biên (Balena / AWS IoT Greengrass / Azure IoT Edge); cập nhật theo từng đợt (Phased Rollout 5% -> 20% -> 100%)", "Cơ chế Tự phục hồi (Watchdog & A/B Partitioning): Thiết bị giữ lại bản sao mô hình cũ; nếu bản cập nhật mới làm thiết bị quá nhiệt hoặc crash trong 10 phút, hệ thống tự động rollback về phiên bản trước"],
    ["Làm thế nào để giám sát sức khỏe phần cứng (Nhiệt độ GPU, mức tiêu thụ điện năng) của 10.000 thiết bị từ xa?", "Cách thu thập có chọn lọc các mẫu dữ liệu biên 'khó phân loại' gửi về đám mây để huấn luyện lại (Active Learning on Edge)?"] ,
    ["Edge AI Architecture", "NVIDIA Jetson Optimization", "OTA Model Updates", "MQTT Lightweight Protocol", "Watchdog Fallback"],
    [DS_SRC.onnx, DS_SRC.internal],
    ["Gửi toàn bộ luồng video HD từ 10.000 cửa hàng về máy chủ đám mây gây nghẽn băng thông và làm bùng nổ hàng triệu USD chi phí Cloud"]
  ),
  q("MLE-SCEN-06", "Machine Learning Engineer", "scenario", "advanced", "senior_lead",
    "Tình huống: Khi kiểm toán hệ thống phục vụ mô hình của công ty, Giám đốc Công nghệ (CTO) nhận thấy chi phí thuê cụm GPU Cloud (A100/H100) hàng tháng lên tới hơn $40,000 nhưng tỷ lệ sử dụng trung bình (Average GPU Utilization) chỉ đạt 18% do lưu lượng người dùng biến động mạnh giữa ngày và đêm. Em lập kế hoạch tối ưu hóa chi phí (ML FinOps) để giảm 60% hóa đơn hạ tầng mà vẫn giữ vững cam kết SLA độ trễ ra sao?",
    ["Bước 1: Phân tích tải và đa dạng hóa phần cứng: Mô hình hóa biểu đồ lưu lượng 24/7; chuyển các mô hình suy luận nhẹ hoặc vừa từ GPU sang CPU tối ưu hóa cao (dùng OpenVINO / Intel Extension for PyTorch với AVX-512) hoặc GPU rẻ hơn (NVIDIA T4 / L4 tiết kiệm chi phí gấp 5 lần so với A100)", "Bước 2: Kiến trúc Co giãn Động (Dynamic Scaling & Scale-to-Zero): Triển khai KServe / vLLM với KEDA; vào ban đêm khi ít lưu lượng, hệ thống tự động co cụm về mức tối thiểu hoặc Scale-to-Zero cho các dịch vụ nội bộ", "Bước 3: Tận dụng Spot / Preemptible Instances: Chạy các tác vụ huấn luyện và thử nghiệm offline trên các máy chủ Spot với giá giảm 70-80%; thiết lập cơ chế Checkpointing thường xuyên để tự động khôi phục khi node bị thu hồi", "Bước 4: Hợp nhất Mô hình (Multi-tenant Model Serving): Tận dụng tính năng Multi-Instance GPU (MIG) trên A100 để chia 1 GPU vật lý thành 7 GPU ảo độc lập phục vụ 7 mô hình khác nhau, hoặc dùng Triton phục vụ nhiều mô hình trên cùng một GPU shared context"],
    ["Chiến lược quản lý rủi ro khi sử dụng Spot Instances cho các tác vụ Fine-tuning dài ngày?", "Làm thế nào để tính toán điểm hòa vốn (Break-even point) giữa việc tự mua phần cứng GPU đặt on-premise so với thuê Cloud?"] ,
    ["ML FinOps", "GPU Cost Optimization", "CPU Serving OpenVINO", "Spot Instances Strategy", "Multi-Instance GPU MIG"],
    [DS_SRC.triton, DS_SRC.internal],
    ["Thuê cố định hàng chục máy chủ GPU A100 chạy 24/7 với chi phí tối đa mà không có bất kỳ cơ chế autoscaling hay tối ưu hóa tài nguyên nào"]
  ),

  // CV Validation (5)
  q("MLE-CV-01", "Machine Learning Engineer", "cv_validation", "advanced", "middle",
    "Trong dự án triển khai hệ thống Machine Learning phục vụ quy mô sản xuất lớn nhất mà em ghi trong CV, kiến trúc hạ tầng phục vụ (Serving Infrastructure) được thiết kế như thế nào? Lưu lượng truy cập (RPS), độ trễ P99 SLA, và số lượng máy chủ/GPU vận hành thực tế là bao nhiêu?",
    ["Mô tả cấu trúc hạ tầng mạch lạc: Từ API Gateway -> Load Balancer -> Inference Server (Triton/TorchServe/FastAPI) -> Backend Workers -> Monitoring Stack", "Cung cấp số liệu kỹ thuật chính xác: Throughput đỉnh điểm (RPS), P99 latency cam kết (ms), số lượng GPU/CPU pods và loại phần cứng sử dụng", "Lý do lựa chọn giải pháp kiến trúc phục vụ đó thay vì các phương án thay thế"],
    ["Thách thức kỹ thuật lớn nhất em gặp phải khi đưa hệ thống đó ra môi trường sản xuất thực tế?", "Khi lưu lượng người dùng tăng đột biến, hệ thống đã ứng phó như thế nào trong thực tế?"] ,
    ["Production Architecture Walkthrough", "Throughput and P99 Metrics", "Serving Stack Selection", "Engineering Reality Check"],
    [DS_SRC.triton, DS_SRC.internal],
    ["Mô tả kiến trúc chung chung, ấp úng khi hỏi về độ trễ P99 thực tế và số lượng GPU vận hành"]
  ),
  q("MLE-CV-02", "Machine Learning Engineer", "cv_validation", "advanced", "middle",
    "Em ghi nhận trên CV về kinh nghiệm tối ưu hóa tốc độ suy luận mô hình (Model Optimization). Em hãy chọn một mô hình cụ thể mà em từng tối ưu và giải thích chi tiết: Em đã sử dụng công cụ nào (TensorRT, ONNX Runtime, OpenVINO)? Tốc độ và tài nguyên bộ nhớ trước và sau khi tối ưu thay đổi như thế nào?",
    ["Nêu rõ kiến trúc mô hình (vd: ResNet-50, YOLOv8, BERT-Base) và bài toán ứng dụng", "Quy trình kỹ thuật cụ thể: Các bước tối ưu hóa đã thực hiện (Operator fusion, Dynamic shapes, FP16/INT8 conversion)", "Bằng chứng định lượng khách quan: Latency giảm từ X ms xuống Y ms, Throughput tăng Z lần, VRAM giảm W% trên cùng một phần cứng"],
    ["Độ chính xác của mô hình có bị suy giảm sau khi tối ưu không và em đã kiểm chứng điều đó ra sao?", "Khó khăn lớn nhất trong việc xuất mô hình sang định dạng tối ưu đó là gì?"] ,
    ["Model Optimization Case Study", "TensorRT Acceleration", "Throughput Gains", "Quantifiable Metrics"],
    [DS_SRC.onnx, DS_SRC.triton],
    ["Khai báo đã tối ưu hóa mô hình nhưng không nhớ nổi số liệu latency trước và sau khi tối ưu"]
  ),
  q("MLE-CV-03", "Machine Learning Engineer", "cv_validation", "advanced", "senior_lead",
    "Trong CV em có đề cập đến việc xây dựng hoặc vận hành Pipeline Huấn luyện Phân tán (Distributed Training Pipeline). Em hãy giải thích chi tiết cách em cấu hình phân bổ tài nguyên, chiến lược đồng bộ hóa gradient, và cách xử lý sự cố khi một GPU Worker bị chết giữa chừng trong lúc huấn luyện?",
    ["Chiến lược song song đã áp dụng: DDP, FSDP, DeepSpeed hay kết hợp; cấu hình giao tiếp mạng qua NCCL", "Cơ chế Checkpointing: Tần suất lưu checkpoint (vd: Lưu mỗi epoch hoặc mỗi 500 steps) lên Object Storage chung; chiến lược Elastic Training (TorchElastic) tự động phát hiện worker chết và tiếp tục huấn luyện từ checkpoint gần nhất mà không làm hủy toàn bộ job", "Kinh nghiệm thực tế về việc điều chỉnh Learning Rate khi tăng Batch Size lớn trong huấn luyện phân tán (Linear Scaling Rule / Cosine Annealing)"],
    ["Sự khác biệt giữa Gradient Accumulation và Distributed Data Parallel?", "Làm thế nào để phát hiện một Worker bị treo ngầm (Straggler) làm chậm toàn bộ cụm?"] ,
    ["Distributed Training Reality", "TorchElastic Fault Tolerance", "Checkpointing Strategy", "NCCL Tuning"],
    [DS_SRC.pytorch, DS_SRC.internal],
    ["Chỉ biết chạy script trên 1 máy GPU đơn lẻ và chép lý thuyết phân tán vào CV"]
  ),
  q("MLE-CV-04", "Machine Learning Engineer", "cv_validation", "advanced", "middle",
    "Em ghi nhận có kinh nghiệm tích hợp Feature Store hoặc xây dựng đường ống tính toán đặc trưng phục vụ suy luận thời gian thực. Em hãy giải thích cách hệ thống của em đảm bảo tính toán đặc trưng nhất quán tuyệt đối giữa lúc Offline Training và Online Serving (No Skew)?",
    ["Kiến trúc nhất quán: Sử dụng chung một định nghĩa mã nguồn (Shared Feature Logic / Logic as Code) hoặc cùng một pipeline trung tâm (Feast / Hopsworks / dbt)", "Cơ chế kiểm thử đối soát tự động: Viết integration tests định kỳ đối chiếu giá trị feature trích xuất từ Online Store (Redis) với feature tính từ Offline Warehouse cho cùng một tập người dùng mẫu", "Xử lý độ trễ thời gian thực: Cách hệ thống streaming (Kafka + Flink) cập nhật tính năng vào Online Store trong vài giây"],
    ["Nếu một tính năng trong Online Store bị lỗi thời (Stale data) do pipeline streaming bị nghẽn, API suy luận sẽ phản ứng ra sao?", "Cách xử lý tính năng fallback khi giá trị feature bị null trong lúc phục vụ?"] ,
    ["Feature Store Integrity", "Training-Serving Parity", "Streaming Feature Ingestion", "Stale Feature Remediation"],
    [DS_SRC.internal],
    ["Tính feature lúc train bằng SQL phức tạp rồi viết lại bằng hàm Python khác hoàn toàn trong API phục vụ"]
  ),
  q("MLE-CV-05", "Machine Learning Engineer", "cv_validation", "intermediate", "junior",
    "Em liệt kê thành thạo Docker và Kubernetes cho Machine Learning trong CV. Em đã từng tự tay viết Dockerfile cho GPU, cấu hình tài nguyên `resources: limits: nvidia.com/gpu: 1` và thiết lập Health Checks (Liveness & Readiness Probes) cho một dịch vụ ML chưa? Hãy giải thích chi tiết cách cấu hình?",
    ["Cấu hình Docker GPU: Lựa chọn Base Image NVIDIA chuẩn, cài đặt CUDA runtime và Python dependencies tối ưu", "Cấu hình Kubernetes Manifest: Khai báo rõ ràng Resource Requests & Limits cho CPU, RAM và GPU; cấu hình Node Affinity hoặc Tolerations để Pod được lên lịch vào đúng GPU Node", "Liveness & Readiness Probes: Phân biệt rõ ràng: Readiness Probe kiểm tra xem mô hình đã hoàn tất việc nạp vào GPU VRAM chưa trước khi cho phép nhận lưu lượng mạng; Liveness Probe kiểm tra xem container có bị deadlock không"],
    ["Tại sao việc không cấu hình Readiness Probe chuẩn có thể dẫn đến việc người dùng nhận lỗi HTTP 502/503 ngay sau khi Pod mới khởi động?", "Sự khác biệt giữa CPU Memory và GPU Memory khi thiết lập Limit trong Kubernetes?"] ,
    ["Kubernetes for ML", "GPU Resource Limits", "Liveness and Readiness Probes", "Pod Scheduling Tolerations"],
    [DS_SRC.internal],
    ["Không biết Readiness Probe là gì và cho phép router gửi traffic vào container khi mô hình còn chưa nạp xong vào RAM"]
  ),

  // Behavioral (5)
  q("MLE-BEHAV-01", "Machine Learning Engineer", "behavioral", "intermediate", "middle",
    "Kỹ sư Machine Learning thường xuyên phải làm việc chặt chẽ với cả Data Scientists (người tập trung vào thuật toán và độ chính xác) và Software/DevOps Engineers (người tập trung vào độ ổn định và tiêu chuẩn mã nguồn). Khi có bất đồng quan điểm giữa việc muốn thử nghiệm linh hoạt của DS và kỷ luật siết chặt của DevOps, em làm thế nào để dung hòa?",
    ["Tôn trọng và thấu hiểu góc nhìn của cả hai bên: Hiểu rằng DS cần không gian linh hoạt để đổi mới và DevOps cần quy chuẩn nghiêm ngặt để bảo vệ hệ thống", "Đóng vai trò cầu nối chuyển giao: Xây dựng các khuôn khổ và nền tảng (Platform Engineering) giúp DS có thể tự do thử nghiệm trong môi trường Sandbox cô lập, đồng thời tự động hóa các bước kiểm thử chuẩn mực trước khi đưa mã vào Production", "Thúc đẩy các tiêu chuẩn mã nguồn chung (Shared Code Quality Standards) mà không làm chậm tốc độ nghiên cứu"],
    ["Kể về một tình huống cụ thể em đã giải quyết thành công một cuộc tranh cãi kỹ thuật giữa DS và DevOps?", "Cách xây dựng văn hóa tôn trọng lẫn nhau giữa các nhóm chức năng khác nhau?"] ,
    ["Bridging DS and DevOps", "Cross-Functional Collaboration", "Platform Engineering Mindset", "Conflict Resolution"],
    [DS_SRC.internal],
    ["Đứng về một phía và chỉ trích phía còn lại, hoặc để mặc sự xung đột làm đình trệ dự án"]
  ),
  q("MLE-BEHAV-02", "Machine Learning Engineer", "behavioral", "advanced", "senior_lead",
    "Khi một mô hình Machine Learning gặp sự cố nghiêm trọng trên môi trường Production vào ban đêm (ví dụ: API suy luận bị crash liên tục hoặc dự đoán sai lệch hàng loạt gây khiếu nại), em tiếp nhận và xử lý áp lực đó như thế nào?",
    ["Giữ bình tĩnh và kích hoạt quy trình ứng cứu sự cố chuẩn hóa (Triage, Containment, Resolution)", "Hành động ưu tiên số 1: Bảo vệ người dùng và dịch vụ kinh doanh trước (Kích hoạt Fallback Rule-based ngay lập tức hoặc Rollback về phiên bản mô hình trước đó trong vòng 5 phút)", "Sau khi dịch vụ ổn định: Thu thập đầy đủ log, trace, và các mẫu dữ liệu đầu vào gây crash để tái lập lỗi trên môi trường local", "Tổ chức buổi Post-Mortem không đổ lỗi và bổ sung các bài kiểm tra tự động (Automated Smoke Tests) để đảm bảo lỗi tương tự không bao giờ tái diễn"],
    ["Làm thế nào để giao tiếp minh bạch về sự cố với các bên liên quan mà không gây hoảng loạn?", "Bài học kinh nghiệm sâu sắc nhất mà em từng rút ra từ một sự cố Production là gì?"] ,
    ["Production Incident Response", "Graceful Fallback Execution", "Blameless Post-Mortem", "Emotional Composure"],
    [DS_SRC.internal],
    ["Hoảng loạn, cố gắng sửa code trực tiếp trên production server đang chạy hoặc tìm cách trốn tránh trách nhiệm"]
  ),
  q("MLE-BEHAV-03", "Machine Learning Engineer", "behavioral", "intermediate", "junior",
    "Kể về một lần em nhận được mã nguồn mô hình từ một Data Scientist hoặc nghiên cứu sinh học thuật viết rất lộn xộn, thiếu kiểm thử, và không tuân thủ các quy chuẩn phần mềm. Em đã trao đổi và làm việc cùng họ như thế nào để tái cấu trúc lại mã nguồn mà không làm họ cảm thấy bị phán xét?",
    ["Tiếp cận với thái độ tôn trọng trí tuệ thuật toán của họ; ghi nhận giá trị chuyên môn to lớn mà mô hình mang lại", "Giải thích lý do tái cấu trúc xuất phát từ yêu cầu vận hành khách quan (Đảm bảo chịu tải, dễ bảo trì, an toàn dữ liệu) chứ không phải vì sở thích cá nhân", "Cùng họ ngồi lại thực hiện quá trình refactor: Tách module, viết Unit Test, tạo các giao diện API chuẩn hóa, hướng dẫn họ các công cụ hỗ trợ như linter và formatter"],
    ["Làm thế nào để đào tạo các bạn Data Scientists viết mã có cấu trúc tốt hơn cho các dự án sau?", "Cách biến việc chuyển giao mô hình (Model Handoff) từ một rào cản đau đớn thành một quy trình cộng tác mượt mà?"] ,
    ["Code Review Empathy", "Academic to Production Translation", "Constructive Mentorship", "Refactoring Collaboration"],
    [DS_SRC.internal],
    ["Chỉ trích gay gắt mã nguồn của người khác là rác rưởi hoặc tự ý viết lại hoàn toàn trong âm thầm"]
  ),
  q("MLE-BEHAV-04", "Machine Learning Engineer", "behavioral", "advanced", "senior_lead",
    "Trong lĩnh vực Machine Learning, có rất nhiều công nghệ và framework mới ra đời liên tục với những lời quảng cáo hào nhoáng. Khi một thành viên trong đội đề xuất áp dụng một công cụ serving hoặc framework hoàn toàn mới chưa được kiểm chứng vào hệ thống sản xuất cốt lõi, em đánh giá và ra quyết định như thế nào?",
    ["Ủng hộ tinh thần khám phá công nghệ mới nhưng kiên định nguyên tắc thận trọng với hệ thống Production (Boring Technology is Good Technology for Production)", "Yêu cầu xây dựng bài kiểm tra chứng minh giá trị (Proof of Concept - PoC) với các tiêu chí đo lường rõ ràng: Throughput, Latency, Mức tiêu thụ RAM/GPU, Tính ổn định dài hạn và Độ trưởng thành của cộng đồng hỗ trợ", "Đánh giá chi phí ẩn: Chi phí bảo trì, tài liệu hỗ trợ, khả năng tương thích với hạ tầng hiện tại và mức độ dễ tìm nhân sự thay thế", "Đưa ra lộ trình thử nghiệm an toàn: Thử nghiệm trên một dịch vụ phụ không trọng yếu trước khi áp dụng rộng rãi"],
    ["Làm thế nào để từ chối một đề xuất công nghệ mới mà không dập tắt sự hào hứng và đam mê tìm tòi của thành viên trong đội?", "Tiêu chí nào để em chính thức quyết định đưa một công nghệ mới vào 'Technology Radar' của công ty?"] ,
    ["Pragmatic Technology Adoption", "Boring Technology Philosophy", "PoC Evaluation Rigor", "Mentoring Innovation"],
    [DS_SRC.internal],
    ["Dễ dãi áp dụng mọi công cụ mới đang 'hot' trên GitHub vào production gây bất ổn định hệ thống, hoặc ngược lại, bảo thủ cấm đoán tuyệt đối"]
  ),
  q("MLE-BEHAV-05", "Machine Learning Engineer", "behavioral", "intermediate", "middle",
    "Kỹ sư Machine Learning thường xuyên phải đối mặt với các vấn đề kỹ thuật 'bí ẩn' rất khó debug (như huấn luyện bị nổ gradient ngẫu nhiên, GPU bỗng nhiên bị chậm không rõ lý do, hoặc kết quả suy luận sai lệch ở một vài trường hợp biên hiếm gặp). Em xây dựng phương pháp tư duy và tính kiên trì của mình như thế nào để không nản lòng khi giải quyết các vấn đề hóc búa này?",
    ["Tư duy gỡ lỗi có hệ thống (First Principles Debugging): Không đoán mò; chia nhỏ hệ thống và cô lập từng thành phần (Isolate variables); kiểm tra từ tầng dữ liệu -> tầng tiền xử lý -> tầng đồ thị mô hình -> tầng phần cứng/driver", "Lập giả thuyết và kiểm chứng có phương pháp: Ghi chép nhật ký gỡ lỗi (Debugging Log); tạo các bài kiểm thử tối thiểu tái lập được lỗi (Minimal Reproducible Example)", "Biết khi nào cần lùi lại và tìm kiếm sự hỗ trợ: Nếu bế tắc sau vài giờ, thảo luận với đồng nghiệp hoặc tham khảo các tài liệu chuyên sâu của cộng đồng mã nguồn mở"],
    ["Kể về một lỗi kỹ thuật kỳ lạ nhất mà em từng tự mình tìm ra và khắc phục thành công?", "Làm thế nào để giữ được sự bình tĩnh và tập trung cao độ khi đối mặt với một vấn đề kỹ thuật chưa từng có tiền lệ?"] ,
    ["Systematic Debugging", "First Principles Thinking", "Technical Tenacity", "Minimal Reproducible Example"],
    [DS_SRC.internal],
    ["Thử các giải pháp ngẫu nhiên chắp vá mà không hiểu nguyên nhân gốc rễ, hoặc bỏ cuộc nhanh chóng khi gặp lỗi khó"]
  )
];

module.exports = {
  dataScientistQuestions,
  mlEngineerQuestions
};
