const { q, SRC } = require('./fe_data.cjs');

const fsQuestions = [
  // Foundation (6)
  q("FS-FOUND-01", "Fullstack Developer", "foundation", "intermediate", "middle",
    "Trình bày vòng đời hoàn chỉnh của một HTTP request từ khi người dùng nhập URL trên trình duyệt, đi qua DNS, CDN/Reverse Proxy, Client hydration, API Gateway, Backend middleware, Database transaction cho đến khi kết quả được vẽ lại trên màn hình?",
    ["Trình bày đủ các tầng mạng: DNS resolution, TCP handshake, TLS negotiation, HTTP request", "Giải thích vai trò của CDN/Nginx trong việc caching static assets và proxying API", "Mô tả dòng chảy bên trong backend (Middleware -> Controller -> Service -> Repository -> DB) và phản hồi render ở client"],
    ["HTTP Keep-Alive và TCP connection reuse đóng vai trò gì trong việc giảm độ trễ?", "Sự khác biệt khi request là REST API thông thường so với Server Action trong Next.js?"],
    ["Request Lifecycle", "Networking", "Architecture", "Fullstack Flow"],
    ["https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work"],
    ["Bỏ qua các tầng mạng hoặc không giải thích được cách backend và frontend liên kết với nhau"]
  ),
  q("FS-FOUND-02", "Fullstack Developer", "foundation", "intermediate", "middle",
    "Cơ chế CORS (Cross-Origin Resource Sharing) hoạt động như thế nào? Sự khác nhau giữa Simple Request và Preflight Request (OPTIONS) là gì, và tại sao việc cấu hình sai CORS có thể dẫn đến rủi ro bảo mật nghiêm trọng?",
    ["Giải thích Same-Origin Policy (Protocol, Domain, Port) của trình duyệt", "Điều kiện kích hoạt Preflight Request (phương thức PUT/DELETE, custom headers, content-type application/json)", "Phân tích rủi ro khi để `Access-Control-Allow-Origin: *` kết hợp với `Access-Control-Allow-Credentials: true`"],
    ["Tại sao việc test bằng Postman hoặc curl luôn thành công dù trình duyệt bị chặn CORS?", "Làm thế nào để cấu hình reverse proxy (Nginx) để bypass CORS trong môi trường dev?"],
    ["CORS", "Security", "HTTP Headers", "Preflight Request"],
    ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"],
    ["Cho rằng CORS là tính năng bảo vệ máy chủ thay vì cơ chế bảo vệ của trình duyệt phía người dùng"]
  ),
  q("FS-FOUND-03", "Fullstack Developer", "foundation", "advanced", "senior_lead",
    "So sánh ưu và nhược điểm giữa kiến trúc Monorepo (sử dụng Turborepo/Nx/pnpm workspaces) và Polyrepo (chia tách repository riêng biệt cho Frontend và Backend). Cơ chế chia sẻ Types và DTOs giữa Client và Server được thiết kế ra sao?",
    ["Phân tích lợi ích Monorepo: chia sẻ kiểu dữ liệu nguyên vẹn, atomic commits, tái sử dụng CI/CD tooling", "Nhược điểm Monorepo: quyền truy cập repository, thời gian clone/build lớn nếu không có remote caching", "Thiết kế package chung `shared-types` chứa Zod schemas và TypeScript types cho cả frontend và backend"],
    ["Turborepo giải quyết bài toán Remote Caching và Task Graph như thế nào?", "Làm thế nào để quản lý versioning độc lập cho các micro-packages trong monorepo?"],
    ["Monorepo", "Turborepo", "Code Sharing", "TypeScript DTO"],
    ["https://turbo.build/repo/docs"],
    ["Chỉ biết copy-paste thủ công file types giữa 2 repository riêng biệt khi API thay đổi"]
  ),
  q("FS-FOUND-04", "Fullstack Developer", "foundation", "intermediate", "middle",
    "So sánh cơ chế xác thực Session-based (HttpOnly Cookie kết hợp Redis session store) và Token-based (Stateless JWT). Khi nào nên chọn Session và khi nào nên chọn JWT cho một sản phẩm Fullstack?",
    ["Session-based: lưu state trên server, thu hồi phiên (revoke) tức thời dễ dàng, tốn tài nguyên RAM server", "JWT: stateless, giảm tải truy vấn DB khi verify, khó thu hồi token trước khi hết hạn (cần blacklist)", "Đề xuất phù hợp: SaaS nội bộ/ngân hàng ưu tiên Session; Hệ thống đa nền tảng phân tán ưu tiên JWT kèm Refresh Token"],
    ["Làm thế nào để xử lý tính năng 'Đăng xuất khỏi tất cả các thiết bị' với cả 2 mô hình?", "Tại sao việc nhúng quá nhiều claims vào JWT có thể làm phình to HTTP header của mọi request?"],
    ["Authentication", "Session", "JWT", "Security Architecture"],
    [SRC.owasp],
    ["Nghĩ rằng JWT luôn hiện đại và tốt hơn Session trong mọi trường hợp mà không lường trước vấn đề revoke token"]
  ),
  q("FS-FOUND-05", "Fullstack Developer", "foundation", "intermediate", "middle",
    "Khi nào một ứng dụng Fullstack nên sử dụng WebSocket, khi nào nên dùng Server-Sent Events (SSE) và khi nào Long-Polling là đủ? Phân tích chi phí tài nguyên máy chủ và độ phức tạp triển khai của từng giao thức?",
    ["SSE: nhẹ, chạy trên HTTP chuẩn, tự động reconnect, một chiều server -> client, lý tưởng cho streaming AI / tin tức", "WebSocket: hai chiều toàn phần, giao thức riêng (ws/wss), giữ kết nối TCP mở, lý tưởng cho chat / game", "Long-polling: tốn tài nguyên nhất do overhead bắt tay HTTP liên tục, chỉ dùng làm fallback cho mạng cũ"],
    ["Làm thế nào để scale WebSocket qua nhiều server backend bằng Redis Pub/Sub adapter?", "Tại sao HTTP/2 multiplexing giúp SSE hiệu quả hơn trên trình duyệt?"],
    ["WebSocket", "SSE", "Long Polling", "Realtime Architecture"],
    ["https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events"],
    ["Dùng WebSocket cho mọi bài toán realtime đơn giản dù chỉ cần hiển thị thông báo một chiều"]
  ),
  q("FS-FOUND-06", "Fullstack Developer", "foundation", "basic", "junior",
    "Sự khác biệt giữa chuẩn hóa dữ liệu (Database Normalization - 3NF) và phi chuẩn hóa (Denormalization). Trong ứng dụng Web thực tế, khi nào em quyết định phi chuẩn hóa dữ liệu để tối ưu hóa hiệu năng đọc của giao diện?",
    ["3NF loại bỏ dư thừa dữ liệu, đảm bảo tính toàn vẹn khi ghi/sửa, nhưng yêu cầu nhiều JOIN khi truy vấn", "Denormalization lưu sẵn các trường tính toán (ví dụ: total_orders, author_name) để đọc nhanh trong 1 query", "Chi phí đánh đổi: phải quản lý đồng bộ dữ liệu khi cập nhật để tránh mâu thuẫn số liệu"],
    ["Kỹ thuật Materialized View trong PostgreSQL hỗ trợ bài toán denormalization như thế nào?", "Cơ sở dữ liệu Document NoSQL (MongoDB) áp dụng triết lý embedding vs referencing ra sao?"],
    ["Database Normalization", "Denormalization", "3NF", "Performance"],
    ["https://en.wikipedia.org/wiki/Database_normalization"],
    ["Phi chuẩn hóa dữ liệu tùy tiện mà không có cơ chế đảm bảo tính nhất quán khi cập nhật"]
  ),

  // Practical Skills (8)
  q("FS-SKILL-01", "Fullstack Developer", "practical_skills", "advanced", "senior_lead",
    "Làm thế nào để thiết lập kiến trúc End-to-End Type Safety giữa Frontend và Backend (sử dụng tRPC, Prisma hoặc OpenAPI TypeScript Codegen)? Lợi ích khi tự động hóa bắt lỗi type mismatch ngay lúc build time?",
    ["Tận dụng schema chia sẻ để tự động suy luận kiểu dữ liệu của API response mà không cần viết type thủ công ở client", "Tích hợp Zod validation ở backend và tự động suy ra TypeScript input type cho form ở frontend", "Giảm thiểu 100% lỗi runtime liên quan đến đổi tên trường hoặc sai kiểu dữ liệu giữa hai đầu"],
    ["tRPC khác gì với REST và GraphQL về độ linh hoạt và khả năng tích hợp mobile app?", "Khi API có phiên bản mobile độc lập, làm sao để duy trì type safety giữa nhiều nền tảng?"],
    ["tRPC", "Type Safety", "Prisma", "Zod", "Fullstack Architecture"],
    ["https://trpc.io/docs"],
    ["Vẫn duy trì 2 bộ interface tách rời ở frontend và backend rồi sửa thủ công bằng tay khi đổi API"]
  ),
  q("FS-SKILL-02", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Khi người dùng cần tải lên các tệp tin dung lượng lớn (video, file zip >1GB), em thiết kế giải pháp Direct Upload lên Cloud Storage (S3/Cloudflare R2) bằng Pre-signed URL như thế nào để không làm nghẽn máy chủ web?",
    ["Client gửi request metadata (tên file, dung lượng, mime) lên backend xin Pre-signed URL có thời hạn ngắn", "Backend xác thực quyền hạn và sinh Pre-signed PUT URL từ AWS SDK", "Client tải trực tiếp file lên S3 qua PUT request có thanh tiến trình (progress bar), sau đó gọi webhook báo hoàn tất"],
    ["Kỹ thuật S3 Multipart Upload được chia nhỏ như thế nào khi file quá lớn (>5GB) hoặc mạng chập chờn?", "Làm thế nào để quét mã độc hoặc virus trên file sau khi được tải trực tiếp lên S3?"],
    ["Pre-signed URL", "S3 Upload", "Cloud Architecture", "Multipart Upload"],
    ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html"],
    ["Tải toàn bộ file 1GB qua web server backend rồi server mới đẩy lên S3 làm nghẽn RAM và bandwidth server"]
  ),
  q("FS-SKILL-03", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Em xây dựng tính năng truyền phát câu trả lời dạng gõ chữ (Streaming Response) giống ChatGPT từ Backend (NestJS/Express/FastAPI) đến giao diện React bằng Server-Sent Events (SSE) như thế nào?",
    ["Cấu hình HTTP headers ở backend: `Content-Type: text/event-stream`, `Cache-Control: no-cache`, `Connection: keep-alive`", "Truyền dữ liệu dạng chunk qua Readable Stream và flush buffer tức thì", "Ở frontend dùng `fetch` với `ReadableStreamDefaultReader` để đọc từng chunk và cập nhật giao diện mượt mà"],
    ["Làm thế nào để xử lý ngắt kết nối (abort request) khi người dùng bấm nút 'Dừng sinh văn bản'?", "Cơ chế xử lý markdown streaming render mượt mà không bị vỡ thẻ cú pháp ở client ra sao?"],
    ["Streaming Response", "SSE", "ReadableStream", "Fullstack AI Integration"],
    [SRC.internal],
    ["Chờ toàn bộ nội dung sinh xong rồi mới trả về một JSON cục bộ làm người dùng phải chờ đợi lâu"]
  ),
  q("FS-SKILL-04", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Em quản lý biến môi trường (.env) và cấu hình ứng dụng đa môi trường (Local, Staging, Production) như thế nào? Cách xác thực tính toàn vẹn của biến môi trường lúc khởi động bằng Zod/Envalid?",
    ["Tạo schema validation cho process.env bằng Zod/Joi, crash ứng dụng ngay lúc khởi động nếu thiếu biến bắt buộc", "Tách biệt rõ ràng biến công khai ở client (NEXT_PUBLIC_) và biến bí mật chỉ chạy trên server (DATABASE_URL, SECRET_KEY)", "Sử dụng secret management an toàn trong CI/CD (GitHub Secrets) và Docker Compose cho môi trường phát triển"],
    ["Rủi ro lộ bí mật khi vô tình import file cấu hình server vào component client là gì?", "Làm thế nào để cấu hình Docker multi-stage build tối ưu kích thước image cho fullstack app?"],
    ["Environment Configuration", "Zod Validation", "Docker", "Secrets Management"],
    [SRC.internal],
    ["Hardcode thông tin bí mật trực tiếp vào code hoặc để lọt secret vào bundle client"]
  ),
  q("FS-SKILL-05", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Em thiết lập quy trình CI/CD tự động hóa cho dự án Fullstack bằng GitHub Actions như thế nào: từ khâu linting, type check, unit test, database migration đến triển khai không gián đoạn?",
    ["Thiết kế pipeline theo các stage rõ ràng: Lint & Test -> Build Docker Images -> Run DB Migration -> Deploy", "Chạy automated tests trên ephemeral environment (Testcontainers / Postgres service container)", "Triển khai chiến lược Blue/Green hoặc Rolling Update để đảm bảo zero-downtime khi release"],
    ["Làm thế nào để rollback tự động nếu health check endpoint trả về lỗi 500 sau khi deploy?", "Chiến lược caching node_modules và Docker layers để giảm thời gian chạy CI xuống dưới 5 phút?"] ,
    ["CI/CD", "GitHub Actions", "Docker", "Deployment Pipeline"],
    [SRC.internal],
    ["Deploy thủ công bằng cách SSH vào server rồi pull code và restart app bằng tay trên production"]
  ),
  q("FS-SKILL-06", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Xử lý tác vụ nền nặng (Background Jobs - ví dụ xuất file báo cáo Excel lớn hoặc gửi email hàng loạt) bằng hàng đợi BullMQ/Redis: Em thiết kế luồng xử lý và cập nhật tiến độ (Progress) lên UI thế nào?",
    ["Client gửi request tạo job, backend đẩy payload vào hàng đợi BullMQ và trả về ngay `jobId` kèm HTTP 202 Accepted", "Worker độc lập lấy job từ queue xử lý, định kỳ emit sự kiện `job.progress(percent)`", "Frontend lắng nghe tiến độ qua WebSocket hoặc polling endpoint `/api/jobs/:id` để hiển thị thanh tiến trình"],
    ["Cơ chế Dead Letter Queue và Auto-retry với Exponential Backoff của BullMQ hoạt động ra sao?", "Làm thế nào để dọn dẹp các job đã hoàn thành để tránh tràn RAM Redis?"],
    ["Background Jobs", "BullMQ", "Redis Queue", "Progress Tracking"],
    ["https://docs.bullmq.io/"],
    ["Xử lý tác vụ xuất báo cáo 10 phút trực tiếp trong luồng request-response HTTP thông thường gây timeout"]
  ),
  q("FS-SKILL-07", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Làm thế nào để tối ưu hóa SEO và chia sẻ mạng xã hội (Open Graph & Twitter Cards) cho các trang có dữ liệu động trong Next.js / Nuxt? Kỹ thuật sinh ảnh thumbnail động (Dynamic OG Image Generation) hoạt động ra sao?",
    ["Sử dụng hàm `generateMetadata` trong Next.js App Router để fetch dữ liệu server và chèn các thẻ meta title, description, og:image", "Áp dụng `@vercel/og` hoặc Satori để render JSX thành ảnh SVG/PNG động theo tên bài viết và tác giả", "Cấu hình robots.txt và sitemap.xml động tự động cập nhật theo các bài viết mới xuất bản"],
    ["Làm thế nào để cache các ảnh OG động tại CDN edge để không phải render lại mỗi lần bot quét?", "Sự khác biệt khi bot của Facebook/Twitter quét trang SSR so với trang CSR thuần?"],
    ["SEO", "Open Graph", "Next.js Metadata", "Dynamic Images"],
    [SRC.next],
    ["Để trang web ở dạng CSR thuần khiến bot mạng xã hội không thể đọc được tiêu đề và ảnh đại diện"]
  ),
  q("FS-SKILL-08", "Fullstack Developer", "practical_skills", "intermediate", "middle",
    "Chiến lược kiểm thử tự động End-to-End (E2E) cho ứng dụng Fullstack bằng Playwright: Em thiết lập môi trường test database độc lập, dữ liệu mẫu (Seeding) và kịch bản test luồng thanh toán ra sao?",
    ["Khởi tạo database test sạch sẽ cho mỗi lượt chạy kiểm thử bằng Docker container hoặc isolated schema", "Viết kịch bản Playwright giả lập hành vi người dùng thật từ đăng nhập, thêm giỏ hàng đến checkout", "Mock các dịch vụ thanh toán bên thứ ba để đảm bảo test chạy ổn định không phụ thuộc mạng ngoài"],
    ["Làm thế nào để chạy song song (Parallel execution) các bài test Playwright mà không xung đột dữ liệu?", "Xử lý kiểm thử các trạng thái bất đồng bộ (visual wait, network idle) trong Playwright thế nào?"] ,
    ["Playwright", "E2E Testing", "Database Seeding", "Test Automation"],
    ["https://playwright.dev/docs/intro"],
    ["Kiểm thử E2E trực tiếp trên database staging chứa dữ liệu chung làm hỏng dữ liệu của đồng nghiệp"]
  ),

  // Scenario (6)
  q("FS-SCEN-01", "Fullstack Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Người dùng báo lỗi họ vừa cập nhật thông tin hồ sơ thành công nhưng khi quay lại trang Dashboard vẫn thấy dữ liệu cũ, trong khi kiểm tra trực tiếp database thì dữ liệu đã được ghi nhận mới. Em khoanh vùng và giải quyết vấn đề cache không đồng bộ này ra sao?",
    ["Xác định các điểm lưu cache có thể gây lỗi: Browser cache, CDN cache, React Query client cache, hoặc Next.js Data Cache", "Phân tích nguyên nhân: Client chưa invalidate query key sau mutation hoặc Next.js server component chưa gọi `revalidatePath`/`revalidateTag`", "Giải pháp: Thực hiện tự động refetch hoặc cập nhật Optimistic UI ngay khi mutation thành công và cấu hình cache tag chuẩn"],
    ["Làm thế nào để kiểm tra header `X-Cache` từ Cloudflare để xem request có bị cache nhầm ở CDN không?", "Cơ chế stale-while-revalidate giải quyết bài toán hiển thị nhanh mà vẫn có dữ liệu mới như thế nào?"],
    ["Cache Invalidation", "Stale Data", "Data Synchronization", "Next.js Cache"],
    [SRC.internal],
    ["Bảo người dùng xóa cache trình duyệt mà không kiểm tra lại cơ chế cache invalidation của hệ thống"]
  ),
  q("FS-SCEN-02", "Fullstack Developer", "scenario", "intermediate", "middle",
    "Tình huống: Hệ thống tích hợp cổng thanh toán trực tuyến. Khách hàng đã bị trừ tiền trong tài khoản ngân hàng nhưng trên màn hình ứng dụng vẫn hiển thị 'Chờ thanh toán' do webhook từ cổng thanh toán gửi về server bị trễ 30 giây. Em thiết kế trải nghiệm người dùng và cơ chế kiểm tra trạng thái bù trừ ra sao?",
    ["Frontend hiển thị trạng thái 'Đang xác thực giao dịch' kèm thanh đếm thời gian và nút 'Kiểm tra trạng thái'", "Client chủ động gửi polling hoặc mở kết nối WebSocket hỏi thăm trạng thái đơn hàng định kỳ 5 giây", "Backend cung cấp endpoint cho phép chủ động gọi API truy vấn trạng thái (Query Transaction API) sang cổng thanh toán thay vì chỉ ngồi chờ webhook"],
    ["Làm thế nào để xử lý trường hợp cả webhook lẫn query API đều báo timeout?", "Cơ chế bảo vệ chống gian lận khi client tự ý thông báo giao dịch thành công là gì?"],
    ["Payment Gateway", "Webhook Latency", "Polling Fallback", "User Experience"],
    [SRC.internal],
    ["Chỉ biết hiển thị thông báo lỗi 'Thanh toán thất bại' ngay lập tức làm khách hàng hoang mang"]
  ),
  q("FS-SCEN-03", "Fullstack Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một botnet liên tục cào dữ liệu (scraping) từ trang sản phẩm làm CPU máy chủ backend tăng 100% và ảnh hưởng nghiêm trọng đến người dùng thật. Em triển khai các tầng phòng thủ từ CDN, Nginx đến Backend API như thế nào?",
    ["Tầng CDN (Cloudflare): bật WAF Bot Management, chặn các ASN đáng ngờ và kích hoạt Managed Challenge", "Tầng Nginx/Gateway: giới hạn tần suất request (Rate Limiting) theo IP và User-Agent", "Tầng Application: ẩn các trường nhạy cảm, áp dụng Obfuscation, honeypot links và yêu cầu xác thực JWT cho API nội bộ"],
    ["Làm thế nào để phân biệt bot có hại với các công cụ tìm kiếm hợp lệ (Googlebot, Bingbot)?", "Cloudflare Turnstile hỗ trợ xác thực người dùng thật mà không gây ức chế như CAPTCHA truyền thống ra sao?"],
    ["Anti-scraping", "Bot Protection", "WAF", "Rate Limiting"],
    [SRC.internal],
    ["Đề xuất bắt tất cả người dùng phải nhập mã CAPTCHA hình ảnh cho mỗi lần xem sản phẩm"]
  ),
  q("FS-SCEN-04", "Fullstack Developer", "scenario", "intermediate", "middle",
    "Tình huống: Ứng dụng quản lý dự án hỗ trợ người dùng chỉnh sửa offline khi mất mạng và tự động đồng bộ lên máy chủ khi có mạng trở lại. Khi hai người cùng chỉnh sửa một tài liệu cùng lúc ở chế độ offline, em xử lý xung đột dữ liệu (Conflict Resolution) như thế nào?",
    ["Lưu trữ dữ liệu ngoại tuyến tại Client bằng IndexedDB / RxDB", "Chiến lược giải quyết xung đột: Last-Write-Wins (dựa trên vector clock/timestamp) hoặc 3-Way Merge", "Với văn bản cộng tác chuyên sâu: áp dụng cấu trúc CRDTs (Conflict-free Replicated Data Types) như Yjs hoặc Automerge"],
    ["Sự khác biệt giữa Operational Transformation (OT) của Google Docs và CRDTs là gì?", "Làm thế nào để hiển thị giao diện thông báo xung đột trực quan cho người dùng tự chọn phiên bản giữ lại?"] ,
    ["Offline-first", "Conflict Resolution", "CRDTs", "IndexedDB"],
    [SRC.internal],
    ["Ghi đè hoàn toàn dữ liệu mới nhất lên dữ liệu cũ làm mất sạch công sức chỉnh sửa của người dùng trước"]
  ),
  q("FS-SCEN-05", "Fullstack Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Trong quá trình triển khai phiên bản mới, quá trình migration cơ sở dữ liệu bị lỗi cú pháp ở bước thứ hai khiến một nửa bảng đã thay đổi còn một nửa chưa. Đội ngũ cần rollback về phiên bản cũ ngay lập tức. Các bước xử lý của em là gì?",
    ["Kích hoạt kịch bản Rollback trong transaction an toàn nếu migration tool hỗ trợ transactional DDL (PostgreSQL)", "Khôi phục phiên bản code trước đó (Revert commit / Redeploy previous Docker tag)", "Nếu bảng đã bị thay đổi không thể rollback tự động: chạy kịch bản Down Migration thủ công đã được kiểm thử trước trên staging"],
    ["Tại sao mọi script migration trước khi lên production đều bắt buộc phải có script 'Down' tương ứng?", "Chiến lược kiểm tra tính toàn vẹn dữ liệu (Data Integrity Check) sau sự cố rollback là gì?"],
    ["Rollback Strategy", "Database Migration Failure", "Disaster Recovery", "Deployment Incident"],
    [SRC.internal],
    ["Hoảng loạn xóa database hoặc chạy các câu lệnh sửa cấu trúc ngẫu hứng trực tiếp trên production"]
  ),
  q("FS-SCEN-06", "Fullstack Developer", "scenario", "intermediate", "middle",
    "Tình huống: Ứng dụng phần mềm dạng dịch vụ (SaaS) chuyển đổi sang mô hình Đa người thuê (Multi-Tenancy). Em lựa chọn kiến trúc lưu trữ dữ liệu nào (Database per Tenant, Schema per Tenant, hay Shared Database với Tenant ID) và cách định tuyến subdomain ở Frontend?",
    ["Phân tích mô hình: Shared DB với Tenant ID (tiết kiệm chi phí, dễ bảo trì, cần Row-Level Security nghiêm ngặt)", "Schema per Tenant: cô lập tốt hơn, phù hợp khách hàng vừa và nhỏ; Database per Tenant: bảo mật tối đa cho khách hàng lớn", "Frontend định tuyến động: đọc subdomain từ hostname (vd: tenant.app.com) trong middleware và gán tenant context xuyên suốt các API call"],
    ["Làm thế nào để áp dụng Row Level Security (RLS) của PostgreSQL để ngăn chặn rò rỉ dữ liệu giữa các tenant?", "Cách quản lý dynamic SSL certificate cho các custom domain của khách hàng?"],
    ["Multi-tenancy", "Row Level Security", "SaaS Architecture", "Subdomain Routing"],
    [SRC.internal],
    ["Chỉ lọc dữ liệu tenant ở tầng frontend bằng JavaScript mà không cô lập ở tầng cơ sở dữ liệu"]
  ),

  // CV Validation (5)
  q("FS-CV-01", "Fullstack Developer", "cv_validation", "advanced", "senior_lead",
    "Trong dự án Fullstack toàn diện nhất trên CV, em đã trực tiếp xây dựng những phần nào từ Frontend đến Backend? Đâu là quyết định kiến trúc quan trọng nhất mà em đã đưa ra và kết quả thực tế ra sao?",
    ["Mô tả rõ ràng vai trò cá nhân trên toàn bộ ngăn xếp công nghệ (Frontend framework, Backend runtime, Database, Hosting)", "Trình bày lý do lựa chọn công nghệ và trade-offs liên quan (ví dụ: chọn monolithic hay chia tách)", "Dẫn chứng kết quả cụ thể: thời gian hoàn thành tính năng, hiệu năng trang web, số lượng người dùng thực tế"],
    ["Nếu có cơ hội làm lại dự án đó từ đầu với ngân sách gấp đôi, em sẽ thay đổi thành phần nào?", "Bài học kỹ thuật sâu sắc nhất mà em đúc kết được từ dự án đó là gì?"],
    ["Fullstack Architecture", "System Design", "Technical Decision", "CV Deep Dive"],
    [SRC.internal],
    ["Chỉ làm phần giao diện hoặc chỉ viết vài API đơn giản nhưng ghi nhận là làm toàn bộ dự án"]
  ),
  q("FS-CV-02", "Fullstack Developer", "cv_validation", "intermediate", "middle",
    "Em có ghi kinh nghiệm triển khai CI/CD và Cloud trên CV. Hãy mô tả chi tiết quy trình release một tính năng từ lúc merge Pull Request đến khi chạy thực tế trên production trong dự án đó?",
    ["Mô tả các bước tự động trong pipeline: testing, linting, build container, migrate DB, deploy", "Môi trường hosting thực tế: AWS ECS, Kubernetes, Vercel, VPS Linux, Docker Compose", "Cách quản lý rollback và theo dõi trạng thái hệ thống sau khi release"],
    ["Thời gian trung bình của pipeline từ lúc merge đến khi hoàn tất là bao lâu?", "Em đã từng xử lý sự cố nào khi pipeline release bị fail giữa chừng chưa?"],
    ["CI/CD Pipeline", "Cloud Deployment", "DevOps for Fullstack", "CV Verification"],
    [SRC.internal],
    ["Ghi thạo CI/CD trên CV nhưng không nắm được các bước chạy trong workflow file"]
  ),
  q("FS-CV-03", "Fullstack Developer", "cv_validation", "intermediate", "middle",
    "Trong dự án Fullstack có xử lý thanh toán hoặc giao dịch tài chính trên CV, em đã thiết kế luồng bảo mật chống tấn công giả mạo yêu cầu (CSRF), giả mạo dữ liệu giá tiền và rò rỉ API keys như thế nào?",
    ["Đảm bảo mọi logic tính giá, mã giảm giá đều thực hiện độc quyền ở Backend, không tin tưởng client", "Bảo vệ CSRF bằng SameSite Cookies hoặc CSRF Token cho các phương thức POST/PUT", "Lưu trữ khóa bí mật API trong biến môi trường máy chủ an toàn, không để lọt vào bundle client"],
    ["Làm thế nào để xác minh chữ ký điện tử (Signature Verification) của các gói tin webhook từ đối tác thanh toán?", "Cách ngăn chặn việc replay request đối với các giao dịch tài chính?"],
    ["Payment Security", "CSRF Prevention", "Secure Design", "CV Verification"],
    [SRC.owasp, SRC.internal],
    ["Cho phép client gửi trực tiếp số tiền cần thanh toán lên server mà không kiểm tra lại trong database"]
  ),
  q("FS-CV-04", "Fullstack Developer", "cv_validation", "advanced", "senior_lead",
    "Em hãy kể về một tình huống mà em phải tự mình giải quyết một vấn đề kỹ thuật phức tạp nằm ở ranh giới giữa Frontend và Backend (ví dụ: memory leak, WebSocket disconnect hàng loạt, hoặc CORS kỳ lạ)?",
    ["Mô tả cụ thể triệu chứng lỗi và cách tư duy đa tầng để xác định lỗi thuộc về tầng nào", "Quy trình sử dụng công cụ điều tra: Network tab, server logs, Wireshark, debugger", "Giải pháp triệt để và bài học phòng ngừa cho đội ngũ"],
    ["Tại sao việc hiểu cả hai đầu Frontend và Backend giúp em giải quyết vấn đề nhanh hơn các bạn chỉ chuyên một mảng?", "Em đã chia sẻ giải pháp này cho nhóm bằng cách nào?"],
    ["Cross-stack Debugging", "Problem Solving", "Troubleshooting", "CV Verification"],
    [SRC.internal],
    ["Đổ lỗi qua lại giữa frontend và backend thay vì tự mình tìm hiểu nguyên nhân gốc rễ"]
  ),
  q("FS-CV-05", "Fullstack Developer", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kỹ năng thiết kế cơ sở dữ liệu quan hệ. Em hãy vẽ lại mô hình thực thể (ERD) của phân hệ phức tạp nhất mà em từng thiết kế, giải thích cách đánh index và quan hệ giữa các bảng?",
    ["Trình bày các thực thể chính, khóa chính (PK), khóa ngoại (FK) và mối quan hệ (1-N, N-N)", "Giải thích chiến lược đánh index (Single vs Composite) phục vụ các câu truy vấn phổ biến nhất", "Xử lý xóa mềm (Soft Delete) và ảnh hưởng của nó đến Unique Constraint"],
    ["Làm thế nào để thiết kế bảng lịch sử thay đổi (Audit Log) cho các bảng dữ liệu trọng yếu?", "Tại sao việc dùng UUID làm khóa chính có thể ảnh hưởng đến hiệu năng ghi của B-Tree index so với Auto-increment ID?"],
    ["Database Modeling", "ERD", "Index Strategy", "CV Verification"],
    [SRC.internal],
    ["Không nhớ cấu trúc các bảng chính hoặc thiết kế quan hệ thiếu chuẩn hóa cơ bản"]
  ),

  // Behavioral (5)
  q("FS-BEHAV-01", "Fullstack Developer", "behavioral", "intermediate", "middle",
    "Là một Fullstack Developer, khi đứng trước áp lực vừa phải hoàn thành giao diện bóng bẩy vừa phải tối ưu hệ thống backend vững chắc trong một sprint ngắn, em phân bổ thời gian và ưu tiên công việc ra sao?",
    ["Xác định rõ ràng phần lõi (Core Business Value) và thỏa thuận phạm vi MVP trước", "Ưu tiên thiết kế API và luồng dữ liệu chuẩn chỉ trước để đảm bảo tính đúng đắn và an toàn", "Phần giao diện tập trung vào tính hữu dụng và trải nghiệm luồng chính, tinh chỉnh hiệu ứng thẩm mỹ sau"],
    ["Khi nhận thấy khối lượng công việc vượt quá thời gian của sprint, em báo cáo và đàm phán với ai?", "Làm thế nào để tránh việc trở thành 'Fullstack nhưng cái gì cũng làm nửa vời'?"],
    ["Time Management", "Prioritization", "Fullstack Mindset", "Agile Sprint"],
    [SRC.internal],
    ["Chỉ tập trung làm giao diện đẹp mắt mà bỏ qua việc xử lý lỗi và bảo mật backend"]
  ),
  q("FS-BEHAV-02", "Fullstack Developer", "behavioral", "intermediate", "middle",
    "Khi Product Manager yêu cầu một tính năng đòi hỏi logic tính toán rất phức tạp nhưng thời gian phản hồi API yêu cầu dưới 100ms, em giải thích các đánh đổi kỹ thuật (Trade-offs) và tư vấn phương án khả thi thế nào?",
    ["Giải thích dễ hiểu bằng thuật ngữ kinh doanh: sự đánh đổi giữa thời gian thực (Realtime) và chi phí tài nguyên phần cứng", "Đề xuất các phương án kỹ thuật thay thế: xử lý bất đồng bộ (Async job với tiến trình thông báo), tính toán sẵn (Pre-computation), hoặc Caching", "Cùng PM cân nhắc xem người dùng có thực sự cần kết quả tức thời trong 100ms hay chấp nhận chờ 2 giây"],
    ["Em làm gì khi PM vẫn khăng khăng muốn cả hai mà không chịu tăng tài nguyên server?", "Cách ghi lại biên bản thống nhất kỹ thuật để tránh tranh cãi sau này?"],
    ["Stakeholder Communication", "Trade-off Analysis", "Technical Advisory", "Product Management"],
    [SRC.internal],
    ["Đồng ý bừa với yêu cầu bất khả thi rồi trễ hạn release hoặc hệ thống bị sập khi chạy thật"]
  ),
  q("FS-BEHAV-03", "Fullstack Developer", "behavioral", "intermediate", "middle",
    "Khi làm việc trong nhóm có các bạn chuyên sâu Frontend hoặc Backend riêng biệt, em tận dụng lợi thế hiểu biết toàn diện của mình để hỗ trợ và gắn kết hai đầu dự án như thế nào?",
    ["Đóng vai trò cầu nối: giúp Frontend hiểu các ràng buộc của cơ sở dữ liệu và giúp Backend hiểu nhu cầu hiển thị của UI", "Chủ động đề xuất các tiêu chuẩn chung (API Contract, error response format, type sharing)", "Hỗ trợ gỡ lỗi nhanh cho đồng nghiệp khi vấn đề phát sinh ở ranh giới giữa hai bên"],
    ["Làm sao để chia sẻ kiến thức mà không tạo cảm giác dạy đời đồng nghiệp chuyên sâu?", "Em tổ chức các buổi trao đổi kỹ thuật (Tech Sharing) trong nhóm như thế nào?"],
    ["Team Bridge", "Cross-functional Collaboration", "Empathy", "Team Player"],
    [SRC.internal],
    ["Xem thường các bạn chỉ làm một mảng hoặc tự cô lập công việc của mình"]
  ),
  q("FS-BEHAV-04", "Fullstack Developer", "behavioral", "intermediate", "middle",
    "Khi tiếp nhận một dự án Fullstack kế thừa (Legacy Codebase) có code lộn xộn, thiếu tài liệu và không có automated test, kế hoạch tiếp cận và cải tiến từng bước của em là gì?",
    ["Không vội vàng đập đi xây lại (Rewrite) toàn bộ vì tiềm ẩn rủi ro kinh doanh cực lớn", "Đọc hiểu luồng nghiệp vụ cốt lõi, viết bổ sung Integration Test bao bọc (Characterization Tests) để tạo lưới an toàn", "Tái cấu trúc từng phần nhỏ (Refactoring) theo Boy Scout Rule (luôn để lại code sạch hơn lúc nhận)"],
    ["Làm thế nào để thuyết phục ban quản lý cấp thời gian (Tech Debt budget) cho việc cải tiến code cũ?", "Cách cân bằng giữa việc sửa code cũ và làm tính năng mới của sprint?"],
    ["Legacy Code", "Refactoring Strategy", "Technical Debt", "Patience"],
    [SRC.internal],
    ["Đòi đập đi viết lại toàn bộ dự án từ đầu mà không lường trước chi phí và rủi ro"]
  ),
  q("FS-BEHAV-05", "Fullstack Developer", "behavioral", "advanced", "senior_lead",
    "Lĩnh vực Fullstack biến đổi công nghệ rất nhanh chóng (frameworks mới, serverless, AI tooling). Em duy trì thói quen tự học và chọn lọc công nghệ nào đáng đầu tư lâu dài cho sự nghiệp của mình?",
    ["Tập trung sâu vào các nguyên lý nền tảng bền vững: Giao thức mạng, cấu trúc dữ liệu, kiến trúc hệ thống, bảo mật", "Thử nghiệm công nghệ mới thông qua các dự án cá nhân (Pet projects) trước khi áp dụng vào công việc chính thức", "Tham gia cộng đồng mã nguồn mở, đọc tài liệu kỹ thuật chính thức và rèn luyện tư duy phản biện trước các xu hướng 'hype'"],
    ["Em đánh giá thế nào về sự hỗ trợ của các công cụ AI (GitHub Copilot, Cursor) đối với vai trò Fullstack Developer hiện nay?", "Kỹ năng nào của kỹ sư phần mềm mà AI không thể thay thế được?"],
    ["Continuous Learning", "Technology Evaluation", "Career Growth", "Engineering Mindset"],
    [SRC.internal],
    ["Bảo thủ từ chối học công nghệ mới hoặc ngược lại chạy theo mọi xu hướng nhất thời không có chiều sâu"]
  )
];

console.log("FS questions defined:", fsQuestions.length);
module.exports = { fsQuestions };
