const { q, SRC } = require('./fe_data.cjs');

const mobQuestions = [
  // Foundation (6)
  q("MOB-FOUND-01", "Mobile Developer (iOS/Android/Flutter)", "foundation", "basic", "junior",
    "Trình bày chi tiết vòng đời ứng dụng di động (Application Lifecycle) trên iOS (Active, Inactive, Background, Suspended) và Android (Activity/Fragment lifecycle). Các tác vụ dọn dẹp tài nguyên hoặc lưu trạng thái nên được gọi ở giai đoạn nào?",
    ["Trình bày đủ các trạng thái vòng đời trên cả iOS (UIApplicationDelegate / SceneDelegate) và Android (onCreate, onStart, onResume, onPause, onStop, onDestroy)", "Giải thích thời điểm hệ điều hành có thể hủy (kill) ứng dụng để giải phóng bộ nhớ khi ở background", "Xử lý lưu state tạm (SavedInstanceState hoặc StateRestoration) để khôi phục khi người dùng mở lại app"],
    ["Khi nào hệ thống gửi cảnh báo Low Memory Warning và app cần phản ứng ra sao?", "Background execution limit trên Android 14+ và iOS 17+ ràng buộc những gì?"],
    ["Mobile Lifecycle", "iOS", "Android", "State Restoration"],
    [SRC.apple, SRC.android],
    ["Cho rằng ứng dụng chạy ở background sẽ được duy trì vĩnh viễn và không bao giờ bị hệ thống kill"]
  ),
  q("MOB-FOUND-02", "Mobile Developer (iOS/Android/Flutter)", "foundation", "intermediate", "middle",
    "Cơ chế quản lý bộ nhớ của thiết bị di động: Phân biệt Automatic Reference Counting (ARC) trên iOS/Swift với Garbage Collection (GC) trên Android/Kotlin và Dart/Flutter. Hiện tượng Retain Cycle / Memory Leak xảy ra như thế nào?",
    ["ARC: đếm tham chiếu lúc compile time, tự giải phóng khi count = 0; GC: chạy định kỳ lúc runtime để quét object graph", "Retain cycle: hai đối tượng giữ strong reference chéo nhau khiến bộ nhớ không thể giải phóng", "Khắc phục: dùng `weak` và `unowned` references trong Swift, weak references trong Kotlin/Java"],
    ["Công cụ Xcode Memory Graph và Android Profiler hỗ trợ truy vết leak memory ra sao?", "Trong Flutter, tại sao việc quên dispose Controller hoặc StreamSubscription gây rò rỉ bộ nhớ?"],
    ["ARC", "Garbage Collection", "Memory Leak", "Retain Cycle"],
    [SRC.apple, SRC.android, SRC.flutter],
    ["Nhầm lẫn giữa ARC (compile-time) và Tracing Garbage Collection (runtime)"]
  ),
  q("MOB-FOUND-03", "Mobile Developer (iOS/Android/Flutter)", "foundation", "intermediate", "middle",
    "Kiến trúc dựng hình của Flutter (Skia / Impeller) khác với kiến trúc của Native Android (Views/Jetpack Compose) và Native iOS (UIKit/SwiftUI) như thế nào? Tại sao Flutter có thể đạt hiệu năng 60fps/120fps ổn định?",
    ["Flutter tự vẽ mọi pixel lên Canvas bằng engine đồ họa riêng (Impeller/Skia) không qua OEM native widgets", "Cơ chế 3 cây trong Flutter: Widget Tree (cấu hình), Element Tree (vòng đời), RenderObject Tree (tính toán layout & paint)", "SwiftUI và Jetpack Compose sử dụng declarative UI nhưng biên dịch trực tiếp sang các thành phần native của hệ điều hành"],
    ["Impeller giải quyết triệt để vấn đề Shader Compilation Jank trên iOS như thế nào?", "Khi nào Native UI vẫn có ưu thế vượt trội hơn Flutter?"],
    ["Flutter Engine", "Impeller", "Rendering Pipeline", "Jetpack Compose", "SwiftUI"],
    [SRC.flutter],
    ["Nghĩ rằng Flutter biên dịch các widget thành native Android Views và iOS UIViews"]
  ),
  q("MOB-FOUND-04", "Mobile Developer (iOS/Android/Flutter)", "foundation", "intermediate", "middle",
    "Nguyên lý hoạt động của Push Notification từ xa (Remote Push Notification): Luồng gửi nhận tin nhắn từ Server qua APNs (Apple) và FCM (Firebase/Google) đến thiết bị diễn ra như thế nào? Cách xử lý token thay đổi?",
    ["Quy trình: App xin quyền -> nhận Device Token từ APNs/FCM -> gửi Token lên Backend -> Backend gửi message qua FCM/APNs -> OS nhận và hiển thị", "Phân biệt Notification Message (OS tự hiển thị) và Data-only / Silent Notification (đánh thức app chạy ngầm)", "Xử lý refresh token khi người dùng đổi thiết bị, cài lại app hoặc token hết hạn"],
    ["Cách xử lý điều hướng Deep Link khi người dùng bấm vào Push Notification từ trạng thái app đang bị đóng (Cold Start)?", "Làm thế nào để mã hóa nội dung nhạy cảm của Push Notification bằng Notification Service Extension trên iOS?"],
    ["Push Notification", "APNs", "FCM", "Deep Link"],
    ["https://firebase.google.com/docs/cloud-messaging"],
    ["Nghĩ rằng thiết bị duy trì kết nối socket trực tiếp liên tục với máy chủ của công ty để nhận thông báo"]
  ),
  q("MOB-FOUND-05", "Mobile Developer (iOS/Android/Flutter)", "foundation", "intermediate", "middle",
    "Kiến trúc Offline-First cho ứng dụng di động: Lựa chọn cơ sở dữ liệu cục bộ (SQLite/Room, Realm, Isar, CoreData) và chiến lược đồng bộ hóa 2 chiều (Bidirectional Sync) với server?",
    ["So sánh SQLite/Room/CoreData (chuẩn quan hệ, ACID vững chắc) với NoSQL nhúng (Hive, Realm, Isar - tốc độ đọc ghi cực nhanh)", "Thiết kế hàng đợi đồng bộ (Sync Queue / Outbox Pattern) lưu các hành động offline", "Chiến lược gán timestamp, Version Vector hoặc Change Tracking để phát hiện xung đột dữ liệu"],
    ["Làm thế nào để mã hóa cơ sở dữ liệu trên thiết bị bằng SQLCipher?", "Cách xử lý đồng bộ ảnh hoặc tệp đính kèm khi mạng chập chờn?"],
    ["Offline-first", "SQLite", "Room", "CoreData", "Data Sync"],
    [SRC.internal],
    ["Lưu dữ liệu cấu trúc lớn vào SharedPreferences hoặc UserDefaults gây chậm ứng dụng"]
  ),
  q("MOB-FOUND-06", "Mobile Developer (iOS/Android/Flutter)", "foundation", "basic", "junior",
    "Bảo mật ứng dụng di động: Tại sao không được lưu trữ API keys hoặc mật khẩu người dùng dưới dạng văn bản thuần trong app? Cơ chế an toàn của iOS Keychain và Android Keystore/EncryptedSharedPreferences hoạt động ra sao?",
    ["Thiết bị đã root hoặc jailbreak có thể trích xuất toàn bộ dữ liệu lưu trong file phẳng hoặc SharedPreferences", "iOS Keychain và Android Keystore sử dụng phần cứng chuyên dụng (Secure Enclave / TEE) để mã hóa dữ liệu nhạy cảm", "Không hardcode Private Keys hoặc Client Secret trong mã nguồn vì dễ bị dịch ngược (Reverse Engineering) bằng decompiler"],
    ["SSL Pinning (Certificate Pinning) bảo vệ ứng dụng chống tấn công Man-in-the-Middle (MitM) ra sao?", "Rủi ro khi chứng chỉ SSL của server hết hạn nếu đã bật SSL Pinning cứng trong app?"] ,
    ["Mobile Security", "Keychain", "Keystore", "SSL Pinning"],
    [SRC.owasp],
    ["Lưu mật khẩu người dùng hoặc token xác thực vào UserDefaults/SharedPreferences"]
  ),

  // Practical Skills (8)
  q("MOB-SKILL-01", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "intermediate", "middle",
    "Em quản lý State Management trong Flutter (Bloc, Riverpod, Provider) hoặc Native (ViewModel, StateFlow, Redux) như thế nào? Tiêu chí nào giúp em quyết định phạm vi của Local State vs Global State?",
    ["Phân tách rõ ràng: UI State ngắn hạn (animation, form input) giữ ở phạm vi cục bộ của widget/view", "App State dài hạn (User session, cart, cached data) quản lý qua Bloc/Riverpod/ViewModel có tính testable cao", "Đảm bảo tính đơn hướng của luồng dữ liệu (Unidirectional Data Flow) và dễ dàng viết Unit Test"],
    ["Bloc Pattern khác với Riverpod thế nào về độ dốc học tập và boilerplate code?", "Làm thế nào để tránh việc cập nhật state toàn cục làm rebuild lại toàn bộ cây Widget?"],
    ["State Management", "Bloc", "Riverpod", "ViewModel", "Unidirectional Data Flow"],
    [SRC.flutter],
    ["Đẩy mọi biến tạm thời của giao diện vào global state store làm phình to bộ nhớ và khó bảo trì"]
  ),
  q("MOB-SKILL-02", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "advanced", "senior_lead",
    "Làm thế nào để tối ưu hóa hiệu năng cuộn danh sách (ListView / RecyclerView / LazyColumn) chứa hàng nghìn phần tử có hình ảnh và nội dung phức tạp để giữ vững tốc độ 60fps/120fps không bị giật khung hình (Jank)?",
    ["Tái sử dụng view/cell thông qua cơ chế ViewHolder / Recycle Pool, tránh khởi tạo view mới khi cuộn", "Nén và giải mã ảnh bất đồng bộ (Image Downsampling) đúng kích thước hiển thị bằng Glide/Coil/CachedNetworkImage", "Tránh thực hiện các phép tính toán phức tạp hoặc thao tác I/O trong hàm bind/build của từng item"],
    ["Kỹ thuật Prefetching dữ liệu trước khi người dùng cuộn tới hoạt động ra sao?", "Làm thế nào để đo lường tỷ lệ rớt khung hình (Dropped Frames) bằng Android GPU Profiler hoặc Flutter DevTools?"] ,
    ["ListView Optimization", "RecyclerView", "Image Caching", "Jank Reduction"],
    [SRC.android, SRC.flutter],
    ["Tải ảnh kích thước gốc 4K về hiển thị trực tiếp trong danh sách item nhỏ mà không resize"]
  ),
  q("MOB-SKILL-03", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "intermediate", "middle",
    "Em xây dựng và bảo trì cầu nối giao tiếp (Platform Channel / MethodChannel trong Flutter hoặc Native Bridge) giữa mã nguồn đa nền tảng và mã nguồn Native (Swift/Kotlin) như thế nào?",
    ["Hiểu cơ chế truyền thông điệp bất đồng bộ (BinaryMessenger) tuần tự hóa dữ liệu giữa Dart và Host platform", "Viết mã nguồn Swift/Kotlin xử lý các tính năng phần cứng đặc thù (Bluetooth BLE, Camera chuyên sâu, Sensors)", "Bắt lỗi và xử lý ngoại lệ (PlatformException) chặt chẽ khi native code trả về lỗi"],
    ["EventChannel khác gì với MethodChannel khi cần truyền luồng dữ liệu liên tục (streaming data)?", "Pigeon code generator hỗ trợ Type-safe Platform Channel trong Flutter như thế nào?"],
    ["Platform Channel", "Native Bridge", "Swift", "Kotlin", "MethodChannel"],
    [SRC.flutter],
    ["Chỉ biết dùng các thư viện có sẵn trên pub.dev mà không biết viết code native khi thư viện bị lỗi"]
  ),
  q("MOB-SKILL-04", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "intermediate", "middle",
    "Chiến lược giảm dung lượng tệp cài đặt (APK, AAB, IPA) của ứng dụng di động: Em sử dụng những phương pháp và công cụ nào để giảm tải tài nguyên?",
    ["Chuyển sang định dạng Android App Bundle (AAB) để Google Play tự tối ưu theo cấu hình thiết bị người dùng", "Kích hoạt R8 / ProGuard trên Android để thu nhỏ mã nguồn (shrinking), làm mờ (obfuscation) và tối ưu hóa", "Chuyển đổi tài nguyên ảnh PNG/JPG sang định dạng Vector Drawable, SVG hoặc WebP, loại bỏ font không dùng"],
    ["Cấu hình App Thinning (App Slicing, On-Demand Resources) trên iOS hoạt động ra sao?", "Làm thế nào để phân tích thành phần kích thước ứng dụng bằng công cụ APK Analyzer trong Android Studio?"] ,
    ["App Size Optimization", "AAB", "R8 ProGuard", "App Thinning"],
    [SRC.android, SRC.apple],
    ["Để nguyên các file media âm thanh, video chất lượng cao chưa nén trong thư mục assets của app"]
  ),
  q("MOB-SKILL-05", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "intermediate", "middle",
    "Em xử lý điều hướng màn hình nâng cao (Deep Linking & Universal Links trên iOS / App Links trên Android) như thế nào? Cách cấu hình tệp xác thực domain (assetlinks.json và apple-app-site-association)?",
    ["Hiểu sự khác biệt giữa Custom URL Scheme (dễ xung đột) và Universal/App Links (bảo mật, gắn liền với domain HTTPS)", "Cấu hình tệp `apple-app-site-association` trên máy chủ web không có đuôi .json và `assetlinks.json` có mã SHA-256", "Điều hướng ứng dụng mượt mà đến đúng màn hình đích (Deferred Deep Linking) kể cả khi người dùng chưa cài app trước đó"],
    ["Deferred Deep Linking hoạt động ra sao khi phải qua khâu tải app từ App Store / Google Play?", "Làm thế nào để xử lý state điều hướng ngăn nắp với AutoRoute hoặc GoRouter trong Flutter?"],
    ["Deep Linking", "Universal Links", "App Links", "GoRouter"],
    [SRC.apple, SRC.android],
    ["Chỉ cấu hình URL Scheme đơn giản mà không nắm được cơ chế Universal Links chuẩn bảo mật"]
  ),
  q("MOB-SKILL-06", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "intermediate", "middle",
    "Em xây dựng quy trình tự động hóa kiểm thử và phát hành ứng dụng (CI/CD Mobile) bằng Fastlane kết hợp GitHub Actions như thế nào: từ quản lý chứng chỉ (Certificates & Provisioning Profiles) đến đẩy bản build lên TestFlight / Google Play Internal Track?",
    ["Sử dụng `fastlane match` để quản lý tập trung và mã hóa chứng chỉ iOS trong private git repository", "Tự động tăng số build (build number), ký số (code signing) và chạy automated tests trên CI", "Tự động tải bản build lên TestFlight và Firebase App Distribution kèm ghi chú phát hành (release notes)"],
    ["Làm thế nào để quản lý Keystore của Android an toàn trong môi trường CI mà không lộ mật khẩu?", "Sự khác biệt giữa Development, Ad-Hoc và App Store Provisioning Profiles trên iOS?"],
    ["Fastlane", "CI/CD Mobile", "Code Signing", "TestFlight", "Match"],
    ["https://docs.fastlane.tools/"],
    ["Ký app và xuất file cài đặt thủ công bằng tay trên máy tính cá nhân cho mỗi bản release"]
  ),
  q("MOB-SKILL-07", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "intermediate", "middle",
    "Chiến lược kiểm thử tự động cho Mobile: Em tổ chức Unit Test, Widget/Component Test và Integration/E2E Test như thế nào? Công cụ mock API và kiểm thử giao diện tự động trên thiết bị thật (Firebase Test Lab)?",
    ["Unit test cho tầng Business Logic (UseCases, Repositories, BLoCs/ViewModels) với Mocktail/Mockito", "Widget Test kiểm tra tương tác hiển thị và hành vi bấm nút cô lập không cần khởi động emulator", "Integration Test (Maestro, Patrol, Appium) kiểm tra luồng xuyên suốt và chạy trên đám mây thiết bị thật"],
    ["Golden Toolkit / Screenshot Testing giúp phát hiện lỗi sai lệch giao diện (Visual Regression) ra sao?", "Làm thế nào để cô lập hoàn toàn mạng ngoài trong quá trình chạy mobile automated tests?"] ,
    ["Mobile Testing", "Widget Test", "Maestro", "Patrol", "Mocking"],
    [SRC.flutter],
    ["Không viết bất kỳ bài kiểm thử tự động nào, chỉ kiểm thử thủ công bằng mắt trên một máy duy nhất"]
  ),
  q("MOB-SKILL-08", "Mobile Developer (iOS/Android/Flutter)", "practical_skills", "advanced", "senior_lead",
    "Quản lý mức tiêu thụ pin và tài nguyên mạng trên thiết bị di động: Em thiết kế cơ chế tiết kiệm pin (Battery Optimization) khi ứng dụng cần theo dõi vị trí GPS ngầm hoặc đồng bộ dữ liệu định kỳ như thế nào?",
    ["Sử dụng Geofencing hoặc thay đổi tần suất lấy mẫu vị trí (Accuracy vs Power trade-off) thay vì liên tục bật GPS độ chính xác cao", "Gộp các request mạng thành từng mẻ (Request Batching) để tránh việc đánh thức chip sóng vô tuyến (Radio State) liên tục", "Tận dụng WorkManager trên Android và BackgroundTasks framework trên iOS với các ràng buộc về sạc pin và kết nối Wi-Fi"],
    ["Cơ chế Doze Mode trên Android ảnh hưởng như thế nào đến tác vụ chạy ngầm?", "Làm thế nào để đo lường mức độ tiêu thụ năng lượng bằng Energy Log trong Xcode Instruments?"] ,
    ["Battery Optimization", "GPS Tracking", "WorkManager", "Background Processing"],
    [SRC.android, SRC.apple],
    ["Bật GPS độ chính xác cao chạy liên tục ở background khiến điện thoại người dùng bị nóng và cạn pin nhanh"]
  ),

  // Scenario (6)
  q("MOB-SCEN-01", "Mobile Developer (iOS/Android/Flutter)", "scenario", "advanced", "senior_lead",
    "Tình huống: Bản cập nhật mới phát hành lên App Store/Google Play bị crash hàng loạt với tỷ lệ 15% ngay khi người dùng khởi động ứng dụng (Crash on launch / Crash Loop). Em kích hoạt quy trình ứng phó khẩn cấp và xử lý sự cố thế nào?",
    ["Tạm dừng ngay lập tức việc phát hành từng giai đoạn (Halt Phased Release / Staged Rollout) trên Play Console và App Store Connect", "Thu thập stack trace từ Firebase Crashlytics hoặc Sentry để xác định lỗi thuộc về dòng code nào và phiên bản OS nào bị ảnh hưởng", "Xây dựng bản sửa lỗi khẩn cấp (Hotfix), yêu cầu duyệt ưu tiên (Expedited Review) từ Apple/Google và cân nhắc cơ chế Remote Config fallback"],
    ["Làm thế nào để ứng dụng tự phát hiện Crash Loop và tự xóa dữ liệu tạm lưu (Clear local corrupted cache) khi khởi động lại?", "Tại sao không nên dựa vào bản cập nhật ứng dụng nếu có thể dùng cờ tính năng (Feature Flag) tắt từ xa?"],
    ["Crash on Launch", "Emergency Response", "Crashlytics", "Hotfix Rollout"],
    [SRC.internal],
    ["Hoảng loạn không biết cách dừng rollout trên store khiến số lượng người dùng bị lỗi tăng gấp bội"]
  ),
  q("MOB-SCEN-02", "Mobile Developer (iOS/Android/Flutter)", "scenario", "intermediate", "middle",
    "Tình huống: Ứng dụng bị Apple Review từ chối (Rejection) theo Điều khoản 4.8 (Sign in with Apple) và 5.1.1 (Data Collection and Storage) do thiếu nút đăng nhập bằng Apple và xin quyền vị trí không rõ lý do. Em xử lý thế nào để pass review nhanh nhất?",
    ["Điều khoản 4.8: Bắt buộc bổ sung Sign in with Apple nếu app có đăng nhập bằng bên thứ ba (Google, Facebook); cấu hình đúng nút theo Apple Human Interface Guidelines", "Điều khoản 5.1.1: Cập nhật tệp `Info.plist` với nội dung giải thích lý do xin quyền (Usage Description) rõ ràng, cụ thể mục đích sử dụng cho người dùng", "Gửi phản hồi lịch sự kèm video demo qua Resolution Center của Apple giải thích rõ các điểm đã khắc phục"],
    ["Khi nào ứng dụng có thể được miễn trừ yêu cầu Sign in with Apple?", "Làm thế nào để chuẩn bị tài khoản test (Demo Account) hoàn hảo cho đội ngũ Review của Apple/Google?"] ,
    ["App Store Rejection", "Sign in with Apple", "Permission Handling", "App Store Guidelines"],
    [SRC.apple],
    ["Cãi vã gay gắt với người kiểm duyệt của Apple hoặc gửi lại bản build mà không sửa chữa vi phạm"]
  ),
  q("MOB-SCEN-03", "Mobile Developer (iOS/Android/Flutter)", "scenario", "intermediate", "middle",
    "Tình huống: Người dùng phản ánh ứng dụng bị mất toàn bộ nội dung đang soạn dở trong biểu mẫu khi họ tạm thời chuyển sang ứng dụng khác để nhận cuộc gọi điện thoại hoặc sao chép mã OTP. Em khắc phục lỗi này ra sao?",
    ["Phân tích nguyên nhân: Hệ điều hành Android/iOS đã kill ứng dụng ở background do thiếu RAM (Process Death), làm mất state trong memory", "Khắc phục: Lưu tự động state của biểu mẫu vào SharedPreferences/UserDefaults hoặc SQLite ngay trong sự kiện `onPause`/`didEnterBackground`", "Khôi phục lại nội dung khi mở lại màn hình và xóa bản lưu nháp khi nộp form thành công"],
    ["Làm thế nào để mô phỏng Process Death trên máy ảo Android bằng lệnh `adb shell am kill`?", "Sự khác biệt giữa cấu hình thay đổi (Configuration Change như xoay màn hình) và Process Death?"],
    ["Process Death", "State Preservation", "Background Kill", "Form UX"],
    [SRC.android, SRC.internal],
    ["Chỉ lưu state trong biến bộ nhớ của ViewModel mà không có cơ chế lưu trữ bền vững (Persistent Storage)"]
  ),
  q("MOB-SCEN-04", "Mobile Developer (iOS/Android/Flutter)", "scenario", "advanced", "senior_lead",
    "Tình huống: Màn hình chụp ảnh và chỉnh sửa ảnh liên tục bị crash do Out Of Memory (OOM) sau khi người dùng chụp từ 5 bức ảnh chất lượng cao trở lên trên các thiết bị cấu hình yếu. Các bước tối ưu hóa luồng xử lý ảnh của em là gì?",
    ["Ngay sau khi chụp, lập tức nén và resize ảnh (Downsampling) về độ phân giải phù hợp với mục đích sử dụng trước khi load vào bộ nhớ", "Giải phóng các đối tượng Bitmap / UIImage cũ ngay khi không còn dùng bằng cách hủy tham chiếu hoặc gọi `recycle()`", "Sử dụng bộ nhớ đệm dạng đĩa (Disk Cache) thay vì giữ nhiều ảnh kích thước lớn trong bộ nhớ RAM"],
    ["Làm thế nào để đọc metadata ảnh (kích thước, hướng xoay EXIF) mà không cần nạp toàn bộ byte ảnh vào RAM?", "Thư viện xử lý ảnh nào hỗ trợ memory pooling hiệu quả?"] ,
    ["OOM Crash", "Image Processing", "Bitmap Memory", "Downsampling"],
    [SRC.internal],
    ["Giữ nguyên file ảnh raw 20MB trong RAM cho mỗi lần chỉnh sửa"]
  ),
  q("MOB-SCEN-05", "Mobile Developer (iOS/Android/Flutter)", "scenario", "intermediate", "middle",
    "Tình huống: Người dùng phàn nàn ứng dụng không hiển thị được giao diện chính xác trên các thiết bị có 'tai thỏ' (Notch), Dynamic Island, thanh điều hướng cử chỉ hoặc màn hình gập (Foldable). Em xử lý khả năng thích ứng màn hình ra sao?",
    ["Bọc giao diện bên trong thành phần `SafeArea` (Flutter/React Native) hoặc neo vào `Safe Area Layout Guide` (iOS) và `WindowInsets` (Android)", "Sử dụng Layout Builder / MediaQuery để phản hồi linh hoạt theo kích thước màn hình và tỷ lệ khung hình khác nhau", "Kiểm thử trên nhiều mẫu thiết bị thực tế hoặc simulator có Dynamic Island và màn hình gập để đảm bảo không bị che khuất nội dung"],
    ["Cách xử lý bàn phím ảo (Virtual Keyboard) đẩy vỡ giao diện (Bottom Overflow) bằng `SingleChildScrollView` và `resizeToAvoidBottomInset`?", "Hỗ trợ màn hình gập hai màn hình (Dual-screen posture) cần lưu ý điều gì?"],
    ["SafeArea", "Dynamic Island", "Responsive Mobile", "WindowInsets"],
    [SRC.apple, SRC.android],
    ["Hardcode kích thước chiều cao status bar bằng số pixel cố định khiến giao diện bị đè lên tai thỏ"]
  ),
  q("MOB-SCEN-06", "Mobile Developer (iOS/Android/Flutter)", "scenario", "advanced", "senior_lead",
    "Tình huống: Ứng dụng tích hợp mô hình Mua hàng trong ứng dụng (In-App Purchases - IAP) để đăng ký gói thành viên VIP. Người dùng đã bị trừ tiền thành công nhưng app không mở khóa tính năng do lỗi mạng lúc trả về. Em thiết kế cơ chế hoàn tất giao dịch (Transaction Receipt Validation) thế nào?",
    ["Không bao giờ hoàn tất giao dịch (finishTransaction) tại Client trước khi backend xác thực thành công", "Client gửi biên lai (Receipt / Purchase Token) lên Backend để server gọi trực tiếp sang Apple StoreKit API / Google Play Developer API xác thực tính hợp lệ", "Lắng nghe sự kiện giao dịch chưa hoàn tất (Unfinished Transactions) ngay khi app khởi động để kích hoạt lại quy trình mở khóa"],
    ["Tại sao việc xác thực biên lai IAP trực tiếp từ Client là cực kỳ nguy hiểm (dễ bị bẻ khóa bằng app patcher)?", "Cơ chế Server-to-Server Notifications của Apple và Real-Time Developer Notifications của Google hỗ trợ gì cho việc gia hạn gói VIP?"] ,
    ["In-App Purchase", "IAP Validation", "Receipt Verification", "StoreKit"],
    [SRC.apple, SRC.android],
    ["Chỉ dựa vào kết quả callback trả về ở client để mở khóa tính năng VIP cho người dùng"]
  ),

  // CV Validation (5)
  q("MOB-CV-01", "Mobile Developer (iOS/Android/Flutter)", "cv_validation", "advanced", "senior_lead",
    "Trong các ứng dụng di động được ghi trên CV của em: Ứng dụng nào có kiến trúc phức tạp nhất và có lượng người dùng hoạt động (DAU/MAU) lớn nhất? Em đã đóng góp gì vào kiến trúc và trải nghiệm người dùng?",
    ["Trình bày mô hình kiến trúc áp dụng: Clean Architecture, MVVM, BLoC, MVI", "Nêu rõ số lượng màn hình, số người dùng thực tế và đánh giá sao (Rating) trên cửa hàng ứng dụng", "Chỉ rõ tính năng khó nhất do chính mình xây dựng và giải pháp vượt qua thách thức"],
    ["Nếu được viết lại ứng dụng đó từ đầu với công nghệ hiện tại, em sẽ thay đổi điều gì?", "Chỉ số Crash-free users của ứng dụng đó duy trì ở mức bao nhiêu phần trăm?"] ,
    ["Architecture", "App Store Presence", "Scale", "CV Deep Dive"],
    [SRC.internal],
    ["Nói chung chung lý thuyết mà không nhớ tên ứng dụng, cấu trúc màn hình hoặc các tính năng chính"]
  ),
  q("MOB-CV-02", "Mobile Developer (iOS/Android/Flutter)", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kinh nghiệm xử lý tính năng bản đồ và định vị GPS. Hãy chia sẻ cách em tối ưu hóa việc vẽ hàng nghìn điểm đánh dấu (Markers) trên bản đồ mà không làm lag ứng dụng?",
    ["Áp dụng kỹ thuật gom cụm điểm đánh dấu (Marker Clustering) để chỉ render số lượng điểm vừa phải theo mức zoom", "Tải trước các icon đánh dấu vào bộ nhớ đệm (Bitmap cache) thay vì tạo mới cho từng marker", "Chỉ tải và hiển thị các địa điểm nằm trong ranh giới khung nhìn bản đồ hiện tại (Visible Map Bounds)"],
    ["Làm thế nào để xử lý vẽ đường đi mượt mà (Polyline animation) theo thời gian thực?", "Cách xin quyền vị trí theo ngữ cảnh (When in use vs Always) để tăng tỷ lệ người dùng chấp thuận?"] ,
    ["Google Maps", "Marker Clustering", "GPS Tracking", "Performance"],
    [SRC.internal],
    ["Render trực tiếp hàng nghìn marker lên bản đồ cùng một lúc khiến ứng dụng bị đơ cứng"]
  ),
  q("MOB-CV-03", "Mobile Developer (iOS/Android/Flutter)", "cv_validation", "intermediate", "middle",
    "Em ghi nhận kinh nghiệm tích hợp SDK bên thứ ba trên mobile (ví dụ Facebook SDK, Firebase, MoEngage, Zalo SDK). Em đã gặp xung đột thư viện (Dependency Conflict) hoặc lỗi biên dịch nào và cách giải quyết ra sao?",
    ["Giải quyết xung đột phiên bản trong Gradle (Dependency Resolution Strategy) hoặc CocoaPods/SPM", "Xử lý lỗi MultiDex khi số lượng phương thức vượt quá 65.536 methods trên Android", "Đảm bảo tuân thủ chính sách bảo mật App Tracking Transparency (ATT) của iOS khi tích hợp SDK quảng cáo"],
    ["Làm thế nào để đo lường dung lượng mà một SDK ngoài cộng thêm vào kích thước app?", "Chiến lược bọc các SDK bên thứ ba bằng Adapter Pattern để dễ dàng thay thế khi cần?"] ,
    ["Third-party SDK", "MultiDex", "CocoaPods", "Dependency Conflict"],
    [SRC.internal],
    ["Thêm SDK vào dự án một cách tùy tiện mà không đọc kỹ tài liệu cấp quyền và ảnh hưởng bảo mật"]
  ),
  q("MOB-CV-04", "Mobile Developer (iOS/Android/Flutter)", "cv_validation", "advanced", "senior_lead",
    "Em hãy kể về một lỗi kỳ lạ chỉ xảy ra trên một dòng máy hoặc phiên bản hệ điều hành cụ thể (ví dụ: máy Xiaomi/Oppo bị tắt ngầm thông báo, hoặc máy Samsung lỗi camera) mà em đã từng xử lý thành công?",
    ["Xác định nguyên nhân đặc thù phần cứng hoặc hệ điều hành tùy biến (MIUI/ColorOS tối ưu pin cực đoan làm ngắt background service)", "Quy trình tái hiện lỗi: mượn thiết bị thật, dùng cloud device farm hoặc kiểm tra logs chi tiết qua Crashlytics", "Giải pháp thích ứng: hướng dẫn người dùng bật quyền tự khởi chạy (Auto-start) hoặc dùng cơ chế fallback phù hợp"],
    ["Tại sao việc chỉ test trên máy ảo Pixel/iPhone là không đủ đối với một ứng dụng Android quy mô lớn?", "Làm thế nào để duy trì danh sách thiết bị kiểm thử đại diện trong công ty?"] ,
    ["Device Fragmentation", "Vendor Customization", "Android OEM", "Troubleshooting"],
    [SRC.internal],
    ["Phủ nhận lỗi và cho rằng nếu máy ảo chạy tốt thì lỗi là do điện thoại của người dùng"]
  ),
  q("MOB-CV-05", "Mobile Developer (iOS/Android/Flutter)", "cv_validation", "intermediate", "middle",
    "Trong dự án có chức năng chat hoặc gọi video thời gian thực trên CV, em đã xử lý các sự kiện vòng đời cuộc gọi (như cuộc gọi điện thoại thông thường xen ngang, hoặc mất mạng giữa chừng) như thế nào?",
    ["Tích hợp CallKit trên iOS và ConnectionService trên Android để cuộc gọi VoIP hiển thị như cuộc gọi hệ thống", "Lắng nghe sự kiện audio session interruption để tạm dừng và kích hoạt lại luồng âm thanh mượt mà", "Xử lý tái kết nối phòng gọi (Room reconnection) tự động và hiển thị trạng thái kết nối mạng yếu cho người dùng"],
    ["Cơ chế VoIP Push Notification (PushKit) hoạt động ra sao và yêu cầu nghiêm ngặt nào của Apple?", "Cách tối ưu hóa chất lượng video thích ứng theo băng thông mạng (Adaptive Bitrate)?"] ,
    ["WebRTC", "CallKit", "VoIP", "Realtime Communication"],
    [SRC.apple, SRC.internal],
    ["Không xử lý sự cố khi có cuộc gọi di động xen ngang khiến âm thanh của app bị mất hoàn toàn"]
  ),

  // Behavioral (5)
  q("MOB-BEHAV-01", "Mobile Developer (iOS/Android/Flutter)", "behavioral", "basic", "junior",
    "Khi Designer đưa ra bản thiết kế giao diện theo phong cách iOS (Human Interface Guidelines) nhưng Product Owner muốn dùng chung 100% giao diện đó cho cả Android, em trao đổi và bảo vệ trải nghiệm người dùng trên từng nền tảng thế nào?",
    ["Tôn trọng phong cách đặc thù của từng hệ điều hành: nút Back vật lý, vị trí Tabs, thanh điều hướng, cử chỉ vuốt", "Chỉ ra rủi ro: người dùng Android sẽ cảm thấy xa lạ và khó chịu nếu bị ép dùng trải nghiệm gượng gạo của iOS", "Đề xuất giải pháp hài hòa: giữ nguyên nhận diện thương hiệu cốt lõi nhưng linh hoạt thích ứng các thành phần điều hướng chuẩn theo platform"],
    ["Khi nào việc sử dụng một giao diện tùy biến hoàn toàn (Branded UI) là chấp nhận được cho cả hai nền tảng?", "Làm thế nào để demo trực tiếp trên 2 máy thật để thuyết phục PO và Designer?"] ,
    ["Platform Guidelines", "Material Design", "HIG", "Design Collaboration"],
    [SRC.internal],
    ["Thụ động làm theo mà không lên tiếng hoặc ngược lại từ chối cộc lốc không giải thích lý do"]
  ),
  q("MOB-BEHAV-02", "Mobile Developer (iOS/Android/Flutter)", "behavioral", "intermediate", "middle",
    "Ứng dụng di động khi đã phát hành thì không thể sửa lỗi tức thời như Web (phải chờ người dùng cập nhật qua store). Em xây dựng quy trình kiểm soát chất lượng (QA) và tư duy an toàn trước mỗi đợt release như thế nào?",
    ["Tâm thế cẩn trọng: mỗi dòng code lên mobile đều phải được kiểm thử kỹ lưỡng vì chi phí sửa sai cực kỳ đắt đỏ", "Thiết lập quy trình Staged Rollout (phát hành dần từ 5% -> 20% -> 50% -> 100%) để theo dõi tỷ lệ crash trước khi mở rộng", "Xây dựng hệ thống Feature Flags và Remote Config để có thể tắt tính năng bị lỗi từ xa mà không cần submit bản build mới"],
    ["Nếu phát hiện bug nghiêm trọng khi app vừa đạt 10% rollout, hành động đầu tiên của em là gì?", "Làm thế nào để thông báo cho người dùng cập nhật phiên bản mới một cách tinh tế?"] ,
    ["Release Management", "Staged Rollout", "Feature Flags", "Mobile Mindset"],
    [SRC.internal],
    ["Cẩu thả release ngay 100% người dùng mà không có giai đoạn thử nghiệm hoặc không chuẩn bị phương án dự phòng"]
  ),
  q("MOB-BEHAV-03", "Mobile Developer (iOS/Android/Flutter)", "behavioral", "intermediate", "middle",
    "Khi Backend API thay đổi cấu trúc dữ liệu đột ngột khiến ứng dụng di động của người dùng bị vỡ giao diện hoặc crash, em xử lý giao tiếp với đội ngũ Backend và xây dựng cơ chế phòng vệ (Defensive Programming) ở Client ra sao?",
    ["Nguyên tắc phòng vệ: Client không bao giờ tin tưởng tuyệt đối vào API, luôn kiểm tra null an toàn và có giá trị fallback mặc định", "Góp ý với đội Backend về tầm quan trọng của tính tương thích ngược (Backward Compatibility) và tuân thủ hợp đồng API", "Thống nhất quy trình kiểm thử hợp đồng (Contract Testing) trước khi deploy backend mới"],
    ["Làm thế nào để parse JSON an toàn trong Swift/Kotlin mà không làm crash app khi thiếu một trường không bắt buộc?", "Cách ứng xử chuyên nghiệp không đổ lỗi khi sự cố xảy ra giữa hai đội?"] ,
    ["Defensive Programming", "Backend Collaboration", "API Mismatch", "Crash Prevention"],
    [SRC.internal],
    ["Viết code parse JSON ép kiểu cứng (force unwrap) rồi đổ lỗi hoàn toàn cho Backend khi có lỗi phát sinh"]
  ),
  q("MOB-BEHAV-04", "Mobile Developer (iOS/Android/Flutter)", "behavioral", "intermediate", "middle",
    "Khi ứng dụng nhận phải hàng loạt đánh giá 1 sao (1-star reviews) tiêu cực trên Google Play và App Store do một lỗi giật lag ở phiên bản mới, em tiếp nhận phản hồi và hành động cùng đội ngũ ra sao?",
    ["Bình tĩnh lắng nghe, phân loại các đánh giá để trích xuất thông tin lỗi kỹ thuật (dòng máy, phiên bản hệ điều hành)", "Phối hợp với Customer Support phản hồi chân thành xin lỗi người dùng và cam kết thời gian khắc phục", "Tập trung cao độ tái hiện và sửa lỗi dứt điểm, release bản vá và mời những người dùng đó trải nghiệm lại để nâng điểm đánh giá"],
    ["Làm thế nào để khuyến khích những người dùng hài lòng đánh giá 5 sao cho app (In-App Review prompt) đúng thời điểm?", "Bài học kinh nghiệm về việc thử nghiệm hiệu năng trước khi release là gì?"] ,
    ["User Feedback", "App Store Rating", "Customer Empathy", "Reputation Management"],
    [SRC.internal],
    ["Phớt lờ phản hồi của người dùng hoặc phản hồi với thái độ bực bội, tiêu cực trên store"]
  ),
  q("MOB-BEHAV-05", "Mobile Developer (iOS/Android/Flutter)", "behavioral", "advanced", "senior_lead",
    "Trước cuộc tranh luận nội bộ về việc nên phát triển Native thuần (Swift & Kotlin) hay dùng Cross-Platform (Flutter / React Native) cho sản phẩm mới của công ty, em phân tích và đưa ra khuyến nghị dựa trên những yếu tố nào?",
    ["Đánh giá dựa trên bài toán kinh doanh: ngân sách, thời gian đưa sản phẩm ra thị trường (Time to Market), nguồn nhân lực hiện có", "Đánh giá yêu cầu kỹ thuật: mức độ can thiệp vào phần cứng sâu (Bluetooth, Camera AR, xử lý âm thanh phức tạp thì ưu tiên Native)", "Khuyến nghị phương án phù hợp nhất cho bối cảnh doanh nghiệp thay vì chỉ chọn theo sở thích cá nhân"],
    ["Khi nào việc chọn Cross-platform có thể trở thành cái bẫy kỹ thuật tốn kém hơn cả làm Native?", "Chiến lược chuyển đổi từng bước nếu một ngày dự án cần chuyển từ Cross-platform sang Native là gì?"] ,
    ["Native vs Cross-platform", "Technology Evaluation", "Strategic Decision", "Business Alignment"],
    [SRC.internal],
    ["Đưa ra ý kiến phiến diện bảo thủ ca ngợi một công nghệ duy nhất mà bỏ qua bối cảnh bài toán doanh nghiệp"]
  )
];

console.log("MOB questions defined:", mobQuestions.length);
module.exports = { mobQuestions };
