const { q, SRC } = require('./fe_data.cjs');
const { TEST_SRC } = require('./qa_data.cjs');

const qcQuestions = [
  // Foundation (6)
  q("QC-FOUND-01", "QC Specialist", "foundation", "basic", "junior",
    "Phân biệt rạch ròi giữa Đảm bảo chất lượng (Quality Assurance - QA) và Kiểm soát chất lượng (Quality Control - QC) theo tiêu chuẩn quốc tế ISO 9000 và CMMI. Trách nhiệm trọng tâm của một QC Specialist trong dự án phần mềm là gì?",
    ["QA tập trung vào quy trình (Process-oriented): xây dựng, cải tiến và ngăn ngừa lỗi (Defect Prevention) trong toàn bộ vòng đời phát triển", "QC tập trung vào sản phẩm (Product-oriented): kiểm tra, đo lường, xác minh và phát hiện lỗi (Defect Detection) trên các sản phẩm bàn giao thực tế", "QC Specialist đóng vai trò cổng kiểm soát chất lượng (Quality Gatekeeper), nghiệm thu sản phẩm dựa trên tiêu chuẩn đã thống nhất trước khi xuất xưởng"],
    ["Tại sao một tổ chức có quy trình QA hoàn hảo vẫn có thể tạo ra sản phẩm bị lỗi nếu khâu QC thực thi yếu kém?", "Sự phối hợp hai chiều giữa QA và QC trong việc cải tiến quy trình diễn ra ra sao?"] ,
    ["QA vs QC", "ISO 9000", "Quality Control", "Quality Gates"],
    [TEST_SRC.istqb],
    ["Đồng nhất hoàn toàn QA và QC làm một và không phân biệt được giữa kiểm soát quy trình và kiểm soát sản phẩm"]
  ),
  q("QC-FOUND-02", "QC Specialist", "foundation", "intermediate", "middle",
    "Các Cổng kiểm soát chất lượng (Quality Gates) trong quy trình phát triển và phát hành phần mềm: Tiêu chí đầu vào (Entry Criteria) và Tiêu chí nghiệm thu đầu ra (Exit Criteria) của từng giai đoạn được thiết lập như thế nào?",
    ["Entry Criteria: điều kiện tiên quyết để bắt đầu một giai đoạn (vd: Code hoàn tất, Unit test pass 100%, deploy staging thành công, tài liệu PRD có chữ ký duyệt)", "Exit Criteria: điều kiện bắt buộc để kết thúc giai đoạn và cho phép chuyển tiếp (vd: 100% test case trọng yếu được thực thi, 0 Blocker/Critical bug, độ bao phủ đạt chuẩn)", "Quy tắc không thỏa hiệp: nếu không đạt Exit Criteria thì cổng kiểm soát chất lượng sẽ tự động chặn việc chuyển giai đoạn"],
    ["Ai là người có thẩm quyền ký duyệt (Sign-off) cho phép một tính năng vượt qua Quality Gate?", "Quy trình xử lý ngoại lệ (Exception Approval) khi một tính năng chưa đạt chuẩn nhưng bắt buộc phải chuyển giai đoạn?"] ,
    ["Quality Gates", "Entry Criteria", "Exit Criteria", "Sign-off Process"],
    [TEST_SRC.istqb],
    ["Cho phép sản phẩm chuyển sang giai đoạn tiếp theo một cách tùy tiện mà không đối chiếu các tiêu chí nghiệm thu"]
  ),
  q("QC-FOUND-03", "QC Specialist", "foundation", "intermediate", "middle",
    "Kỹ thuật Phân tích nguyên nhân gốc rễ (Root Cause Analysis - RCA): Em sử dụng phương pháp '5 Whys' và Biểu đồ xương cá (Ishikawa / Fishbone Diagram) để tìm ra nguồn gốc của một lỗi chất lượng nghiêm trọng như thế nào?",
    ["5 Whys: liên tục đặt câu hỏi 'Tại sao' ít nhất 5 lần để đào sâu từ triệu chứng bề mặt đến nguyên nhân gốc rễ trong quy trình hoặc con người", "Biểu đồ xương cá Ishikawa: phân loại nguyên nhân theo các nhóm chính (Con người - People, Quy trình - Process, Công nghệ - Technology, Môi trường - Environment, Dữ liệu - Data)", "Đưa ra hành động khắc phục phòng ngừa (CAPA - Corrective and Preventive Actions) chứ không chỉ dừng lại ở việc vá lỗi tạm thời"],
    ["Làm thế nào để tránh việc 5 Whys biến thành một cuộc thẩm vấn quy kết tội cá nhân?", "Cách đo lường hiệu quả của một hành động khắc phục sau 3 tháng triển khai?"] ,
    ["Root Cause Analysis", "5 Whys", "Ishikawa Fishbone", "CAPA", "Problem Solving"],
    [TEST_SRC.internal],
    ["Chỉ dừng lại ở nguyên nhân bề mặt như 'Do lập trình viên gõ sai code' mà không tìm ra lỗ hổng trong quy trình"]
  ),
  q("QC-FOUND-04", "QC Specialist", "foundation", "intermediate", "middle",
    "Quy trình Kiểm soát Tài liệu và Cấu hình (Document & Configuration Control): Làm thế nào để đảm bảo đội ngũ kiểm soát chất lượng luôn đối chiếu trên đúng phiên bản tài liệu đặc tả (BRD/SRS) và phiên bản phần mềm (Build Version) chuẩn xác nhất?",
    ["Áp dụng quy tắc quản lý phiên bản tài liệu có lịch sử thay đổi (Document Revision History) và chữ ký phê duyệt của các bên liên quan", "Gắn thẻ phiên bản phần mềm (Semantic Versioning - SemVer) liên kết chặt chẽ với Git Commit Hash trên từng môi trường", "Kiểm tra tính nhất quán: đối chiếu bản kiểm thử với đúng tài liệu đã được phê duyệt, ghi nhận ngay sai lệch nếu tài liệu chưa được cập nhật"],
    ["Sự cố gì xảy ra nếu đội ngũ QC kiểm thử trên phiên bản tài liệu cũ đã bị sửa đổi mà không được thông báo?", "Làm thế nào để thiết lập quy trình quản lý yêu cầu thay đổi (Change Control Board - CCB)?"] ,
    ["Configuration Control", "Document Management", "SemVer", "Audit Trail"],
    [TEST_SRC.internal],
    ["Kiểm thử tùy tiện theo lời nói miệng mà không có tài liệu đối soát phiên bản chính thức"]
  ),
  q("QC-FOUND-05", "QC Specialist", "foundation", "basic", "junior",
    "Kiểm tra khói (Smoke Testing) và Kiểm tra độ lành mạnh (Sanity Testing): Phân biệt mục tiêu, thời điểm thực hiện và phạm vi kiểm tra của hai loại kiểm thử kiểm soát chất lượng này?",
    ["Smoke Testing (Build Verification Test): kiểm tra các chức năng cơ bản nhất ngay khi nhận bản build mới để xác nhận bản build có đủ ổn định để bắt đầu kiểm thử hay không", "Sanity Testing: kiểm tra nhanh có trọng tâm vào một module vừa được sửa lỗi hoặc cập nhật để xác nhận tính hợp lý của chức năng trước khi đi vào kiểm thử sâu", "Cả hai đều có phạm vi hẹp, thực hiện nhanh (15-30 phút), và nếu fail thì bản build sẽ bị từ chối ngay lập tức"],
    ["Nếu bản build bị fail ở bước Smoke Test, quy trình từ chối bản build (Build Rejection Protocol) diễn ra ra sao?", "Tại sao không nên bắt đầu kiểm thử chi tiết khi Smoke Test chưa vượt qua?"] ,
    ["Smoke Testing", "Sanity Testing", "Build Verification", "QC Checklist"],
    [TEST_SRC.istqb],
    ["Nhầm lẫn Smoke Testing với kiểm thử hồi quy toàn diện (Regression Testing)"]
  ),
  q("QC-FOUND-06", "QC Specialist", "foundation", "intermediate", "middle",
    "Phân tích Biểu đồ Pareto (Nguyên lý 80/20) trong kiểm soát chất lượng phần mềm: Làm thế nào để phân loại các lỗi theo danh mục và tập trung nguồn lực kiểm soát vào 20% nguyên nhân gây ra 80% số lỗi của sản phẩm?",
    ["Thu thập và gắn nhãn toàn bộ lỗi trong dự án theo danh mục nguyên nhân (Module, Loại lỗi: logic, giao diện, dữ liệu, hiệu năng)", "Vẽ biểu đồ Pareto sắp xếp các danh mục lỗi theo thứ tự giảm dần kết hợp đường tích lũy phần trăm (Cumulative % line)", "Xác định các 'yếu tố thiểu số trọng yếu' (Vital few) để đề xuất hành động cải tiến quy trình tập trung mang lại hiệu quả cao nhất"],
    ["Làm thế nào để sử dụng biểu đồ Pareto để thuyết phục ban lãnh đạo đầu tư tái cấu trúc một module thường xuyên phát sinh lỗi?", "Cách kết hợp biểu đồ Pareto với biểu đồ kiểm soát (Control Charts) để giám sát chất lượng ổn định?"] ,
    ["Pareto Analysis", "80/20 Rule", "Quality Metrics", "Defect Distribution"],
    [TEST_SRC.istqb],
    ["Xem mọi lỗi phát sinh đều có tầm quan trọng như nhau mà không biết ưu tiên tập trung vào các cụm lỗi trọng yếu"]
  ),

  // Practical Skills (8)
  q("QC-SKILL-01", "QC Specialist", "practical_skills", "intermediate", "middle",
    "Thiết lập Bảng kiểm tra nghiệm thu phát hành (Release Verification Checklist): Em xây dựng các hạng mục kiểm tra bắt buộc trước khi đóng gói sản phẩm và các bước kiểm tra xác nhận sau khi triển khai (Post-Deployment Verification) trên môi trường Production như thế nào?",
    ["Pre-deployment Checklist: xác nhận 100% test case pass, kiểm tra tài liệu release notes, xác nhận cấu hình môi trường, và phê duyệt từ các bên liên quan", "Deployment Checklist: giám sát quy trình chạy migration, kiểm tra tình trạng sức khỏe dịch vụ (Health check endpoints)", "Post-deployment Verification (Sanity Test): thực hiện kiểm tra các giao dịch nghiệp vụ cốt lõi bằng tài khoản kiểm thử chuyên dụng trên môi trường sống mà không làm ảnh hưởng dữ liệu thật"],
    ["Kế hoạch Rollback (Rollback Procedure) được chuẩn bị sẵn sàng trong Checklist như thế nào nếu có sự cố xảy ra?", "Làm thế nào để phối hợp nhịp nhàng giữa đội QC, DevOps và Đội ngũ Vận hành trong đêm release?"] ,
    ["Release Checklist", "Post-deployment Verification", "Production Sanity", "Release Governance"],
    [TEST_SRC.internal],
    ["Bấm duyệt release mà không có checklist đối soát từng bước cụ thể"]
  ),
  q("QC-SKILL-02", "QC Specialist", "practical_skills", "intermediate", "middle",
    "Điều phối quy trình Nghiệm thu Người dùng (User Acceptance Testing - UAT): Em lập kế hoạch, chuẩn bị kịch bản kiểm thử nghiệp vụ (Business Scenarios), hướng dẫn khách hàng/người dùng cuối và quản lý danh sách phản hồi (Feedback Log) như thế nào?",
    ["Soạn thảo tài liệu hướng dẫn UAT (UAT Guide) thân thiện với người dùng không am hiểu kỹ thuật kèm các kịch bản hành trình thực tế", "Chuẩn bị môi trường UAT sạch sẽ và dữ liệu mẫu phản ánh đúng nghiệp vụ hàng ngày của khách hàng", "Tổ chức buổi họp điều phối hàng ngày để phân loại phản hồi thành: Lỗi thực tế (Defects) cần sửa ngay, hoặc Yêu cầu mới (Change Requests) chuyển sang giai đoạn sau"],
    ["Biên bản nghiệm thu UAT (UAT Sign-off Document) cần có những chữ ký và điều khoản pháp lý quan trọng nào?", "Cách xử lý khi khách hàng trì hoãn không chịu tham gia kiểm thử UAT đúng lịch trình?"] ,
    ["UAT Coordination", "User Acceptance", "Business Scenarios", "Sign-off Protocol"],
    [TEST_SRC.internal],
    ["Bỏ mặc khách hàng tự mày mò trong môi trường UAT mà không có kịch bản hướng dẫn và không quản lý danh sách phản hồi"]
  ),
  q("QC-SKILL-03", "QC Specialist", "practical_skills", "advanced", "senior_lead",
    "Kiểm toán Tuân thủ Quy trình (Quality Audit & Process Compliance): Em tiến hành các buổi đánh giá nội bộ định kỳ để kiểm tra xem các dự án có tuân thủ đúng Quy trình Vận hành Tiêu chuẩn (SOP) và tiêu chuẩn chất lượng của tổ chức hay không ra sao?",
    ["Lập kế hoạch kiểm toán (Audit Plan): xác định phạm vi, tiêu chí đánh giá, danh sách dự án và nhân sự được phỏng vấn", "Thu thập bằng chứng khách quan (Objective Evidence): kiểm tra hồ sơ dự án, biên bản họp, tỷ lệ code review, tài liệu thiết kế và kết quả kiểm thử", "Lập báo cáo kiểm toán ghi nhận các điểm không phù hợp (Non-Conformities - NCs) và theo dõi hành động khắc phục của dự án"],
    ["Phân biệt giữa Điểm không phù hợp nghiêm trọng (Major NC), không phù hợp nhỏ (Minor NC), và Điểm cần lưu ý (Observation)?", "Làm thế nào để buổi kiểm toán chất lượng diễn ra trên tinh thần hỗ trợ cải tiến thay vì cảm giác bị thanh tra soi mói?"] ,
    ["Quality Audit", "SOP Compliance", "Non-Conformity", "Process Assessment"],
    [TEST_SRC.internal],
    ["Thực hiện kiểm toán mang tính hình thức đối phó trên giấy tờ mà không kiểm tra bằng chứng thực tế"]
  ),
  q("QC-SKILL-04", "QC Specialist", "practical_skills", "intermediate", "middle",
    "Đo lường và Báo cáo Hiệu quả Loại bỏ Lỗi (Defect Removal Efficiency - DRE): Cách tính toán chỉ số DRE và ứng dụng chỉ số này để đánh giá năng lực của các chặng kiểm soát chất lượng trước khi sản phẩm đến tay khách hàng?",
    ["Công thức: DRE = (Số lỗi phát hiện trước khi release / Tổng số lỗi phát hiện trước và sau khi release) * 100%", "Chỉ số DRE trên 90-95% phản ánh hệ thống kiểm soát chất lượng nội bộ hoạt động hiệu quả", "Phân rã DRE theo từng giai đoạn (DRE của Review Yêu cầu, DRE của Code Review, DRE của QA Testing) để tìm ra khâu nào đang để lọt nhiều lỗi nhất"],
    ["Khi chỉ số DRE của một dự án giảm xuống dưới 80%, các bước can thiệp khẩn cấp của QC Specialist là gì?", "Làm thế nào để gắn chỉ số DRE vào mục tiêu đánh giá chất lượng của toàn bộ phòng kỹ thuật?"] ,
    ["DRE Metric", "Defect Removal Efficiency", "Quality Measurement", "Process Analytics"],
    [TEST_SRC.istqb],
    ["Không biết cách tính toán và đo lường chỉ số hiệu quả loại bỏ lỗi DRE"]
  ),
  q("QC-SKILL-05", "QC Specialist", "practical_skills", "intermediate", "middle",
    "Xây dựng và Chuẩn hóa Quy trình Thao tác Chuẩn (Standard Operating Procedures - SOP): Em viết tài liệu SOP cho quy trình báo cáo lỗi, quy trình bàn giao phần mềm giữa Dev và QC, và quy trình nghiệm thu sản phẩm như thế nào?",
    ["Cấu trúc SOP chuẩn: Mục đích, Phạm vi áp dụng, Định nghĩa, Trách nhiệm của các bên (RACI matrix), Lưu đồ quy trình (Flowchart), và Các bước thực hiện chi tiết kèm biểu mẫu", "Ngôn từ rõ ràng, chính xác, có thể đo lường và thực thi được; tránh các hướng dẫn mơ hồ chung chung", "Quy trình xem xét, phê duyệt và đào tạo phổ biến SOP mới cho toàn thể nhân sự dự án"],
    ["Làm thế nào để kiểm tra tính khả thi của một SOP mới trước khi ban hành chính thức?", "Định kỳ rà soát và cập nhật SOP (Annual Review) diễn ra theo những tiêu chí nào?"] ,
    ["SOP Authoring", "Process Standardization", "RACI Matrix", "Documentation Quality"],
    [TEST_SRC.internal],
    ["Viết tài liệu quy trình dài dòng lý thuyết nhưng không ai có thể áp dụng được vào công việc thực tế"]
  ),
  q("QC-SKILL-06", "QC Specialist", "practical_skills", "intermediate", "middle",
    "Quản lý Khắc phục và Phòng ngừa (CAPA - Corrective and Preventive Action): Khi một sự cố chất lượng nghiêm trọng xảy ra trên môi trường sống của khách hàng, em điều phối quy trình CAPA từ khâu phân tích đến đóng hồ sơ như thế nào?",
    ["Bước 1: Khắc phục tức thời (Containment / Immediate Action) để ngăn chặn thiệt hại lan rộng", "Bước 2: Điều tra nguyên nhân gốc rễ (Root Cause Analysis bằng 5 Whys)", "Bước 3: Lập kế hoạch hành động khắc phục và phòng ngừa (CAPA Action Plan) có người chịu trách nhiệm và hạn chót", "Bước 4: Đánh giá tính hiệu quả (Effectiveness Review) sau 30-60 ngày để xác nhận sự cố tương tự không còn tái diễn trước khi đóng hồ sơ CAPA"],
    ["Tại sao việc đóng hồ sơ CAPA ngay sau khi vừa fix xong lỗi là một sai lầm về mặt kiểm soát chất lượng?", "Làm thế nào để lưu trữ cơ sở dữ liệu các bài học kinh nghiệm (Lessons Learned Database) cho toàn tổ chức?"] ,
    ["CAPA Management", "Corrective Action", "Preventive Action", "Effectiveness Review"],
    [TEST_SRC.internal],
    ["Chỉ tập trung sửa phần mềm trước mắt mà không có bất kỳ hành động nào để phòng ngừa lỗi tái diễn"]
  ),
  q("QC-SKILL-07", "QC Specialist", "practical_skills", "basic", "junior",
    "Kiểm tra Tuân thủ Tiêu chuẩn Bàn giao Sản phẩm (Deliverables Acceptance Inspection): Khi đội ngũ phát triển bàn giao gói phần mềm kèm mã nguồn, tài liệu hướng dẫn và mã cài đặt, em thực hiện quy trình kiểm tra đối soát vật lý các thành phần bàn giao ra sao?",
    ["Đối chiếu danh mục sản phẩm bàn giao (Bill of Materials / Deliverables Checklist) so với hợp đồng", "Kiểm tra tính đầy đủ: mã nguồn có thể biên dịch thành công từ repo sạch (Clean Build Verification), tài liệu hướng dẫn cài đặt và vận hành có chính xác từng bước không", "Kiểm tra các báo cáo đi kèm: báo cáo Unit test, báo cáo quét mã tĩnh (SonarQube report), và biên bản nghiệm thu nội bộ"],
    ["Nếu thiếu một tài liệu hướng dẫn cài đặt trong gói bàn giao, quy trình phát hành Phiếu yêu cầu bổ sung (Discrepancy Notice) diễn ra ra sao?", "Cách xác thực mã băm tính toàn vẹn (Checksum / SHA-256 hash) của gói cài đặt bàn giao?"] ,
    ["Deliverables Inspection", "Clean Build Verification", "Checklist Auditing", "Handover Process"],
    [TEST_SRC.internal],
    ["Bỏ qua việc kiểm tra tài liệu và hướng dẫn cài đặt, chỉ kiểm tra xem ứng dụng có chạy được hay không"]
  ),
  q("QC-SKILL-08", "QC Specialist", "practical_skills", "advanced", "senior_lead",
    "Thiết lập Bảng điều khiển Chất lượng Doanh nghiệp (Enterprise Quality Dashboard): Em tổng hợp các dữ liệu chất lượng từ Jira, Git, CI/CD, và Hệ thống hỗ trợ khách hàng để xây dựng báo cáo sức khỏe chất lượng sản phẩm cho Ban Lãnh đạo như thế nào?",
    ["Xác định các chỉ số cốt lõi: Tỷ lệ lỗi theo mức độ nghiêm trọng, Xu hướng phát hiện và đóng lỗi, Tỷ lệ lỗi khách hàng báo (Customer Reported Defect Rate), và Tỷ lệ tuân thủ quy trình", "Trực quan hóa dữ liệu bằng biểu đồ cảnh báo (RAG Status: Red - Amber - Green) giúp lãnh đạo nắm bắt nhanh các điểm nóng cần can thiệp", "Phân tích xu hướng (Trend Analysis) để dự báo chất lượng của bản phát hành tiếp theo"],
    ["Làm thế nào để phát hiện sớm dấu hiệu suy giảm chất lượng của một dự án thông qua số liệu trên dashboard?", "Cách chuẩn bị bài thuyết trình định kỳ về bức tranh chất lượng trước Hội đồng Quản trị?"] ,
    ["Quality Dashboard", "RAG Status", "Trend Analysis", "Executive Metrics"],
    [TEST_SRC.internal],
    ["Báo cáo chất lượng chỉ bằng cảm tính chung chung như 'Dự án dạo này chạy khá ổn định' mà không có số liệu chứng minh"]
  ),

  // Scenario (6)
  q("QC-SCEN-01", "QC Specialist", "scenario", "advanced", "senior_lead",
    "Tình huống: Trong buổi nghiệm thu sản phẩm định kỳ trước ngày bàn giao cho khách hàng chính phủ, em phát hiện báo cáo kiểm tra an toàn thông tin bắt buộc chưa được thực hiện, nhưng Giám đốc Dự án (Project Manager) thúc ép em ký biên bản nghiệm thu nội bộ để kịp giải ngân hợp đồng. Em xử lý tình huống đạo đức nghề nghiệp này ra sao?",
    ["Tuyệt đối không ký duyệt biên bản nghiệm thu sai sự thật: vi phạm tiêu chuẩn chất lượng và có thể gây rủi ro pháp lý nghiêm trọng cho công ty", "Báo cáo minh bạch và chính thức bằng văn bản cho Giám đốc Dự án và Trưởng phòng Đảm bảo Chất lượng về việc thiếu sót hồ sơ an toàn thông tin bắt buộc", "Chủ động đề xuất phương án giải quyết khẩn cấp: liên hệ ngay đơn vị kiểm định bảo mật thực hiện đánh giá nhanh có giới hạn phạm vi hoặc đàm phán với khách hàng xin gia hạn bàn giao có lý do chính đáng"],
    ["Làm thế nào để bảo vệ nguyên tắc nghề nghiệp của một người gác cổng chất lượng mà không làm căng thẳng quan hệ nội bộ?", "Hậu quả pháp lý và uy tín nếu sản phẩm bị khách hàng phát hiện lỗ hổng bảo mật sau khi đã ký nghiệm khống là gì?"] ,
    ["Professional Ethics", "Quality Gate Enforcement", "Compliance Risk", "Integrity"],
    [TEST_SRC.internal],
    ["Dễ dàng nhắm mắt ký duyệt biên bản khống theo yêu cầu của Giám đốc Dự án"]
  ),
  q("QC-SCEN-02", "QC Specialist", "scenario", "intermediate", "middle",
    "Tình huống: Tỷ lệ lỗi do khách hàng phát hiện trên môi trường Production (Defect Leakage) trong quý vừa qua tăng vọt lên 25%, cao gấp đôi so với ngưỡng cam kết SLA là 10%. Ban Giám đốc yêu cầu em chủ trì cuộc điều tra toàn diện để xác định nguyên nhân và đưa ra kế hoạch chấn chỉnh. Em tiến hành ra sao?",
    ["Thu thập toàn bộ danh sách các lỗi bị lọt: phân loại theo từng module, mức độ nghiêm trọng và nguyên nhân trực tiếp", "Thực hiện RCA (Phân tích nguyên nhân gốc rễ): xác định lỗi lọt là do thiếu test case, môi trường Staging khác biệt với Production, hay do quy trình review vội vàng bị cắt bớt thời gian", "Lập kế hoạch hành động chấn chỉnh (Remediation Plan): bổ sung các cổng kiểm soát bắt buộc, nâng cao chất lượng môi trường test, và tái đào tạo đội ngũ về các kịch bản thường bị bỏ sót"],
    ["Làm thế nào để báo cáo kết quả điều tra một cách khách quan, tập trung vào giải pháp thay vì biến buổi họp thành nơi chỉ trích lẫn nhau?", "Cách đo lường hiệu quả của kế hoạch chấn chỉnh trong quý tiếp theo?"] ,
    ["Defect Leakage Investigation", "Quality Crisis", "Remediation Plan", "RCA Facilitation"],
    [TEST_SRC.internal],
    ["Vội vã kết luận và đổ toàn bộ lỗi cho nhân viên kiểm thử cấp dưới mà không phân tích lỗ hổng hệ thống"]
  ),
  q("QC-SCEN-03", "QC Specialist", "scenario", "intermediate", "middle",
    "Tình huống: Khi kiểm tra gói phần mềm bàn giao chuẩn bị chuyển giao cho đối tác, em phát hiện mã nguồn của dự án có nhúng một thư viện mã nguồn mở có giấy phép GNU GPL v3.0 nghiêm ngặt (yêu cầu toàn bộ mã nguồn của phần mềm thương mại phải được mở công khai nếu phân phối). Em xử lý rủi ro pháp trị bản quyền này ra sao?",
    ["Tạm dừng ngay lập tức việc phát hành gói phần mềm ra bên ngoài để ngăn chặn rủi ro vi phạm bản quyền và lộ bí mật kinh doanh", "Báo cáo ngay cho Đội ngũ Pháp chế (Legal) và Tech Lead về sự hiện diện của giấy phép copyleft nghiêm ngặt (GPL v3)", "Phối hợp với đội kỹ thuật tìm kiếm thư viện thay thế có giấy phép thoáng hơn (MIT, Apache 2.0, BSD) hoặc mua bản quyền thương mại để loại bỏ hoàn toàn rủi ro"],
    ["Tại sao việc không kiểm soát giấy phép mã nguồn mở (Open Source License Compliance) lại có thể dẫn đến các vụ kiện tụng hàng triệu đô la?", "Quy trình quét bản quyền mã nguồn mở tự động (SCA tools) cần được tích hợp vào bước nào của quy trình QC?"] ,
    ["Open Source Compliance", "GPL License Risk", "Software Legal Risk", "Deliverables Inspection"],
    [TEST_SRC.internal],
    ["Xem nhẹ vấn đề bản quyền mã nguồn mở và cho rằng 'cứ lấy trên mạng về dùng miễn phí là được'"]
  ),
  q("QC-SCEN-04", "QC Specialist", "scenario", "advanced", "senior_lead",
    "Tình huống: Hai bộ phận Phát triển (R&D) và Vận hành (Operations) liên tục đổ lỗi cho nhau khi có sự cố xảy ra sau mỗi đợt release: Dev cho rằng Ops triển khai sai cấu hình, Ops cho rằng Dev bàn giao mã nguồn kém chất lượng và thiếu tài liệu. Là một QC Specialist độc lập, em can thiệp và thiết lập cơ chế bàn giao chuẩn mực ra sao?",
    ["Đóng vai trò trọng tài chất lượng khách quan: phân tích các sự cố gần nhất dựa trên bằng chứng dữ liệu cụ thể chứ không nghe lời nói miệng", "Thiết lập Hợp đồng Bàn giao Chuẩn mực (Handover Contract / Release Package Standard): quy định rõ Dev phải bàn giao đầy đủ những gì (Artifacts, Config docs, Rollback script) và được QC nghiệm thu trước khi chuyển sang Ops", "Xây dựng buổi họp bàn giao chính thức (Pre-release Handover Meeting) và checklist có sự xác nhận của cả ba bên trước khi bấm nút deploy"],
    ["Làm thế nào để văn bản hóa trách nhiệm của từng bên thông qua ma trận RACI rõ ràng?", "Cách thúc đẩy văn hóa hợp tác DevOps để xóa bỏ ranh giới 'đổ lỗi qua hàng rào' (Over-the-wall syndrome)?"] ,
    ["Cross-department Conflict", "Handover Governance", "DevOps Alignment", "Objective Arbitration"],
    [TEST_SRC.internal],
    ["Đứng về một phía để chỉ trích phía còn lại làm mâu thuẫn nội bộ thêm sâu sắc"]
  ),
  q("QC-SCEN-05", "QC Specialist", "scenario", "intermediate", "middle",
    "Tình huống: Trong buổi kiểm tra đánh giá chất lượng đột xuất tại một dự án phần mềm quan trọng, em phát hiện các lập trình viên đang bỏ qua hoàn toàn quy trình Code Review (tự tạo Pull Request và tự bấm Merge trực tiếp vào nhánh chính). Em xử lý sự việc không tuân thủ quy trình này như thế nào?",
    ["Ghi nhận điểm không phù hợp (Non-Conformity) kèm theo bằng chứng cụ thể từ lịch sử commit trên Git", "Trao đổi trực tiếp với Tech Lead và Scrum Master của dự án để tìm hiểu nguyên nhân: do áp lực tiến độ, do quy trình review quá rườm rà hay do thiếu nhân sự", "Cùng dự án thiết lập cấu hình bảo vệ nhánh chính (Branch Protection Rules trên GitHub/GitLab): bắt buộc phải có ít nhất 1 phê duyệt (Approval) từ đồng nghiệp và các bài kiểm tra tự động phải pass mới được merge"],
    ["Làm thế nào để hướng dẫn đội ngũ cải tiến quy trình review nhanh gọn mà không làm chậm nhịp độ công việc?", "Quy trình theo dõi và tái kiểm tra (Follow-up Audit) sau 2 tuần để xác nhận việc khắc phục diễn ra ra sao?"] ,
    ["Process Non-Conformity", "Branch Protection", "Code Review Governance", "Quality Assurance"],
    [TEST_SRC.internal],
    ["Bỏ qua vi phạm và không ghi nhận báo cáo chỉ vì dự án đang trong giai đoạn chạy nước rút"]
  ),
  q("QC-SCEN-06", "QC Specialist", "scenario", "advanced", "senior_lead",
    "Tình huống: Khách hàng yêu cầu áp dụng tiêu chuẩn chất lượng khắt khe theo chuẩn quốc tế CMMI Level 3 cho dự án mới trong vòng 6 tháng tới. Hiện tại dự án đang làm theo mô hình Agile tự do và thiếu hầu hết các tài liệu quy trình chuẩn. Em lập lộ trình thu hẹp khoảng cách (Gap Analysis & Roadmap) như thế nào?",
    ["Thực hiện Đánh giá khoảng cách (Gap Analysis): so sánh hiện trạng thực tế của dự án với các mục tiêu và thực hành cụ thể của CMMI Level 3", "Lập lộ trình từng bước (CMMI Roadmap): chuẩn hóa các quy trình cốt lõi trước (Quản lý yêu cầu, Lập kế hoạch, Đảm bảo chất lượng, Quản lý cấu hình)", "Dung hòa giữa Agile và CMMI: giữ tính linh hoạt và tốc độ của Agile nhưng bổ sung các bằng chứng kiểm soát chất lượng cần thiết (Agile-CMMI hybrid)"],
    ["Làm thế nào để tránh biến việc tuân thủ CMMI thành một gánh nặng hành chính giấy tờ vô nghĩa?", "Cách chuẩn bị hồ sơ bằng chứng (Artifact Repository) sẵn sàng cho đợt đánh giá chính thức của chuyên gia thẩm định (Lead Appraiser)?"] ,
    ["CMMI Level 3", "Gap Analysis", "Agile CMMI Hybrid", "Process Transformation"],
    [TEST_SRC.internal],
    ["Áp đặt máy móc toàn bộ quy trình sách vở khiến đội ngũ bị quá tải giấy tờ và tê liệt tốc độ phát triển"]
  ),

  // CV Validation (5)
  q("QC-CV-01", "QC Specialist", "cv_validation", "advanced", "senior_lead",
    "Trong các dự án trên CV mà em đảm nhận vai trò QC Specialist: Dự án áp dụng tiêu chuẩn chất lượng hoặc quy trình nào (ISO 9001, ISO 27001, CMMI, hoặc Agile SOP)? Em đã đóng góp gì cụ thể vào việc xây dựng hoặc cải tiến quy trình kiểm soát chất lượng đó?",
    ["Trình bày cụ thể tiêu chuẩn chất lượng áp dụng và vai trò cá nhân trong việc ban hành hoặc giám sát quy trình", "Dẫn chứng quy trình cụ thể do chính mình cải tiến (vd: tái cấu trúc checklist nghiệm thu, chuẩn hóa quy trình release)", "Số liệu định lượng chứng minh hiệu quả: giảm thời gian nghiệm thu, giảm tỷ lệ lỗi lọt, tăng điểm hài lòng của khách hàng"],
    ["Khó khăn lớn nhất khi thuyết phục các đội ngũ kỹ thuật tuân thủ quy trình chất lượng mới là gì?", "Nếu được thay đổi một điều trong quy trình chất lượng cũ đó, em sẽ thay đổi điều gì?"] ,
    ["Quality Standards", "Process Improvement", "Compliance", "CV Deep Dive"],
    [TEST_SRC.internal],
    ["Ghi tên các chứng chỉ hoặc tiêu chuẩn trên CV nhưng không hiểu nguyên lý vận hành thực tế trong dự án"]
  ),
  q("QC-CV-02", "QC Specialist", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kinh nghiệm quản lý và điều phối các đợt kiểm thử nghiệm thu UAT với khách hàng doanh nghiệp lớn (Enterprise). Hãy chia sẻ cách em thiết lập tiêu chí ký nghiệm thu (Sign-off Criteria) và xử lý các tranh chấp về lỗi trong dự án đó?",
    ["Mô tả quy mô đợt UAT: số lượng người dùng tham gia, số lượng kịch bản nghiệp vụ, thời gian diễn ra", "Tiêu chí Sign-off rõ ràng: 100% kịch bản nghiệp vụ chính được thông qua, 0 lỗi mức độ 1 và mức độ 2, các lỗi mức độ 3 có cam kết lộ trình sửa chữa", "Cách giải quyết tranh chấp: đối chiếu tài liệu phạm vi ban đầu và tổ chức trao đổi trực tiếp tìm giải pháp kỹ thuật dung hòa"],
    ["Làm thế nào để hỗ trợ khách hàng không rành công nghệ hoàn thành bài kiểm thử UAT đúng hạn?", "Kinh nghiệm soạn thảo biên bản bàn giao và bảo hành sản phẩm sau UAT?"] ,
    ["Enterprise UAT", "Sign-off Criteria", "Dispute Resolution", "Customer Alignment", "CV Verification"],
    [TEST_SRC.internal],
    ["Không nêu được tiêu chí nghiệm thu cụ thể và cho rằng UAT kết thúc khi khách hàng không phàn nàn gì nữa"]
  ),
  q("QC-CV-03", "QC Specialist", "cv_validation", "intermediate", "middle",
    "Em ghi nhận kinh nghiệm thực hiện Phân tích nguyên nhân gốc rễ (RCA) cho các sự cố chất lượng trên CV. Hãy dẫn chứng một ca sự cố cụ thể mà phân tích RCA của em đã giúp thay đổi tận gốc quy trình làm việc của công ty?",
    ["Tường thuật sự cố cụ thể: nguyên nhân bề mặt là gì và sau khi đào sâu 5 Whys thì phát hiện ra nguyên nhân cốt lõi ở đâu (vd: do thiếu môi trường test giống thật hoặc do yêu cầu nghiệp vụ bị hiểu sai)", "Hành động phòng ngừa (CAPA) được đưa ra và áp dụng cho toàn công ty", "Kết quả theo dõi sau 6 tháng: không còn bất kỳ sự cố tương tự nào tái diễn trong toàn bộ tổ chức"],
    ["Làm thế nào để đảm bảo các hành động CAPA được thực thi nghiêm túc chứ không chỉ nằm trên giấy tờ?", "Cách lưu trữ và chia sẻ bài học kinh nghiệm cho các dự án mới gia nhập?"] ,
    ["RCA Case Study", "5 Whys", "Process Transformation", "CAPA Success", "CV Verification"],
    [TEST_SRC.internal],
    ["Kể về một lần sửa lỗi thông thường của lập trình viên thay vì một phân tích nguyên nhân gốc rễ ở tầng quy trình"]
  ),
  q("QC-CV-04", "QC Specialist", "cv_validation", "advanced", "senior_lead",
    "Em hãy kể về một lần em kiên quyết từ chối ký duyệt xuất xưởng một sản phẩm phần mềm (Rejection of Release) trên dự án CV vì không đạt tiêu chuẩn chất lượng, dù phải chịu áp lực rất lớn từ các bên liên quan?",
    ["Trình bày cụ thể bối cảnh: sản phẩm vi phạm tiêu chí chất lượng nào (lỗi bảo mật, hiệu năng không đạt, rò rỉ dữ liệu)", "Áp lực phải đối mặt: sức ép từ Giám đốc kinh doanh hoặc Quản lý dự án về việc giao hàng đúng hẹn", "Cách xử lý dũng cảm và chuyên nghiệp: bảo vệ lập trường dựa trên dữ liệu phân tích rủi ro, đưa ra phương án khắc phục và kết quả cuối cùng đã chứng minh quyết định từ chối là hoàn toàn chính xác"],
    ["Lãnh đạo công ty đã phản ứng như thế nào sau khi hiểu rõ rủi ro mà em đã giúp ngăn chặn?", "Bài học về bản lĩnh nghề nghiệp của một người kiểm soát chất lượng là gì?"] ,
    ["Release Rejection", "Quality Gatekeeper", "Ethical Decision", "Courage", "CV Verification"],
    [TEST_SRC.internal],
    ["Thừa nhận mình luôn luôn ký duyệt mọi thứ theo lệnh của sếp và chưa bao giờ dám từ chối điều gì"]
  ),
  q("QC-CV-05", "QC Specialist", "cv_validation", "intermediate", "middle",
    "Trong dự án xây dựng hệ thống báo cáo và bảng điều khiển chỉ số chất lượng (Quality Metrics Dashboard) trên CV, em đã thu thập dữ liệu từ những nguồn nào và ban giám đốc đã sử dụng các chỉ số đó để ra quyết định kinh doanh ra sao?",
    ["Nguồn thu thập dữ liệu: Jira API (dữ liệu bug), GitHub/GitLab (tần suất commit và PR review), SonarQube (độ sạch của code), Zendesk (phản hồi khách hàng)", "Các chỉ số chính hiển thị: Defect Density, MTTR, DRE, Test Execution Progress, Code Coverage", "Tác động kinh doanh: giúp ban giám đốc quyết định chính xác thời điểm sản phẩm sẵn sàng mở bán rộng rãi ra thị trường"],
    ["Làm thế nào để tự động hóa việc cập nhật dữ liệu lên dashboard mà không phải làm báo cáo Excel thủ công hàng tuần?", "Cách giải thích các chỉ số kỹ thuật cho ban lãnh đạo không chuyên về công nghệ hiểu được?"] ,
    ["Quality Dashboard", "Automated Metrics", "Executive Decision", "Data-driven Management", "CV Verification"],
    [TEST_SRC.internal],
    ["Chỉ làm báo cáo thủ công bằng file Word/Excel gửi email mà không có hệ thống theo dõi trực quan"]
  ),

  // Behavioral (5)
  q("QC-BEHAV-01", "QC Specialist", "behavioral", "intermediate", "middle",
    "Bộ phận Kiểm soát chất lượng (QC) thường bị xem là 'người đi phán xét', 'kẻ khó tính làm chậm tiến độ' của các đội ngũ phát triển. Em làm thế nào để thay đổi định kiến này và xây dựng hình ảnh QC như một đối tác hỗ trợ (Supportive Partner) đồng hành cùng thành công của dự án?",
    ["Chủ động tham gia sớm với thái độ hỗ trợ: cung cấp checklist rõ ràng ngay từ đầu để dev biết tiêu chuẩn cần đạt, không 'đánh úp' vào phút chót", "Giải thích rõ ràng mục tiêu: QC không phải đi tìm người có lỗi mà là cùng nhau bảo vệ sản phẩm trước khi đến tay khách hàng", "Ghi nhận và tôn vinh những nỗ lực làm tốt của đội ngũ phát triển; luôn đưa ra giải pháp khắc phục đi kèm thay vì chỉ chỉ trích điểm yếu"],
    ["Làm thế nào để xây dựng sự tin tưởng và tôn trọng từ các kỹ sư phần mềm cao cấp?", "Cách xử lý khi một thành viên trong nhóm có thái độ bất hợp tác khi QC kiểm tra hồ sơ?"] ,
    ["Quality Mindset", "Partnering not Policing", "Interpersonal Skills", "Culture Building"],
    [TEST_SRC.internal],
    ["Hành xử như một cảnh sát quan liêu chỉ biết hạch sách và bắt bẻ đồng nghiệp"]
  ),
  q("QC-BEHAV-02", "QC Specialist", "behavioral", "advanced", "senior_lead",
    "Khi có sự bất đồng lớn giữa Tiêu chuẩn Chất lượng lý thuyết và Áp lực Thực tế kinh doanh (Thị trường đòi hỏi phải ra mắt ngay nếu không sẽ mất khách hàng vào tay đối thủ), em cân bằng giữa nguyên tắc và sự linh hoạt thực tế (Pragmatism) ra sao?",
    ["Tư duy linh hoạt có kiểm soát: chất lượng không phải là sự hoàn hảo tuyệt đối mà là sự phù hợp với mục đích sử dụng (Fitness for purpose)", "Đánh giá mức độ rủi ro có thể chấp nhận được: phân biệt giữa lỗi an toàn nghiêm trọng (tuyệt đối không thỏa hiệp) và các lỗi trải nghiệm nhỏ (có thể chấp nhận khắc phục sau)", "Xây dựng phương án phát hành có kiểm soát: giới hạn số lượng người dùng thử nghiệm ban đầu (Beta release) kèm theo cam kết lộ trình hoàn thiện chất lượng ngay sau đó"],
    ["Làm thế nào để văn bản hóa các cam kết nợ kỹ thuật (Tech Debt) và kế hoạch trả nợ chất lượng sau khi phát hành?", "Bài học về việc không cứng nhắc giáo điều trong kinh doanh là gì?"] ,
    ["Pragmatic Quality", "Business Alignment", "Controlled Risk", "Flexibility"],
    [TEST_SRC.internal],
    ["Cứng nhắc giáo điều từ chối mọi sự linh hoạt khiến công ty mất cơ hội kinh doanh sống còn"]
  ),
  q("QC-BEHAV-03", "QC Specialist", "behavioral", "intermediate", "middle",
    "Khi một khách hàng giận dữ phàn nàn gay gắt về chất lượng sản phẩm trong buổi họp nghiệm thu, em giữ bình tĩnh, lắng nghe và dẫn dắt cuộc thảo luận quay trở lại hướng giải quyết vấn đề chuyên nghiệp như thế nào?",
    ["Giữ thái độ điềm tĩnh, lắng nghe thấu cảm và không ngắt lời hay tranh cãi phòng thủ khi khách hàng đang bức xúc", "Ghi nhận đầy đủ các phản ánh cụ thể của khách hàng, xác nhận lại để đảm bảo đã hiểu đúng trọng tâm vấn đề", "Chuyển hướng cuộc trò chuyện sang kế hoạch hành động: trình bày rõ ràng các bước cô lập sự cố, cam kết thời hạn khắc phục và phương thức cập nhật tiến độ minh bạch cho khách hàng"],
    ["Tại sao việc xin lỗi chân thành về trải nghiệm không tốt của khách hàng lại giúp hạ nhiệt căng thẳng nhanh chóng?", "Làm thế nào để bảo vệ đội ngũ kỹ thuật nội bộ trước các chỉ trích quá đà của khách hàng?"] ,
    ["Customer De-escalation", "Crisis Communication", "Active Listening", "Professional Composure"],
    [TEST_SRC.internal],
    ["Tranh cãi đôi co với khách hàng hoặc đổ lỗi cho khách hàng không biết dùng phần mềm"]
  ),
  q("QC-BEHAV-04", "QC Specialist", "behavioral", "basic", "junior",
    "Khi bản thân em vô tình phát hiện ra một tài liệu nghiệm thu quan trọng do chính mình ký duyệt trước đây có một sai sót số liệu, em hành động và chịu trách nhiệm ra sao?",
    ["Trung thực và minh bạch: chủ động báo cáo ngay lập tức cho quản lý trực tiếp và các bên liên quan về sai sót phát hiện được, không che giấu", "Đánh giá ngay mức độ ảnh hưởng của sai sót đó đến các quyết định hoặc giai đoạn tiếp theo của dự án", "Đề xuất phương án đính chính chính thức bằng phụ lục hoặc bản hiệu chỉnh tài liệu, rút kinh nghiệm sâu sắc để kiểm tra kỹ lưỡng hơn trong tương lai"],
    ["Tại sao tính liêm chính và trung thực lại là phẩm chất số 1 của một người làm công tác kiểm soát chất lượng?", "Làm thế nào để duy trì sự cẩn trọng và không bị cuốn theo thói quen kiểm tra qua loa?"] ,
    ["Professional Integrity", "Accountability", "Self-Correction", "Transparency"],
    [TEST_SRC.internal],
    ["Âm thầm sửa tài liệu lén lút hoặc che giấu sai sót với hy vọng không ai phát hiện ra"]
  ),
  q("QC-BEHAV-05", "QC Specialist", "behavioral", "advanced", "senior_lead",
    "Làm thế nào để em thúc đẩy và lan tỏa 'Văn hóa Chất lượng Tự thân' (Quality Culture) trong toàn công ty, để mỗi lập trình viên, designer, và product manager đều tự giác xem mình là một người kiểm soát chất lượng?",
    ["Tuyên truyền triết lý: 'Chất lượng không thể kiểm tra vào một sản phẩm, nó phải được xây dựng vào sản phẩm ngay từ đầu'", "Công khai minh bạch các chỉ số chất lượng và vinh danh các cá nhân, dự án có sáng kiến nâng cao chất lượng tiêu biểu", "Tổ chức các chương trình đào tạo nội bộ thực tế, cung cấp các bộ công cụ tự kiểm tra (Self-check tools) giúp các thành viên dễ dàng làm đúng ngay từ lần đầu tiên"],
    ["Làm thế nào để gắn chất lượng vào tiêu chí đánh giá hiệu quả công việc (KPIs/OKRs) của toàn bộ nhân viên?", "Cách duy trì ngọn lửa nhiệt huyết về chất lượng trong một tổ chức đang phát triển nóng?"] ,
    ["Quality Culture", "Whole Team Quality", "Leadership Advocacy", "Continuous Excellence"],
    [TEST_SRC.internal],
    ["Xem chất lượng là việc độc quyền của riêng phòng QC và để mặc các bộ phận khác làm việc thiếu trách nhiệm"]
  )
];

console.log("QC questions defined:", qcQuestions.length);
module.exports = { qcQuestions };
