const { q, SRC } = require('./fe_data.cjs');

const rnQuestions = [
  // Foundation (6)
  q("RN-FOUND-01", "React Native Developer", "foundation", "intermediate", "middle",
    "Giải thích kiến trúc New Architecture của React Native: Sự khác biệt cơ bản giữa cơ chế cũ (Old Bridge bất đồng bộ qua JSON) và kiến trúc mới (JavaScript Interface - JSI, Fabric Renderer, TurboModules) là gì?",
    ["Old Bridge: serialize/deserialize dữ liệu JSON qua hàng đợi bất đồng bộ gây nghẽn cổ chai (Bridge bottleneck)", "JSI: cho phép JavaScript giữ tham chiếu trực tiếp đến các đối tượng C++ Host Objects mà không cần serialize JSON", "Fabric Renderer: hỗ trợ render đồng bộ, tích hợp sâu với React 18 Concurrent features; TurboModules: tải module lười (lazy loading)"],
    ["Tại sao JSI giúp các thao tác cử chỉ vuốt chạm và animation 60fps mượt mà hơn trước?", "Quá trình chuyển đổi từ Old Architecture sang New Architecture gặp những rào cản tương thích nào với các thư viện cũ?"],
    ["New Architecture", "JSI", "Fabric", "TurboModules", "Bridge"],
    [SRC.rn],
    ["Cho rằng React Native biên dịch mã nguồn JavaScript thành mã máy mã Swift/Kotlin trực tiếp"]
  ),
  q("RN-FOUND-02", "React Native Developer", "foundation", "intermediate", "middle",
    "Công cụ máy ảo JavaScript Hermes Engine đóng vai trò gì trong React Native? Tại sao Hermes giúp cải thiện đáng kể thời gian khởi động (Time to Interactive - TTI), dung lượng bộ nhớ RAM và kích thước app?",
    ["Hermes biên dịch trước mã JavaScript thành mã bytecode tối ưu lúc build-time (AOT Compilation) thay vì JIT lúc runtime", "Cơ chế Garbage Collection tối ưu riêng biệt cho môi trường thiết bị di động với bộ nhớ hạn chế", "Giảm thiểu thời gian phân tích cú pháp (parsing) và biên dịch script khi người dùng mở ứng dụng lần đầu (Cold Start)"],
    ["Khi nào việc bật Hermes có thể gây lỗi không tương thích với một số tính năng JavaScript hiện đại (như Intl hoặc Proxy cũ)?", "Làm thế nào để phân tích CPU và Heap profile của Hermes bằng Chrome DevTools hoặc Flipper?"] ,
    ["Hermes Engine", "Bytecode", "TTI", "Garbage Collection", "Performance"],
    ["https://hermesengine.dev/"],
    ["Không biết Hermes Engine là gì và nghĩ rằng React Native luôn dùng JavaScriptCore mặc định"]
  ),
  q("RN-FOUND-03", "React Native Developer", "foundation", "basic", "junior",
    "Trong React Native, sự khác biệt giữa JavaScript Thread và UI Thread (Native Main Thread) là gì? Hiện tượng sụt giảm khung hình (Frame Drop) khi chạy animation nặng xảy ra do nguyên nhân nào?",
    ["JavaScript Thread: xử lý logic React, tính toán state, gọi API và chạy các hàm JS", "UI Thread: phụ trách vẽ pixel, xử lý cử chỉ vuốt chạm và animation native", "Nếu JS Thread bị block bởi tác vụ tính toán nặng, animation dựa trên JS sẽ bị giật lag; cần dùng `useNativeDriver: true` hoặc Reanimated để đẩy tính toán sang UI Thread"],
    ["React Native Reanimated thực thi code animation trên UI Thread thông qua cơ chế Worklet như thế nào?", "Sự khác biệt giữa layout engine Yoga (Flexbox C++) và layout engine của trình duyệt web?"] ,
    ["JS Thread", "UI Thread", "useNativeDriver", "Reanimated", "Yoga"],
    [SRC.rn],
    ["Không phân biệt được tác vụ nào đang chạy trên JS Thread và tác vụ nào chạy trên UI Thread"]
  ),
  q("RN-FOUND-04", "React Native Developer", "foundation", "intermediate", "middle",
    "Cơ chế Layout Yoga Engine trong React Native: Yoga hiện thực hóa Flexbox CSS trên C++ để tương thích cả iOS và Android như thế nào? Những thuộc tính CSS Web nào KHÔNG được hỗ trợ hoặc có hành vi khác trong React Native?",
    ["Yoga tính toán layout dựa trên Flexbox tiêu chuẩn và gán tọa độ x, y, width, height trực tiếp cho các view native", "Sự khác biệt cốt lõi: `flexDirection` mặc định là `column` (không phải `row` như web), không hỗ trợ CSS Grid, không kế thừa style (no cascading)", "Đơn vị kích thước trong React Native là Density-independent Pixels (dp/pt), không có `px`, `rem`, `em`"],
    ["Tại sao việc lồng ghép quá nhiều tầng View có thể làm suy giảm hiệu năng tính toán layout của Yoga?", "Cơ chế hiển thị văn bản (Text component) trong React Native có gì đặc thù so với thẻ `span`/`p` trên Web?"] ,
    ["Yoga Engine", "Flexbox", "Layout Architecture", "Styling Differences"],
    ["https://yogalayout.dev/"],
    ["Nhầm lẫn flex-direction mặc định của React Native giống như CSS trên trình duyệt web"]
  ),
  q("RN-FOUND-05", "React Native Developer", "foundation", "advanced", "senior_lead",
    "Quy trình xây dựng một Native Module tùy chỉnh (Custom Native Module) trong React Native: Làm thế nào để viết mã Swift/Objective-C trên iOS và Kotlin/Java trên Android để phơi bày (expose) một tính năng phần cứng sang JavaScript?",
    ["iOS: dùng macro `RCT_EXPORT_MODULE()` và `RCT_EXPORT_METHOD()`, trả kết quả qua Callback hoặc Promise", "Android: kế thừa `ReactContextBaseJavaModule`, dùng annotation `@ReactMethod`, xử lý luồng background an toàn", "Với kiến trúc mới TurboModules: định nghĩa giao diện trừu tượng bằng TypeScript/Flow Spec và Codegen tự sinh mã C++"],
    ["Làm thế nào để gửi sự kiện (Event Emitter) từ Native ngược về JavaScript mà không cần JS chủ động gọi hàm?", "Cách xử lý đồng bộ luồng (Thread Safety) khi gọi phương thức native từ JS?"] ,
    ["Native Modules", "TurboModules", "Codegen", "Swift", "Kotlin"],
    [SRC.rn],
    ["Chỉ biết cài thư viện có sẵn qua npm mà không hiểu cấu trúc của một Native Module bên dưới"]
  ),
  q("RN-FOUND-06", "React Native Developer", "foundation", "basic", "junior",
    "Các giải pháp lưu trữ dữ liệu ngoại tuyến (Offline Storage) trong React Native: So sánh AsyncStorage, MMKV (Tencent), WatermelonDB và SQLite. Tại sao react-native-mmkv có tốc độ đọc ghi nhanh gấp hàng chục lần AsyncStorage?",
    ["AsyncStorage lưu trữ qua SQLite/file và truyền dữ liệu bất đồng bộ qua Bridge, tốc độ chậm khi đọc ghi lượng lớn", "MMKV sử dụng cơ chế Memory-mapped file (mmap) trong C++ kết hợp JSI, cho phép đọc ghi đồng bộ tức thì trực tiếp vào RAM", "WatermelonDB và SQLite tối ưu cho dữ liệu quan hệ phức tạp, hỗ trợ truy vấn dải và quan sát thay đổi (Observable)"],
    ["Khi nào việc lưu dữ liệu đồng bộ bằng MMKV có thể gây block JS Thread nếu lạm dụng lưu trữ object quá lớn?", "Làm thế nào để mã hóa dữ liệu nhạy cảm được lưu trong MMKV bằng khóa bảo mật?"] ,
    ["MMKV", "AsyncStorage", "SQLite", "mmap", "Offline Storage"],
    ["https://github.com/mrousavy/react-native-mmkv"],
    ["Mặc định sử dụng AsyncStorage để lưu toàn bộ cache dữ liệu lớn của ứng dụng"]
  ),

  // Practical Skills (8)
  q("RN-SKILL-01", "React Native Developer", "practical_skills", "advanced", "senior_lead",
    "Tối ưu hóa hiệu năng FlatList và FlashList: Khi danh sách chứa hàng nghìn bài viết có ảnh và video, em cấu hình các thuộc tính `getItemLayout`, `windowSize`, `maxToRenderPerBatch`, `removeClippedSubviews` ra sao để tránh màn hình trắng khi cuộn nhanh?",
    ["Cung cấp `getItemLayout` để bỏ qua bước đo đạc kích thước động của các item có chiều cao cố định", "Tinh chỉnh `windowSize` (mặc định 21) giảm xuống khoảng 5-7 để tiết kiệm RAM và giảm số phần tử trong bộ nhớ", "Sử dụng FlashList của Shopify để tái sử dụng view theo cơ chế recycling tương tự RecyclerView thay vì unmount DOM liên tục"],
    ["Tại sao việc truyền hàm ẩn danh (anonymous inline functions) vào `renderItem` lại làm mất tác dụng của `React.memo`?", "Cách xử lý danh sách có chiều cao phần tử biến thiên phức tạp trong FlashList?"] ,
    ["FlatList", "FlashList", "Performance Optimization", "List Recycling"],
    ["https://shopify.github.io/flash-list/"],
    ["Tăng số lượng render ban đầu (initialNumToRender) lên tối đa để chống màn hình trắng khiến app bị đơ ngay khi mở"]
  ),
  q("RN-SKILL-02", "React Native Developer", "practical_skills", "intermediate", "middle",
    "Em xây dựng các hoạt cảnh phức tạp và tương tác cử chỉ mượt mà (Gestures & Animations) bằng React Native Reanimated và Gesture Handler như thế nào? Tại sao không nên dùng Animated API mặc định cho các cử chỉ phức tạp?",
    ["Animated API mặc định phải gửi event qua Bridge về JS Thread để tính toán rồi gửi ngược lại, gây độ trễ và giật lag cử chỉ", "Reanimated chạy toàn bộ logic animation và gesture trên UI Thread bằng Worklets thông qua JSI", "Kết hợp `GestureDetector` với các hàm shared values (`useSharedValue`, `useAnimatedStyle`) để tạo hiệu ứng vuốt đóng thẻ hoặc kéo thả mượt 120fps"],
    ["Worklet là gì và cơ chế biên dịch Babel plugin biến đổi hàm JS thành Worklet ra sao?", "Làm thế nào để xử lý layout animation tự động khi thêm/xóa phần tử bằng Reanimated?"] ,
    ["Reanimated", "Gesture Handler", "Worklets", "UI Thread Animation"],
    ["https://docs.swmansion.com/react-native-reanimated/"],
    ["Sử dụng setState thông thường bên trong callback cử chỉ vuốt làm nghẽn JS Thread"]
  ),
  q("RN-SKILL-03", "React Native Developer", "practical_skills", "intermediate", "middle",
    "Em triển khai giải pháp Cập nhật qua mạng (Over-The-Air - OTA Updates) bằng CodePush hoặc Expo Updates như thế nào? Những thay đổi nào KHÔNG THỂ cập nhật qua OTA mà bắt buộc phải submit bản build mới lên App Store/Google Play?",
    ["OTA chỉ có thể cập nhật gói bundle JavaScript và các tài nguyên hình ảnh tĩnh (assets)", "Mọi thay đổi liên quan đến Native Code (cài thêm thư viện native mới, sửa Podfile, sửa build.gradle, đổi quyền hệ thống) đều không thể cập nhật qua OTA", "Thiết lập cơ chế Rollback tự động nếu bản bundle mới tải về bị crash ngay khi khởi động (Rollback on error)"],
    ["Quy định của Apple App Store (Điều khoản 3.3.2) về việc cập nhật code qua OTA cho phép những gì và cấm những gì?", "Làm thế nào để chia nhỏ việc phát hành OTA theo tỷ lệ phần trăm (Targeted Rollout)?"] ,
    ["CodePush", "OTA Updates", "Expo Updates", "Release Strategy"],
    [SRC.rn],
    ["Nghĩ rằng có thể thêm thư viện Native mới bằng OTA mà không cần build lại file APK/IPA"]
  ),
  q("RN-SKILL-04", "React Native Developer", "practical_skills", "advanced", "senior_lead",
    "Quy trình nâng cấp phiên bản React Native (React Native Upgrade): Em sử dụng công cụ React Native Upgrade Helper để xử lý các xung đột native code (Podfile, Gradle, AppDelegate, MainApplication) giữa các phiên bản lớn ra sao?",
    ["Đọc kỹ bản so sánh diff trên Upgrade Helper giữa phiên bản cũ và phiên bản đích", "Cập nhật từng bước: nâng cấp file package.json, dọn dẹp node_modules, cập nhật Podfile/build.gradle, resolve conflict trong native code", "Chạy thử nghiệm toàn diện trên cả iOS Simulator và Android Emulator, kiểm tra tính tương thích của tất cả các thư viện thứ ba"],
    ["Khi nào nên cân nhắc tạo một dự án mới hoàn toàn ở phiên bản đích rồi chuyển code sang thay vì upgrade in-place?", "Chiến lược xử lý khi một thư viện native quan trọng chưa hỗ trợ phiên bản React Native mới nhất là gì?"] ,
    ["Upgrade Helper", "Dependency Management", "Gradle", "CocoaPods", "Maintenance"],
    ["https://react-native-community.github.io/upgrade-helper/"],
    ["Chỉ tăng số phiên bản trong package.json rồi chạy npm install mà không cập nhật các tệp native"]
  ),
  q("RN-SKILL-05", "React Native Developer", "practical_skills", "intermediate", "middle",
    "Em tổ chức điều hướng ứng dụng bằng React Navigation (Stack, Tab, Drawer, Modal) như thế nào? Cách cấu trúc TypeScript Types cho các màn hình và tham số điều hướng (Navigation Prop Type-Safety)?",
    ["Định nghĩa kiểu dữ liệu `RootStackParamList` ánh xạ tên màn hình với kiểu dữ liệu của params", "Sử dụng `NativeStackNavigationProp` và `RouteProp` để đảm bảo type-safety hoàn hảo lúc truyền và nhận params", "Tối ưu hóa bộ nhớ: chỉ nạp màn hình khi cần thiết (unmountInactiveRoutes) và tránh lồng ghép quá nhiều Navigator phức tạp"],
    ["Sự khác biệt giữa JS-based Stack Navigator và Native Stack Navigator (sử dụng UINavigationController/Fragment) là gì?", "Làm thế nào để đồng bộ trạng thái điều hướng với Universal Links và Deep Linking?"] ,
    ["React Navigation", "Native Stack", "Type Safety", "Deep Linking"],
    ["https://reactnavigation.org/docs/typescript/"],
    ["Truyền các object dữ liệu quá lớn hoặc callback functions qua route params gây lỗi cảnh báo non-serializable values"]
  ),
  q("RN-SKILL-06", "React Native Developer", "practical_skills", "intermediate", "middle",
    "Em thiết lập quy trình kiểm thử tự động cho dự án React Native: Cách sử dụng React Native Testing Library (RNTL) để kiểm thử component và Maestro / Detox để kiểm thử E2E trên ứng dụng thật?",
    ["RNTL kiểm thử hành vi người dùng (fireEvent, waitFor, findByText) dựa trên component render cô lập không cần native runtime", "Maestro viết kịch bản E2E bằng YAML trực quan, chạy trực tiếp trên simulator với tốc độ cao và ít bị flaky", "Detox chạy E2E với cơ chế Gray-box synchronization, tự động chờ JS Thread và UI Thread nhàn rỗi mới thực thi lệnh tiếp theo"],
    ["Tại sao việc test component với Jest trong React Native cần mock rất nhiều native modules?", "Làm thế nào để thiết lập CI tự động chạy Maestro tests trên GitHub Actions?"] ,
    ["Testing", "RNTL", "Maestro", "Detox", "E2E Testing"],
    ["https://callstack.github.io/react-native-testing-library/"],
    ["Không viết bất kỳ unit test nào và cho rằng React Native rất khó để tự động hóa kiểm thử"]
  ),
  q("RN-SKILL-07", "React Native Developer", "practical_skills", "intermediate", "middle",
    "Em quản lý các biến môi trường nhạy cảm và cấu hình nhiều phiên bản app (Staging, Production với Bundle ID / Package Name khác nhau) trong React Native bằng phương pháp nào?",
    ["Sử dụng Build Flavors trên Android (staging/prod trong build.gradle) và Schemes/Configurations trên iOS (Xcode Schemes)", "Tách biệt Application ID / Bundle ID để có thể cài đặt đồng thời cả bản Test và bản Production trên cùng một điện thoại", "Dùng `react-native-config` để truyền biến môi trường vào cả native code (AndroidManifest, Info.plist) và JavaScript"],
    ["Làm thế nào để đổi icon và tên hiển thị của app theo từng build flavor tự động?", "Cách bảo vệ các API keys quan trọng không bị lộ khi phân tích file APK bằng decompiler?"] ,
    ["Build Flavors", "Xcode Schemes", "Environment Configuration", "Multi-environment"],
    [SRC.internal],
    ["Thay đổi thủ công biến môi trường trong code trước mỗi lần build và xuất file cài đặt"]
  ),
  q("RN-SKILL-08", "React Native Developer", "practical_skills", "advanced", "senior_lead",
    "Làm thế nào để sử dụng Flipper, React DevTools Profiler và Xcode Instruments / Android Studio Profiler để phát hiện rò rỉ bộ nhớ (Memory Leak) và tối ưu hóa thời gian khởi động (Startup Time) trong React Native?",
    ["Sử dụng React DevTools Profiler để theo dõi các component bị re-render liên tục trên JS Thread", "Dùng Xcode Instruments (Allocations, Time Profiler) để tìm kiếm các native view không được thu hồi bộ nhớ", "Phân tích Startup Time bằng Android Systrace / Perfetto để đo chính xác thời gian nạp native framework, khởi tạo JS engine và chạy root component"],
    ["Làm thế nào để đo lường chỉ số JS Heap Size trong môi trường production thông qua Crashlytics hoặc New Relic?", "Kỹ thuật Inline Requires hỗ trợ giảm thời gian khởi động ban đầu ra sao?"] ,
    ["Profiling", "Instruments", "Flipper", "Memory Leak", "Startup Optimization"],
    [SRC.rn],
    ["Chỉ dựa vào cảm tính cá nhân khi đánh giá ứng dụng nhanh hay chậm mà không dùng công cụ đo đạc số liệu"]
  ),

  // Scenario (6)
  q("RN-SCEN-01", "React Native Developer", "scenario", "intermediate", "middle",
    "Tình huống: Người dùng phàn nàn rằng khi gõ bàn phím vào ô nhập liệu TextInput trên Android thì bàn phím che mất nút bấm Xác nhận, còn trên iOS thì giao diện bị đẩy lên quá cao để lại khoảng trống trắng. Em xử lý vấn đề Keyboard Handling đa nền tảng ra sao?",
    ["Sử dụng thư viện chuyên dụng như `react-native-keyboard-controller` hoặc `KeyboardAvoidingView` với cấu hình riêng cho từng OS", "Trên iOS: dùng behavior `padding` kết hợp `keyboardVerticalOffset`; trên Android: cấu hình `windowSoftInputMode='adjustResize'` trong AndroidManifest", "Bọc form bên trong `ScrollView` có thuộc tính `keyboardShouldPersistTaps='handled'` để người dùng có thể chạm ngoài màn hình đóng bàn phím"],
    ["Tại sao KeyboardAvoidingView mặc định của React Native thường hoạt động không nhất quán trên các thiết bị Android?", "Cách xử lý bàn phím mượt mà khi kết hợp với Modal bottom sheet?"] ,
    ["Keyboard Handling", "TextInput", "KeyboardAvoidingView", "Cross-platform UI"],
    [SRC.internal],
    ["Hardcode số pixel đẩy màn hình cố định khiến giao diện bị vỡ trên các thiết bị có kích thước màn hình khác nhau"]
  ),
  q("RN-SCEN-02", "React Native Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Sau khi người dùng mở ứng dụng và lướt xem danh sách sản phẩm khoảng 15 phút, điện thoại bắt đầu nóng lên và tốc độ khung hình sụt giảm từ 60fps xuống 15fps. Em khoanh vùng và khắc phục hiện tượng rò rỉ bộ nhớ hoặc vòng lặp tác vụ ra sao?",
    ["Kết nối app với Flipper hoặc Chrome DevTools Memory để chụp Memory Heap Snapshot tại phút thứ 1 và phút thứ 15", "Kiểm tra xem có component nào unmount nhưng không dọn dẹp interval, event listener hoặc subscription (Redux/EventEmitter)", "Rà soát cache hình ảnh xem thư viện image có giải phóng bộ nhớ đệm hay đang tích lũy hàng nghìn ảnh kích thước lớn trong RAM"],
    ["Làm thế nào để sử dụng biến cờ `isMounted` hoặc AbortController để ngăn chặn cập nhật state sau khi component đã unmount?", "Tại sao việc lưu trữ quá nhiều dữ liệu vào Redux store mà không dọn dẹp có thể làm nặng JS engine?"] ,
    ["Memory Leak", "Performance Degradation", "Heap Snapshot", "Jank Investigation"],
    [SRC.internal],
    ["Khuyên người dùng khởi động lại ứng dụng định kỳ thay vì tìm kiếm nguyên nhân rò rỉ tài nguyên"]
  ),
  q("RN-SCEN-03", "React Native Developer", "scenario", "intermediate", "middle",
    "Tình huống: Khi người dùng bấm vào đường link chia sẻ sản phẩm từ Zalo hoặc Facebook Messenger, ứng dụng React Native chỉ mở màn hình trang chủ (Home) chứ không mở đúng màn hình chi tiết sản phẩm. Em điều tra và sửa lỗi Deep Linking như thế nào?",
    ["Kiểm tra cấu hình scheme và prefixes trong cấu hình `linking` của React Navigation container", "Xử lý 2 kịch bản: Cold Start (sử dụng `getInitialURL()`) và Warm Start (lắng nghe sự kiện `Linking.addEventListener('url')`)", "Rà soát cấu hình URL parsing để đảm bảo trích xuất chính xác `productId` từ path hoặc query parameter"],
    ["Làm thế nào để test deep link nhanh chóng từ terminal bằng lệnh `adb shell am start` và `xcrun simctl openurl`?", "Khi đường link bị ứng dụng mạng xã hội mở trong In-App Browser của họ, làm sao để kích hoạt mở app chính?"] ,
    ["Deep Linking", "Universal Links", "React Navigation", "Cold Start Routing"],
    [SRC.internal],
    ["Chỉ kiểm tra khi app đang mở sẵn mà bỏ qua trường hợp app bị đóng hoàn toàn từ trước"]
  ),
  q("RN-SCEN-04", "React Native Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Đội ngũ cập nhật một thư viện Native Module mới bằng npm nhưng lệnh `pod install` trên iOS báo lỗi xung đột phiên bản phụ thuộc (CocoaPods dependency conflict) và Android build báo lỗi trùng lặp tệp trùng tên trong `mergeDexDebug`. Các bước giải quyết xung đột của em là gì?",
    ["Trên iOS: kiểm tra file `Podfile.lock`, phân tích đồ thị phụ thuộc để xem thư viện nào đang yêu cầu phiên bản cũ hơn, dùng `pod update [pod_name]` hoặc override version", "Trên Android: kiểm tra `gradle dependencies` để tìm dependency trùng lặp, dùng lệnh `exclude group: '...', module: '...'` để loại bỏ thư viện dư thừa", "Kiểm tra tài liệu của thư viện để đảm bảo nó tương thích với phiên bản React Native hiện tại và có hỗ trợ New Architecture hay không"],
    ["Làm thế nào để sử dụng `patch-package` để sửa tạm thời lỗi biên dịch của một thư viện bên thứ ba trong node_modules?", "Sự khác biệt giữa CocoaPods truyền thống và Swift Package Manager (SPM) trong các dự án React Native mới?"] ,
    ["Dependency Conflict", "CocoaPods", "Gradle Build", "Patch-package"],
    [SRC.internal],
    ["Xóa sạch dự án tải lại từ đầu mà không hiểu bản chất xung đột của các package phụ thuộc"]
  ),
  q("RN-SCEN-05", "React Native Developer", "scenario", "intermediate", "middle",
    "Tình huống: Ứng dụng tích hợp thông báo đẩy (Push Notifications). Khi ứng dụng đang mở (Foreground), thông báo từ FCM không tự hiển thị biểu ngữ (Banner) trên màn hình iOS. Em xử lý thông báo Foreground và tương tác bấm thông báo ra sao?",
    ["iOS mặc định không hiển thị banner thông báo khi ứng dụng đang ở Foreground trừ khi cấu hình rõ trong delegate", "Sử dụng callback `willPresentNotification` trong iOS Native code hoặc cấu hình `onMessage` trong Firebase Messaging để hiển thị in-app banner hoặc notification cục bộ", "Thống nhất payload dữ liệu để khi người dùng bấm vào thông báo ở cả Foreground, Background hay Quit state đều kích hoạt điều hướng chính xác"],
    ["Làm thế nào để sử dụng thư viện Notifee để tùy biến thông báo hiển thị cục bộ mượt mà trong React Native?", "Cách xử lý số lượng huy hiệu thông báo (Badge count) trên icon ứng dụng?"] ,
    ["Push Notification", "Foreground Notification", "FCM", "Notifee"],
    [SRC.internal],
    ["Cho rằng thông báo không hiển thị ở foreground là lỗi của máy chủ Firebase"]
  ),
  q("RN-SCEN-06", "React Native Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Ứng dụng tài chính ngân hàng yêu cầu phải phát hiện thiết bị đã bị can thiệp hệ thống (Root trên Android hoặc Jailbreak trên iOS) và chặn không cho mở ứng dụng để đảm bảo an toàn. Em triển khai giải pháp này và phòng chống bị bypass ra sao?",
    ["Tích hợp thư viện bảo mật native (như JailMonkey, react-native-security) kiểm tra sự tồn tại của các tệp binary nguy hiểm (su, Cydia, Frida, Magisk)", "Kiểm tra tính toàn vẹn của ứng dụng thông qua Google Play Integrity API trên Android và Apple DeviceCheck / App Attest trên iOS", "Đưa ra màn hình cảnh báo từ chối dịch vụ và xóa sạch dữ liệu phiên đăng nhập lưu trong bộ nhớ tạm"],
    ["Làm thế nào để chống kẻ tấn công can thiệp sửa đổi mã JavaScript bằng công cụ Frida để bypass hàm kiểm tra root?", "Tại sao không nên đặt tên hàm kiểm tra là `isJailbroken` một cách công khai trong mã nguồn?"] ,
    ["Root Detection", "Jailbreak Detection", "Play Integrity", "Device Security"],
    [SRC.owasp, SRC.internal],
    ["Chỉ kiểm tra đơn giản bằng một hàm JS ở client rất dễ dàng bị kẻ xấu vô hiệu hóa qua Frida"]
  ),

  // CV Validation (5)
  q("RN-CV-01", "React Native Developer", "cv_validation", "advanced", "senior_lead",
    "Trong dự án React Native tiêu biểu nhất trên CV, em đã trực tiếp viết đoạn mã Native Code (Swift hoặc Kotlin) nào để giải quyết một tính năng mà các thư viện mã nguồn mở có sẵn không đáp ứng được?",
    ["Mô tả tính năng thực tế: xử lý kết nối máy in Bluetooth đặc thù, tích hợp SDK phần cứng, xử lý camera scan mã vạch tốc độ cao", "Trình bày cách thức liên kết giữa Native Module và React Native (viết Method, Callback, Promise, Event Emitter)", "Khó khăn gặp phải về đồng bộ luồng hoặc quản trị bộ nhớ và cách giải quyết"],
    ["Tại sao em không chọn phương án chờ thư viện cộng đồng cập nhật?", "Đoạn mã native đó được kiểm thử và bảo trì như thế nào khi nâng cấp phiên bản hệ điều hành mới?"] ,
    ["Custom Native Module", "Swift", "Kotlin", "Hardware Integration", "CV Deep Dive"],
    [SRC.internal],
    ["Ghi thạo Native Module trên CV nhưng không giải thích được cấu trúc của một file module native đơn giản"]
  ),
  q("RN-CV-02", "React Native Developer", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kinh nghiệm tối ưu hóa hiệu năng ứng dụng React Native từ mức giật lag lên 60fps mượt mà. Hãy dẫn chứng màn hình cụ thể em đã tối ưu, công cụ dùng để đo đạc và các kỹ thuật đã áp dụng?",
    ["Chỉ rõ màn hình: Bảng tin cuộn dài, màn hình biểu đồ tài chính, hoặc giỏ hàng có nhiều tương tác phức tạp", "Công cụ đo lường thực tế: React DevTools Profiler, Flipper, Android GPU Rendering profile", "Kỹ thuật áp dụng: chuyển sang FlashList, áp dụng Reanimated worklets, bọc memo chuẩn xác, nén ảnh thông minh"],
    ["Chỉ số thời gian render của component trước và sau khi tối ưu giảm từ bao nhiêu ms xuống bao nhiêu ms?", "Có sự đánh đổi nào về dung lượng bộ nhớ khi áp dụng các kỹ thuật caching đó không?"] ,
    ["Performance Optimization", "60fps", "Profiler", "Case Study", "CV Verification"],
    [SRC.internal],
    ["Đưa ra con số 60fps chung chung mà không nhớ được màn hình nào và kỹ thuật cụ thể đã can thiệp"]
  ),
  q("RN-CV-03", "React Native Developer", "cv_validation", "intermediate", "middle",
    "Em ghi nhận kinh nghiệm triển khai OTA Update bằng CodePush trong dự án trên CV. Em đã thiết lập chiến lược phát hành bản cập nhật (Staged Rollout) và xử lý tình huống bản cập nhật JS bị lỗi runtime ra sao?",
    ["Cấu hình triển khai dần theo tỷ lệ phần trăm (vd: 10% -> 25% -> 100%) để theo dõi tỷ lệ crash qua Crashlytics", "Kích hoạt cơ chế tự động Rollback của CodePush nếu ứng dụng không gọi hàm `codePush.notifyAppReady()` trong lần mở đầu tiên", "Quản lý phiên bản nhắm mục tiêu (Target Binary Version) chính xác để tránh việc cập nhật bundle cho app phiên bản native cũ hơn"],
    ["Nếu bản cập nhật OTA bị lỗi nghiêm trọng làm crash app ngay lập tức, lệnh CLI nào của CodePush giúp rollback tức thời?", "Làm thế nào để hiển thị thanh tiến trình tải cập nhật ngầm cho người dùng?"] ,
    ["CodePush", "Rollback Strategy", "Target Binary Version", "CV Verification"],
    [SRC.internal],
    ["Không biết cơ chế Target Binary Version dẫn đến việc gửi bản cập nhật JS dùng tính năng native mới cho app phiên bản cũ"]
  ),
  q("RN-CV-04", "React Native Developer", "cv_validation", "advanced", "senior_lead",
    "Em hãy chia sẻ về một bug phức tạp nhất mà em từng gặp chỉ xảy ra trên phiên bản Release (Production build) nhưng hoàn toàn KHÔNG THỂ tái hiện trong môi trường Debug (Development mode)?",
    ["Phân tích nguyên nhân phổ biến: tối ưu hóa mã nguồn của ProGuard/R8 làm xóa nhầm class native cần thiết, Hermes bytecode optimization, hoặc khác biệt về tính đồng bộ I/O", "Quy trình điều tra: build bản release cục bộ có kèm source map, đọc logcat qua Android Studio và thiết lập log crash chi tiết", "Giải pháp dứt điểm: cấu hình rule giữ lại class (keep rules) trong `proguard-rules.pro` hoặc fix lỗi logic phụ thuộc timing debug"],
    ["Tại sao việc bật debugger từ xa (Remote JS Debugging) lại làm sai lệch tốc độ thực thi của Event Loop?", "Làm thế nào để debug bản release build bằng source map trong Sentry?"] ,
    ["Release-only Bug", "ProGuard Rules", "Hermes Bytecode", "Debugging", "CV Verification"],
    [SRC.internal],
    ["Bỏ qua lỗi chỉ vì 'trên máy dev của em chạy bình thường' và không biết cách build bản release để kiểm tra cục bộ"]
  ),
  q("RN-CV-05", "React Native Developer", "cv_validation", "intermediate", "middle",
    "Trong dự án đa ngôn ngữ và hỗ trợ giao diện người dùng theo hướng từ phải sang trái (RTL) trên CV, em đã tổ chức cấu trúc chuỗi ngôn ngữ và thích ứng layout Flexbox ra sao?",
    ["Sử dụng thư viện `i18next` hoặc `react-intl` quản lý tệp tài nguyên ngôn ngữ theo namespace", "Hỗ trợ RTL bằng API `I18nManager.allowRTL(true)` và sử dụng các thuộc tính hướng linh hoạt (`start`/`end` thay vì `left`/`right`)", "Khởi động lại ứng dụng tự động khi người dùng thay đổi ngôn ngữ sang khu vực có chiều văn bản ngược lại"],
    ["Tại sao việc dùng `marginRight` cố định có thể làm vỡ giao diện trên thiết bị tiếng Ả Rập (Arabic)?", "Cách định dạng ngày tháng, tiền tệ theo đúng Locale của thiết bị di động?"] ,
    ["i18n", "RTL Support", "Localization", "Flexbox Adaptation", "CV Verification"],
    [SRC.internal],
    ["Hardcode chuỗi văn bản trực tiếp trong các file component JSX"]
  ),

  // Behavioral (5)
  q("RN-BEHAV-01", "React Native Developer", "behavioral", "intermediate", "middle",
    "Khi đội ngũ Native iOS/Android trong công ty có cái nhìn nghi ngại về hiệu năng và độ ổn định của React Native, em chứng minh năng lực công nghệ và xây dựng mối quan hệ hợp tác tôn trọng lẫn nhau như thế nào?",
    ["Tôn trọng chuyên môn sâu của các kỹ sư Native và thừa nhận trung thực các giới hạn của React Native", "Chứng minh bằng số liệu thực tế: thời gian ra mắt tính năng nhanh gấp đôi, chia sẻ 80-90% mã nguồn, chỉ số FPS và độ trễ đạt chuẩn người dùng", "Chủ động học hỏi và nhờ các bạn Native hỗ trợ ở các phần việc liên quan đến hạ tầng native, bridge và CI/CD"],
    ["Làm thế nào để thúc đẩy tinh thần học hỏi chung giữa nhóm Web, nhóm Mobile Native và nhóm React Native?", "Em xử lý thế nào khi một bạn Native phản ánh rằng code React Native làm chậm ứng dụng chung?"] ,
    ["Cross-team Collaboration", "Professional Respect", "Advocacy", "Engineering Culture"],
    [SRC.internal],
    ["Tranh cãi cực đoan cho rằng React Native sẽ thay thế hoàn toàn Native hoặc ngược lại tự ti thu mình"]
  ),
  q("RN-BEHAV-02", "React Native Developer", "behavioral", "intermediate", "middle",
    "Khi có một thư viện mã nguồn mở quan trọng trong dự án bị tác giả ngừng duy trì (abandoned/deprecated) sau khi React Native nâng cấp phiên bản mới, em xử lý tình huống này thế nào để không làm đình trệ dự án?",
    ["Đánh giá mức độ phụ thuộc: thư viện làm nhiệm vụ gì, có thể tự viết thay thế bằng code nội bộ được không", "Phương án ngắn hạn: dùng `patch-package` để tự sửa lỗi biên dịch hoặc fork repository về tổ chức để duy trì", "Phương án dài hạn: tìm kiếm thư viện cộng đồng tương đương có bảo trì tích cực hoặc tự viết giải pháp riêng cho team"],
    ["Quy trình đánh giá mức độ rủi ro của một thư viện bên thứ ba trước khi quyết định đưa vào dự án là gì?", "Em đã từng đóng góp bản sửa lỗi (Pull Request) ngược lại cho cộng đồng mã nguồn mở chưa?"] ,
    ["Deprecated Library", "Open Source Maintenance", "Risk Mitigation", "Patch-package"],
    [SRC.internal],
    ["Bỏ cuộc hoặc dừng việc nâng cấp phiên bản của toàn bộ dự án chỉ vì một thư viện phụ bị lỗi"]
  ),
  q("RN-BEHAV-03", "React Native Developer", "behavioral", "basic", "junior",
    "Khi Designer yêu cầu tạo các chuyển động hoạt cảnh (animations) rất phức tạp nhưng việc triển khai có thể khiến các dòng máy Android đời cũ bị giật lag, em trao đổi và tìm điểm cân bằng với Designer ra sao?",
    ["Mang trực tiếp thiết bị Android đời cũ đến trao đổi trực tiếp với Designer để họ nhìn thấy trải nghiệm thực tế", "Giải thích nguyên nhân giới hạn phần cứng và đề xuất phương án tinh chỉnh: giữ nguyên hiệu ứng mượt mà trên máy mạnh và tự động hạ độ phức tạp trên máy yếu", "Cùng Designer thống nhất một phiên bản animation thanh lịch, tối ưu mà vẫn giữ trọn vẹn cảm xúc thương hiệu"],
    ["Làm thế nào để kiểm tra năng lực phần cứng thiết bị (low-end device detection) để giảm bớt hiệu ứng tự động?", "Cách giải thích trade-off trải nghiệm một cách thấu cảm không làm Designer nản lòng?"] ,
    ["Designer Empathy", "Hardware Constraints", "Animation Compromise", "Communication"],
    [SRC.internal],
    ["Âm thầm cắt bỏ animation mà không thông báo cho Designer hoặc cố đấm ăn xôi làm lag app của người dùng"]
  ),
  q("RN-BEHAV-04", "React Native Developer", "behavioral", "intermediate", "middle",
    "Trước hạn chót phát hành ứng dụng, Product Owner muốn đưa thêm gấp một tính năng mới vào bản build. Em phân tích quy trình kiểm duyệt của App Store (có thể mất 24-48 tiếng) và tư vấn phương án cho PO như thế nào?",
    ["Giải thích rõ ràng về chu kỳ release của Mobile: thời gian kiểm duyệt của Apple/Google nằm ngoài tầm kiểm soát của công ty", "Cảnh báo rủi ro: việc thêm tính năng gấp thiếu kiểm thử có thể dẫn đến bị rejected và làm chậm ngày ra mắt chính thức của toàn công ty", "Đề xuất phương án an toàn: phát hành bản build hiện tại đã được kiểm thử kỹ lưỡng đúng hạn, tính năng mới sẽ ra mắt ngay trong bản cập nhật tiếp theo"],
    ["Nếu PO vẫn yêu cầu phải đưa vào bằng mọi giá, em thiết lập cơ chế bảo vệ (Feature Flag / Remote Config) thế nào?", "Kinh nghiệm yêu cầu Apple duyệt khẩn cấp (Expedited Review) khi có lý do chính đáng là gì?"] ,
    ["Release Planning", "App Store Review Cycle", "Scope Management", "Stakeholder Alignment"],
    [SRC.internal],
    ["Đồng ý thêm vội vàng tính năng mới vào sát giờ submit khiến ứng dụng bị Apple từ chối và trễ kế hoạch toàn công ty"]
  ),
  q("RN-BEHAV-05", "React Native Developer", "behavioral", "advanced", "senior_lead",
    "Khi đứng trước quyết định kỹ thuật: Tiếp tục sử dụng React Native truyền thống (CLI thuần) hay chuyển dịch sang sử dụng Expo Application Services (EAS) cho các dự án mới của công ty, em phân tích bài toán ra sao?",
    ["Phân tích sự phát triển của Expo hiện đại (EAS Build, Config Plugins, Continuous Native Generation) đã giải quyết hầu hết nhược điểm trước đây", "So sánh chi phí vận hành: Expo giúp giảm tải rất lớn công sức duy trì native build environment cho các lập trình viên frontend", "Đánh giá các ranh giới: dự án có dùng SDK native nội bộ cực kỳ đặc thù không thể viết Config Plugin không để quyết định chọn lựa"],
    ["Khi nào React Native CLI truyền thống vẫn là sự lựa chọn bắt buộc cho doanh nghiệp lớn?", "Chiến lược di chuyển từ React Native CLI sang Expo Prebuild diễn ra như thế nào?"] ,
    ["Expo vs RN CLI", "EAS", "Strategic Decision", "Developer Experience"],
    [SRC.internal],
    ["Giữ định kiến cũ cho rằng 'Expo chỉ dành cho dự án học tập/đồ án sinh viên' mà không cập nhật tiến bộ công nghệ mới"]
  )
];

console.log("RN questions defined:", rnQuestions.length);
module.exports = { rnQuestions };
