const { q, SRC } = require('./fe_data.cjs');

const tsNodeQuestions = [
  // Foundation (6)
  q("TS_NODE-FOUND-01", "TypeScript / Node.js Developer", "foundation", "advanced", "senior_lead",
    "Trình bày chi tiết các pha (Phases) của Node.js Event Loop theo thứ tự thực thi: Timers, Pending Callbacks, Idle/Prepare, Poll, Check và Close Callbacks. `process.nextTick()` và microtasks (Promise) được ưu tiên thực thi ở thời điểm nào giữa các pha?",
    ["Trình bày chuẩn 6 pha: Timers (setTimeout/setInterval) -> Pending Callbacks -> Poll (I/O) -> Check (setImmediate) -> Close Callbacks", "Microtask Queue (bao gồm process.nextTick và Promise callback) được xả cạn (drained) ngay lập tức sau mỗi tick của mỗi pha trước khi chuyển sang pha tiếp theo", "Giải thích sự khác biệt giữa `process.nextTick()` (chạy trước mọi microtask khác) và `setImmediate()` (chạy trong pha Check)"],
    ["Tại sao việc gọi đệ quy `process.nextTick()` vô hạn có thể làm chết đói (I/O Starvation) toàn bộ Event Loop?", "Khi thực thi ngoài phạm vi I/O callback, thứ tự chạy giữa `setTimeout(..., 0)` và `setImmediate()` có được đảm bảo không?"] ,
    ["Node.js Event Loop", "Libuv", "process.nextTick", "setImmediate", "Microtasks"],
    ["https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick"],
    ["Nghĩ rằng Node.js Event Loop giống hệt với Browser Event Loop hoặc không biết process.nextTick chạy lúc nào"]
  ),
  q("TS_NODE-FOUND-02", "TypeScript / Node.js Developer", "foundation", "intermediate", "middle",
    "Hệ thống kiểu dữ liệu nâng cao trong TypeScript: Phân biệt `any`, `unknown` và `never`. Từ khóa `infer`, Mapped Types và Conditional Types (`T extends U ? X : Y`) giải quyết những bài toán Type-level programming nào?",
    ["`any` tắt hoàn toàn type-checker; `unknown` là type an toàn yêu cầu Type Narrowing trước khi sử dụng; `never` đại diện cho giá trị không bao giờ xảy ra (hàm throw exception hoặc exhaustive checking)", "Conditional Types cho phép lập trình logic ở tầng kiểu dữ liệu; từ khóa `infer` dùng để suy luận kiểu ẩn bên trong generics", "Mapped Types (`[K in keyof T]: ...`) biến đổi cấu trúc object type hàng loạt (tạo Readonly, Partial, Record)"],
    ["Exhaustive Type Checking với `never` trong câu lệnh `switch-case` bảo vệ ứng dụng khi thêm enum mới ra sao?", "Tại sao nên hạn chế tối đa việc sử dụng ép kiểu cưỡng bức (`as unknown as Type`)?"] ,
    ["TypeScript", "Type System", "Conditional Types", "infer", "never"],
    ["https://www.typescriptlang.org/docs/handbook/2/conditional-types.html"],
    ["Lạm dụng `any` khắp nơi để tắt cảnh báo của compiler hoặc không phân biệt được `unknown` và `any`"]
  ),
  q("TS_NODE-FOUND-03", "TypeScript / Node.js Developer", "foundation", "intermediate", "middle",
    "Cơ chế Stream và Buffer trong Node.js: Phân biệt 4 loại Stream (Readable, Writable, Duplex, Transform). Hiện tượng Backpressure xảy ra khi nào và hàm `stream.pipeline()` giải quyết việc rò rỉ bộ nhớ và dọn dẹp lỗi ra sao?",
    ["Buffer lưu trữ dữ liệu nhị phân thô bên ngoài V8 heap memory; Stream xử lý dữ liệu theo từng chunk liên tục thay vì nạp toàn bộ vào RAM", "Backpressure xảy ra khi Writable Stream ghi dữ liệu chậm hơn tốc độ đọc của Readable Stream, làm dữ liệu ứ đọng trong bộ đệm (highWaterMark)", "`pipeline()` tự động lắng nghe sự kiện drain, xử lý lỗi tập trung và đảm bảo đóng luồng an toàn khi có ngoại lệ phát sinh"],
    ["Tại sao sử dụng `readable.pipe(writable)` truyền thống có thể gây rò rỉ file descriptor nếu luồng bị lỗi giữa chừng?", "Transform Stream được ứng dụng trong các bài toán nén dữ liệu (gzip) hoặc mã hóa dữ liệu ra sao?"] ,
    ["Node.js Streams", "Buffer", "Backpressure", "pipeline", "Memory Optimization"],
    ["https://nodejs.org/api/stream.html"],
    ["Đọc toàn bộ file 2GB vào bộ nhớ bằng `fs.readFile()` thông thường làm crash V8 heap memory"]
  ),
  q("TS_NODE-FOUND-04", "TypeScript / Node.js Developer", "foundation", "advanced", "senior_lead",
    "Xử lý tác vụ tính toán nặng (CPU-Intensive Tasks) trong Node.js: Phân biệt sự khác nhau giữa Worker Threads (`worker_threads`), Cluster Module (`cluster`) và Child Process (`child_process`). Chi phí chia sẻ bộ nhớ qua `SharedArrayBuffer` và `Atomics`?",
    ["Node.js mặc định đơn luồng cho JS; tác vụ CPU nặng sẽ làm block Event Loop, khiến mọi request khác bị treo", "Worker Threads chia sẻ cùng một tiến trình OS, có V8 instance riêng và có thể chia sẻ bộ nhớ qua SharedArrayBuffer", "Cluster Module phân nhánh (fork) thành nhiều tiến trình OS độc lập dùng chung cổng mạng (IPC), phù hợp scale số lượng CPU core"],
    ["Atomics API trong JavaScript giải quyết bài toán đồng bộ hóa (Race Condition) trên SharedArrayBuffer thế nào?", "Tại sao không nên khởi tạo Worker Thread mới cho mỗi request HTTP mà nên dùng Thread Pool?"] ,
    ["Worker Threads", "Cluster Module", "SharedArrayBuffer", "CPU-bound", "Atomics"],
    ["https://nodejs.org/api/worker_threads.html"],
    ["Cho rằng Node.js không thể xử lý tác vụ CPU-bound hoặc cố gắng giải quyết CPU-bound bằng `setTimeout`"]
  ),
  q("TS_NODE-FOUND-05", "TypeScript / Node.js Developer", "foundation", "basic", "junior",
    "Phân biệt sâu sắc giữa CommonJS (`require` / `module.exports`) và ES Modules (`import` / `export`) trong hệ sinh thái Node.js hiện đại. Tại sao việc kết hợp cả hai chuẩn module trong cùng một dự án thường gây ra lỗi phức tạp?",
    ["CommonJS nạp module đồng bộ lúc runtime; ES Modules phân tích cú pháp tĩnh lúc compile-time và hỗ trợ nạp bất đồng bộ", "ES Modules hỗ trợ Tree-shaking tự nhiên vì cấu trúc import là tĩnh, không cho phép import có điều kiện bên trong hàm", "Lỗi phổ biến: không thể `require()` một ES Module thuần túy mà không dùng `await import()`, sự vắng mặt của `__dirname` và `__filename` trong ESM"],
    ["Làm thế nào để lấy đường dẫn tệp hiện tại trong ES Modules bằng `import.meta.url` và `fileURLToPath`?", "Cấu hình trường `\"type\": \"module\"` và `\"exports\"` trong package.json điều khiển hành vi nạp module ra sao?"] ,
    ["CommonJS", "ES Modules", "Node.js Internals", "Module System"],
    ["https://nodejs.org/api/esm.html"],
    ["Nhầm lẫn cú pháp import/export của Babel/TypeScript với cơ chế native ES Modules của Node.js"]
  ),
  q("TS_NODE-FOUND-06", "TypeScript / Node.js Developer", "foundation", "intermediate", "middle",
    "Kiến trúc Type Narrowing và Discriminated Unions (Tagged Unions) trong TypeScript: Làm thế nào để TypeScript tự động thu hẹp kiểu dữ liệu một cách an toàn mà không cần ép kiểu thủ công (`as Type`)?",
    ["Sử dụng thuộc tính phân biệt chung (literal discriminator ví dụ: `kind: 'success' | 'error'`) trên các interface", "Tận dụng các Type Guards tích hợp: `typeof`, `instanceof`, `in`, và Custom Type Guard predicates (`val is Type`)", "Giúp trình biên dịch loại trừ các nhánh không thể xảy ra và cảnh báo lỗi lúc biên dịch nếu thiếu trường hợp xử lý"],
    ["Assertion Functions trong TypeScript (`asserts condition`) hoạt động ra sao?", "Tại sao việc lạm dụng Optional Chaining (`?.`) bừa bãi có thể che giấu các lỗi logic dữ liệu nghiêm trọng?"] ,
    ["Type Narrowing", "Discriminated Unions", "Type Guards", "Type Safety"],
    ["https://www.typescriptlang.org/docs/handbook/2/narrowing.html"],
    ["Dùng ép kiểu thô bạo (`as any as SpecificType`) thay vì sử dụng cơ chế Type Narrowing an toàn của TypeScript"]
  ),

  // Practical Skills (8)
  q("TS_NODE-SKILL-01", "TypeScript / Node.js Developer", "practical_skills", "advanced", "senior_lead",
    "Kiến trúc ứng dụng doanh nghiệp với NestJS: Em thiết kế các tầng Controller, Service, Module, Dependency Injection (DI Container), Custom Decorators, Pipes, và Interceptors như thế nào để đảm bảo tính module hóa và dễ kiểm thử?",
    ["Áp dụng Dependency Inversion Principle thông qua DI Container của NestJS, inject theo interface/token", "Pipes đảm nhận validation và transformation dữ liệu đầu vào (tích hợp Class-Validator / Zod)", "Interceptors ghi log thời gian thực thi, format response chuẩn hoặc áp dụng caching; Exception Filters bắt lỗi tập trung"],
    ["Sự khác biệt giữa Injection Scope mặc định (Singleton), Request Scope, và Transient Scope trong NestJS?", "Tại sao việc lạm dụng Request Scope có thể gây suy giảm nghiêm trọng hiệu năng throughput của NestJS?"] ,
    ["NestJS", "Dependency Injection", "Interceptors", "Pipes", "Enterprise Architecture"],
    ["https://docs.nestjs.com/"],
    ["Viết toàn bộ logic nghiệp vụ lẫn truy vấn database trực tiếp bên trong Controller"]
  ),
  q("TS_NODE-SKILL-02", "TypeScript / Node.js Developer", "practical_skills", "intermediate", "middle",
    "Quản lý cơ sở dữ liệu với TypeORM hoặc Prisma ORM: So sánh Data Mapper pattern (TypeORM) với Prisma Schema Engine. Cách xử lý bài toán N+1 Query và tối ưu hóa quan hệ phức tạp?",
    ["Prisma sinh Type-safe client từ schema file, không dùng decorator, tránh được N+1 query qua cơ chế batching ngầm", "TypeORM dùng Data Mapper / Active Record với decorators, dễ kiểm soát SQL thuần hơn nhưng dễ dính N+1 nếu không cẩn thận", "Giải quyết N+1: sử dụng `relationLoadStrategy: 'join'` trong TypeORM hoặc dùng Dataloader / batch queries"],
    ["Khi nào việc sử dụng ORM trở nên kém hiệu quả và cần viết SQL query thuần túy qua QueryBuilder hoặc raw query?", "Cơ chế Connection Pool và Transaction Management được cấu hình như thế nào trong Prisma?"] ,
    ["TypeORM", "Prisma", "N+1 Query", "Database Access", "Data Mapper"],
    ["https://www.prisma.io/docs"],
    ["Không nhận biết được hiện tượng N+1 Query và để ứng dụng gọi hàng nghìn câu truy vấn vào DB trong vòng lặp"]
  ),
  q("TS_NODE-SKILL-03", "TypeScript / Node.js Developer", "practical_skills", "intermediate", "middle",
    "Xử lý xác thực dữ liệu đầu vào (Input Validation & Serialization) an toàn bằng Zod hoặc Class-Validator: Làm thế nào để ngăn chặn tấn công Mass Assignment và tự động loại bỏ các trường không mong muốn (Strip unknown fields)?",
    ["Sử dụng Zod `.strict()` hoặc Class-Validator `whitelist: true, forbidNonWhitelisted: true` để từ chối các trường ngoài schema", "Tự động parse và sanitize dữ liệu đầu vào thành kiểu TypeScript an toàn trước khi vào service logic", "Ngăn chặn hoàn toàn việc kẻ xấu chèn các trường đặc quyền như `isAdmin: true` hoặc `role: 'admin'` qua payload"],
    ["Làm thế nào để sinh OpenAPI / Swagger documentation tự động từ Zod schemas hoặc NestJS DTOs?", "Custom validation logic bất đồng bộ (Async Refinement) trong Zod được cấu hình ra sao?"] ,
    ["Zod", "Validation", "Mass Assignment", "Data Sanitization", "Class-Validator"],
    ["https://zod.dev/"],
    ["Chấp nhận trực tiếp `req.body` thô vào câu lệnh INSERT/UPDATE của database mà không có bước validate/sanitize"]
  ),
  q("TS_NODE-SKILL-04", "TypeScript / Node.js Developer", "practical_skills", "advanced", "senior_lead",
    "Xử lý lỗi toàn diện (Comprehensive Error Handling): Em thiết kế cấu trúc Custom Error Hierarchy trong TypeScript và cơ chế bắt lỗi toàn cục (Global Exception Handler / Unhandled Rejection) trong Node.js như thế nào?",
    ["Tạo lớp `AppError` kế thừa từ `Error` chứa `statusCode`, `isOperational`, `errorCode`, và ngữ cảnh chi tiết", "Phân biệt rạch ròi giữa Operational Errors (lỗi dự kiến được: sai input, không tìm thấy) và Programmer Errors (lỗi code, bug)", "Lắng nghe `unhandledRejection` và `uncaughtException`, ghi log chi tiết và thực hiện Graceful Shutdown dịch vụ"],
    ["Tại sao sau khi bắt được `uncaughtException` thì bắt buộc phải thoát tiến trình (process.exit) thay vì cố chạy tiếp?", "Làm thế nào để đảm bảo không để lộ chi tiết Stack Trace cho client trên môi trường production?"] ,
    ["Error Handling", "Custom Errors", "Graceful Shutdown", "Operational Errors"],
    ["https://nodejs.org/api/process.html#event-uncaughtexception"],
    ["Bỏ qua việc bắt lỗi trong Promise khiến ứng dụng bị crash âm thầm hoặc nuốt lỗi (swallow errors) không ghi log"]
  ),
  q("TS_NODE-SKILL-05", "TypeScript / Node.js Developer", "practical_skills", "intermediate", "middle",
    "Tắt ứng dụng an toàn (Graceful Shutdown) trong Node.js: Khi nhận tín hiệu `SIGTERM` hoặc `SIGINT` từ hệ điều hành hoặc Kubernetes, em triển khai quy trình đóng các kết nối đang mở ra sao để không làm gián đoạn request của người dùng?",
    ["Lắng nghe tín hiệu `process.on('SIGTERM', ...)` và dừng nhận các request mới (`server.close()`)", "Chờ các request đang xử lý dở hoàn tất trong một khoảng thời gian timeout an toàn (grace period)", "Đóng an toàn các kết nối: Database Connection Pool, Redis client, WebSocket connections và Message Queue consumers trước khi `process.exit(0)`"],
    ["Tại sao việc không cấu hình Graceful Shutdown khiến người dùng gặp lỗi 502 Bad Gateway mỗi lần deploy pod mới trên K8s?", "Làm thế nào để cấu hình `terminationGracePeriodSeconds` trong Kubernetes pod spec phù hợp với thời gian shutdown của Node.js?"] ,
    ["Graceful Shutdown", "SIGTERM", "Kubernetes", "Connection Teardown"],
    [SRC.internal],
    ["Ngắt ứng dụng ngay lập tức bằng process.exit(0) khiến các transaction đang chạy dở bị đứt gãy và lỗi dữ liệu"]
  ),
  q("TS_NODE-SKILL-06", "TypeScript / Node.js Developer", "practical_skills", "intermediate", "middle",
    "Bảo mật ứng dụng Node.js: Cách phòng chống các lỗ hổng phổ biến như ReDoS (Regular Expression Denial of Service), Prototype Pollution, và Command Injection trong môi trường runtime JavaScript?",
    ["ReDoS: tránh các biểu thức chính quy có tính backtracking theo hàm mũ (Evil Regex), dùng linter kiểm tra hoặc timeout", "Prototype Pollution: sử dụng `Object.create(null)`, `Map`, hoặc đóng băng `Object.freeze()` khi gộp đối tượng (deep merge)", "Command Injection: không bao giờ truyền input trực tiếp vào `child_process.exec()`, luôn dùng `execFile` hoặc `spawn` với danh sách tham số mảng"],
    ["Làm thế nào để cấu hình các HTTP security headers bằng thư viện Helmet trong Node.js?", "Công cụ npm audit hoặc Snyk hỗ trợ rà soát các gói thư viện chứa lỗ hổng bảo mật ra sao?"] ,
    ["Node Security", "ReDoS", "Prototype Pollution", "Command Injection", "Helmet"],
    [SRC.owasp],
    ["Nối chuỗi trực tiếp input của người dùng vào câu lệnh thực thi hệ điều hành `exec('rm ' + input)`"]
  ),
  q("TS_NODE-SKILL-07", "TypeScript / Node.js Developer", "practical_skills", "intermediate", "middle",
    "Ghi log có cấu trúc (Structured Logging) và Giám sát hiệu năng: Em cấu hình thư viện Pino hoặc Winston trong Node.js như thế nào? Tại sao Pino có tốc độ ghi log nhanh hơn Winston gấp nhiều lần?",
    ["Pino tối ưu hóa ghi log bất đồng bộ trực tiếp ra stdout dưới dạng JSON nhị phân, giảm tối đa overhead trên Event Loop", "Đính kèm Trace ID / Correlation ID vào mỗi dòng log thông qua `AsyncLocalStorage` trong Node.js", "Tránh việc format log phức tạp hoặc ghi log đồng bộ ra file đĩa làm nghẽn Event Loop của ứng dụng"],
    ["Cơ chế `AsyncLocalStorage` trong Node.js hoạt động tương tự như ThreadLocal của Java như thế nào?", "Làm thế nào để ẩn (redact) các trường nhạy cảm như mật khẩu, số thẻ tín dụng trong log tự động?"] ,
    ["Structured Logging", "Pino", "AsyncLocalStorage", "Correlation ID", "Winston"],
    ["https://getpino.io/"],
    ["Sử dụng `console.log()` thông thường khắp nơi hoặc ghi log đồng bộ làm nghẽn hiệu năng của server"]
  ),
  q("TS_NODE-SKILL-08", "TypeScript / Node.js Developer", "practical_skills", "advanced", "senior_lead",
    "Chiến lược kiểm thử tự động toàn diện cho TypeScript/Node.js: Em tổ chức Unit Test bằng Vitest / Jest, Mocking dữ liệu, và Integration Test với Testcontainers / Supertest như thế nào?",
    ["Tách biệt Unit test cho business logic cô lập với tốc độ chạy mili-giây", "Sử dụng Supertest để kiểm tra toàn diện các HTTP endpoints bao gồm cả Middleware, Pipes, và Guard validation", "Dùng Testcontainers để chạy cơ sở dữ liệu thật trong Docker cho Integration Test, tránh sự sai lệch cú pháp SQL"],
    ["Làm thế nào để đo lường và thiết lập ngưỡng Code Coverage (Branches, Statements) trong CI/CD pipeline?", "Sự khác biệt khi viết test cho NestJS bằng `Test.createTestingModule` so với viết test Express thông thường?"] ,
    ["Testing", "Vitest", "Supertest", "Testcontainers", "Integration Test"],
    ["https://vitest.dev/"],
    ["Bỏ qua khâu kiểm thử tích hợp và chỉ dựa vào việc test tay qua Postman"]
  ),

  // Scenario (6)
  q("TS_NODE-SCEN-01", "TypeScript / Node.js Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một API xử lý xuất dữ liệu báo cáo sang file Excel chứa 500.000 dòng. Mỗi khi người dùng bấm xuất báo cáo, máy chủ Node.js bị đơ hoàn toàn không phản hồi bất kỳ request nào khác trong 30 giây rồi crash với lỗi `JavaScript heap out of memory`. Em giải quyết triệt để ra sao?",
    ["Phân tích nguyên nhân: Tác vụ tạo file Excel là CPU-bound và nạp toàn bộ 500.000 dòng vào memory làm nghẽn Event Loop và tràn heap", "Giải pháp 1: Chuyển sang đọc dữ liệu từ DB theo cơ chế Stream (Cursor) và ghi trực tiếp ra tệp bằng Transform Stream / ExcelJS streaming writer", "Giải pháp 2: Đẩy toàn bộ tác vụ xuất báo cáo ra hàng đợi xử lý nền (Worker Thread hoặc Background Job độc lập)"],
    ["Làm thế nào để tăng tạm thời giới hạn V8 heap bằng cờ `--max-old-space-size` trong trường hợp cấp bách?", "Tại sao không nên để các tác vụ xử lý tệp lớn chạy chung tiến trình với API Server chính?"] ,
    ["Event Loop Block", "Heap Out of Memory", "Streaming File", "Worker Threads"],
    [SRC.internal],
    ["Nạp toàn bộ 500.000 object vào một mảng trong RAM rồi dùng hàm JSON.stringify"]
  ),
  q("TS_NODE-SCEN-02", "TypeScript / Node.js Developer", "scenario", "intermediate", "middle",
    "Tình huống: Sau khi refactor mã nguồn sang TypeScript Strict Mode, dự án xuất hiện hàng trăm lỗi biên dịch. Một lập trình viên trong nhóm bắt đầu thêm `// @ts-ignore` và `as any` hàng loạt để kịp tiến độ release. Em xử lý tình huống này và đưa ra quy chuẩn kiểm soát ra sao?",
    ["Tạm dừng việc bypass cẩu thả: giải thích cho nhóm hiểu rằng việc dùng `any` và `ts-ignore` phá vỡ hoàn toàn giá trị của TypeScript và tạo ra các lỗi runtime nguy hiểm", "Cấu hình ESLint rule `@typescript-eslint/no-explicit-any: error` và cấm `@ts-ignore` trong pre-commit hook và CI pipeline", "Hướng dẫn nhóm kỹ thuật sử dụng `unknown`, Type Narrowing, và utility types để sửa lỗi kiểu dữ liệu đúng đắn"],
    ["Chiến lược bật dần dần các cờ strict (`strictNullChecks`, `noImplicitAny`) từng bước trong `tsconfig.json` là gì?", "Làm thế nào để viết migration script hoặc codemod hỗ trợ refactor type an toàn?"] ,
    ["TypeScript Strict", "Code Quality", "Linting Governance", "Technical Debt"],
    [SRC.internal],
    ["Đồng tình với việc lạm dụng `as any` để chạy cho nhanh mà bỏ qua sự an toàn của hệ thống"]
  ),
  q("TS_NODE-SCEN-03", "TypeScript / Node.js Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một endpoint API bỗng nhiên có thời gian phản hồi tăng từ 50ms lên 10 giây trong khi cơ sở dữ liệu hoàn toàn không bị quá tải. Em nghi ngờ Event Loop đang bị nghẽn (Event Loop Delay). Các bước sử dụng công cụ Profiling để tìm chính xác dòng code gây nghẽn?",
    ["Sử dụng thư viện `clinicjs` (cụ thể là `clinic doctor` và `clinic flame`) hoặc cờ `--prof` của Node.js để tạo Flame Graph", "Theo dõi chỉ số Event Loop Lag thông qua API `perf_hooks.monitorEventLoopDelay()`", "Xác định dòng code gây nghẽn: thuật toán xử lý chuỗi phức tạp, biểu thức chính quy (ReDoS), hoặc hàm mã hóa/nén đồng bộ (`crypto.pbkdf2Sync`, `fs.readFileSync`)"],
    ["Làm thế nào để thay thế các hàm đồng bộ bằng phiên bản bất đồng bộ hoặc chuyển sang Worker Thread?", "Cách thiết lập alert cảnh báo khi Event Loop Lag vượt ngưỡng 100ms trên Prometheus?"] ,
    ["Event Loop Lag", "Clinic.js", "Flame Graph", "CPU Profiling", "Performance"],
    ["https://clinicjs.org/"],
    ["Đoán mò không dùng công cụ profiling hoặc đổ lỗi cho mạng/database mà không kiểm tra Event Loop"]
  ),
  q("TS_NODE-SCEN-04", "TypeScript / Node.js Developer", "scenario", "intermediate", "middle",
    "Tình huống: Một dịch vụ Node.js microservice liên tục bị sập và khởi động lại ngẫu nhiên trên Kubernetes. Log hệ thống chỉ hiển thị dòng chữ `UnhandledPromiseRejection` mà không có ngữ cảnh hoặc stack trace rõ ràng. Em truy vết và sửa lỗi ra sao?",
    ["Cấu hình cờ `--unhandled-rejections=strict` để Node.js in đầy đủ stack trace và dừng an toàn thay vì nuốt lỗi", "Tìm kiếm các Promise không có khối `.catch()` hoặc hàm async không được bọc trong `try-catch`", "Tạo middleware hoặc interceptor bắt lỗi tập trung đảm bảo mọi Promise trong luồng request đều được xử lý ngoại lệ"],
    ["Tại sao việc không await một Promise trong hàm async có thể dẫn đến Unhandled Rejection ngoài luồng try-catch?", "Làm thế nào để sử dụng thư viện `express-async-errors` trong các dự án Express cũ?"] ,
    ["UnhandledPromiseRejection", "Async Await", "Error Tracing", "Node.js Debugging"],
    [SRC.internal],
    ["Bật chế độ bỏ qua unhandled rejection để app không crash mà không tìm nguyên nhân gốc rễ"]
  ),
  q("TS_NODE-SCEN-05", "TypeScript / Node.js Developer", "scenario", "intermediate", "middle",
    "Tình huống: Khi triển khai ứng dụng Node.js chạy nhiều tiến trình qua PM2 hoặc Kubernetes cluster, tính năng đặt lịch gửi thông báo (Cron Job / Scheduled Task) bị chạy lặp lại 4 lần cùng lúc trên cả 4 instance. Em xử lý vấn đề lập lịch phân tán (Distributed Cron) ra sao?",
    ["Phân tích nguyên nhân: Mỗi tiến trình Node.js độc lập đều khởi chạy cronjob riêng của nó trong bộ nhớ cục bộ", "Giải pháp 1: Sử dụng Distributed Lock (Redis Lock với Redlock) để đảm bảo chỉ có duy nhất 1 instance giành được quyền thực thi job tại một thời điểm", "Giải pháp 2: Tách biệt cronjob ra thành một service/pod riêng biệt hoặc sử dụng hệ thống quản lý queue phân tán (BullMQ repeatable jobs / Kubernetes CronJob)"],
    ["Làm thế nào để xử lý trường hợp instance đang giữ lock bị crash giữa chừng bằng cơ chế Lock TTL?", "Tại sao không nên hardcode cronjob chạy trên instance số 0 (instance_id = 0) trong môi trường autoscaling?"] ,
    ["Distributed Cron", "Redis Lock", "BullMQ Repeatable", "Clustering"],
    [SRC.internal],
    ["Để mặc cronjob chạy lặp lại 4 lần gửi spam email cho khách hàng"]
  ),
  q("TS_NODE-SCEN-06", "TypeScript / Node.js Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một dịch vụ tải tệp media cho phép người dùng truyền tham số đường dẫn tệp vào URL. Tin tặc lợi dụng điều này để tấn công Path Traversal (`../../etc/passwd`) nhằm đọc các tệp cấu hình nhạy cảm của máy chủ. Em kiểm tra và vá lỗ hổng này như thế nào?",
    ["Phân tích rủi ro: Nối chuỗi đường dẫn trực tiếp bằng `path.join(__dirname, userInput)` mà không kiểm tra ranh giới thư mục", "Vá lỗi: Sử dụng `path.resolve()` để chuẩn hóa đường dẫn tuyệt đối, sau đó kiểm tra xem đường dẫn kết quả có bắt đầu bằng thư mục gốc cho phép hay không (`resolvedPath.startsWith(ALLOWED_DIR)`)", "Sử dụng whitelist tên tệp hoặc lưu trữ tệp theo ID ngẫu nhiên thay vì cho phép truyền tên tệp tùy ý từ người dùng"],
    ["Làm thế nào để viết bài kiểm thử tự động (Security Test) giả lập các chuỗi path traversal nguy hiểm?", "Quyền hạn của tài xế hệ điều hành chạy ứng dụng Node.js (Non-root user trong Docker) bảo vệ hệ thống ra sao?"] ,
    ["Path Traversal", "Directory Traversal", "File System Security", "Vulnerability Remediation"],
    [SRC.owasp, SRC.internal],
    ["Chỉ dùng hàm replace đơn giản `input.replace('../', '')` rất dễ dàng bị kẻ xấu vượt qua bằng chuỗi `....//`"]
  ),

  // CV Validation (5)
  q("TS_NODE-CV-01", "TypeScript / Node.js Developer", "cv_validation", "advanced", "senior_lead",
    "Trong dự án Node.js phức tạp nhất trên CV của em: Em đã thiết kế kiến trúc backend theo mô hình nào (Layered Architecture, Hexagonal / Ports & Adapters, Clean Architecture)? Ranh giới trách nhiệm giữa các tầng được phân định ra sao?",
    ["Mô tả ranh giới rõ ràng: Tầng Domain (Business Rules độc lập), Tầng Application (UseCases), Tầng Infrastructure (DB, Redis, External APIs)", "Thể hiện nguyên lý Dependency Inversion: Tầng Domain không phụ thuộc vào Framework hay ORM cụ thể", "Lợi ích thực tế: khả năng thay đổi cơ sở dữ liệu hoặc viết unit test mà không cần dựng database thật"],
    ["Tại sao việc không để entity của ORM (TypeORM entity) rò rỉ vào tầng Domain logic lại giúp code bền vững hơn?", "Đánh đổi về số lượng file và boilerplate code khi áp dụng Clean Architecture là gì?"] ,
    ["Clean Architecture", "Hexagonal Architecture", "Domain Driven Design", "CV Deep Dive"],
    [SRC.internal],
    ["Nói rằng mình áp dụng Clean Architecture nhưng trong code tầng Service gọi trực tiếp raw SQL và xử lý cả HTTP response"]
  ),
  q("TS_NODE-CV-02", "TypeScript / Node.js Developer", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kinh nghiệm làm việc với WebSocket thời gian thực quy mô lớn. Hãy chia sẻ cách em thiết kế cụm WebSocket Server mở rộng ngang (Horizontal Scaling) qua nhiều pod với Redis Adapter?",
    ["Mỗi máy chủ Node.js giữ kết nối TCP của các client kết nối tới nó", "Tích hợp `@socket.io/redis-adapter` hoặc Redis Pub/Sub để phát tán tin nhắn (broadcast) xuyên suốt tất cả các instance", "Cấu hình Session Affinity (Sticky Sessions) trên Load Balancer nếu cần nâng cấp handshake từ HTTP sang WebSocket"],
    ["Làm thế nào để xử lý việc lưu trữ trạng thái người dùng online/offline phân tán trên Redis?", "Cách đo lường số lượng kết nối đồng thời tối đa (Concurrent Connections) mà một instance Node.js có thể chịu tải?"] ,
    ["WebSocket Scaling", "Redis Adapter", "Socket.io", "Realtime Architecture", "CV Verification"],
    [SRC.internal],
    ["Chỉ biết dùng WebSocket trên 1 server duy nhất và không biết cách scale khi chạy nhiều container"]
  ),
  q("TS_NODE-CV-03", "TypeScript / Node.js Developer", "cv_validation", "advanced", "senior_lead",
    "Em ghi nhận kinh nghiệm xây dựng các tiện ích Custom Decorators hoặc Metadata Reflection trong TypeScript trên CV. Em hãy dẫn chứng một trường hợp cụ thể em tự tạo decorator và cách Reflection API hoạt động bên dưới?",
    ["Trình bày use-case: tạo Decorator `@CurrentUser()` trích xuất user từ request, `@Roles('ADMIN')` để kiểm tra quyền, hoặc `@AuditLog()` ghi lại thao tác", "Sử dụng `Reflect.defineMetadata` và `Reflect.getMetadata` từ thư viện `reflect-metadata` để lưu trữ và đọc metadata lúc runtime", "Cấu hình cờ `experimentalDecorators` và `emitDecoratorMetadata` trong `tsconfig.json`"],
    ["Sự khác biệt giữa TypeScript Stage 3 Decorators (chuẩn ECMAScript mới) và Legacy Experimental Decorators?", "Cách một Decorator can thiệp sửa đổi hành vi của một phương thức (Method Wrapper) diễn ra ra sao?"] ,
    ["TypeScript Decorators", "Reflect Metadata", "Metaprogramming", "CV Verification"],
    [SRC.ts, SRC.internal],
    ["Dùng decorator có sẵn của framework nhưng không hiểu cách thức một decorator được định nghĩa và thực thi"]
  ),
  q("TS_NODE-CV-04", "TypeScript / Node.js Developer", "cv_validation", "intermediate", "middle",
    "Em hãy kể về một tình huống mà em phải điều tra và xử lý một lỗi rò rỉ bộ nhớ (Memory Leak) khó khăn trong ứng dụng Node.js trên CV. Em đã dùng công cụ gì để phân tích Heap Snapshot và nguyên nhân gốc rễ là gì?",
    ["Sử dụng lệnh `node --inspect` kết hợp Chrome DevTools hoặc clinicjs để chụp 3 lần Heap Snapshot tại các thời điểm khác nhau", "Sử dụng tính năng so sánh (Comparison View) để tìm các đối tượng tăng dần về số lượng (Delta > 0) mà không được thu hồi", "Chỉ rõ nguyên nhân gốc rễ: tích lũy dữ liệu trong biến Global Cache không có giới hạn, rò rỉ EventEmitter listener, hoặc closure giữ tham chiếu DOM/Buffer lớn"],
    ["Chỉ số Shallow Size và Retained Size của một đối tượng trong Heap Snapshot mang ý nghĩa gì?", "Làm thế nào để phòng chống rò rỉ EventEmitter bằng phương thức `emitter.setMaxListeners()`?"] ,
    ["Memory Leak", "Heap Snapshot", "V8 Engine", "Debugging", "CV Verification"],
    [SRC.internal],
    ["Nói chung chung là 'tăng RAM cho server' thay vì tìm và sửa nguyên nhân gây rò rỉ bộ nhớ"]
  ),
  q("TS_NODE-CV-05", "TypeScript / Node.js Developer", "cv_validation", "intermediate", "middle",
    "Trong dự án có tích hợp hệ thống thanh toán hoặc xử lý giao dịch tài chính trên CV, em đã đảm bảo tính toàn vẹn dữ liệu (Data Consistency) và tính bất biến (Immutability) của lịch sử giao dịch như thế nào?",
    ["Áp dụng mô hình Sổ cái kép (Double-entry Bookkeeping) với mỗi giao dịch đều có dòng Nợ (Debit) và Có (Credit) cân bằng", "Không bao giờ thực hiện lệnh `UPDATE` số dư trực tiếp, mà ghi nhận bản ghi giao dịch mới trong một Transaction ACID duy nhất", "Sử dụng UUID cho Idempotency Key và cơ chế khóa dòng lạc quan hoặc bi quan để ngăn chặn Race Condition"],
    ["Tại sao việc không cho phép xóa (No hard deletes) là nguyên tắc bắt buộc trong hệ thống tài chính?", "Làm thế nào để kiểm toán đối soát số dư tài khoản định kỳ bằng background job?"] ,
    ["Financial Architecture", "Double-entry Bookkeeping", "ACID", "Immutability", "CV Verification"],
    [SRC.internal],
    ["Cập nhật trực tiếp số dư tài khoản bằng câu lệnh `UPDATE accounts SET balance = balance + 100` không có transaction bảo vệ"]
  ),

  // Behavioral (5)
  q("TS_NODE-BEHAV-01", "TypeScript / Node.js Developer", "behavioral", "intermediate", "middle",
    "Hệ sinh thái Node.js/npm có số lượng thư viện mã nguồn mở khổng lồ. Khi một thành viên trong nhóm muốn cài đặt một package mới cho một tác vụ đơn giản (ví dụ chỉ để format ngày tháng hoặc kiểm tra chuỗi), em trao đổi và đánh giá rủi ro Dependency Bloat ra sao?",
    ["Nhẹ nhàng chỉ ra rủi ro: việc thêm package kéo theo hàng chục sub-dependencies, tăng kích thước bundle, tăng nguy cơ dính lỗ hổng bảo mật chuỗi cung ứng (Supply Chain Attack)", "Khuyến khích tận dụng các API native hiện đại của Node.js (như `Intl`, `crypto`, `fetch`) hoặc viết helper function nội bộ nhỏ nếu yêu cầu đơn giản", "Cùng nhóm xây dựng quy tắc đánh giá package: kiểm tra số lượng tải hàng tuần, tần suất bảo trì, số lượng open issues và dung lượng package"],
    ["Em làm gì nếu thành viên đó cho rằng 'tự viết thì tốn thời gian hơn là cài thư viện có sẵn'?", "Công cụ bundlephobia hỗ trợ phân tích kích thước và rủi ro của package như thế nào?"] ,
    ["Dependency Management", "Supply Chain Security", "Code Review", "Pragmatism"],
    [SRC.internal],
    ["Cài đặt bừa bãi hàng chục thư viện không rõ nguồn gốc vào dự án công ty"]
  ),
  q("TS_NODE-BEHAV-02", "TypeScript / Node.js Developer", "behavioral", "advanced", "senior_lead",
    "Khi phát hiện một đồng nghiệp Senior khác trong nhóm viết code tắt bỏ qua các quy chuẩn Type-safety của TypeScript (dùng `any` vô tội vạ) khiến các module khác bị lỗi runtime bất ngờ, em tiếp cận phản hồi và giải quyết vấn đề thế nào?",
    ["Trao đổi riêng tư với tinh thần tôn trọng chuyên môn, mang theo bằng chứng cụ thể về lỗi runtime đã phát sinh để thảo luận khách quan", "Lắng nghe lý do của đồng nghiệp: có thể do áp lực thời gian hoặc do kiểu dữ liệu của bên thứ ba quá phức tạp chưa kịp gõ type", "Chủ động hỗ trợ viết type định nghĩa chuẩn và đề xuất đưa quy tắc chặn `any` vào CI để trở thành tiêu chuẩn chung của cả nhóm, không nhắm vào cá nhân"],
    ["Làm thế nào để tạo môi trường cởi mở tiếp nhận góp ý kỹ thuật trong nhóm?", "Cách cân bằng giữa tính nghiêm ngặt của TypeScript và tốc độ phát triển trong giai đoạn thử nghiệm?"] ,
    ["Peer Review", "Constructive Feedback", "Professionalism", "Type Safety Culture"],
    [SRC.internal],
    ["Chỉ trích gay gắt đồng nghiệp công khai hoặc im lặng chịu đựng rồi âm thầm phàn nàn sau lưng"]
  ),
  q("TS_NODE-BEHAV-03", "TypeScript / Node.js Developer", "behavioral", "intermediate", "middle",
    "Trước yêu cầu từ khách hàng muốn xây dựng một tính năng mới rất gấp nhưng yêu cầu nghiệp vụ còn mơ hồ và có nguy cơ thay đổi liên tục, em thiết kế mã nguồn Backend như thế nào để vừa kịp tiến độ vừa linh hoạt thích ứng?",
    ["Chủ động làm việc với Product Owner để chốt phạm vi phiên bản tối thiểu khả dụng (MVP) với các giả định rõ ràng", "Thiết kế kiến trúc lỏng lẻo có tính module hóa cao (Decoupled Architecture), che giấu các phần logic biến động đằng sau các Interface", "Viết mã nguồn ngắn gọn, dễ hiểu và dễ xóa/thay thế; không cố gắng thiết kế kiến trúc quá phức tạp vượt trước nhu cầu (tránh Over-engineering)"],
    ["Làm thế nào để ghi chép lại các giả định kỹ thuật để đối soát sau này khi yêu cầu thay đổi?", "Bài học về việc không tối ưu hóa sớm (Premature Optimization) trong giai đoạn khám phá sản phẩm là gì?"] ,
    ["Agile Mindset", "Unclear Requirements", "Decoupled Design", "Pragmatic Architecture"],
    [SRC.internal],
    ["Từ chối làm việc cho đến khi có bản đặc tả hoàn hảo 100% hoặc xây dựng một kiến trúc quá cồng kềnh không cần thiết"]
  ),
  q("TS_NODE-BEHAV-04", "TypeScript / Node.js Developer", "behavioral", "basic", "junior",
    "Khi nhận được thông báo lỗi từ hệ thống giám sát vào ban đêm về việc dịch vụ API chính bị sập, em giữ bình tĩnh và thực hiện quy trình xử lý sự cố khẩn cấp (On-call Incident Management) ra sao?",
    ["Bình tĩnh tiếp nhận thông tin, thông báo lên kênh sự cố xác nhận bản thân đang xử lý để các bên liên quan nắm tình hình", "Kiểm tra nhanh dashboard giám sát và log lỗi gần nhất để khoanh vùng nguyên nhân (sập DB, tràn RAM, lỗi code mới deploy)", "Ưu tiên phục hồi dịch vụ trước tiên (Rollback phiên bản cũ hoặc khởi động lại pod), sau đó mới tiến hành phân tích sâu nguyên nhân gốc rễ vào ngày hôm sau"],
    ["Tại sao việc đầu tiên trong sự cố sản xuất là phục hồi hoạt động chứ không phải ngồi debug từng dòng code?", "Quy trình viết báo cáo sự cố (Post-incident Report) sau khi hệ thống hoạt động ổn định trở lại?"] ,
    ["Incident Response", "On-call Duty", "Emergency Handling", "Composure"],
    [SRC.internal],
    ["Hoảng loạn không biết bắt đầu từ đâu hoặc cố gắng debug trực tiếp trên môi trường production đang sập"]
  ),
  q("TS_NODE-BEHAV-05", "TypeScript / Node.js Developer", "behavioral", "advanced", "senior_lead",
    "Là một kỹ sư Backend chủ chốt, em định hình văn hóa kiểm thử tự động (Automated Testing Culture) và quy chuẩn viết mã (Code Review Standards) cho các thành viên mới trong nhóm như thế nào?",
    ["Làm gương thông qua các Pull Request cá nhân: luôn có unit/integration test đi kèm, mô tả rõ ràng mục đích và kết quả test", "Xây dựng tài liệu hướng dẫn bắt đầu (Onboarding Guide) có các dự án mẫu và mẫu test chuẩn mực", "Review code với tinh thần người hướng dẫn: giải thích nguyên lý 'tại sao', đặt câu hỏi gợi mở tư duy thay vì chỉ bắt bẻ lỗi cú pháp"],
    ["Làm thế nào để đo lường hiệu quả của quy trình Code Review (giảm tỷ lệ bug lọt lên production)?", "Cách khuyến khích các bạn Junior chủ động tham gia review code của các bạn Senior?"] ,
    ["Engineering Culture", "Mentorship", "Code Review Standards", "Leadership"],
    [SRC.internal],
    ["Xem việc review code như một thủ tục hình thức bấm nút duyệt qua loa mà không đọc kỹ nội dung"]
  )
];

console.log("TS_NODE questions defined:", tsNodeQuestions.length);
module.exports = { tsNodeQuestions };
