const { q, SRC } = require('./fe_data.cjs');

const vueNgQuestions = [
  // Foundation (6)
  q("VUE_NG-FOUND-01", "Vue.js / Angular Developer", "foundation", "intermediate", "middle",
    "So sánh cơ chế phản ứng dữ liệu (Reactivity System) của Vue 3 (sử dụng JavaScript Proxy) với cơ chế Change Detection của Angular (Zone.js kết hợp Signals trong Angular 16+). Mỗi giải pháp phát hiện và cập nhật thay đổi trên DOM ra sao?",
    ["Vue 3 Proxy theo dõi thao tác get/set trực tiếp trên object, kích hoạt hiệu ứng (effect) chính xác ở cấp độ biến (fine-grained)", "Angular truyền thống dùng Zone.js monkey-patch các API bất đồng bộ để kích hoạt kiểm tra toàn bộ cây component từ root xuống", "Angular Signals mới mang lại mô hình reactive đồng bộ không cần Zone.js, tương tự như computed/ref của Vue"],
    ["Tại sao Vue 2 dùng Object.defineProperty không thể theo dõi việc thêm thuộc tính mới hoặc thay đổi mảng trực tiếp?", "Chiến lược `ChangeDetectionStrategy.OnPush` trong Angular tối ưu hóa hiệu năng render như thế nào?"] ,
    ["Reactivity", "Vue 3 Proxy", "Angular Zone.js", "Angular Signals", "Change Detection"],
    [SRC.vue, SRC.angular],
    ["Nhầm lẫn giữa cơ chế dirty checking toàn cây của Zone.js và cơ chế dependency tracking của Proxy"]
  ),
  q("VUE_NG-FOUND-02", "Vue.js / Angular Developer", "foundation", "intermediate", "middle",
    "Hệ thống Tiêm phụ thuộc (Dependency Injection - DI) phân cấp trong Angular: Phân biệt sự khác nhau giữa `@Injectable({ providedIn: 'root' })`, cung cấp ở cấp Module (`providers: [...]`), và cung cấp ở cấp Component (`Component({ providers: [...] })`)?",
    ["`providedIn: 'root'`: tạo dịch vụ Singleton toàn cục, hỗ trợ Tree-shaking nếu service không được dùng", "Module providers: chia sẻ thể hiện (instance) cho toàn bộ các component thuộc module đó và module con", "Component providers: tạo một instance mới độc lập cho mỗi component và chia sẻ cho các component con của nó theo cây phân cấp"],
    ["Resolution Modifiers trong Angular (@Self, @SkipSelf, @Optional, @Host) điều khiển hướng tìm kiếm dependency ra sao?", "Trong Vue 3, cơ chế Provide/Inject có điểm gì tương đồng và khác biệt so với hệ thống DI của Angular?"] ,
    ["Dependency Injection", "Angular Providers", "Singleton", "Hierarchical Injector", "Vue Provide Inject"],
    [SRC.angular, SRC.vue],
    ["Nghĩ rằng mọi service khai báo trong Angular đều tự động là Singleton duy nhất trong toàn ứng dụng"]
  ),
  q("VUE_NG-FOUND-03", "Vue.js / Angular Developer", "foundation", "intermediate", "middle",
    "Trong Angular và ứng dụng Vue lớn: RxJS đóng vai trò gì trong việc xử lý luồng dữ liệu bất đồng bộ? Phân biệt giữa Observable, Subject, BehaviorSubject và ReplaySubject?",
    ["Observable: luồng dữ liệu đơn hướng lạnh (cold), chỉ chạy khi có người subscribe", "Subject: hot multicast, phát giá trị cho nhiều subscriber cùng lúc", "BehaviorSubject: luôn lưu trữ giá trị hiện tại (current value) và phát ngay lập tức cho subscriber mới", "ReplaySubject: lưu trữ số lượng giá trị quá khứ nhất định để phát lại cho subscriber mới"],
    ["Toán tử `switchMap`, `mergeMap`, `concatMap` và `exhaustMap` khác nhau thế nào trong xử lý tác vụ mạng?", "Tại sao việc quên `unsubscribe()` trong Angular là nguyên nhân hàng đầu gây ra memory leak?"] ,
    ["RxJS", "Observable", "BehaviorSubject", "switchMap", "Memory Leak"],
    ["https://rxjs.dev/guide/overview"],
    ["Không phân biệt được sự khác biệt giữa switchMap (hủy request cũ) và mergeMap (chạy song song tất cả)"]
  ),
  q("VUE_NG-FOUND-04", "Vue.js / Angular Developer", "foundation", "basic", "junior",
    "Trong Vue 3, sự khác biệt giữa Composition API (`setup()`, `<script setup>`) và Options API (`data`, `methods`, `computed`) là gì? Tại sao Composition API giúp tổ chức mã nguồn tốt hơn trong các dự án phức tạp?",
    ["Options API phân chia mã nguồn theo loại thuộc tính (data/methods), khiến logic của cùng một tính năng bị phân tán khắp file", "Composition API gom nhóm mã nguồn theo tính năng logic (Composables), dễ dàng tái sử dụng và kiểm thử độc lập", "`<script setup>` mang lại cú pháp ngắn gọn, hiệu năng biên dịch nhanh hơn và hỗ trợ TypeScript Type-inference hoàn hảo"],
    ["Phân biệt sâu sắc giữa `ref` (bọc giá trị nguyên thủy) và `reactive` (chỉ nhận object) trong Vue 3?", "Cơ chế `shallowRef` và `triggerRef` được áp dụng trong tình huống tối ưu hóa nào?"] ,
    ["Vue 3", "Composition API", "Options API", "Composables", "TypeScript"],
    [SRC.vue],
    ["Vẫn giữ tư duy Options API gò bó khi viết Composition API hoặc lạm dụng biến toàn cục"]
  ),
  q("VUE_NG-FOUND-05", "Vue.js / Angular Developer", "foundation", "intermediate", "middle",
    "Cơ chế đóng gói CSS (View Encapsulation) trong Angular: Sự khác biệt giữa `ViewEncapsulation.Emulated`, `None`, và `ShadowDom` là gì? Điều này tương đồng thế nào với thuộc tính `<style scoped>` và CSS Modules trong Vue?",
    ["`Emulated` (mặc định): Angular tự động sinh các thuộc tính duy nhất (ví dụ `_ngcontent-c12`) vào HTML và CSS selector để giới hạn phạm vi", "`None`: style trở thành toàn cục (Global CSS) ảnh hưởng toàn bộ ứng dụng", "`ShadowDom`: sử dụng Shadow DOM chuẩn của trình duyệt web, cô lập hoàn toàn style nhưng không kế thừa được CSS ngoài"],
    ["Toán tử `::ng-deep` trong Angular hoặc `:deep()` trong Vue scoped CSS được sử dụng khi nào và rủi ro gì?", "Tại sao việc lạm dụng `:deep()` có thể phá vỡ tính đóng gói của component thư viện?"] ,
    ["View Encapsulation", "Scoped CSS", "Shadow DOM", "Component Styling"],
    [SRC.angular, SRC.vue],
    ["Tùy tiện dùng ViewEncapsulation.None để sửa CSS component con làm hỏng giao diện của các trang khác"]
  ),
  q("VUE_NG-FOUND-06", "Vue.js / Angular Developer", "foundation", "advanced", "senior_lead",
    "Kiến trúc Standalone Components trong Angular hiện đại (từ v14+) thay đổi cách tổ chức ứng dụng thế nào so với kiến trúc dựa trên NgModule truyền thống? Xu hướng loại bỏ Zone.js (Zoneless Angular) mang lại lợi ích gì?",
    ["Standalone Components cho phép component trực tiếp import các dependency mà không cần bọc trong NgModule cồng kềnh", "Giảm đáng kể boilerplate code, hỗ trợ Lazy Loading từng component đơn lẻ dễ dàng qua Router", "Zoneless Angular loại bỏ hoàn toàn chi phí overhead của Zone.js, giúp ứng dụng nhẹ hơn, debug stack trace rõ ràng và tối ưu hiệu năng tối đa"],
    ["Làm thế nào để di chuyển từng bước (Migration) một dự án Angular dùng NgModule sang Standalone?", "Angular Router cấu hình lazy load standalone component với `loadComponent` ra sao?"] ,
    ["Standalone Components", "NgModule", "Zoneless Angular", "Angular Modernization"],
    [SRC.angular],
    ["Vẫn khăng khăng tạo NgModule cho mọi component mới mà không nắm bắt kiến trúc Standalone hiện đại"]
  ),

  // Practical Skills (8)
  q("VUE_NG-SKILL-01", "Vue.js / Angular Developer", "practical_skills", "intermediate", "middle",
    "Quản lý trạng thái ứng dụng: So sánh Pinia trong hệ sinh thái Vue với NgRx / NgRx ComponentStore trong Angular. Khi nào nên dùng Signal Store mới của NgRx thay vì Store truyền thống có Action/Reducer/Effect phức tạp?",
    ["Pinia loại bỏ mutations, hỗ trợ TypeScript tự nhiên, module hóa tự động và cú pháp gọn nhẹ tương tự composition API", "NgRx cổ điển áp dụng chặt chẽ Redux pattern (Actions, Reducers, Effects, Selectors), phù hợp hệ thống tài chính yêu cầu audit trail nghiêm ngặt", "NgRx Signal Store mới giảm 80% boilerplate code, kết hợp reactivity của Angular Signals với khả năng quản lý state chuyên nghiệp"],
    ["Tại sao Pinia trở thành state manager chính thức thay thế Vuex trong Vue 3?", "Làm thế nào để xử lý tác vụ bất đồng bộ (side effects) trong NgRx Effects an toàn không bị vỡ luồng stream?"] ,
    ["Pinia", "NgRx", "Signal Store", "State Management", "Redux Pattern"],
    [SRC.vue, SRC.angular],
    ["Viết quá nhiều boilerplate code cho các state cục bộ đơn giản làm phức tạp hóa dự án không cần thiết"]
  ),
  q("VUE_NG-SKILL-02", "Vue.js / Angular Developer", "practical_skills", "advanced", "senior_lead",
    "Tối ưu hóa hiệu năng render trong Angular bằng `ChangeDetectionStrategy.OnPush`: Cách thức hoạt động, vai trò của `ChangeDetectorRef.markForCheck()`, `detectChanges()` và Async Pipe (`| async`)?",
    ["`OnPush` chỉ kiểm tra thay đổi khi: @Input() đổi tham chiếu (object reference), sự kiện DOM kích hoạt trong component, hoặc Observable qua async pipe phát dữ liệu", "Async Pipe tự động quản lý việc subscribe và unsubscribe khi component hủy, đồng thời kích hoạt markForCheck tự động", "Giảm thiểu 90% số lần chạy kiểm tra cây component không cần thiết, tăng vọt hiệu năng ứng dụng lớn"],
    ["Khi nào việc đột biến dữ liệu trực tiếp (mutating object property) khiến component OnPush không cập nhật giao diện?", "Sự khác biệt giữa `markForCheck()` (đánh dấu để chạy ở chu kỳ tiếp theo) và `detectChanges()` (chạy đồng bộ ngay lập tức)?"] ,
    ["OnPush", "ChangeDetectorRef", "Async Pipe", "Performance Optimization"],
    [SRC.angular],
    ["Thay đổi thuộc tính bên trong object mà không tạo tham chiếu mới rồi thắc mắc tại sao OnPush component không render"]
  ),
  q("VUE_NG-SKILL-03", "Vue.js / Angular Developer", "practical_skills", "intermediate", "middle",
    "Xây dựng Custom Composables trong Vue 3 hoặc Custom Directives / Pipes trong Angular: Em thiết kế các module tái sử dụng logic (như theo dõi kích thước cửa sổ, debounce input, hoặc phân quyền theo role) ra sao?",
    ["Vue Composables: tuân thủ quy ước đặt tên `useXxx`, trả về các `ref` để duy trì tính reactive khi destructuring", "Angular Custom Directive: can thiệp trực tiếp vào Host Element bằng `@HostBinding` và `@HostListener` hoặc `hostDirectives` mới", "Angular Pure Pipe: tự động memoize kết quả tính toán, chỉ chạy lại khi tham số đầu vào thay đổi tham chiếu"],
    ["Tại sao không nên tạo Impure Pipe trong Angular nếu hàm tính toán nặng?", "Làm thế nào để quản lý việc dọn dẹp event listener (cleanup on scope dispose) bên trong một Composable bằng `onScopeDispose`?"] ,
    ["Composables", "Custom Directives", "Pure Pipes", "Logic Reuse"],
    [SRC.vue, SRC.angular],
    ["Destructure trực tiếp các thuộc tính từ reactive object trong Vue làm mất tính reactivity của biến"]
  ),
  q("VUE_NG-SKILL-04", "Vue.js / Angular Developer", "practical_skills", "intermediate", "middle",
    "Bảo vệ luồng điều hướng (Route Guards): Em thiết lập các Guard kiểm tra đăng nhập (CanActivate), kiểm tra quyền hạn (Role-based), và cảnh báo người dùng khi thoát form chưa lưu (CanDeactivate) trong Vue Router hoặc Angular Router như thế nào?",
    ["Angular: triển khai `CanActivateFn` và `CanDeactivateFn` dạng functional guards hiện đại, trả về boolean, UrlTree hoặc Promise/Observable", "Vue Router: sử dụng navigation guards toàn cục `router.beforeEach` hoặc per-route guards `beforeEnter`", "CanDeactivate: kiểm tra trạng thái form `isDirty`, hiển thị hộp thoại xác nhận nếu người dùng cố tình chuyển trang khi chưa lưu dữ liệu"],
    ["Làm thế nào để xử lý Race Condition khi chuyển trang liên tục trong Router?", "Cơ chế Route Resolvers giúp nạp sẵn dữ liệu trước khi render component ra sao?"] ,
    ["Route Guards", "CanActivate", "CanDeactivate", "Vue Router", "Angular Router"],
    [SRC.angular, SRC.vue],
    ["Chỉ kiểm tra quyền ở giao diện mà không chặn ở Route Guard khiến người dùng gõ trực tiếp URL vẫn truy cập được"]
  ),
  q("VUE_NG-SKILL-05", "Vue.js / Angular Developer", "practical_skills", "advanced", "senior_lead",
    "Xây dựng ứng dụng Enterprise quy mô lớn bằng kiến trúc Micro-Frontends sử dụng Module Federation trong Webpack / Vite cho Angular hoặc Vue: Em giải quyết bài toán chia sẻ thư viện chung (Shared Dependencies) và định tuyến độc lập thế nào?",
    ["Cấu hình Module Federation: Host app và Remote apps biên dịch độc lập, chia sẻ các singleton dependency (Angular Core, Vue, Pinia)", "Quản lý phiên bản SemVer giữa các micro-frontends để tránh tải trùng lặp nhiều phiên bản framework", "Định tuyến tích hợp: Host Router điều hướng đến các route vỏ bọc, tải remote bundle theo cơ chế lười (Dynamic Import)"],
    ["Làm thế nào để truyền thông điệp giữa các micro-frontends độc lập (Custom Events, Event Bus phân tán)?", "Chiến lược xử lý CSS isolation để tránh style của micro-frontend A làm vỡ giao diện của micro-frontend B?"] ,
    ["Micro-Frontends", "Module Federation", "Enterprise Architecture", "Vite", "Webpack"],
    [SRC.internal],
    ["Nhúng các micro-frontend qua thẻ iframe thô sơ gây khó khăn cho việc đồng bộ state và trải nghiệm người dùng"]
  ),
  q("VUE_NG-SKILL-06", "Vue.js / Angular Developer", "practical_skills", "intermediate", "middle",
    "Tối ưu hóa thời gian tải trang và hiệu năng hiển thị trong Nuxt 3 hoặc Angular SSR (Universal): Kỹ thuật Server Engine (Nitro), Hydration, và giải quyết lỗi gọi API lặp lại 2 lần (Double Data Fetching)?",
    ["Sử dụng `useAsyncData` hoặc `useFetch` trong Nuxt 3 để tự động cache payload từ server truyền xuống client qua window.__NUXT__", "Trong Angular Universal: áp dụng `TransferState` để chuyển dữ liệu từ server render sang client, ngăn client gọi lại API một lần nữa", "Tối ưu hóa Nitro engine: cấu hình server storage, hybrid rendering (route rules: SSR cho sản phẩm, SWR cho tin tức)"],
    ["Lỗi Hydration mismatch trong Nuxt/Angular SSR thường phát sinh do những thẻ HTML hoặc mã JS nào?", "Làm thế nào để cấu hình Island Architecture hoặc Server Components trong Nuxt 3?"] ,
    ["Nuxt 3", "Angular Universal", "SSR", "TransferState", "Hydration"],
    ["https://nuxt.com/docs"],
    ["Không sử dụng cơ chế Transfer State khiến ứng dụng gọi API 2 lần liên tiếp (1 lần ở server và 1 lần ở client)"]
  ),
  q("VUE_NG-SKILL-07", "Vue.js / Angular Developer", "practical_skills", "intermediate", "middle",
    "Chiến lược kiểm thử tự động cho Vue (Vitest + Vue Test Utils) và Angular (Jasmine/Karma hoặc Jest/Angular Testing Library): Cách viết bài test giả lập sự kiện người dùng, mock service qua Dependency Injection và kiểm thử async pipe?",
    ["Angular: dùng `TestBed.configureTestingModule` để ghi đè providers bằng mock services hoặc `provideMockStore`", "Vue: dùng `shallowMount` / `mount` từ Vue Test Utils, mock Pinia bằng `createTestingPinia`", "Kiểm thử các tác vụ bất đồng bộ với `fakeAsync`, `tick()`, `flushMicrotasks()` trong Angular hoặc `flushPromises()` trong Vue"],
    ["Tại sao xu hướng hiện nay của Angular chuyển từ Karma/Jasmine sang Jest hoặc Vitest để tăng tốc độ chạy test?", "Harnesses component trong Angular Material hỗ trợ việc viết test UI ổn định ra sao?"] ,
    ["Testing", "Vitest", "Vue Test Utils", "TestBed", "Jest"],
    [SRC.angular, SRC.vue],
    ["Kiểm thử bằng cách can thiệp trực tiếp vào biến private nội bộ của class thay vì kiểm tra output và DOM"]
  ),
  q("VUE_NG-SKILL-08", "Vue.js / Angular Developer", "practical_skills", "intermediate", "middle",
    "Quản lý biểu mẫu phức tạp (Forms): So sánh Reactive Forms trong Angular với giải pháp VeeValidate / FormKit trong Vue. Cách xây dựng Custom Async Validator kiểm tra tính duy nhất của dữ liệu (vd: kiểm tra email đã tồn tại qua API)?",
    ["Angular Reactive Forms: mô hình hướng đối tượng dựa trên luồng (`FormControl`, `FormGroup`, `FormArray`) với Observable theo dõi giá trị", "Custom Async Validator: trả về Observable/Promise phát ra lỗi hoặc null, áp dụng debounceTime để tránh spam request lên server", "Vue 3 với VeeValidate + Zod: liên kết schema validation chặt chẽ, tự động quản lý trạng thái touched/dirty/errors"],
    ["Tại sao không nên dùng Template-driven Forms cho các form doanh nghiệp phức tạp trong Angular?", "Làm thế nào để quản lý mảng các trường động (Dynamic FormArray) thêm/bớt linh hoạt?"] ,
    ["Reactive Forms", "Async Validator", "VeeValidate", "Zod", "Form Architecture"],
    [SRC.angular, SRC.vue],
    ["Gọi API kiểm tra validation trực tiếp trên mỗi phím bấm mà không có debounceTime làm nghẽn máy chủ"]
  ),

  // Scenario (6)
  q("VUE_NG-SCEN-01", "Vue.js / Angular Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một ứng dụng Angular sau khi người dùng chuyển qua lại giữa 10 màn hình dashboard thì tab trình duyệt ngốn hơn 2GB RAM và bắt đầu lag đơ. Kết quả phân tích cho thấy các subscription của RxJS chưa bao giờ bị hủy. Em tái cấu trúc mã nguồn để loại bỏ triệt để rò rỉ bộ nhớ ra sao?",
    ["Sử dụng toán tử `takeUntilDestroyed()` mới trong Angular 16+ hoặc mẫu `takeUntil(this.destroy$)` truyền thống", "Tận dụng tối đa `async pipe` trong template HTML để Angular tự động quản lý vòng đời subscribe/unsubscribe", "Thiết lập quy tắc linting bắt buộc (ESLint RxJS rules) để phát hiện ngay lúc compile time các lệnh subscribe không an toàn"],
    ["Toán tử `first()` và `take(1)` có an toàn để tự động hoàn thành stream không?", "Làm thế nào để kiểm tra số lượng active subscriptions còn sót lại bằng DevTools?"] ,
    ["Memory Leak", "RxJS Unsubscribe", "takeUntilDestroyed", "Angular Profiling"],
    [SRC.internal],
    ["Gọi lệnh subscribe thủ công khắp mọi nơi trong component mà không có hàm ngOnDestroy để dọn dẹp"]
  ),
  q("VUE_NG-SCEN-02", "Vue.js / Angular Developer", "scenario", "intermediate", "middle",
    "Tình huống: Trong Vue 3, một component cha truyền dữ liệu xuống component con qua prop. Component con muốn chỉnh sửa trực tiếp thuộc tính của prop đó nhưng Vue đưa ra cảnh báo 'Avoid mutating a prop directly'. Em xử lý kiến trúc luồng dữ liệu 2 chiều (v-model) chuẩn mực ra sao?",
    ["Tuân thủ nguyên tắc dòng dữ liệu một chiều (One-Way Data Flow): component con không được đột biến prop của cha", "Sử dụng cú pháp `v-model:propName` kết hợp emit sự kiện `update:propName` từ component con lên cha", "Tận dụng hàm tiện ích `useVModel` từ thư viện VueUse hoặc computed property có getter/setter để viết mã ngắn gọn"],
    ["Tại sao việc sửa prop trực tiếp làm mã nguồn trở nên khó đoán định và phá vỡ kiến trúc cây component?", "Cách định nghĩa nhiều v-model trên cùng một component trong Vue 3?"] ,
    ["Vue v-model", "One-Way Data Flow", "Component Communication", "Props Mutation"],
    [SRC.vue, SRC.internal],
    ["Cố tình mutate trực tiếp prop object để 'tiện lợi' và bỏ qua cảnh báo của Vue console"]
  ),
  q("VUE_NG-SCEN-03", "Vue.js / Angular Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một bảng dữ liệu lớn trong Angular chứa 2.000 dòng có nhiều tính toán phức tạp. Mỗi khi người dùng gõ phím vào ô tìm kiếm ở góc màn hình, toàn bộ 2.000 dòng đều bị tính toán lại khiến gõ phím bị trễ (Keypress Lag). Em áp dụng OnPush và Angular CDK Virtual Scroll thế nào?",
    ["Chuyển toàn bộ các component dòng (Row Component) sang `ChangeDetectionStrategy.OnPush`", "Thay thế việc render toàn bộ DOM bằng `cdk-virtual-scroll-viewport` từ Angular CDK để chỉ render các dòng nhìn thấy", "Tách các hàm tính toán phức tạp trong template ra thành Pure Pipe có tính năng memoize kết quả"],
    ["Tại sao gọi trực tiếp một hàm `calculateValue()` trong template HTML của Angular lại là thảm họa hiệu năng?", "Làm thế nào để đo lường số lần chạy Change Detection bằng công cụ Angular DevTools Profiler?"] ,
    ["Keypress Lag", "OnPush", "Virtual Scroll", "Angular CDK", "Performance"],
    [SRC.angular, SRC.internal],
    ["Gọi hàm JavaScript trực tiếp trong biểu thức template `{{ calculate(item) }}` lặp lại hàng nghìn lần mỗi frame"]
  ),
  q("VUE_NG-SCEN-04", "Vue.js / Angular Developer", "scenario", "intermediate", "middle",
    "Tình huống: Khi triển khai ứng dụng Vue 3 lên production, một số người dùng sử dụng trình duyệt cũ trên máy tính bảng chuyên dụng của doanh nghiệp gặp lỗi màn hình trắng xóa do thiếu Polyfills cho các tính năng hiện đại. Em cấu hình build tool (Vite) ra sao để tương thích?",
    ["Cấu hình plugin `@vitejs/plugin-legacy` để tự động sinh bản build dự phòng kèm polyfills cho các trình duyệt cũ", "Thiết lập danh sách `targets` trong cấu hình Browserslist phù hợp với yêu cầu thực tế của doanh nghiệp", "Kiểm tra xem các tính năng CSS hiện đại (như CSS Grid, aspect-ratio) có cần Autoprefixer và PostCSS polyfill hay không"],
    ["Tại sao bản build legacy thường có kích thước lớn hơn đáng kể so với bản build ES modules hiện đại?", "Cơ chế `<script type='module'>` kết hợp `<script nomodule>` giúp tải đúng bản build cho từng trình duyệt ra sao?"] ,
    ["Browser Compatibility", "Vite Legacy", "Polyfills", "Production Build"],
    [SRC.internal],
    ["Đổ lỗi cho khách hàng dùng trình duyệt cũ mà không có phương án kỹ thuật xử lý khả năng tương thích ngược"]
  ),
  q("VUE_NG-SCEN-05", "Vue.js / Angular Developer", "scenario", "advanced", "senior_lead",
    "Tình huống: Một ứng dụng Nuxt 3 thương mại điện tử bị lỗi rò rỉ bộ nhớ (Memory Leak) ở tầng Node.js Server khiến dịch vụ SSR bị crash sau mỗi 12 tiếng chịu tải cao. Nguyên nhân được xác định do chia sẻ state toàn cục không an toàn giữa các request. Em khắc phục lỗi này ra sao?",
    ["Phân tích nguyên nhân: Khởi tạo biến state bên ngoài phạm vi hàm của request handler, khiến biến này bị chia sẻ chung cho mọi người dùng (Cross-request State Pollution)", "Khắc phục: Luôn sử dụng `useState()` của Nuxt hoặc tạo Pinia store mới cho mỗi SSR request", "Đảm bảo không lưu trữ dữ liệu cá nhân của người dùng vào các biến singleton hoặc global module scope ở server"],
    ["State Pollution trong SSR có thể dẫn đến rủi ro lộ lọt thông tin của người dùng này cho người dùng khác ra sao?", "Cách dùng công cụ autocannon kết hợp clinicjs để stress-test và phát hiện rò rỉ bộ nhớ SSR cục bộ?"] ,
    ["SSR Memory Leak", "Nuxt 3", "Cross-request State Pollution", "Security Vulnerability"],
    [SRC.internal],
    ["Khai báo biến lưu trữ thông tin user ở top-level của file JavaScript trong môi trường chạy SSR"]
  ),
  q("VUE_NG-SCEN-06", "Vue.js / Angular Developer", "scenario", "intermediate", "middle",
    "Tình huống: Trong Angular, khi gọi đồng thời 3 API phụ thuộc nhau (API 1 lấy User, API 2 lấy Danh sách quyền dựa trên User, API 3 lấy Cấu hình giao diện dựa trên quyền). Nếu dùng `subscribe` lồng nhau (Callback Hell) thì code rất lộn xộn và dễ lỗi. Em tái cấu trúc bằng các toán tử RxJS ra sao?",
    ["Sử dụng toán tử `switchMap` để xâu chuỗi các Observable tuần tự theo một luồng đơn hướng mạch lạc", "Nếu các API độc lập có thể chạy song song: kết hợp bằng toán tử `forkJoin` hoặc `combineLatest` để giảm tổng thời gian chờ", "Bổ sung toán tử `catchError` để xử lý bắt lỗi tập trung và trả về giá trị fallback an toàn"],
    ["Sự khác biệt cốt lõi giữa `forkJoin` (chờ tất cả hoàn thành và chỉ lấy giá trị cuối) và `combineLatest` là gì?", "Cách xử lý retry tự động khi 1 trong 3 request bị lỗi mạng bằng `retryWhen`?"] ,
    ["RxJS Chaining", "switchMap", "forkJoin", "Clean Code", "Reactive Architecture"],
    [SRC.angular, SRC.internal],
    ["Viết lồng 3 hàm subscribe vào nhau theo phong cách Callback Hell truyền thống"]
  ),

  // CV Validation (5)
  q("VUE_NG-CV-01", "Vue.js / Angular Developer", "cv_validation", "advanced", "senior_lead",
    "Trong dự án Vue hoặc Angular quy mô lớn nhất trên CV của em: Cấu trúc thư mục của dự án được tổ chức theo kiến trúc nào (Feature Modules, Clean Architecture, hay Monorepo)? Đâu là thách thức lớn nhất khi mở rộng quy mô dự án lên hàng trăm component?",
    ["Trình bày cấu trúc module rõ ràng: Core (singletons), Shared (reusable components/pipes), Features (lazy-loaded domain modules)", "Giải thích cơ chế kiểm soát phụ thuộc để tránh vòng lặp tham chiếu (Circular Dependency)", "Dẫn chứng về số lượng lập trình viên cùng tham gia và cách duy trì quy chuẩn code nhất quán"],
    ["Nếu có một module mới cần dùng một phần nhỏ của module cũ, em xử lý chia sẻ code ra sao?", "Em đã áp dụng công cụ nào (Nx boundaries, ESLint rules) để ngăn chặn việc import sai tầng kiến trúc?"] ,
    ["Project Architecture", "Modular Design", "Scale", "CV Deep Dive"],
    [SRC.internal],
    ["Tập hợp toàn bộ hàng trăm component vào chung một thư mục phẳng duy nhất không có phân cấp"]
  ),
  q("VUE_NG-CV-02", "Vue.js / Angular Developer", "cv_validation", "intermediate", "middle",
    "Trên CV em có nêu kinh nghiệm chuyển đổi (Migration) dự án từ Vue 2 sang Vue 3 hoặc nâng cấp phiên bản Angular cũ lên Angular hiện đại. Em đã lập kế hoạch và vượt qua những breaking changes lớn nào trong quá trình chuyển đổi?",
    ["Vue: chuyển đổi từ Options API sang Composition API, cập nhật Vue Router 4, chuyển từ Vuex sang Pinia, xử lý Event Bus bị loại bỏ", "Angular: chạy `ng update` từng phiên bản tuần tự, chuyển từ ViewEngine sang Ivy compiler, refactor sang Standalone components", "Duy trì hoạt động liên tục của sản phẩm: kế hoạch phát hành theo từng giai đoạn và kiểm thử hồi quy kỹ lưỡng"],
    ["Chiến lược xử lý các thư viện bên thứ ba chưa tương thích với phiên bản mới là gì?", "Làm thế nào để đảm bảo đội ngũ không bị gián đoạn công việc phát triển tính năng mới trong lúc nâng cấp?"] ,
    ["Migration", "Vue 2 to Vue 3", "Angular Upgrade", "Ivy Compiler", "CV Verification"],
    [SRC.internal],
    ["Nói chung chung là 'chỉ cần đổi version rồi build lại' mà không kể được các breaking changes thực tế"]
  ),
  q("VUE_NG-CV-03", "Vue.js / Angular Developer", "cv_validation", "intermediate", "middle",
    "Em ghi nhận kinh nghiệm làm việc chuyên sâu với RxJS trên CV. Em hãy dẫn chứng một use-case phức tạp nhất mà em từng giải quyết bằng cách kết hợp nhiều toán tử RxJS trong dự án thực tế?",
    ["Trình bày bài toán cụ thể: tính năng tìm kiếm realtime có debounce, tự động hủy request cũ (`switchMap`), caching kết quả và retry khi lỗi", "Các toán tử kết hợp: `debounceTime`, `distinctUntilChanged`, `switchMap`, `catchError`, `shareReplay`", "Lợi ích mang lại: code ngắn gọn, kiểm soát hoàn hảo trạng thái loading và không bị race condition"],
    ["Tại sao toán tử `shareReplay(1)` lại quan trọng khi muốn chia sẻ dữ liệu stream cho nhiều subscribers?", "Làm thế nào để viết Unit Test cho một luồng RxJS phức tạp bằng Marble Testing?"] ,
    ["RxJS Mastery", "Complex Stream", "Marble Testing", "shareReplay", "CV Verification"],
    [SRC.internal],
    ["Ghi thạo RxJS trên CV nhưng chỉ biết mỗi lệnh subscribe và catchError cơ bản"]
  ),
  q("VUE_NG-CV-04", "Vue.js / Angular Developer", "cv_validation", "advanced", "senior_lead",
    "Em hãy chia sẻ về một vấn đề hiệu năng khó khăn nhất trong dự án Vue/Angular trên CV mà em đã trực tiếp dùng công cụ Profiler để tìm ra điểm nghẽn và cải thiện thành công?",
    ["Xác định công cụ đo: Angular DevTools Profiler, Vue DevTools Performance tab, Chrome DevTools Timeline", "Chỉ rõ nguyên nhân gốc rễ: quá nhiều watcher sâu (deep watchers) trong Vue, hoặc Change Detection chạy liên tục do setInterval ngoài Zone", "Số liệu cải thiện rõ rệt: giảm thời gian render frame từ 80ms xuống dưới 16ms, giảm tải CPU"],
    ["Hàm `NgZone.runOutsideAngular()` được em sử dụng trong tình huống nào để tránh kích hoạt Change Detection?", "Cách tránh việc lạm dụng deep watcher trong Vue 3?"] ,
    ["Profiler Investigation", "Performance Bottleneck", "NgZone", "Deep Watcher", "CV Verification"],
    [SRC.internal],
    ["Không nhớ công cụ nào đã sử dụng hoặc đưa ra các giải pháp đoán mò không có số liệu chứng minh"]
  ),
  q("VUE_NG-CV-05", "Vue.js / Angular Developer", "cv_validation", "intermediate", "middle",
    "Trong dự án xây dựng thư viện thành phần giao diện (UI Component Library) dùng chung cho công ty trên CV, em đã đóng gói và xuất bản (publish) thư viện đó như thế nào bằng Angular CLI (ng-packagr) hoặc Vite Library Mode?",
    ["Angular: sử dụng `ng-packagr` xuất bản chuẩn định dạng Angular Package Format (APF) tương thích Ivy và ESM", "Vue: cấu hình Vite Library Mode (`build.lib`), định nghĩa externals để không đóng gói kèm Vue vào bundle", "Quản lý types định dạng `.d.ts`, cấu hình `exports` trong `package.json` và tài liệu hóa bằng Storybook"],
    ["Làm thế nào để kiểm tra tính tương thích của thư viện trên các dự án mẫu trước khi publish lên npm registry?", "Chiến lược quản lý Semantic Versioning khi có breaking changes trong component library?"] ,
    ["Component Library", "ng-packagr", "Vite Library Mode", "NPM Package", "CV Verification"],
    [SRC.internal],
    ["Chỉ copy các file component dạng thô giữa các dự án mà chưa từng đóng gói thành package chuẩn"]
  ),

  // Behavioral (5)
  q("VUE_NG-BEHAV-01", "Vue.js / Angular Developer", "behavioral", "intermediate", "middle",
    "Angular và Vue thường có các chuẩn mực kiến trúc và quy ước đặt tên rất rõ ràng (Opinionated). Khi một thành viên mới trong nhóm liên tục viết code theo thói quen tự do phá vỡ quy ước chung, em hỗ trợ và duy trì kỷ luật kỹ thuật ra sao?",
    ["Tổ chức buổi trao đổi 1-on-1 nhẹ nhàng để giải thích lý do tại sao quy ước chung giúp toàn đội ngũ bảo trì code dễ dàng hơn", "Thiết lập công cụ tự động hóa bắt lỗi: cấu hình Angular ESLint / Vue ESLint nghiêm ngặt kết hợp Git hooks (Husky)", "Đồng hành pair-programming cùng bạn trong vài Pull Request đầu tiên để giúp bạn nhanh chóng làm quen với văn hóa chung"],
    ["Nếu thành viên đó vẫn bảo thủ không tuân thủ, em xử lý bước tiếp theo thế nào?", "Làm sao để tiếp nhận các ý kiến đóng góp cải tiến quy ước nếu bạn ấy có đề xuất hợp lý?"] ,
    ["Code Conventions", "Mentorship", "Engineering Standards", "Automated Linting"],
    [SRC.internal],
    ["Chỉ trích gay gắt trên kênh chat chung hoặc tự mình âm thầm sửa lại toàn bộ code của bạn ấy"]
  ),
  q("VUE_NG-BEHAV-02", "Vue.js / Angular Developer", "behavioral", "advanced", "senior_lead",
    "Khi công ty cân nhắc lựa chọn công nghệ cho một sản phẩm web lớn mới giữa React, Vue 3 và Angular, em tham gia đóng góp ý kiến và phân tích khách quan các điểm mạnh/yếu của từng framework như thế nào?",
    ["Phân tích dựa trên bài toán tổ chức: quy mô đội ngũ, nguồn nhân lực sẵn có trên thị trường tuyển dụng, thời gian hoàn vốn", "So sánh khách quan: Angular phù hợp cho hệ thống doanh nghiệp lớn cần tính chuẩn hóa cao; Vue 3 linh hoạt, dễ học, tốc độ phát triển nhanh; React có hệ sinh thái thư viện khổng lồ", "Khuyến nghị giải pháp tối ưu cho mục tiêu kinh doanh của công ty thay vì đưa ra nhận định mang tính thiên vị cá nhân"],
    ["Khi nào việc chọn một framework 'ít phổ biến hơn' lại mang lại lợi thế cạnh tranh cho công ty?", "Làm thế nào để xây dựng lộ trình đào tạo cho đội ngũ nếu công ty quyết định chuyển sang framework mới?"] ,
    ["Framework Comparison", "Technology Selection", "Strategic Thinking", "Objective Evaluation"],
    [SRC.internal],
    ["Tranh luận mang tính tôn giáo công nghệ (framework war) và hạ thấp các framework khác một cách thiếu căn cứ"]
  ),
  q("VUE_NG-BEHAV-03", "Vue.js / Angular Developer", "behavioral", "intermediate", "middle",
    "Khi thư viện bên thứ ba đang sử dụng trong dự án bất ngờ phát hiện lỗ hổng bảo mật nghiêm trọng (CVE) và phiên bản vá lỗi yêu cầu phải nâng cấp toàn bộ framework lên phiên bản lớn tiếp theo, em quản trị rủi ro và điều phối kế hoạch ra sao?",
    ["Đánh giá phạm vi ảnh hưởng thực tế: lỗ hổng có nằm trên luồng code mà ứng dụng thực sự gọi tới hay không", "Nếu cần nâng cấp khẩn cấp: cô lập phạm vi thay đổi, tạo branch riêng và chạy kiểm thử tự động toàn diện để phát hiện breaking changes", "Giao tiếp minh bạch với Product Manager và Ban Quản lý về sự đánh đổi giữa an toàn thông tin và tiến độ tính năng mới"],
    ["Giải pháp vá lỗi tạm thời (Hot-patch) trong khi chờ kế hoạch nâng cấp lớn là gì?", "Làm thế nào để thiết lập quy trình quét lỗ hổng tự động (Snyk, Dependabot) vào CI/CD để phát hiện sớm?"] ,
    ["Security Incident", "CVE Remediation", "Dependency Risk", "Stakeholder Communication"],
    [SRC.internal],
    ["Xem nhẹ cảnh báo bảo mật và tiếp tục để lỗ hổng tồn tại trên môi trường production"]
  ),
  q("VUE_NG-BEHAV-04", "Vue.js / Angular Developer", "behavioral", "basic", "junior",
    "Khi nhận được phản hồi từ Tester rằng trang web chạy rất chậm trên máy tính của họ nhưng trên máy tính cấu hình mạnh của em thì chạy mượt mà, em phối hợp với Tester để kiểm chứng và giải quyết vấn đề thế nào?",
    ["Không bao giờ nói 'trên máy em vẫn chạy bình thường' để gạt bỏ phản hồi của Tester", "Chủ động mượn máy tính của Tester hoặc sử dụng tính năng CPU Throttling (hạ 4x/6x CPU) và Network Throttling trong Chrome DevTools để mô phỏng chính xác môi trường", "Thu thập dữ liệu hiệu năng cụ thể và tìm kiếm giải pháp tối ưu hóa để đảm bảo ứng dụng chạy mượt mà trên cả thiết bị phổ thông"],
    ["Tại sao việc kiểm thử trên thiết bị cấu hình trung bình lại quan trọng đối với trải nghiệm người dùng cuối?", "Cách em cảm ơn và khuyến khích Tester tiếp tục phát hiện các lỗi hiệu năng như vậy?"] ,
    ["Empathy with QA", "CPU Throttling", "Cross-environment Testing", "Professional Attitude"],
    [SRC.internal],
    ["Phản ứng khó chịu và cho rằng Tester đang săm soi lỗi vặt"]
  ),
  q("VUE_NG-BEHAV-05", "Vue.js / Angular Developer", "behavioral", "intermediate", "middle",
    "Khi các thành viên trong nhóm có sự chia rẽ: một nửa muốn viết Vue theo phong cách Composition API hiện đại, một nửa muốn giữ Options API truyền thống cho dễ đọc, em đóng góp ý kiến để thống nhất định hướng nhóm ra sao?",
    ["Thừa nhận ưu điểm của cả hai: Options API dễ tiếp cận cho người mới, Composition API vượt trội khi dự án mở rộng phức tạp", "Đề xuất lộ trình hài hòa: giữ nguyên các component cũ đang chạy ổn định, nhưng thống nhất áp dụng Composition API cho các tính năng mới và các logic cần tái sử dụng (Composables)", "Tổ chức một buổi chia sẻ nội bộ trình bày các mẫu thiết kế thực tế để giúp các bạn quen với tư duy mới"],
    ["Làm thế nào để văn bản hóa (Document) quyết định kỹ thuật này vào sổ tay kỹ thuật của nhóm (Architecture Decision Record - ADR)?", "Cách theo dõi mức độ tiếp nhận của đội ngũ sau khi thống nhất định hướng?"] ,
    ["Team Alignment", "Architecture Decision", "Consensus Building", "Change Management"],
    [SRC.internal],
    ["Áp đặt ý kiến cá nhân bằng quyền hạn hoặc để tranh cãi nội bộ kéo dài gây mất đoàn kết"]
  )
];

console.log("VUE_NG questions defined:", vueNgQuestions.length);
module.exports = { vueNgQuestions };
